### ISSUE TITLE
xbmc not starting - libGL.so not found, other problems

### ISSUE THREAD

**Issue by doits** [OpenELEC/OpenELEC.tv#1334]
XBMC does not start on boot.

First problem is that symlinks are wrong using master at version 363e2bd65cfa19b8fdf9f5d2695806b5864d212e:

```
root ~ # ldd /usr/lib/xbmc/xbmc.bin
[...]
        libGL.so.1 => not found
[...]
root /usr/lib # ls -lha libGL*
lrwxrwxrwx    1 root     root          10 Oct 12 22:44 libGL.so -> libGL.so.1
lrwxrwxrwx    1 root     root          17 Oct 12 22:44 libGL.so.1 -> /var/lib/libGL.so
[...]
-rwxr-xr-x    1 root     root      414.4K Oct 12 22:44 libGL_mesa.so.1
-rwxr-xr-x    1 root     root        1.0M Oct 12 22:44 libGL_nvidia.so.1
root ~ # ls /var/lib/libGL.so
ls: /var/lib/libGL.so: No such file or directory
```

with following build command:

```
make PROJECT=ION ARCH=x86_64 XBMC=frodo release
```

I corrected this by simply doing the following (which of course is only a hack and only works when nvidia drivers are present, so a better solution must be found):

```
diff --git a/packages/graphics/Mesa/install b/packages/graphics/Mesa/install
index 610315d..802e899 100755
--- a/packages/graphics/Mesa/install
+++ b/packages/graphics/Mesa/install
@@ -24,8 +24,8 @@

 mkdir -p $INSTALL/usr/lib
   cp -P $PKG_BUILD/lib/libGL.so.1.2 $INSTALL/usr/lib/libGL_mesa.so.1 # rename for cooperate with nvidia drivers
-    ln -sf libGL.so.1 $INSTALL/usr/lib/libGL.so
-    ln -sf /var/lib/libGL.so $INSTALL/usr/lib/libGL.so.1
+    ln -sf libGL_nvidia.so.1 $INSTALL/usr/lib/libGL.so
+    ln -sf libGL.so $INSTALL/usr/lib/libGL.so.1
   cp -P $PKG_BUILD/lib/libGLU.so* $INSTALL/usr/lib
   cp -P $PKG_BUILD/lib/libglapi.so* $INSTALL/usr/lib
   if [ -f $PKG_BUILD/lib/gallium/libxatracker.so ] ; then
```

Nevertheless, xbmc still does not start at boot - and launching manually gives:

```
root ~ # /usr/lib/xbmc/xbmc.bin 
Can't open display :0.0
ERROR: Unable to create GUI. Exiting
Segmentation fault
```

I got it working out of the box with a version of openelec-next a week ago or so:

```
# cat RELEASE
ION.x86_64-devel-20121004190705-r12119
XBMC commit: 6cf5b9d
```

I first tried the latest openelec-next, then switched to master because I thought the more unstable -next branch was the problem. Unfortunately on both branches xbmc does not start atm.

Any help is appreciated.

**Comment by esbiete** [comment]
Hi! 

Just installed OpenELEC 5 i386 on an old computer and happened the same mentioned in the previous comments

![image](https://cloud.githubusercontent.com/assets/10363434/5592007/8990e66a-91a9-11e4-8df2-d343ba319280.png)


As /var/lib is writeable I just created a link to /usr/lib/libGL_nvidia.so.1 there.

Anyway, unable to open Kodi:

OpenELEC:/usr/lib/kodi # ./kodi.bin
Can't open display :0.0
ERROR: Unable to create GUI. Exiting
Segmentation fault
OpenELEC:/usr/lib/kodi #

**Comment by stefansaraev** [comment]
that's because your old hardware is not even supported by nvidia-legacy driver ;)
