### ISSUE TITLE
Raspberry Pi CPU load ~90%

### ISSUE THREAD

**Issue by m0rtal** [OpenELEC/OpenELEC.tv#1622]
Just got my ne RPi, installed fresh (r12577) OpenELEC there, and found out that CPU load is always around 90%
Here's output of the top, mostly all of the cpu resource are going to xbmc.bin process:

Mem: 318828K used, 62920K free, 0K shrd, 36208K buff, 238476K cached
CPU: 80.7% usr 14.0% sys  0.0% nic  5.1% idle  0.0% io  0.0% irq  0.0% sirq
Load average: 2.31 1.05 0.40 2/101 1549
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
  948     1 root     R     276m 74.0   0 85.7 /usr/lib/xbmc/xbmc.bin --standalone -fs --lircdev /var/run/lirc/lircd
  544     2 root     SW<      0  0.0   0  3.5 [VCHIQr-0]
  543     2 root     SW<      0  0.0   0  1.3 [VCHIQ-0]
 1290  1221 root     R     2556  0.6   0  0.7 top
    6     2 root     SW       0  0.0   0  0.7 [kworker/u:0]
 1507     2 root     SW       0  0.0   0  0.7 [kworker/u:3]
 1177   931 root     S     6712  1.7   0  0.5 {sshd} sshd: root@pts/0
  583     2 root     SW       0  0.0   0  0.3 [kworker/u:2]
 1542  1541 root     S    51364 13.4   0  0.1 transmission-daemon -f -w /storage/server/Downloadz/ --incomplete-dir /storage/server/Downloadz//incoming --watch-dir /storage/server/Downloadz//watch -e /var/
    3     2 root     SW       0  0.0   0  0.1 [ksoftirqd/0]
 1549     2 root     SW       0  0.0   0  0.1 [kworker/0:2]
 1366     2 root     SW       0  0.0   0  0.1 [cifsd]
  951     1 root     S    24016  6.2   0  0.0 /usr/lib/polkit-1/polkitd --no-debug
  900     1 root     S    20400  5.3   0  0.0 /usr/sbin/vcfiled
  916     1 root     S    15588  4.0   0  0.0 /usr/lib/udisks/udisks-daemon
 1117     1 root     S    11448  3.0   0  0.0 nmbd --daemon --configfile=/var/run/smb.conf
 1119     1 root     S    11440  2.9   0  0.0 smbd --daemon --configfile=/var/run/smb.conf
  945   916 root     S     6048  1.5   0  0.0 udisks-daemon: not polling any devices
  955     1 root     S     5672  1.4   0  0.0 /usr/bin/wpa_supplicant -B -u -f /var/log/wpa_supplicant.log -c /etc/wpa_supplicant/wpa_supplicant.conf -P /var/run/wpa_supplicant.pid
  872   812 root     S     4752  1.2   0  0.0 /usr/sbin/connmand -n
  931     1 root     S     3984  1.0   0  0.0 /usr/sbin/sshd
 1072     1 avahi    S     3156  0.8   0  0.0 avahi-daemon: running [openelec.local]
    1     0 root     S     3084  0.8   0  0.0 {init} /bin/sh /sbin/init
  812     1 root     S     3084  0.8   0  0.0 {init} /bin/sh /sbin/init
  768     1 root     S     3084  0.8   0  0.0 {init} /bin/sh /sbin/init
 1221  1177 root     S     3080  0.8   0  0.0 -sh
 1541     1 root     S     3080  0.8   0  0.0 {transmission.st} /bin/sh /storage/.xbmc/addons/service.downloadmanager.transmission/bin/transmission.start
  826     1 dbus     S     2948  0.7   0  0.0 dbus-daemon --system
  766     1 root     S     2832  0.7   0  0.0 /lib/systemd/systemd-udevd --daemon
  759     1 root     S     2552  0.6   0  0.0 syslogd
  763     1 root     S     2552  0.6   0  0.0 klogd
  772   768 root     S     2488  0.6   0  0.0 udevadm monitor -e
  846     1 root     S     2384  0.6   0  0.0 rpcbind
  897     1 root     S     2136  0.5   0  0.0 eventlircd --evmap=/etc/eventlircd.d --socket=/var/run/lirc/lircd --release=_UP
  657     2 root     SW<      0  0.0   0  0.0 [loop0]
  626     2 root     SW       0  0.0   0  0.0 [mmcqd/0]
    8     2 root     SW       0  0.0   0  0.0 [rcu_kthread]
   11     2 root     SW       0  0.0   0  0.0 [kworker/u:1]
  310     2 root     SW       0  0.0   0  0.0 [khubd]
    4     2 root     SW       0  0.0   0  0.0 [kworker/0:0]
    2     0 root     SW       0  0.0   0  0.0 [kthreadd]
    5     2 root     SW<      0  0.0   0  0.0 [kworker/0:0H]
    7     2 root     SW<      0  0.0   0  0.0 [kworker/u:0H]
    9     2 root     SW<      0  0.0   0  0.0 [khelper]
   10     2 root     SW       0  0.0   0  0.0 [kdevtmpfs]
  296     2 root     SW       0  0.0   0  0.0 [bdi-default]
  298     2 root     SW<      0  0.0   0  0.0 [kblockd]
  326     2 root     SW<      0  0.0   0  0.0 [cfg80211]
  327     2 root     SW       0  0.0   0  0.0 [kworker/0:1]
  411     2 root     SW<      0  0.0   0  0.0 [rpciod]
  421     2 root     SW       0  0.0   0  0.0 [kswapd0]
  422     2 root     SW       0  0.0   0  0.0 [fsnotify_mark]
  423     2 root     SW<      0  0.0   0  0.0 [nfsiod]
  424     2 root     SW<      0  0.0   0  0.0 [cifsiod]

Turning RSS off doesn't change anything.
Is it ok?

**Comment by vbell** [comment]
Hi. 
I have OpenElec 5.0 stable on Raspberry Pi B+.
Lirc CPU load up to 40-50%... 
How to fix it?
![screenshot 2015-01-04 00 50 32](https://cloud.githubusercontent.com/assets/2427512/5604024/c1feb7b2-93ab-11e4-8981-c85cf5d72a87.png)

**Comment by fritsch** [comment]
Nothing to fix here. That's fine for rendering the GUI that is constantly
changing. Set your refreshrate to 24 hz and it will reduce.

2015-01-03 23:51 GMT+01:00 voha <notifications@github.com>:

> Hi.
> I have OpenElec 5.0 stable on Raspberry Pi B+.
> Lirc CPU load up to 40-50%...
> How to fix it?
> [image: screenshot 2015-01-04 00 50 32]
> <https://cloud.githubusercontent.com/assets/2427512/5604024/c1feb7b2-93ab-11e4-8981-c85cf5d72a87.png>
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/1622#issuecomment-68612815>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B
