### ISSUE TITLE
Driver support Realtek DVB-T RTL2832

### ISSUE THREAD

**Issue by ghost** [OpenELEC/OpenELEC.tv#1648]
I can't seem to get working in all betas but works in the last stable version of Openelec

full name:
 Conceptronic USB 2.0 Digital TV Receiver CTVDIGUSB2 - DVB-T

There is also a topic running with a similar chipset.
http://openelec.tv/forum/71-pvr--live-tv/55993-oe-20-vs-oe-295-beta

**Comment by medyagh** [comment]
Hi I have OpenElec 7.0 Beta 3 and I have RTL2838 DVB-T  (USB Stick) and it doesn't work for me.
I can not see the tv tuner in the the tvhead web interface.
here is the lsusb of my device:
`lsusb`
`Bus 002 Device 017: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T`

**Comment by medyagh** [comment]
Btw I also see this in dmesg

```[    8.466117] input: MCE IR Keyboard/Mouse (dvb_usb_rtl28xxu) as /devices/virtual/input/input15
[    8.469846] usb 1-1.1: dvb_usb_v2: schedule remote query interval to 200 msecs
[    8.475057] lirc_dev: IR Remote Control driver registered, major 246 
[    8.478502] usb 1-1.1: dvb_usb_v2: 'Realtek RTL2832U reference design' successfully initialized and connected
[    8.478610] usbcore: registered new interface driver dvb_usb_rtl28xxu
[    8.505473] rc rc0: lirc_dev: driver ir-lirc-codec (dvb_usb_rtl28xxu) registered at minor = 0
```
