### ISSUE TITLE
Inclusion of btrfs command (from btrfs-progs) so snapshots can be created/deleted

### ISSUE THREAD

**Issue by corepl** [OpenELEC/OpenELEC.tv#1772]
Feature request as per subject. This is needed to make use of snapshots and other advanced features of btrfs

**Comment by unsacrificed** [comment]
@jenkins101 @stefansaraev May it is time to support btrfs and include btrfs tools (mkfs.btrfs and others)?

**Comment by lrusak** [comment]
@unsacrificed see, https://github.com/lrusak/lrusak-openelec-addons
specifically, https://github.com/lrusak/lrusak-openelec-addons/tree/master/addons/tools/btrfs-progs
