### ISSUE TITLE
RaspberryPi + bgscan = Wifi drops for 5 seconds every 30 seconds

### ISSUE THREAD

**Issue by abrinner** [OpenELEC/OpenELEC.tv#1956]
# Setup:

Raspberry Pi with OpenElec 2.99.3 and TP-Link TL-WN821N
connected to a WPA protected Wifi
# Problem:

It is nearly impossible to stream a HD movie over Wifi. This works for a random amount of time (sometimes up to 30 minutes) before the movie stops and buffers, even with buffersize set to 50MB. After that it is playing again for a random amount of time.
Playing the same HD movie from directly connected HDD is no problem, as well as streaming the same movie to another XBMC instance on a laptop. The Raspberry Pi and the Wifi are in principle capable of streaming and playing the HD movie.
# Test:

ping Raspberry Pi:
64 bytes from 192.168.45.97: icmp_req=4059 ttl=64 time=1.50 ms
64 bytes from 192.168.45.97: icmp_req=4060 ttl=64 time=1.40 ms
64 bytes from 192.168.45.97: icmp_req=4061 ttl=64 time=4163 ms
64 bytes from 192.168.45.97: icmp_req=4062 ttl=64 time=3163 ms
64 bytes from 192.168.45.97: icmp_req=4063 ttl=64 time=2163 ms
64 bytes from 192.168.45.97: icmp_req=4064 ttl=64 time=1163 ms
64 bytes from 192.168.45.97: icmp_req=4065 ttl=64 time=163 ms
64 bytes from 192.168.45.97: icmp_req=4066 ttl=64 time=1.36 ms
64 bytes from 192.168.45.97: icmp_req=4067 ttl=64 time=1.39 ms
.... [approx 30 seconds] ...
64 bytes from 192.168.45.97: icmp_req=4093 ttl=64 time=1.60 ms
64 bytes from 192.168.45.97: icmp_req=4094 ttl=64 time=3.77 ms
64 bytes from 192.168.45.97: icmp_req=4095 ttl=64 time=5062 ms
64 bytes from 192.168.45.97: icmp_req=4096 ttl=64 time=4053 ms
64 bytes from 192.168.45.97: icmp_req=4097 ttl=64 time=3045 ms
64 bytes from 192.168.45.97: icmp_req=4098 ttl=64 time=2037 ms
64 bytes from 192.168.45.97: icmp_req=4099 ttl=64 time=1029 ms
64 bytes from 192.168.45.97: icmp_req=4100 ttl=64 time=21.5 ms
64 bytes from 192.168.45.97: icmp_req=4101 ttl=64 time=1.45 ms
64 bytes from 192.168.45.97: icmp_req=4102 ttl=64 time=1.61 ms

Notice the ping time is increasing up to 5 seconds every 30 seconds. This can be reproduced every time.

So it seems, that the Wifi connection is blocked for approximately 5 seconds every 30 seconds.
# Reason:

I am absolutely sure, that the reason for Wifi blocking is the bgscan process. I can observe related dbus messages and while blocking wpa_supplicant (killall -s STOP wpa_supplicant) I have no more Wifi droppings.
# Solution:

As I am not roaming with my Raspberry Pi there is no reason for these background scans. Would be good to have an option to disable bgscan.

**Comment by jonfspencer** [comment]
Background scanning is useful on a mobile device when you are roaming (e.g., walking around a building or driving tot he Pizza Place.  You don't generally need it if you are stationary.
