### ISSUE TITLE
Enable PulseAudio RTP send / receive for RaspberryPi

### ISSUE THREAD

**Issue by hcw70** [OpenELEC/OpenELEC.tv#2058]
Dear OpenElec Team.

I am a very happy OpenElec user (watching MythTV with the RaspberryPi). 

One thing that would be great to have is to allow
. Sending current audio data via Pulseaudion RTP stream to the network to allow listening in other rooms.
. Receiving RTP streams and mixing these into the local playback of the RPi.

Configuring this via the OpenElec Config plugin would be great also.

I tried to enable PulseAudio in OpenElec, but did not see any effect after the build.

As background please note 
. http://raspberrypi.stackexchange.com/questions/639/how-to-get-pulseaudio-running/1544#1544 and 
. http://raspberrypi.stackexchange.com/questions/639/how-to-get-pulseaudio-running/4022#4022 which describes how to do it.

I have setup a raspbian image using the instruction there to receive RTP streams.

**Comment by hcw70** [comment]
Just stumbled upon:
http://kodi.wiki/view/PulseAudio

which describes how to setup Kodi for PulseAudio and also have multi channel output.

Maybe its time now to have that option?

**Comment by fritsch** [comment]
Not really. Read the end of the wiki entry, especially the FAQ.

2015-06-05 17:38 GMT+02:00 Hauke Wintjen <notifications@github.com>:

> Just stumbled upon:
> http://kodi.wiki/view/PulseAudio
>
> which describes how to setup Kodi for PulseAudio and also have multi
> channel output.
>
> Maybe its time now to have that option?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/2058#issuecomment-109332884>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by hcw70** [comment]
So the point here is i really want to stream my audio to other devices. So the FAQ says i want PulseAudio. I Also want to try combined audio to several sources.
And i dont really care about 2.0 or more channels.

**Comment by fritsch** [comment]
Yeah, that's right for you, but not for 99 % of the other OE users. You
should go with a general purpose distro then. As PA by default would remove
all the functionality others wanted to use, meaning bitstream passthrough
and so on.

2015-06-05 17:54 GMT+02:00 Hauke Wintjen <notifications@github.com>:

> So the point here is i really want to stream my audio to other devices. So
> the FAQ says i want PulseAudio. I Also want to try combined audio to
> several sources.
> And i dont really care about 2.0 or more channels.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/2058#issuecomment-109339441>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B
