### ISSUE TITLE
Support acting as a Bluetooth A2DP target

### ISSUE THREAD

**Issue by cristim** [OpenELEC/OpenELEC.tv#2099]
# Use case

I am an user of an NFC-enabled phone, and I also own a NFC-enabled speaker that can pair with the phone by tapping. Many times when I arrive home I continue music playback from my phone into my NFC-enabled speaker simply by tapping them together. Considering the fact that I have a better sound system attached to my media center computer running OpenELEC, I wish I was able to continue playback onto the media center too.
# Requirements for this use case
- the OpenELEC machine should have Bluetooth hardware and a Bluetooth stack installed, including bluetooth A2DP sound enablers.
- there should be an NFC tag that would allow quickly pairing the device with the media center computer (trivial)
- OpenELEC should be configured to support acting as an A2DP target device, similar to a Bluetooth headset.
# Acceptance criteria
- there should be an user-friendly way to connect/pair a bluetooth device (phone/tablet) with a media center computer running OpenELEC, with NFC if available
- the media file being played on the mobile device should sound on the media center's speakers after a successful pairing.
# Technical challenges

So far OpenELEC is only providing Alsa builds, but all the tutorials I have seen are doing it using PulseAudio. PulseAudio makes all this pretty trivial, I tried it on my laptop and it's all working just as expected. It's likely that a PulseAudio build of OpenELEC might be required, unless it can also be configured to do it with Alsa alone(I wasn't able to find any documentation on how to do it). I talked to the developers on IRC and some of them are reluctant to using PulseAudio, but hopefully we can agree to make an additional PulseAudio Generic build for this kind of use case, and also supporting other networked-sound use cases that PulseAudio makes very easy.

**Comment by Whoopie** [comment]
xbian uses a2dp-alsa for bluetooth alsa, see https://github.com/xbianonpi/a2dp-alsa and https://github.com/belese/xbian-package-a2dp.
This works great and removes the pulseaudio dependency.

**Comment by stefansaraev** [comment]
not with bluez5.
