### ISSUE TITLE
Free MPEG2, VC1, DTS hardware decoding for Raspberry Pi

### ISSUE THREAD

**Issue by turexy** [OpenELEC/OpenELEC.tv#2149]
Hi,

Any chance you could implement this hack into your Pi release of OpenELEC?

http://pastebin.com/A7HB6h16

The Raspbmc did it so maybe OpenELEC could do the same:)

http://www.raspbmc.com/2013/04/crack-for-mpeg2-vc1-dts-hardware-decoding/

Thanks
Raf

**Comment by 20kdc** [comment]
possible idea: just reboot with different random values until it works...
April fools issue or not, the whole thing really is madness. Hardware blocks that decide not to work without a key...
