### ISSUE TITLE
Shutdown Issue

### ISSUE THREAD

**Issue by dayton967** [OpenELEC/OpenELEC.tv#2152]
Here's the system Configuration
Openelec 3.0.0
Zotac AD10, connected via HDMI to my televisio, using a logitech harmony 650

When shutting down, if the Television goes off first, xbmc.bin segfaults and loops through a start up and segfault repeatedly, when it receives the "74 0 KEY_POWER devinput".

Apr  1 14:04:10 openelec user.info kernel: [   68.447070] xbmc.bin[1840]: segfault at 10 ip 0000000000ebe650 sp 00007f7c19c03d80 error 4 in xbmc.bin[400000+108b000]
Apr  1 14:04:11 openelec user.info kernel: [   69.659704] xbmc.bin[1856]: segfault at 10 ip 0000000000ebe650 sp 00007f9bee86fd80 error 4 in xbmc.bin[400000+108b000]
Apr  1 14:04:12 openelec user.info kernel: [   70.886754] xbmc.bin[1872]: segfault at 10 ip 0000000000ebe650 sp 00007fd1d37fdd80 error 4 in xbmc.bin[400000+108b000]
Apr  1 14:04:13 openelec user.info kernel: [   72.006014] xbmc.bin[1888]: segfault at 10 ip 0000000000ebe650 sp 00007f92420d4d80 error 4 in xbmc.bin[400000+108b000]
Apr  1 14:04:14 openelec user.info kernel: [   73.126017] xbmc.bin[1904]: segfault at 10 ip 0000000000ebe650 sp 00007fa4633a9d80 error 4 in xbmc.bin[400000+108b000]
Apr  1 14:04:15 openelec user.info kernel: [   74.238299] xbmc.bin[1920]: segfault at 10 ip 0000000000ebe650 sp 00007f8f477fdd80 error 4 in xbmc.bin[400000+108b000]

**Comment by mrdominuzq** [comment]
still have the problem on the latest :)?

**Comment by dayton967** [comment]
I haven't seen it in awhile
