### ISSUE TITLE
Tevii S480 stucks from time to time (Tevii 660)

### ISSUE THREAD

**Issue by Krautmaster** [OpenELEC/OpenELEC.tv#2496]
Installed Openelec 3.1.3 - with a Tevii S480 V2.1 - had heavy stuttering from time to time, like evry 2 minutes strange atrefacts and lags for around 10 seconds.

Card:

OpenELEC:~ # dmesg | grep dvb
[    2.652320] dvb-usb: found a 'TeVii S660 USB' in cold state, will try to load a firmware
[    2.663658] dvb-usb: downloading firmware from file 'dvb-usb-s660.fw'
[    2.824769] dvb-usb: found a 'TeVii S660 USB' in warm state.
[    2.824850] dvb-usb: will pass the complete MPEG2 transport stream to the software demuxer.
[    3.157467] dvb-usb: MAC address: 00:18:bd:5a:c4:d9
[    3.179126] dvb-usb: schedule remote query interval to 150 msecs.
[    3.179129] dvb-usb: TeVii S660 USB successfully initialized and connected.
[    3.179149] dvb-usb: found a 'TeVii S660 USB' in cold state, will try to load a firmware
[    3.179176] dvb-usb: downloading firmware from file 'dvb-usb-s660.fw'
[    3.334659] dvb-usb: found a 'TeVii S660 USB' in warm state.
[    3.334731] dvb-usb: will pass the complete MPEG2 transport stream to the software demuxer.
[    3.601575] dvb-usb: MAC address: 00:18:bd:5a:c4:da
[    3.618029] dvb-usb: schedule remote query interval to 150 msecs.
[    3.618033] dvb-usb: TeVii S660 USB successfully initialized and connected.
[    7.760347] ds3000_firmware_ondemand: Waiting for firmware upload (dvb-fe-ds3000.fw)...
[    8.331013] ds3000_firmware_ondemand: Waiting for firmware upload (dvb-fe-ds3000.fw)...

Exchanged the firmware files and seems to be better to fine now..
Using this file now:

DOWNLOAD_URL="ftp://night.dyndns.org/htpc_test/files/"
wget -c $DOWNLOAD_URL/tevii_ds3000.tar.gz > /dev/null 2>&1
    tar xfv tevii_ds3000.tar.gz > /dev/null 2>&1
    sudo cp tevii_ds3000/dvb-fe-ds3000.fw /lib/firmware/ > /dev/null 2>&1
    rm /tmp/tevii_ds3000.tar.gz > /dev/null 2>&1
    rm -R /tmp/tevii_ds3000 > /dev/null 2>&1

=> ftp://night.dyndns.org/htpc_test/files/tevii_ds3000.tar.gz

Edit Can report after ~ 15 min that the issue seems to be gone with that fw files.

**Comment by polojoe** [comment]
Hi @Krautmaster 

did you find out anything?

**Comment by Krautmaster** [comment]
hm sadly my tv card isnt availiable right now. Its dilive driver in a ubuntu based tv server. Switched from vdr to tvheadend.

**Comment by polojoe** [comment]
I also switched from vdr to tvheadend, no problems any more!
