### ISSUE TITLE
python-lxml should be installed

### ISSUE THREAD

**Issue by mbr** [OpenELEC/OpenELEC.tv#2661]
At the moment, there are four popular parsers for XML/HTML:

* html5lib (2k downloads/day)
* ElementTree in the stdlib
* BeautifulSoup (4k downloads/day)
* lxml (30k downloads/day)

html5lib doesn't seem to appear as widespread, and BeautifulSoup has a reputation of being somewhat slow. stdlib-ElementTree occasionally stumbles over badly formatted HTML. Also, lxml is way faster

For this reason lxml seems rather popular (5x that both BeautifulSoup and html5lib combined), having tried all solutions myself, I can say as well that I vastly prefer lxml.

HTML-parsing is a core functionality for most addons that scrape stuff from the web and display the results. Some will have very long run times mainly due to XML parsing. lxml's interface and feature-completeness is also unrivaled by its competitors.

For this reason, it'd be nice to have lxml available per default. So far I've found a patch that I'm trying out right now (without any results, compiling takes quite a while):

* http://openelec.tv/forum/90-miscellaneous/63961-add-binary-python-modules-to-openelec (scroll to the bottom)

Some addons are (maybe carelessly?) already written using lxml, maybe I can try to find a list of some later on.

Still, lxml would be *very* nice to have.

--
Some anecdotal links:

* http://www.animeftw.tv/forums/xbmc-plugin-support/topic-3294/ (about the speed relevance)
* http://forum.xbmc.org/showthread.php?tid=60031&page=3 (ease of use, cssselect is a huge plus)
* https://mail.python.org/pipermail/python-dev/2009-March/086792.html (discussion about including lxml into the python stdlib)

**Comment by mrdominuzq** [comment]
Not Even a thanks to @stefansaraev 
thats not nice ;)

**Comment by mrdominuzq** [comment]
what about this @stefansaraev 

been here a long time :)

**Comment by stefansaraev** [comment]
keep open. but I have no time for this, really

**Comment by mrdominuzq** [comment]
it would be nice if any of those people who put a +1 on this would test and reply back :)

**Comment by chewitt** [comment]
I'm closing this ticket down due to lack of update. If this is still wanted as an addition to core builds one of you needs to submit a PR with the changes so it can be reviewed/merged. Thanks.
