### ISSUE TITLE
joystick.WiiRemote.xml keymap being loaded but not "added" in 3.2.4(stable)

### ISSUE THREAD

**Issue by ghat** [OpenELEC/OpenELEC.tv#2828]
hi

The Wiimote keymapping in the 3.2.* series is not what it used to be with default XBMC any more.. some investigation leads to the fact that the wiimote keymap is being loaded but not being added as seen in the log below.

The Wiimote connects over BT, perfectly but the keymapping is all mixed up inspite of having the correct keymap file. I believe it is not being recognized properly, hence its applying the wrong keymap

21:47:02 T:140096467375936    INFO: load keymapping
21:47:02 T:140096467375936    INFO: Loading special://xbmc/system/keymaps/appcommand.xml
21:47:02 T:140096467375936    INFO: Loading special://xbmc/system/keymaps/gamepad.xml
21:47:02 T:140096467375936    INFO: Loading special://xbmc/system/keymaps/joystick.Alienware.Dual.Compatible.Controller.xml
21:47:02 T:140096467375936    INFO: Loading special://xbmc/system/keymaps/joystick.AppleRemote.xml
21:47:02 T:140096467375936    INFO: Loading special://xbmc/system/keymaps/joystick.Harmony.xml
21:47:02 T:140096467375936    INFO: Loading special://xbmc/system/keymaps/joystick.Interact.AxisPad.xml
21:47:02 T:140096467375936    INFO: Loading special://xbmc/system/keymaps/joystick.Logitech.RumblePad.2.xml
21:47:02 T:140096467375936    INFO: Loading special://xbmc/system/keymaps/joystick.Microsoft.Xbox.360.Controller.xml
21:47:02 T:140096467375936    INFO: Loading special://xbmc/system/keymaps/joystick.Microsoft.Xbox.Controller.S.xml
21:47:02 T:140096467375936    INFO: Loading special://xbmc/system/keymaps/joystick.PS3.Remote.Keyboard.xml
21:47:02 T:140096467375936    INFO: Loading special://xbmc/system/keymaps/joystick.Sony.PLAYSTATION(R)3.Controller.xml
21:47:02 T:140096467375936    INFO: Loading special://xbmc/system/keymaps/joystick.WiiRemote.xml
21:47:02 T:140096467375936    INFO: Loading special://xbmc/system/keymaps/keyboard.xml
21:47:02 T:140096467375936    INFO: Loading special://xbmc/system/keymaps/mouse.xml
21:47:02 T:140096467375936    INFO: Loading special://xbmc/system/keymaps/remote.xml
21:47:02 T:140096467375936    INFO: Loading special://masterprofile/keymaps/joystick.WiiRemote.xml
21:47:02 T:140096467375936    INFO: Loading special://profile/keymaps/joystick.WiiRemote.xml
21:47:02 T:140096467375936    INFO: Loading special://xbmc/system/Lircmap.xml
21:47:02 T:140096467375936    INFO: * Adding remote mapping for device 'mceusb'
21:47:02 T:140096467375936    INFO: * Adding remote mapping for device 'XboxDVDDongle'
21:47:02 T:140096467375936    INFO: * Adding remote mapping for device 'Microsoft_Xbox'
21:47:02 T:140096467375936    INFO: * Adding remote mapping for device 'PinnacleSysPCTVRemote'
21:47:02 T:140096467375936    INFO: * Adding remote mapping for device 'anysee'
21:47:02 T:140096467375936    INFO: * Adding remote mapping for device 'iMON-PAD'
21:47:02 T:140096467375936    INFO: * Adding remote mapping for device 'Antec_Veris_RM200'
21:47:02 T:140096467375936    INFO: * Adding remote mapping for device 'MCE_via_iMON'
21:47:02 T:140096467375936    INFO: * Adding remote mapping for device 'TwinHanRemote'
21:47:02 T:140096467375936    INFO: * Adding remote mapping for device 'linux-input-layer'
21:47:02 T:140096467375936    INFO: * Linking remote mapping for 'linux-input-layer' to 'cx23885_remote'
21:47:02 T:140096467375936    INFO: * Adding remote mapping for device 'mediacenter'
21:47:02 T:140096467375936    INFO: * Adding remote mapping for device 'devinput'
21:47:02 T:140096467375936   DEBUG: CButtonTranslator::Load - no userdata Lircmap.xml found, skipping

**Comment by chewitt** [comment]
Closing as we no longer support 3.x builds - please open a new ticket for 6.0.0 if this is still an issue
