### ISSUE TITLE
RPi build breaking - configure: error: *** POSIX caps headers not found

### ISSUE THREAD

**Issue by cpswan** [OpenELEC/OpenELEC.tv#2836]
From latest master (commit 9819fef6b11601a20d9faafc1069b935abddaefb), in INSTALL network AUTORECONF systemd...

checking for library containing dlsym... -ldl
checking sys/capability.h usability... no
checking sys/capability.h presence... no
checking for sys/capability.h... no
configure: error: **\* POSIX caps headers not found
make: **\* [release] Error 1

Last successful build was r16722-g1b111d2

**Comment by jawahardeee** [comment]
same error for me. How to solve ??

**Comment by lrusak** [comment]
@jamesmacwhite ```PROJECT=<something> ARCH=<something> ./scripts/clean libcap```
