### ISSUE TITLE
Port OpenELEC to PrismCube (open source Linux ARM set-top box)

### ISSUE THREAD

**Issue by Hedda** [OpenELEC/OpenELEC.tv#2866]
OpenELEC developers, this is a feature request for you to consider.

Please port OpenELEC to PrismCube Ruby, the new open source (Linux on ARM) DVB PVR/DVR set-top box from Marusys, who is also an offical sponsor of xbmc.org

http://www.prismcube.com
http://www.prismcube-community.net/board/index.php

PrismCube by Marusys is a DVB-S2 Twin-Tuner high-definition DVR/PVR set-top-box running native XBMC as its main media center GUI interface on-top of Linux for embedded systems. Released in October 2013, this first hardware model is marketed as "PrismCube Ruby" in Europe, North Africa, and Middle East, and it is also sold under different brand names such as "Kasys Prismcube Ruby", "AB IPBox Prismcube Ruby", and "Openbox Prismcube Ruby".

PrismCube Ruby firmware image is based on OpenEmbedded-Linux, and uses Marusys's own PVR backend software that integrated itself into XBMC's GUI, so currently the PVR GUI (OpenGL) elements on PrismCube are not part of native XBMC core code even though they use the same skin textures to get similar look and feel interface, a ported fork which Marusys calls "XBMC4STB" (XBMC for Set-Top-Boxes), which is the same name that Vu+ have given to their XBMC port too.

Third-party firmware images for PrismCube Ruby is also already being developed by the Black Hole Team, a team of independent developers of long popular community driven firmware images for Vu+-based set top-boxes.

**Comment by i3laze** [comment]
And here's a great device (first XBMC sattelite receiver) is on it's way into oblivion.
Last official firmware update was 06/2015.

I urge you to revive the device by merging it to OpenELEC project, while retaining current PVR/sat functionality.
