### ISSUE TITLE
Blackscreen after S3 on ZBOX AQ01 (AMD A4-5000)

### ISSUE THREAD

**Issue by taleteller** [OpenELEC/OpenELEC.tv#2933]
I am testing OpenELEC on a ZBOX AQ01 (nano PC AMD-A4-5000 Kamini APU). OpenELEC Version is: Generic x86_64 r17682 (Nightly)

Getting the system into S3 works fine, as does waking up, except for the integrated IR-Remote which is of no concern to this problem. Starting the Box afterwards results in a black screen. SSH and Samba are reachable, thus the system itself has started. Only XBMC is not returning on the screen. Xorg is only partially running.

This is a Xorg.log from a fresh start:
http://pastebin.com/NEPKG3bn

This is a Xorg.log after S3 wakeup and killing the previous Xorg process by hand:
http://pastebin.com/C2iQQE2c

After EDID Probing the X server runs into problems loading the DRI and GLX modules. Only a full restart can restore the system.

**Comment by chewitt** [comment]
closing as no update to the ticket in 17 months
