### ISSUE TITLE
serial port support (console and python)

### ISSUE THREAD

**Issue by everslick** [OpenELEC/OpenELEC.tv#2934]
there is no way to use the serial ports from openelec now. shell scripts miss a way to initialize the a serial port (no stty program) and python lacks the pySerial module. I'd like to control my sanyo z4 projector from xbmc via a custom addon or shell. pls add stty and pySerial.

**Comment by tatayet38** [comment]
Hello, i use this solution to command an Samsung screen:

#!/usr/bin/python
import os
#import serial
import time
#ser = serial.Serial(port='/dev/ttyUSB0', baudrate=9600)
print "screen on + DVI"
#screen on
os.system("echo -e \xAA\x11\xFE\x01\x01\x11 > /dev/ttyUSB0")
#ser.write("\xAA\x11\xFE\x01\x01\x11")
time.sleep( 0.5 )
#set mode DVI
os.system("echo -e \xAA\x14\xFE\x01\x18\x2B > /dev/ttyUSB0")
#ser.write("\xAA\x14\xFE\x01\x18\x2B")
