### ISSUE TITLE
Incorporate Valve's xpad patches

### ISSUE THREAD

**Issue by jazz1138** [OpenELEC/OpenELEC.tv#3003]
Any chance of incorporating the patches Valve has made to xpad to fix controller support under SteamOS before 4.0 is released. The patches fix the issue where when a wireless xpad controller is plugged in, 4 joystick devices are created, no matter how many are really
attached to the system. This also resolves the flashing LED's on the 360 Controller.

More info here:

http://thread.gmane.org/gmane.linux.kernel.input/33971

Apparently the patches are slated for release in the 3.15 Kernel.

**Comment by stefansaraev** [comment]
the patches are now in but not working well? closing this

**Comment by zzattack** [comment]
Correct. Maybe they should be reverted though. At least until the panics
are solved.
