### ISSUE TITLE
python platform.linux_distribution() returns an empty tuple

### ISSUE THREAD

**Issue by hostmaster** [OpenELEC/OpenELEC.tv#3013]
```python 
import platform
print platform.linux_distribution()
```
produces an empty tuple 
```
('', '', '')
```
In my case this breaks a platform detection logic in ansible.  I assume it should be something like 
('OpenELEC', '3.2.4', '')

**Comment by mrdominuzq** [comment]
Is there any reason why You want to do a platform detection ?

**Comment by mrdominuzq** [comment]
no answer in a long time :(
