### ISSUE TITLE
IMON LCD Backlight fails to deactivate

### ISSUE THREAD

**Issue by anoma** [OpenELEC/OpenELEC.tv#3092]
Fix detailed here:

http://tomstechcorner.blogspot.co.uk/2013/02/xbmc-and-imonlcd-backlight-does-not.html

Confirmed working although it is likely a smaller subset of the changes might achieve the same result.

**Comment by mrdominuzq** [comment]
does it still happen on latest ?:)

**Comment by anoma** [comment]
I still have the above fix in place so it still works. However I do not know if the changes are native yet.

**Comment by mrdominuzq** [comment]
any chance to do a test without fix? :)

**Comment by anoma** [comment]
Yup but not soon I am not even in the same country as the box this now.

**Comment by mrdominuzq** [comment]
no problem :)

just nice to keep issues updated :)

**Comment by anoma** [comment]
Reconfirmed as fix still required on official x64 5.0.8

**Comment by stefansaraev** [comment]
why is this not a pr.

**Comment by anoma** [comment]
last time we discussed it the fear was it broke other installs and it got left open for others to test and frankly after that point I forgot about it.

**Comment by anoma** [comment]
Why dont we just commit the fix? I was waiting for another tester before a PR but if none is forthcoming (obviously) we might as well apply fix.
