### ISSUE TITLE
Gotham betas boot to striped grey screen (AMD)

### ISSUE THREAD

**Issue by dimangi** [OpenELEC/OpenELEC.tv#3096]
All five betas so far boot to to striped grey screen (as posted here http://openelec.tv/forum/120-news-announcements/70282-beta-openelec-4-0-beta-5-released?start=45#103139 ).

FM2A75M-ITX, A6-5400K, TV connected with HDMI, 3.2.4 works fine, xbmcbuntu has the same issue.

xrandr gives no output
xorg.log > http://sprunge.us/BKfe

**Comment by sakos** [comment]
I would like to reopen this issue.
The same fault is still present in OE 5.0.1
See this topic: http://openelec.tv/forum/64-installation/75141-garbled-pink-screen-after-first-boot#130618

**Comment by fritsch** [comment]
Does Ubuntu 14.10 boot on your system? You can try with the live cd?

**Comment by sakos** [comment]
No, It does not boot either. It ends up in a similar scrambled screen.

**Comment by fritsch** [comment]
Yeah -> bugs.freedesktop.org - it's sadly an upstream kernel issue. You can
file it also with Ubuntu if you want.

2015-02-10 17:47 GMT+01:00 sakos <notifications@github.com>:

> No, It does not boot either. It ends up in a similar scrambled screen.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3096#issuecomment-73734981>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B
