### ISSUE TITLE
boblightd needs patch to support multiple Lightpack devices

### ISSUE THREAD

**Issue by wohali** [OpenELEC/OpenELEC.tv#3099]
By applying [this patch](https://github.com/timsat/boblight-for-enigma2/commit/96c2f70d93f4b96bfd133541e4899ca7bfc6eb0c.patch) to your boblightd sources, boblightd will support multiple Lightpack devices at the same time.

References:

  * http://github.com/timsat/boblight-lightpack/issues/4
  * http://openelec.tv/forum/85-boblightd/70347-fixing-boblightd-for-multiple-lightpack-devices

**Comment by mrdominuzq** [comment]
shouldn't this be upstream on boblight instead of patch here?

**Comment by stefansaraev** [comment]
yes, see what will happen next few weeks with libcec (huge patches that probably nobody will rebase).

closing this.
