### ISSUE TITLE
3.95.4 + 3.95.5 HDMI Issue

### ISSUE THREAD

**Issue by mboni95** [OpenELEC/OpenELEC.tv#3119]
I have been running the Generic i386 build on a Dell Zino HD 410.  This system has a quad-core AMD Phenom II X4 P940 processor and ATI Mobility Radeon HD 5450 graphics built onto the motherboard. 

There was no issue with 3.95.3 but when running 3.95.4 + 3.95.5 I do not get any HDMI output.  When the boot loader runs, I get the syslinux text line at the top and then all goes blank.  I can hear the beeps/clicks from XBMC when moving across the menu when it is fully booted up but no onscreen display.

Manually downgrading to 3.95.3 brings everything back again.

Martin

**Comment by rdelmotte** [comment]
Hello,

I have the exact same issue as @mboni95 used to have: a Dell Zino HD 410 with no HDMI output.
Also, I just tried with the latest release, the x86_64 5.0.0.

Cannot get my hand on the 3.95.6 to try it out as @mboni95 did, though…

Can you please help me with this?

Thanks a lot,


Romain
