### ISSUE TITLE
Irtrans not working

### ISSUE THREAD

**Issue by deraaij** [OpenELEC/OpenELEC.tv#3186]
Hi,

Today I migrated to openelec 4.0 (Generic) and unfortunately the remote and LCD with the IRtrans driver is not working. 

The setting is not picked up at boot, it does not start:

Irserver, (e.g. "irserver -logfile /var/log/irserver.log -pidfile /var/run/irserver.pid -daemon /dev/irtrans0")
LCDd (e.g. "LCDd -c /storage/.config/LCDd.conf -d irtrans -s true")

and it starts XBMC as: "/usr/lib/xbmc/xbmc.bin --standalone -fs --lircdev /var/run/lirc/lircd" while it should be "/usr/lib/xbmc/xbmc.bin --standalone -fs --lircdev /var/run/lirc/lircd.irtrans"

If I manually start Irserver, LCDd and restart XBMC with lircd.irtans it works.

I think something is wrong in the setup scripts but I could not find them as there are not longer in /init...

Any idea?

**Comment by woutervdkolk** [comment]
Openelec 5.0.6: this issue still exists.
Just tested my workaround as posted earlier with Openelec 5.0.6. It works fine after replacing the "xbmc" arguments with "kodi".

**Comment by Dollso** [comment]
Hi, im using a D-Vine HTPC case with the irtrans Remote/VFD, with Openelec 5.0.8 installed, I followed your steps above creating autostart.sh, made executable, edited it with the following:

#!/bin/sh
irserver -logfile /var/log/irserver.log -pidfile /var/run/irserver.pid -daemon /dev/irtrans0
LCDd -c /etc/LCDd.conf -d irtrans -s true
rm /run/openelec/kodi.conf
echo "XBMC_ARGS="\""--lircdev /run/lirc/lircd.irtrans"\" > /run/openelec/kodi.conf

Changing xbmc.conf to kodi.conf in both instances?

This didn't work for me, so i also edited the remote.conf file and changed lirc to irtrans, still nothing.

Am i missing something or doing something incorrectly?

Thanks in advance!

**Comment by Dollso** [comment]
alao using the comand "irserver -loglevel 4 -debug_code /dev/ttyUSB0" i get the following:

Init Server Socket done
IRServer64 Version 6.03.08
Init Events done
Opening Device: /dev/ttyUSB0
IRTRans Send Done: 1
Name   :
Version: D5.08.10
FW SNo : 20021
Capab  : Power On;
FW Cap : 0x3c8019
USB SNo:
Node   : /dev/ttyUSB0

Init communication ...
[ 0]:                      D5.08.10     SN: 20021
Chdir to DB OK
Read routing OK
Read Switches OK
Open DIR: 12
Get Dirent: 120
Remote irtrans              compiled:     1 Timings -     33 Commands
Remote mediacenter          compiled:     1 Timings -     49 Commands
Get Dirent: 0
Total:   2 Remotes  -   2 Timings -   82 Commands -    0 Calib. Commands
         0 Togglec. -   0 CCF Data -   0 CCF RAW  -    0 CCF Error
IRTRans Send Done: 1
IRTRans Send Done: 1

**Comment by chewitt** [comment]
closing old tickets with no update.. should the issue still exist on a current release please start a forum thread, thanks.

**Comment by ElMatthews** [comment]
Just checked it today with OpenElec 6. Seems to work with:
#!/bin/sh
irserver -logfile /var/log/irserver.log -pidfile /var/run/irserver.pid -daemon /dev/irtrans0
LCDd -c /etc/LCDd.conf -d irtrans -s true

in /storage/.config/autostart.sh. The rest was already present in the config file.
