### ISSUE TITLE
Raspberry Pi: Openelec 4.0.3 Black screen with (certain) video files

### ISSUE THREAD

**Issue by lolboy** [OpenELEC/OpenELEC.tv#3270]
As reported in the forum by some users, some video files will stay black with sound playing.

For someone, changing the aspect ratio worked. Testing with my RPi on an 4:3 screen, this obviously didn't do the trick for me, but zooming out below 0.92 instantly gives me a working picture every time, with any video file.

Further inspecting many, many working and nonworking video files, it seems that files above a certain width/height stay black until zoomed out
Files with 360p, 480p, 720p play fine without adjustment.
Files with 1080p stay black until zoomed out.

I could reproduce the above mentioned effect with a fresh and clean (4.0.3) installation.

Seeing that for others, the change of aspect mode worked, while for me it was zooming out, this problem might be isolated to screens with certain aspect ratios (mine is 4:3).

**Comment by stefansaraev** [comment]
I forgot to close this. closing now.
