### ISSUE TITLE
[rfe] add adjtimex

### ISSUE THREAD

**Issue by djzort** [OpenELEC/OpenELEC.tv#3292]
adjtimex actually reduces clock drift by calculating the difference between hardware and system clocks - then reconciling them. The end result is far less drift or perhaps eliminated.

debian has convenient scripts which will measure the clocks and spit out the /etc/adjtime file which saves the drift data for later use.

this perhaps a pedantic enhancement, but debian has done the heavy lifting such that openelec's init scripts would simply need to run their script if /etc/adjtime isnt present

**Comment by mrdominuzq** [comment]
@stefansaraev do you have any opinion on this ?
from what i read this is not recommended since we are using ntp

**Comment by stefansaraev** [comment]
I dont want adjtimex in openelec.

**Comment by chewitt** [comment]
closing as there are no plans for this
