### ISSUE TITLE
OpenELEC Bluetooth Keyboard Support - Microsoft Wedge Keyboard

### ISSUE THREAD

**Issue by J876** [OpenELEC/OpenELEC.tv#3312]
To OpenELEC development team,

Can you please add better support for the Microsoft Wedge Bluetooth Keyboards?

When I try to pair it with my RaspberryPi XBMC reports Bluetooth I/O error and when I press any key on the keyboard, it sends "12345" no matter what I press.

????

I have the following USB bluetooth dongle:

Pluggable USB 2.0/1.1 to Bluetooth 4.0 Adaptor.  This is compatible with Linux according to the Manufacturer.

Please help.

Thanks in advance.

**Comment by StatusQuo** [comment]
I don't know why this issue is closed i have just the same problem with 5.95.5 Beta on RPI2
