### ISSUE TITLE
[Feature Request] RTL8188CUS

### ISSUE THREAD

**Issue by piiii** [OpenELEC/OpenELEC.tv#3319]
Hi guys,
i have a TP-link TL-WN725N V1 wifi adapter. And i have found that it uses the RTL8188CUS chipset. Can you please add the driver to OpenElec (for Raspberry Pi).

Device is :

Bus 001 Device 004: ID 0bda:8176 Realtek Semiconductor Corp. RTL8188CUS 802.11n WLAN Adapter

Kind Regards and Thanks in Advance.

**Comment by gres147679** [comment]
I'm having this exact same problem right now! Any ideas?
![image](https://cloud.githubusercontent.com/assets/2453371/7669222/2b92dbd6-fc1b-11e4-96ea-6e74d6c6cf48.jpg)
