### ISSUE TITLE
Driver Request - Adding of VID/PID for Sky Wireless Connector to ath6kl_usb driver

### ISSUE THREAD

**Issue by kashavsehra** [OpenELEC/OpenELEC.tv#3328]
I am trying to get openelec 3.2.4 working with a Sky Wireless Connector, which is basically an AR6004 based wireless dongle but with a custom VID/PID as follows:

usb 1-1.2.4: new high-speed USB device number 6 using dwc_otg
usb 1-1.2.4: New USB device found, idVendor=27d5, idProduct=0080
usb 1-1.2.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
usb 1-1.2.4: Product: USBWLAN
usb 1-1.2.4: Manufacturer: Qualcomm Atheros.
usb 1-1.2.4: SerialNumber: 12345678

I can type in the following commands and it appears to work fine:

root@raspbmc:/# modprobe ath6kl_usb
root@raspbmc:/# echo 27d5 0080 > /sys/bus/usb/drivers/ath6kl_usb/new_id
root@raspbmc:/# dmesg

However after a reboot, the VID/PID I have entered appear to be lost and are not saved. Can this VID/PID be added to future openelec builds for the Raspberry Pi? It would be very useful here in the UK as there are many of these wireless connectors around...

**Comment by mrdominuzq** [comment]
you should create a patch in the linux patch folder containing the link, compile and test
http://wiki.openelec.tv/index.php?title=Compile_from_source

**Comment by stefansaraev** [comment]
if still not working with OE 5.0.x, should be reported upstream (kernel bugzilla?)
