### ISSUE TITLE
[PVR] Hardware support request - TerraTec Cinergy HTC USB XS HD (USB DVB-T/DVB-C)

### ISSUE THREAD

**Issue by GittaHub** [OpenELEC/OpenELEC.tv#3349]
Hi OE-team,

I`d be happy to see that OE supports the TerraTec Cinergy HTC USB XS HD stick (http://www.terratec.net/details.php?artnr=Cinergy+HTC+USB+XS+HD&lang=en#.U6-zR4228Sg). I`m trying to utilize it with UPC Cablecom (CH) / DVB-C.

Current status: tvheadend sees the stick and does the initial muxes scan. Afterwards, mapping the DVB-services looks like this for every channel:

Jun 29 06:35:26.011 serviceprobe:            Eurosport: checking...
Jun 29 06:35:26.011 subscription: "serviceprobe" direct subscription to adapter: "Terratec DVB-C", network: "Rete Ticino 862", mux: "Rete Ticino 862: 346,000 kHz", provider: "upc", service: "Eurosport", quality: 100
Jun 29 06:35:36.011 subscription: "serviceprobe" unsubscribing
Jun 29 06:35:36.011 serviceprobe:            Eurosport: skipped: No input detected

I`m happy to supply all kinds of logs if needed.

Thanks
GittaHub

**Comment by mrdominuzq** [comment]
@GittaHub quite some months with no logs :)
