### ISSUE TITLE
[Feature Request] Hyperion Ambilight Raspberry Pi

### ISSUE THREAD

**Issue by kaiomatico** [OpenELEC/OpenELEC.tv#3354]
It is easy and supported to install hyperion packages as ambilight clone on raspbmc, and it works with some hacks on OpenELEC too, but officiall support for this plugin in the latest images would be a great feature to have in my opinion.

**Comment by mrdominuzq** [comment]
https://github.com/Mikka20/service.multimedia.hyperiond

Maintained here.
Close this request please :)
