### ISSUE TITLE
Incorrect resolution when switching back from 3D to 2D on r-pi

### ISSUE THREAD

**Issue by Trakkat78** [OpenELEC/OpenELEC.tv#3371]
When stopping a 3D movie file (HSBS), the confluence screen appear only showing half the image on the entire screen when "Disable stereoscopic mode when playback is stopped" is enabled.

If "Disable stereoscopic mode when playback is stopped" is disabled, the resolution is still incorrect but the entire confluence image is displayed.

In both cases, a reboot of the R-Pi corrects the problem.

**Comment by chewitt** [comment]
closing old tickets with no update.. should the issue still exist on a current release please start a forum thread, thanks.
