### ISSUE TITLE
No HD Audio bitstreaming Intel Pentium G620T

### ISSUE THREAD

**Issue by cncb-gh** [OpenELEC/OpenELEC.tv#3385]
I am unable to bitstream DTS-HD and TrueHD audio in my MKVs to my Onkyo AVR via HDMI as discussed in this thread: http://openelec.tv/forum/68-audio/62627-linux-3-8-kernel-for-intel-hd-audio?limitstart=0#112803

This is a Pentium G620T CPU with Intel HD graphics which can bitstream DTS-HD in Windows. When I enable DTS-HD in the Advanced XBMC settings, I get no audio from files with DTS-HD (AVR says "analog" and outputs no sound).  If I disable DTS-HD in the settings I get the DTS core bitstreamed as expected.

Here is a log file showing that it correctly identifies all the HD audio codecs for my AVR: http://sprunge.us/PHNP

My eld file shows the correct codecs and I have tried the "disable-spdif-for-hd-audio.conf" workaround described in another forum thread with no success.

**Comment by chewitt** [comment]
closing due to length of time with no update
