### ISSUE TITLE
Lossless DTS/ HD MA does not work on OpenElec ( AMD HTPC)

### ISSUE THREAD

**Issue by kaosolid** [OpenELEC/OpenELEC.tv#3405]
I have OpenElec on AMD HTPC based and it's working perfectly put the Lossless audio not working.
I have another windows based HTPC and the Lossless audio works.
 Is it from my configration or Linux does not support Lossless audio.

**Comment by fritsch** [comment]
If you are still reading this, try: http://forum.kodi.tv/showthread.php?tid=259533
