### ISSUE TITLE
Zotac Remote - solution for all buttons working

### ISSUE THREAD

**Issue by piotrasd** [OpenELEC/OpenELEC.tv#3420]
Hi
Zotac's nettops are very popular many users use with Openelec
topic about not fully working remote (missing buttons etc.) was few time touched on forum openelec
I found solution

So i have please to add this patch

https://github.com/FernetMenta/lirc/commit/cf9027d7052f31ddfeb3e90c62c822381a37fde8.patch

this change also need add to udev rule (because default is recognized like keyboard)

for old one 
<code>SUBSYSTEM=="usb" , ATTRS{idVendor}=="0471", ATTRS{idProduct}=="20cc", SYMLINK+="remote", ACTION=="add"</code>

I: Bus=0003 Vendor=0471 Product=20cc Version=0100
N: Name="PHILIPS MCE USB IR Receiver- Spinel plus"
P: Phys=usb-0000:00:12.0-2/input0
S: Sysfs=/devices/pci0000:00/0000:00:12.0/usb4/4-2/4-2:1.0/input/input2
U: Uniq=
H: Handlers=sysrq kbd event2
B: PROP=0
B: EV=120013
B: KEY=c0000 400 0 0 0 0 58000 8001f8 4000c004 e0beffdf 1cfffff ffffffff fffffffe
B: MSC=10
B: LED=1f

for new one
<code>SUBSYSTEM=="usb" , ATTRS{idVendor}=="0471", ATTRS{idProduct}=="2168", SYMLINK+="remote", ACTION=="add"</code>

I: Bus=0003 Vendor=0471 Product=2168 Version=0111
N: Name="PHILIPS OVU710023"
P: Phys=usb-0000:00:1d.0-1.4/input0
S: Sysfs=/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.4/2-1.4:1.0/0003:0471:2168.0001/input/input5
U: Uniq=
H: Handlers=sysrq kbd mouse0 event2
B: PROP=0
B: EV=120017
B: KEY=c0000 40000000000 30000 58000 8001f84000c004 e0beffdf01cfffff fffffffffffffffe
B: REL=3
B: MSC=10
B: LED=1f

topic on forum with solution
http://forum.xbmc.org/showthread.php?tid=133071

actual Openelec - dmesg (remote)

[    3.418756] input: PHILIPS OVU710023 as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.4/2-1.4:1.0/0003:0471:2168.0001/input/input5
[    3.420305] hid-generic 0003:0471:2168.0001: input,hiddev0,hidraw0: USB HID v1.11 Keyboard [PHILIPS OVU710023] on usb-0000:00:1d.0-1.4/input0

**Comment by mrdominuzq** [comment]
zotac has been merged to upstream lirc.

so this should be a "package update" but as stated on lirc "python3-PyYAML is strongly recommended. lirc builds without it, but crippled (no table.html or lirc.hwdb, lirc-setup doesn't work)"

so i'm not sure if it works

**Comment by Schaussi** [comment]
Would really appreciate it if we could use the OVU710023 receivers, as I am currently running out of working OVU710001 models...
Is there a chance that it could be included in one of the next upcoming releases?

**Comment by mmdl** [comment]
also +1 for adding that support

**Comment by piotrasd** [comment]
i foung this patch and almost is ok, only i 2 place i get field, maybe someone could fix ?
https://raw.githubusercontent.com/DestroyFX/nxtoo-portage/master/app-misc/lirc/files/lirc-0.9.0-add-zotac-support.patch

**Comment by fritsch** [comment]
What about you?

2015-03-02 19:03 GMT+01:00 piotrasd <notifications@github.com>:

> i foung this patch and almost is ok, only i 2 place i get field, maybe
> someone could fix ?
>
> https://raw.githubusercontent.com/DestroyFX/nxtoo-portage/master/app-misc/lirc/files/lirc-0.9.0-add-zotac-support.patch
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3420#issuecomment-76764225>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by sraue** [comment]
we use already a patch to the kernel to support Zotacs remote. Which buttons dont work? We dont use lirc at all for MCE based and similiar remotes, instead we use the kernel event drivers

**Comment by sraue** [comment]
we use already a patch to the kernel to support Zotacs remote. Which buttons dont work? We dont use lirc at all for MCE based and similiar remotes, instead we use the kernel event drivers

**Comment by sraue** [comment]
we use already a patch to the kernel to support Zotacs remote. Which buttons dont work? We dont use lirc at all for MCE based and similiar remotes, instead we use the kernel event drivers

**Comment by sraue** [comment]
we use already a patch to the kernel to support Zotacs remote. Which buttons dont work? We dont use lirc at all for MCE based and similiar remotes, instead we use the kernel event drivers

**Comment by piotrasd** [comment]
yes i saw this patch spineplus 0.2 .... but only few buttons works :( arrows, back, ok etc. 
tomorrow i try make full list button which work

**Comment by sraue** [comment]
if Vendor=0471 Product=2168 is something like a zotac remote/receiver, can anypoint give me a ebay/amazon product link to this exact combo?

**Comment by piotrasd** [comment]
i have 3-4 all from zotac's but doesn't have this same product number. Anyway i remeber this few buttons works on all ...

**Comment by chewitt** [comment]
closing old tickets with no update.. should the issue still exist on a current release please start a forum thread, thanks.
