### ISSUE TITLE
Full RGB colour range broken on Intel

### ISSUE THREAD

**Issue by trisk** [OpenELEC/OpenELEC.tv#3445]
On a fresh install of 4.1.4, the 'Use limited color range (16-235)' video output option is initially unchecked. Toggling the option does make the screen appear brighter so it did appear to be functioning. However, when I disabled it again and configured my TV input to use the full RGB range, pure black was displayed as dark grey. Clearly the RGB values were still being limited.

I checked `xrandr --props` and it showed that the 'Broadcast RGB' property for the output (HDMI1) was set to 'Automatic':

        Broadcast RGB: Automatic
                supported: Automatic, Full, Limited 16:235

It remains on 'Automatic' regardless of the setting in XBMC.

Running `xrandr --output HDMI1 --set 'Broadcast RGB' 'Full'` fixes the black level for the picture and appears to produce the correct colours. It appears the driver output setting is correct and the setting in XBMC is controlling some other RGB scaling.

Upgrading to 4.1.5 did not change anything. I still need to run xrandr from autostart.sh as a workaround.

FWIW, this is a laptop with an internal LVDS display as well as HDMI outputs (The 'Switch off other monitor' option doesn't appear to do anything).

**Comment by trisk** [comment]
Both the driver and Kodi scale values to the same range (16-235) and produce the same result for the display. The software mechanism is consistent across platforms.

**Comment by fritsch** [comment]
That's wrong.

Kodi does not scale at all, it uses full range by default. It's only scaled
if "Use Limited Range" is ticked - which also only works if VAAPI
Rendermethod is not used ... Intel's driver is default on Limited Range,
that's right.

"Use Limited Range" in kodi settings only makes sense anyways if the GPU is
set to Full and the TV to limited. Remember you need to disable Use VAAPI
Rendermethod to have the kodi setting an affect.

Only other combination that makes sense is: Use Prefer VAAPI Rendermethod
enabled, TV set to full range, xorg driver set to full range.

2015-01-22 0:36 GMT+01:00 Albert Lee <notifications@github.com>:

> Both the driver and Kodi scale values to the same range (16-235) and
> produce the same result for the display. The software mechanism is
> consistent across platforms.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3445#issuecomment-70944432>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by chewitt** [comment]
closing due to length of time with no update
