### ISSUE TITLE
Request for inclusion of rsync

### ISSUE THREAD

**Issue by kward** [OpenELEC/OpenELEC.tv#3453]
I'd like to request that the [rsync](http://rsync.samba.org/) command be included in the distribution. From time to time I need to sync files to or off my AppleTV, and right that is supported is scp. I'd especially use the command to make backups of the configuration on the device, as well as any other files I'd copied over to it.

**Comment by cbluth** [comment]
If I were to create a custom build that included rsync myself, how would I do that? Add an 'rsync' directory to packages?
