### ISSUE TITLE
Network does not connect automatically.

### ISSUE THREAD

**Issue by Mettbrot** [OpenELEC/OpenELEC.tv#3457]
With DHCP on  it does not connect automatically after boot. You have to manually select the "wired" connection ans click connect. With manually set ip network does work from the beginning but I have no internet connection. I believe this is since 4.2 beta 1. See here: http://openelec.tv/forum/120-news-announcements/72065-openelec-4-2-beta-1-released#112945

**Comment by stefansaraev** [comment]
should be fixed in 01bf6480e8a0a13089f41ed28a9055295066baa0

**Comment by dgenezini** [comment]
Can I apply the changes in the 5.0?
If not, is there a release date for this change?
