### ISSUE TITLE
2.1.5 Beta - Random Crash during VDPAU Playback

### ISSUE THREAD

**Issue by sonicnkt** [OpenELEC/OpenELEC.tv#3462]
Hey,
i now noticed several crashes of the whole System playing some Video files (AVC, H264 only i guess).
First the screen freezes audio still playing, then screen goes black with some colorful artifacts (no audio anymore) and shortly after this a complete reboot of the System.

This only happens if using VDPAU acceleration and didnt happen with the option deactivated. 
I never noticed this with 4.0.X and it has happen now several times running the latest beta and before that experimental.

My guess its related to the Video Drivers/Kernel because of the full crash. 

My System:
AMD Kabini APU: Athlon 5350

Attached is the xbmc log until the crash but i doesnt seem to be that usefull and the system.log.
XBMC: http://xbmclogs.com/show.php?id=287461
System: http://pastebin.com/WGwRUaj0

**Comment by mrdominuzq** [comment]
@mattystorey did you try @fritsch test build ? 

https://github.com/OpenELEC/OpenELEC.tv/issues/3763

**Comment by mattystorey** [comment]
Hi Fritsch, I found that I was only running with two gig of ram due to a dodgy ram dimm. Replaced the ram and it is more stable - I haven't tested properly. 

What is everyone else's ram allocation? Is there sufficient resources?

**Comment by chewitt** [comment]
closing due to length of time with no update
