### ISSUE TITLE
[Feature Request] CuBox-i : Internal bluetooth support

### ISSUE THREAD

**Issue by tifredfr** [OpenELEC/OpenELEC.tv#3488]
Hi,

I use the latest version of OpenELEC "devel-20140909224511-r19208-geb55ed4", the support is really starting to be perfect, except for the internal bluetooth.

The USB bluetooth works perfectly, but not the internal adapter.

I bring my help, if you need information about my order CuBox-i2eX  get things hoping full support for the next version.

Discussions on the problem found :
http://www.solid-run.com/community/topic461.html

Thank you in advance
kind regards

**Comment by zilexa** [comment]
@jenkins101 do you think it would be possible to use the internal Bluetooth as a BT speaker? Sending audio through optical out and/or hdmi? That would be pretty awesome!

**Comment by stefansaraev** [comment]
@zilexa no it would not be possible. and it wont be

for questions, use forums or irc, please
thanks.
