### ISSUE TITLE
PS3 Remote doesn't use ps3remote.evmap

### ISSUE THREAD

**Issue by dtowsey** [OpenELEC/OpenELEC.tv#3491]
Hello,

By default my ps3 remote was not recognised, and was defaulting back to default bluetooth keymap (not the ps3 keymap). Only the directional keys, play, select etc worked. Colours, display, skip buttons etc had not mapping.

Build: OpenELEC-Generic.x86_64-4.1.6
Remote Control Model: CECH-ZRCIE (bluetooth and IR model / Australia)

dmesg extract:

[   13.751584] Bluetooth: HIDP (Human Interface Emulation) ver 1.2
[   13.751597] Bluetooth: HIDP socket layer initialized
[   13.752220] input: Sony Computer Entertainment Inc BD Remote Control as /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.0/bluetooth/hci0/hci0:21/0005:054C:0306.0005/input/input15
[   13.752323] sony 0005:054C:0306.0005: input,hidraw2: BLUETOOTH HID v1.10 Gamepad [Sony Computer Entertainment Inc BD Remote Control] on 90:48:9a:4f:b2:a8

Temporary Fix:

modify /usr/lib/udev/rules.d/98-eventlircd.rules and append the detail below to the bluetooth section

-----// begin
ATTRS{name}=="Sony Computer Entertainment Inc BD Remote Control", \
  ENV{eventlircd_enable}="true", \
  ENV{eventlircd_evmap}="ps3remote.evmap"
-----// end

mksquash and upgrade

**Comment by mrdominuzq** [comment]
still a problem ?

**Comment by secretsmurf** [comment]
Yes It is still a problem, here I create the above pull request https://github.com/OpenELEC/OpenELEC.tv/pull/3918

**Comment by sraue** [comment]
should be fixed in https://github.com/OpenELEC/OpenELEC.tv/commit/5c70a3c0d66b3bbd882ba1decdf6fe38e208842a
