### ISSUE TITLE
STK1160 support does not work

### ISSUE THREAD

**Issue by tociek** [OpenELEC/OpenELEC.tv#3503]
Hi,

STK1160 support does not work in 4.1.6. I do have /dev/video0, but when I start hyperion with the grabber, I get a lot of "frame too small errors"

Frame too small: 686552 != 691200
Frame too small: 687444 != 691200
Frame too small: 686964 != 691200
(...)

lsusb and dmesg output can be found here:
https://github.com/OpenELEC/OpenELEC.tv/commit/d66494b9b4a998ac49fd23a7f316a09584b47b9c

Let me know if I can deliver some more details. I can also send you STK1160 for testing if needed.

Jacek

**Comment by slovdahl** [comment]
Is there any progress on this issue? It would be awesome to have working STK1160 support out of the box! OpenELEC 5.0.0 and 5.0.1 on my 1st gen model B RPi isn't able to detect the video grabber at all, nothing shows up in dmesg or lsusb.

**Comment by stefansaraev** [comment]
there is none. if you find out how to fix, please send us a PR. 
my opinion is still we shouldnt support this hardware at all. it has been added, I disagreed, then it didnt work and whoever added it doesnt care

**Comment by tociek** [comment]
Hi, there is a solution developed by Endo - he added frame scaling to the driver. 

Here is the patch: img.lightberry.eu/download/linux-049-STK1160-addFramescaling.patch

I agree that it would be great to have it included in official OE release (even better in official linux kernel)

**Comment by dalehamel** [comment]
i can confirm the patch provided by @tociek works in OE 5.0.3, which is what the latest version of rasplex is based on. I recommend merging it

**Comment by dalehamel** [comment]
@stefansaraev here's the patch that fixes the issue, verified working against OE 5.0.3 and master branch kernel (3.19)

**Comment by tociek** [comment]
Guys, is the patch in 5.0.8? it doesn't look like it - scaling does not work.

**Comment by mmodler** [comment]
Is there any reason why the patch hasn't made it into currect openelec? I have the frame to small issue.

Is there any chance the patch gets applied?
