### ISSUE TITLE
Bluetooth 4.0, Bluetooth low energy support

### ISSUE THREAD

**Issue by bam80** [OpenELEC/OpenELEC.tv#3514]
*Microsoft Arc Touch Surface Edition Mouse* doesn't work - this is Bluetooth low energy(BLE) device. The mouse pairs but cursor doesn't appear.

Tried it on OE Generic x86_64 4.2, 5.0 - I thought bluez 5 is enough to make it work, but seems like it is not.
Simple BT mouse (not BLE) works ok.

The logs:
[01_KODI.log]( http://sprunge.us/EGdT)
[02_System.log]( http://sprunge.us/giNP)
[03_Hardware.log]( http://sprunge.us/bYai)
[04_Audio.log  ](http://sprunge.us/QCCa)
[05_Network.log]( http://sprunge.us/MKJc)
[06_varlog.log  ](http://sprunge.us/ZMPJ)
[07_input.log  ](http://sprunge.us/PABF)
[08_Filesystem.log  ](http://sprunge.us/aQLc)
[09_Journal-cur.log  ]( http://sprunge.us/PKEH)
[10_Journal-prev.log ](http://sprunge.us/PjgG)

**Comment by mrdominuzq** [comment]
@bam80 any luck on The logs :)?

Aldo update to latest and See if it works

**Comment by bam80** [comment]
Oh, sorry - not so much. They just don't contain any interesting when I insert BT 4.0 dongle.. Will test it again though

**Comment by bam80** [comment]
Just tested - results are the same - mouse paired but no reaction on movement and buttons. I switched on mouse in input settings

**Comment by bam80** [comment]
PS: tested on Openelec 5.0

**Comment by mrdominuzq** [comment]
Are You using rpi ?

**Comment by bam80** [comment]
No, I am using x86-64 board

**Comment by mrdominuzq** [comment]
okay, provide the logs, then we see what we can find out :)

**Comment by bam80** [comment]
Here are the logs (see updated description). Didn't find anything about my mouse in them though - but in OpenELEC Bluetooth config window I can pair it (with no usefulness). Maybe bluetooth debugging can be switched on somehow?
And now I formalized the issue according to CONTRIBUTING.md - so please remove *Invalid* label if it's ok now

**Comment by bam80** [comment]
Any thoughts?
@stefansaraev, please, remove *Invalid* label from the issue

**Comment by bam80** [comment]
On pair and connect of the mouse, corresponding *Input* device file does not appear in /sys, as it does in case of Sony PS3 BD Remote. What can be the reason?

**Comment by mrdominuzq** [comment]
i dont think bluez supports mouse on LE yet

http://www.bluez.org/profiles/

**Comment by bam80** [comment]
Just enabling **CONFIG_UHID** feature in kernel config will do the trick. It will compile in user-space I/O driver for HID subsystem to the kernel. It's required for HID over GATT (HID on Bluetooth Low Energy).

**Comment by bam80** [comment]
Thank you @sraue

**Comment by brthurr** [comment]
Has this been enabled in 5.0.6? I'm having the same issue with this mouse and want to make sure that this wasn't something that had to be configured separately from the generic build. Thanks.

**Comment by stefansaraev** [comment]
no.
