### ISSUE TITLE
Sound Blaster F-Xi HD S/PDIF out not working out of the box with Openelec

### ISSUE THREAD

**Issue by bluebiker2000** [OpenELEC/OpenELEC.tv#3523]
Hi Openelec Dev Team,
I had a problem to get the S/PDIF output working with openelec version 4.2.0 and 4.2.1 (I have not tested older versions) and an Sound Blaster F-XI HD USB sound card. I opened a post in the openelec forum (http://openelec.tv/forum/68-audio/73170-sound-blaster-f-xi-hd-s-pdif-and-openelec-4-2-0) and found a solution with the help of another post in the xbmc forum (http://forum.xbmc.org/showthread.php?tid=199223). I combined the solution provided by user: anssi for the sound card "PHIREE U2" and the sound blaster F-Xi HD and created a patch for the ALSA file "USB-Audio.conf" used by openelec 4.2.1. It would be very nice if you can add it into the next version of openelec.
If you need further information just contact me and i will try to provide it. 
(Hope this are enough informations, because i have never done this before. Logfiles and Screenshots are available in the thread mentioned above)

regards
bluebiker aka bluebiker2000

spdif.patch can downloaded from the following url: http://tinyurl.com/pgwqc38

**Comment by fritsch** [comment]
@sraue ping, that patch in the zip is good to go from my side and valid for 5.0.1 - it fixes @bluebiker2000 's issue.

**Comment by fritsch** [comment]
See: https://github.com/OpenELEC/OpenELEC.tv/pull/3769
