### ISSUE TITLE
TP-Link Archer T4U-AC1200 Raspberry P

### ISSUE THREAD

**Issue by Peppi87** [OpenELEC/OpenELEC.tv#3529]
TP-Link Archer T4U-AC1200 don´t work with OpenElec 4.2.1 on Raspberry P Model B

dmesg:
http://pastebin.com/rfvd7YPJ

**Comment by mrdominuzq** [comment]
what about 5.0 ?

**Comment by Peppi87** [comment]
Its running on 5.0 :) thanks a lot
Am 16.01.2015 19:12 schrieb "Patrick Rasmussen" <notifications@github.com>:

**Comment by virajkanwade** [comment]
Doesn't work on 6.0? I removed the ethernet cable, attached the T4U and started the raspberry pi. The openelec network tab does not indicate anything other than wired networks.

**Comment by sraue** [comment]
@virajkanwade you think we look at closed ticket? whats done is done. if there is a problem create a new bug report with new logs from your system
