### ISSUE TITLE
XBMC in Openelec crashed when I open a mkv video.

### ISSUE THREAD

**Issue by chuhuanping** [OpenELEC/OpenELEC.tv#3530]
I Attached last couples lines in XBMC.log

09:07:16 T:2778588240  NOTICE: Opening Subtitle stream: 0 source: 1024
09:07:16 T:2690638928  NOTICE: Thread FileCache start, auto delete: false
09:07:17 T:2778588240  NOTICE: OMXClock using audio as reference
09:07:17 T:2733634640  NOTICE: Display resolution ADJUST : 1920x1080 (1920x1080) @ 23.98 - Full Screen (28) (weight: 0.000)
09:07:17 T:3059016224  NOTICE: Using GL_TEXTURE_2D
09:07:17 T:3059016224  NOTICE: GL: Using BYPASS render method
09:07:17 T:3059016224  NOTICE: GL: NPOT texture support detected
09:07:33 T:3059016224  NOTICE: Samba is idle. Closing the remaining connections
09:21:11 T:2733634640 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
09:28:04 T:2778588240 WARNING: Previous line repeats 1 times.
09:28:04 T:2778588240  NOTICE: COMXPlayer::OnExit()
09:28:04 T:2778588240  NOTICE: OMXPlayer: closing audio stream
09:28:04 T:2778588240  NOTICE: Closing audio stream
09:28:04 T:2725246032  NOTICE: thread end: OMXPlayerAudio::OnExit()
09:28:04 T:2778588240  NOTICE: OMXPlayer: closing video stream
09:28:04 T:2778588240  NOTICE: Closing video stream
09:28:04 T:2733634640  NOTICE: thread end: video_thread
09:28:04 T:2778588240  NOTICE: OMXPlayer: closing subtitle stream
09:28:04 T:2778588240  NOTICE: Closing subtitle stream
09:28:04 T:2778588240  NOTICE: COMXPlayer::OnExit() deleting demuxer
09:28:04 T:2778588240  NOTICE: COMXPlayer::OnExit() deleting input stream
09:28:04 T:3059016224  NOTICE: COMXPlayer: finished waiting
09:28:04 T:2778588240  NOTICE: Thread BackgroundLoader start, auto delete: false
09:28:05 T:3059016224  NOTICE: COMXPlayer: finished waiting
09:28:05 T:3059000400  NOTICE: Previous line repeats 1 times.
09:28:05 T:3059000400  NOTICE: Found 1 Lists of Devices
09:28:05 T:3059000400  NOTICE: Enumerated PI devices:
09:28:05 T:3059000400  NOTICE:     Device 1
09:28:05 T:3059000400  NOTICE:         m_deviceName      : HDMI
09:28:05 T:3059000400  NOTICE:         m_displayName     : HDMI
09:28:05 T:3059000400  NOTICE:         m_displayNameExtra:
09:28:05 T:3059000400  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
09:28:05 T:3059000400  NOTICE:         m_channels        : FL,FR
09:28:05 T:3059000400  NOTICE:         m_sampleRates     : 8000,11025,16000,22050,24000,32000,44100,48000,88200,96000,176400,192000
09:28:05 T:3059000400  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE,AE_FMT_AC3,AE_FMT_DTS,AE_FMT_EAC3
09:28:05 T:3059000400  NOTICE:     Device 2
09:28:05 T:3059000400  NOTICE:         m_deviceName      : Analogue
09:28:05 T:3059000400  NOTICE:         m_displayName     : Analogue
09:28:05 T:3059000400  NOTICE:         m_displayNameExtra:
09:28:05 T:3059000400  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
09:28:05 T:3059000400  NOTICE:         m_channels        : FL,FR
09:28:05 T:3059000400  NOTICE:         m_sampleRates     : 48000
09:28:05 T:3059000400  NOTICE:         m_dataFormats     : AE_FMT_FLOAT,AE_FMT_S32LE,AE_FMT_S16LE
09:28:05 T:2778588240  NOTICE: Thread JobWorker start, auto delete: true
09:28:09 T:3059016224  NOTICE: COMXPlayer: Opening: /var/media/sda1-usb-TOSHIBA_External/TV/2.Broke.Girls.S01E12.720p.BluRay.X264-FLHD.mkv
09:28:09 T:3059016224 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
09:28:09 T:2755839056  NOTICE: Thread OMXPlayer start, auto delete: false
09:28:09 T:2755839056  NOTICE: Creating InputStream
09:28:09 T:2733634640  NOTICE: Thread FileCache start, auto delete: false
09:28:09 T:2755839056  NOTICE: Creating Demuxer
09:28:09 T:2755839056  NOTICE: Opening video stream: 0 source: 256
09:28:09 T:2755839056  NOTICE: Creating video thread
09:28:09 T:2725246032  NOTICE: Thread OMXPlayerVideo start, auto delete: false
09:28:09 T:2755839056  NOTICE: Opening audio stream: 1 source: 256
09:28:09 T:2755839056  NOTICE: Creating audio thread
09:28:09 T:2925802576  NOTICE: Thread OMXPlayerAudio start, auto delete: false
09:28:09 T:2755839056  NOTICE: Opening Subtitle stream: 0 source: 1024
09:28:09 T:2873791568  NOTICE: Thread FileCache start, auto delete: false
09:28:10 T:2755839056  NOTICE: OMXClock using audio as reference
09:28:10 T:2725246032  NOTICE: Display resolution ADJUST : 1920x1080 (1920x1080) @ 23.98 - Full Screen (28) (weight: 0.000)
09:28:10 T:3059016224  NOTICE: Using GL_TEXTURE_2D
09:28:10 T:3059016224  NOTICE: GL: Using BYPASS render method
09:28:10 T:3059016224  NOTICE: GL: NPOT texture support detected

**Comment by mrdominuzq** [comment]
Did The latest anything for You guys ?

**Comment by mrdominuzq** [comment]
well should be closed and if the problem is still there a new issue should open with log files :)
