### ISSUE TITLE
4.2.1 RPi, Bluetooth Keyboard not reconnecting (Logitech K811)

### ISSUE THREAD

**Issue by jonathanphanle** [OpenELEC/OpenELEC.tv#3545]
I can connect my Logitech K811 to Bluetooth through service.openelec.settings, but after a reboot or after the keyboard sleeps/hibernates (I don't know the difference here), it doesn't reconnect. Instead, the keyboard's LED keeps blinking, indicating it isn't connecting to anything. It can connect through the settings no problem, but once it disconnects, it's as though the system doesn't remember my keyboard.

One feature of this keyboard is that it stores connections to three devices. That may add a wrinkle to the whole process, but it wasn't a problem on RaspBMC with bluez. Granted, I had to create a startup script to reconnect it on boot, but I don't know how to do that on OE.

My bluetooth adapter is the [ASUS BT211](http://www.asus.com/Networking/USBBT211_Mini_Bluetooth_Dongle/), based on Atheros AR3011.

I'm on OpenELEC 4.2.1 on RPi, but I don't know how to check my build or arch as per [these instructions](https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md).

Logfile
https://www.dropbox.com/s/tyx7mspovgccv65/log-2014-10-14-04.09.04.zip?dl=0

**Comment by bionicao** [comment]
I have the same issue with the PS3 BD remote on OpenElec 5.0 . I'm also using an autostart/cron script as a workaround.

**Comment by chewitt** [comment]
closing old tickets with no update.. should the issue still exist on a current release please start a forum thread, thanks.
