### ISSUE TITLE
OE 4.2/4.2.1 MJPEG video not playing correctly/green screen

### ISSUE THREAD

**Issue by knocktrade** [OpenELEC/OpenELEC.tv#3547]
When trying to play an MJPEG stream in OE final builds 4.2.0 and 4.2.1, I dont get a working video - only a green screen.  This was feature was working on OE 4.0.7 without an issues.  I've tried the same video on my macbook pro retina, mac mini, and Yoga 11s, using XMBC Gotham 13.2 Final on OS X and Windows 8, and all play the video fine.

What did you do?
  - Tried to play an MJPEG file.
What did you expect to happen?
  - Video to be played in OpenELEC, as it was working in OE 4.0.7
What happened instead?
  - Green screen of the video, sometimes some slight movement seen among the green, but not much else.

Debug Info:

Hardware:
Asus Chromebox M400U, 2GB RAM, (stock hardware, etc...), Standalone mode (non-dual boot).

Software Build:
Distribution: OpenELEC (official)
Version: 4.2.1
Architecture: Generic.x86_64

Sample MJPEG File used:
http://jjc.freeshell.org/turning_pages.avi

XBMC Debug Logs (After enabling debugs in XBMC):
http://sprunge.us/XVdF

**Comment by mrdominuzq** [comment]
Does it still happen on The latest,  I tried The file on rc Build, played fine

**Comment by mrdominuzq** [comment]
Any news :)?

**Comment by cw-kid** [comment]
Working for me fine with Kodi Helix / OpenElec 5.0.6 I can view / stream my Foscam IP camera again.
