### ISSUE TITLE
Upgrade libssh

### ISSUE THREAD

**Issue by squarooticus** [OpenELEC/OpenELEC.tv#3587]
Hey guys, could you maybe upgrade the libssh you're using for your builds at some point soon?

Brief summary: when I upgraded openssh-server on my file server from 6.6 to 6.7, SFTP from OpenELEC stopped working. Examining xbmc.log, I noted the following error:

```
kex error : did not find one of algos diffie-hellman-group1-sha1 in list curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1 for kex algos
```

This indicates that the only key exchange algorithm supported by the version of libssh linked into OpenELEC is no longer supported by OpenSSH, presumably for security reasons.

I was curious to see if libssh was just behind the times, but that is not the case. Examining the git history for libssh, this error message was changed to "kex error : no match for..." back in September of 2011. Since that time, several key exchange algorithms have been added and I'm guessing some security fixes have been made, so for a ton of reasons, not the least of which is interoperability, you should upgrade your build environment.

Using OpenELEC 4.2.1 generic x86_64.

**Comment by stefansaraev** [comment]
closing this, as libssh was upgraded long time ago.
