### ISSUE TITLE
gpio support via adding python-rpi.gpio

### ISSUE THREAD

**Issue by chillman90** [OpenELEC/OpenELEC.tv#3603]
Please integrate this small module to make gpio-use possible:
https://pypi.python.org/pypi/RPi.GPIO

Openelec is - when installed and fully configured - easy to use - even for people who have almost no computerskills. The possibility the add a powerswitch via a led, two resistors and a tactile switch 
(see: http://www.forum-raspberrypi.de/Thread-tutorial-hoch-und-runterfahren-mittels-taster-incl-status-led) would make it even easier for this group of (potential) users. 
For more experienced users it would be possible to write cool scripts to maybe light an led when a movie is being recorded. 
Maybe you could even integrate the script from the first link: 

"import RPi.GPIO as GPIO
import os
import time

# use the pin number as on the raspi board

GPIO.setmode(GPIO.BOARD)

# set pin 7 as output and HIGH, pin 5 is input

GPIO.setup(7, GPIO.OUT)
GPIO.output(7, True)
GPIO.setup(5, GPIO.IN)

# start the loop for every .5 seconds, waiting for LOW on pin 5
# then 2 short flashes with led to confirm and shutdown to sleep mode

while True:
        if not (GPIO.input(5)):
                GPIO.output(7, False)
                time.sleep(.1)
                GPIO.output(7, True)
                time.sleep(.1)
                GPIO.output(7, False)
                time.sleep(.1)
                GPIO.output(7, True)
                os.system("sudo shutdown -h now")
        time.sleep(.5)"

So only the hardware part for the switch would be required (rest of the installation guide in the first link). 
There was also an older request for this package and there were quite some comments, that people said they would like to have this module. I'm quite sure that neither xbian nor raspbmc has this script preconfigured so it would be a unique characteristic of openelec. 

Older request:
https://github.com/OpenELEC/OpenELEC.tv/issues/1955
In this older request it seems not to be too hard to integrate it for experts (sadly I'm not). 

Greetings from Germany

Chillman90

**Comment by mrdominuzq** [comment]
I think i saw a package.mk on The forum, try to look there.

**Comment by mrdominuzq** [comment]
okay i just put this together.
give it a test

http://pastebin.com/n5ue6wvF
