### ISSUE TITLE
OPENELEC + NUC + SUBTITLES GLITCH?

### ISSUE THREAD

**Issue by Haris1977** [OpenELEC/OpenELEC.tv#3641]
My machine: Intel NUC DN2820FYKH + 4 gb ram 
OE Image: OpenELEC-Generic.x86_64-4.2.1 (installation on usb stick)

Greetings. I have a "strange" problem with my subs. 

When i play a movie with extrernal subtitles (*.srt, either from nas or usb stick doesnt matter and in every language doesnt matter either) when the very first line of my subtitles appear i get a very small image stuttering/pause (like a small pause for milliseconds). This is happening ONLY on the very first line appears and not afterwards.

Can anyone reproduce it? Any ideas?

my log file: http://pastebin.com/zzWPdaY4

**Comment by mrdominuzq** [comment]
And now You should try latest :)

**Comment by Haris1977** [comment]
I think the problem has faded:)

**Comment by mrdominuzq** [comment]
Good to hear. Please Close if the issue is solved :)
