### ISSUE TITLE
Hama MCE Remote Control does not respond after standby

### ISSUE THREAD

**Issue by daffunn** [OpenELEC/OpenELEC.tv#3663]
Hi,
I am on OpenELEC release: Generic.x86_64-4.97.1 and after standby my remote control does not respond. If I plugin in my keyboard, everything works fine. Is it a lirc problem?

Logfiles:
https://www.dropbox.com/s/bceftmu5aaf1hzb/log-2014-12-04-13.07.23.zip?dl=0

Hope someone knows a solution?

**Comment by chewitt** [comment]
closing old tickets with no update.. should the issue still exist on a current release please start a forum thread, thanks.
