### ISSUE TITLE
USB IR "Keyboard" ignored if plugged in during boot

### ISSUE THREAD

**Issue by thedecibelkid** [OpenELEC/OpenELEC.tv#3675]
Deliberate duplicate of https://github.com/OpenELEC/OpenELEC.tv/issues/3589 which was closed for lack of evidence.

Evidence is here : In System.log you can see it seeing a "USB keyboard" so it must be getting part way there. http://thedecibelkid.com/junk/log-usb-ir-ignored-bootup.zip

Problem is IR devices not working if plugged in during a boot. Once the system is loaded you have to unplug and re-plug the usb dongle for it to start working.

**Comment by stefansaraev** [comment]
@popcornmix input hotpug is not supported on rpi, right ?

**Comment by popcornmix** [comment]
Hotplug should be fine. Connecting a keyboard to a running system works fine for me (I did that earlier today). Takes up to ten seconds for kodi to spot it.

The model B can reset when hotplugging a high-current USB device (e.g. wifi or dvb), but that shouldn't happen with a keyboard. Model B+ doesn't have this issue.

**Comment by stefansaraev** [comment]
ok. thanks ;)

**Comment by chewitt** [comment]
closing old tickets with no update.. should the issue still exist on a current release please start a forum thread, thanks.
