### ISSUE TITLE
Choppy playback on OE5 RC2

### ISSUE THREAD

**Issue by bluefuzz** [OpenELEC/OpenELEC.tv#3681]
I'm still getting choppy video playback on OE5 RC2 with certain files.  This is on a Shuttle XS35GS V3L - Intel Atom 1.86 GHz, AMD Radeon HD 7450 GPU, 4GB RAM.

Logfile: http://sprunge.us/ciJg

Cheers
Ian

**Comment by mrdominuzq** [comment]
Can You update to latest and See if there is any difference. Which files does it happen to ?

**Comment by bluefuzz** [comment]
The release version of OE5.0.0 has the same problem. It happens on most videos (although not all). I haven't found any specific pattern. Live TV is fine.

However Fritsch's testbuild from here https://github.com/OpenELEC/OpenELEC.tv/issues/3763 seems to fix the issue for me.

Cheers
Ian

**Comment by schumi2004** [comment]
@bluefuzz what kind of media are you playing?
avi, mkv, iso?

I noticed this with iso files only.

**Comment by bluefuzz** [comment]
I had stuttering with Video_TS.IFO (mpeg2), AVI (Xvid) and at least some MKV (h264)
MP4 (avc1) always played fine however.

Cheers
Ian

**Comment by mrdominuzq** [comment]
so everything is fine now :)?

**Comment by fritsch** [comment]
He should check this one - as I am interested on especially his paltform: https://github.com/OpenELEC/OpenELEC.tv/issues/3763#issuecomment-70926476

**Comment by bluefuzz** [comment]
Everything was fine in Fritsch's experimental build posted a couple of weeks ago but the build from yesterday is back to choppy/stuttering playback on everything except h264 as far as I can tell. It may be a little better than the release OE5, but not much (~20 fps instead of 10-15fps).

**Comment by fritsch** [comment]
Okay, so we have a HD 7450 GPU which has still issues. Can you make triple sure, that you tested my build?

**Comment by bluefuzz** [comment]
Well, I checked the systeminfo that it was your build from yesterday. I've just reverted to your previous build and everything is fine again ...

**Comment by chewitt** [comment]
closing due to length of time with no update
