### ISSUE TITLE
SPDIF Pass through not working on cubox-i4 with [RC] OpenELEC 4.97.2 (arm) build

### ISSUE THREAD

**Issue by omerra** [OpenELEC/OpenELEC.tv#3689]
I flashed [RC] OpenELEC 4.97.2 (arm) today to try it out on my cubox-i4.
Everything seems to work nicely, however when I set audio output to be SPDIF, I can only get the GUI and stereo sounds to work. When playing movies with DTS and DD no sound is heard.
I have a DD and DTS capable Receiver.
Previous version of OpenElec and GeeXbox that I had installed on the cubox-i worked fine with this kind of configuration. 
Notice that if pass through is disabled, sounds from movies work but in stereo.
Is this a known issue? 
Notice that video is connected through HDMI.
I turned on debug log, changed the settings to enable passthrough and played a movie with DD/AC3 sound.
The log file is available at:
https://www.dropbox.com/s/s4bq4o7sdnam3ct/log-2014-12-12-18.03.53.zip?dl=0

**Comment by mrdominuzq** [comment]
So this solved @omerra :)?

**Comment by tunf** [comment]
Can be closed as omerra mentioned it works.

**Comment by sraue** [comment]
thanks much
