### ISSUE TITLE
Display freeze when changing refresh rates at play / stop time

### ISSUE THREAD

**Issue by foresto** [OpenELEC/OpenELEC.tv#3690]
I'm testing on a CuBox-i4pro with an LG TV at 1080p. I have "Adjust display refresh rate to match video" enabled, my default refresh rate is 60Hz, and my test video file is 23.976fps.

When starting or stopping the test video, the display sometimes freezes. I can tell that Kodi is still running because I can hear the expected audio (from the test file if I just pressed Play or from the Kodi UI if I just pressed Stop and am blindly navigating the menus). Meanwhile, the screen is stuck displaying a single frame from the test video, or a black frame, or a single frame from the Kodi UI.

Occasionally, starting and stopping the test video a few more times will restore correct display behavior, but most of the time it doesn't help. Regardless of whether starting and stopping the test video restores the display, the TV reports that the refresh rate is being changed between 60Hz and 24Hz as I do so.

This problem occurs with OpenELEC 5.0 RC 2, aka OpenELEC-imx6.arm-4.97.2

Here are logs from one case when playback started normally but the display froze upon pressing stop:

01_XBMC.log
http://sprunge.us/afhd

02_System.log
http://sprunge.us/UWWd

03_Hardware.log
http://sprunge.us/iXGS

04_Audio.log
http://sprunge.us/LALZ

05_Network.log
http://sprunge.us/CUhM

06_varlog.log
http://sprunge.us/TVPB

07_input.log
http://sprunge.us/BCRj

08_Filesystem.log
http://sprunge.us/ENhK

09_Journal-cur.log
http://sprunge.us/gFiL

10_Journal-prev.log
http://sprunge.us/IMPM

This may be related to #3402.

**Comment by kazooless** [comment]
Is this fix going to be added to the official OpenElec download for CuBox soon? I think this is one of the problems I am experiencing on my Cubox i2ex. I am running 5.02 now.

**Comment by foresto** [comment]
I haven't seen this bug since I installed 5.0 on my i4pro.

**Comment by fritsch** [comment]
Was fixed long ago before the 5.0.x release.

2015-02-23 1:55 GMT+01:00 Forest <notifications@github.com>:

> I haven't seen this bug since I installed 5.0 on my i4pro.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3690#issuecomment-75476448>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by foresto** [comment]
Thanks, gents!
