### ISSUE TITLE
Black screen on resume, but killing XBMC / Kodi recovers: Zotac AD02 (Radeon HD 6310)

### ISSUE THREAD

**Issue by AdamWill** [OpenELEC/OpenELEC.tv#3697]
Ever since ~OpenELEC 3.x - it used to work with 2.x - quite often when I resume from suspend, the screen is black and interacting with XBMC / Kodi doesn't recover it. However, I can ssh into the system, and if I kill -9 the xbmc or kodi process, it respawns and displays correctly. I don't see anything immediately obvious in the journal, but I'll try and reproduce with debugging on and attach the logs soon (just wanted to file the issue before I forget about it again). Currently running 4.97.2 and still seeing this. Adapter is:

    VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Wrestler [Radeon HD 6310] [1002:9802]

**Comment by DavidKeller** [comment]
I'm running into the same issue.

# Bug description
1. Play and pause a movie located on a samba share.
2. Wait for the system to sleep.
3. Resume using official android remote controller.
4. Screen remains black while audio is still working fine.

# Workaround
`#pkill -9 xmbc.bin`

# System description

* OpenELEC (official) Version: 4.2.1
* `#lspci`

>00:00.0 Host bridge: Intel Corporation Atom Processor Z36xxx/Z37xxx Series SoC Transaction Register (rev 0e)
>00:02.0 VGA compatible controller: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display (rev 0e)
>00:14.0 USB controller: Intel Corporation Atom Processor Z36xxx/Z37xxx Series USB xHCI (rev 0e)
>00:1a.0 Encryption controller: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Trusted Execution Engine (rev 0e)
>00:1b.0 Audio device: Intel Corporation Atom Processor Z36xxx/Z37xxx Series High Definition Audio Controller (rev 0e)
>00:1c.0 PCI bridge: Intel Corporation Device 0f48 (rev 0e)
>00:1c.1 PCI bridge: Intel Corporation Device 0f4a (rev 0e)
>00:1c.2 PCI bridge: Intel Corporation Device 0f4c (rev 0e)
>00:1c.3 PCI bridge: Intel Corporation Device 0f4e (rev 0e)
>00:1f.0 ISA bridge: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Power Control Unit (rev 0e)
>00:1f.3 SMBus: Intel Corporation Device 0f12 (rev 0e)
>03:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 11)
>04:00.0 SATA controller: ASMedia Technology Inc. ASM1062 Serial ATA Controller (rev 02)

**Comment by mrdominuzq** [comment]
update latest test, if it still dosent work provide logs :)

**Comment by AdamWill** [comment]
oh, sorry, forgot I meant to attach them. lately I applied a workaround that just kills kodi on every resume from suspend, so I haven't cared as much, but I'll try and get around to it.

**Comment by mrdominuzq** [comment]
any logs :)?

**Comment by polojoe** [comment]
I had the same issue on ad02, solved by starting tv before waking up the box.

**Comment by chewitt** [comment]
closing due to length of time with no update

**Comment by AdamWill** [comment]
Sorry, I wound up getting newer hardware so couldn't debug this any further :(
