### ISSUE TITLE
Some mv4 files do not play hardware decoded on imx6 Cubox OE 5.0 RC2

### ISSUE THREAD

**Issue by aleX1964** [OpenELEC/OpenELEC.tv#3699]
This sample file ( https://www.dropbox.com/s/xlt1r4xej73b5i8/sample.mp4?dl=0 )  plays on Openelec 5.0 RC2 only when software decoding is switched on. I think that shouldn't be.
At the end of this debuglog you should find information: http://sprunge.us/dSWh

thanks 
aleXander

**Comment by chewitt** [comment]
closing as resolved upstream (some time ago)
