### ISSUE TITLE
libxml just build with specified zlib path

### ISSUE THREAD

**Issue by X4fyr** [OpenELEC/OpenELEC.tv#3709]
Hey,
I just can build, when I specify
```
--with-zlib="$SYSROOT_PREFIX/usr/include/"
```
in `packages/textproc/libxml2/package.mk`
I can't say what raises this problem, but while running libtool I throws errors about unknown references.

**Comment by sraue** [comment]
added in https://github.com/OpenELEC/OpenELEC.tv/commit/741721ab47892410e4a40df59979f5879a2f1a19
