### ISSUE TITLE
LADSPA plugins for ALSA

### ISSUE THREAD

**Issue by kentnielsen** [OpenELEC/OpenELEC.tv#3721]
Hi.

Is it possible to add BLOP and CMT plugins to OE?  They are needed for crossover (low/high-pass filter) when using analog multichannel output.  M-ch input on receivers (often) don't follow receiver's crossover.
For me this would be awesome!

More info http://alsa.opensrc.org/Low-pass_filter_for_subwoofer_channel_(HOWTO)

**Comment by chewitt** [comment]
I'm closing this ticket as there are no plans to add these at the current time. Thanks.
