### ISSUE TITLE
OE 5.0.X hangs randomly 

### ISSUE THREAD

**Issue by hussainalhaddad** [OpenELEC/OpenELEC.tv#3727]
whenever i start scanning from local info, it get some movies, around 20 maybe and then hangs and i have to force power it off.

it's a fresh install

latest KODI.log http://pastebin.com/ff75eQYA

**Comment by hussainalhaddad** [comment]
ok, this appears to be an issue with nvidia drivers, as it works great for hours on an identical system with ati card

**Comment by hussainalhaddad** [comment]
i was right... the new and updated nvidia drivers in 5.0.2 fixed my issue

**Comment by sraue** [comment]
thanks for the report
