### ISSUE TITLE
OpenELEC 5.0 Raspberry Pi - Airtunes crash

### ISSUE THREAD

**Issue by i-tek** [OpenELEC/OpenELEC.tv#3729]
Hello,

when starting OpenELEC with Airtunes sink turned on, my external computer (using pulseaudio) connected to this sink. I tried to turn it off via Settings->Services->Airtunes-->"Receive Airtunes Content". As soon as I did so, the complete Kodi froze. It was still possible to connect by using SSH and retrieve the logs.
It is very likely that this issue occurs on Desktop Kodi, too. Unfortunately I had no chance to verify this.

The logs were created with special logging for AUDIO and AIRTUNES.

kodi.log
https://gist.github.com/i-tek/2d89dfa4ce3c939484cd

Edit 1:
When stopping Airplay playback before trying to turn off the service, the crash still occurs.

**Comment by chewitt** [comment]
Closing because OE team are not responsible for Airplay issues in Kodi .. please report upstream to the Kodi devs via their forums.
