### ISSUE TITLE
Virtual suspend on Pi greyed out on OE 5

### ISSUE THREAD

**Issue by mcaptur** [OpenELEC/OpenELEC.tv#3734]
Cannot select virtual suspend on PI in power settings, option is greyed out.

**Comment by fritsch** [comment]
It's simply not there. Will come, when it is merged upstream.

2015-01-01 10:07 GMT+01:00 mcaptur <notifications@github.com>:

> Cannot select virtual suspend on PI in power settings, option is greyed
> out.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3734>.
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by popcornmix** [comment]
If you need that feature then use a Milhouse nightly build which includes it.
It's not considered well tested enough for official builds.

**Comment by mcaptur** [comment]
OK got confused.. Using Milhouse builds, but have problem where kodi
freezes shortly after resume from suspend.. Trying to go back in versions
to see which change introduced problem..

**Comment by popcornmix** [comment]
Report any issues in the Milhouse thread (http://forum.kodi.tv/showthread.php?tid=211501).
This is not the right place for reporting issues with custom builds.
