### ISSUE TITLE
Intel Wireless-N 7260 disconnects

### ISSUE THREAD

**Issue by dechief** [OpenELEC/OpenELEC.tv#3736]
After the move to kernel 3.17 and the wireless firmware iwlwifi-7260-ucode-23.10.10.0 the connection is not stable anymore. The connection terminates complete and initate new. Somtetimes only reboot bring it back.

OpenELEC 5.0 RC1 was the last build who worked with this Wlan Adpater.

This is the dmesg Output from 5.0 RC1

iwlwifi 0000:02:00.0: irq 46 for MSI/MSI-X
iwlwifi 0000:02:00.0: Direct firmware load for iwlwifi-7260-10.ucode failed with error -2
iwlwifi 0000:02:00.0: loaded firmware version 23.214.9.0 op_mode iwlmvm

With 5.0 Final iwlwifi-7260-ucode-23.10.10.0 is loaded.

Can a newer firmware driver be added to the nightlies? There is a newer firmware driver for the Intel Wireless-N 7260.

Direct download can be found here: http://wireless.kernel.org/en/users/Drivers/iwlwifi?action=AttachFile&do=get&target=iwlwifi-7260-ucode-23.11.10.0.tgz

**Comment by dechief** [comment]
still exists with 5.0.1. Wifi is not usable. In the meantime i have compiled 5.0.0 with kernel 3.16.3 on my own. This build works flawless.

**Comment by vhanadium** [comment]
Could you explain how to do that or share your build ?
My Intel NUC got this WLAN chipset.

**Comment by dechief** [comment]
This is my build OE 5.0.1 with kernel 3.16.3

http://1drv.ms/1v8Mtnh


To build from scratch you need a VM with Linux.

I started with this guide


http://wiki.openelec.tv/index.php/Compile_from_source


then make a checkout for 5.0.1 and make changes in two files

for the 3.16.3 kernel.









Von: vhanadium
Gesendet: ‎Samstag‎, ‎7‎. ‎Februar‎ ‎2015 ‎00‎:‎06
An: OpenELEC/OpenELEC.tv
Cc: Florian Urban





Could you explain how to do that or share your build ?
My Intel NUC got this WLAN chipset.

**Comment by dechief** [comment]
Please update the iwl firmware package. I have build a OE 5.0.5 with the newest Firmware driver and the disconnects are gone.

**Comment by fritsch** [comment]
@dechief Thanks for reporting - can you send a PR to us? a bump is very simple to accomplish.

**Comment by fritsch** [comment]
@sraue just seen it is packaged manually - please update - as filing upstream bugreports is much easier that way anyways.

**Comment by fritsch** [comment]
@dechief for the time being, create /storage/.config/firmware/ and put the new files in there - that way they will be prefered to the internal files.

**Comment by chewitt** [comment]
I'm closing this ticket due to elapsed time and because the Intel wireless firmwares we embed were updated in 6.0.1. Thanks.
