### ISSUE TITLE
OE 5.0 on NUC: no HDMI sound after resume from sleep 

### ISSUE THREAD

**Issue by edd--** [OpenELEC/OpenELEC.tv#3737]
Hi, I sometimes (mostly, not always) get no sound after resume from sleep:

using an intel NUC with openelec 5.0, audio over HDMI, had no problems with the Gotham releases.

Interesting note: When I have no sound and I go into settings -> system (not even sound but the default video item is checked when entering the system settings), the screen flashes for a moment and the sound is back ...

**Comment by edd--** [comment]
can you please let me know why this is labeled invalid ? Are there any rules I should follow ?

**Comment by fritsch** [comment]
https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md <- that was presented to you when filing this issue.

**Comment by edd--** [comment]
Ok, I hope this will help:


What did you do?
 - resume from sleep
What did you expect to happen?
- sound hearable
What happened instead?
-no sound
If I go into settings -> system (not even sound but the default video item is checked when entering the system settings), the screen flashes for a moment and the sound is back ... (I did this in koi.log around 13:28, resume from sleep without sound around 13:27)


OpenELEC version:
OpenELEC (official) - Version: 5.0.0, kernel: Linux x86 64-bit version 3.17.7

this is my kodi.log: 

http://pastebin.com/JyWChfUp

hardware.log:

http://pastebin.com/qnsdzDDW

audio.log:

http://pastebin.com/HELwspu0

**Comment by edd--** [comment]
I got a tip on the forum to try:

DISPLAY=:0 /usr/lib/kodi/kodi-xrandr --output HDMI1 --off

And then

DISPLAY=:0 /usr/lib/kodi/kodi-xrandr --output HDMI1 --auto

and it solves the problem ...

I'm using a HDMI splitter (sound amp) and this could cause the issue according to jamesw4, I'm not experiencing this in Gotham though ...

**Comment by jcjdammers** [comment]
Hi Edd,

I have the same problem.
Could you share the script that you created and provide the instructions where to place it?
That would be much appreciated. Thanks.

**Comment by edd--** [comment]
sure,

mkdir /storage/.config/sleep.d/

create a file called 01-reinit-hdmi.power with following contents:

#!/bin/sh
case "$1" in
   pre)
     ;;
   post)
     sleep 4; /usr/lib/kodi/kodi-xrandr --output HDMI1 --auto
     ;;
esac

afterwards do a chmod a+x /storage/.config/sleep.d/01-reinit-hdmi.power

You have to play a bit with the sleep delay, it depends how fast your HDMI device turns on ...
It could also be that your output is HDMI0 instead of HDMI1, first try the /usr/lib/kodi/kodi-xrandr --output HDMI1 --auto command manually to be sure ...

**Comment by MilhouseVH** [comment]
I'm also seeing this problem on recent master running on a Revo3700 (x86_64, ION2), will try the script but is there anything anyone needs to investigate this further?

**Comment by fritsch** [comment]
On an ION2 you can hardcode your EDID - i have written a howto for this on the forums, that way the gpu will always think it is connected to the AVR / TV and the races on resume are gone.

**Comment by MilhouseVH** [comment]
Thanks, do you mean this: http://wiki.openelec.tv/index.php?title=Config_EDID_nvidia ?

I think I may have to save that for a rainy day... looks rather long and complex!

**Comment by fritsch** [comment]
Nearly: http://openelec.tv/forum/68-audio/61795-setting-audio-to-hdmi-lost-depending-on-order-in-which-devices-are-turned-on#69329

the nvidia-xconfig is already included now by default

**Comment by chewitt** [comment]
closing due to length of time with no update
