### ISSUE TITLE
vdr-plugin-xvdr-7f49bfa not found

### ISSUE THREAD

**Issue by CvH** [OpenELEC/OpenELEC.tv#3738]
http://sources.openelec.tv/5.0.0/vdr-plugin-xvdr-7f49bfa.tar.xz
and
http://sources.openelec.tv/mirror/vdr-plugin-xvdr/vdr-plugin-xvdr-7f49bfa.tar.xz

are not uploaded -> vdr-addon not compile out of the box :) (already at /devel/)

vdr-plugin-vnsiserver-a7cb405.tar.xz, vdr-plugin-streamdev-40704cd.tar.xz, vdr-plugin-dvbapi-2617a7f.tar.xz, vdr-epgsearch-29c174a.tar.xz, vdr-plugin-eepg-d7dc614.tar.xz also missing (probably others too)

**Comment by vpeter4** [comment]
I'm using this patch to download from devel folder even if stable is used: http://pastebin.com/vsKyjgF5

**Comment by stefansaraev** [comment]
fixed serverside.
