### ISSUE TITLE
OpenELEC 5 - RaspberryPi - missing bluetooth-firmware

### ISSUE THREAD

**Issue by Shadowghost** [OpenELEC/OpenELEC.tv#3742]
Hey guys,
I recognized, that on OpenELEC 5 (and also on older versions) my bluetooth-stick isn't recognized because of missing firmware-files (dmesg: http://sprunge.us/jbLU).
On raspbian it's recognized correctly and I can pair it and use it as audio-device, there I have bluez installed (I know that BT-audio isn't supported, is just for confirming that it's working).
Because of this I think there should be a firmware avialable for the usage of the chipset on the rpi.

Regards,
Shadowghost

**Comment by stefansaraev** [comment]
you can drop your .hcd firmware file in /storage/.config/firmware

**Comment by Shadowghost** [comment]
I'll try to extract it from raspbian an see if it's working

**Comment by Shadowghost** [comment]
Seems like it is s part of bluetooth-linux.

**Comment by stefansaraev** [comment]
thanks. would be nice if you share the file so @sraue can add it to (misc?)-firmware

**Comment by Shadowghost** [comment]
The problem is, that the file itself can't be found but the BT-device is working...

**Comment by stefansaraev** [comment]
then there is no problem at all ;)

**Comment by Shadowghost** [comment]
Explan that please :D because if there wouldn't be a problem it should be working - but it isn't as shown in the log

**Comment by stefansaraev** [comment]
you said "it works" .. with raspbian? older kernel without all the patchram stuff that is probably mainlined later and is NOT in raspbian kernel (yet)?

**Comment by Shadowghost** [comment]
Yeah I thought that is clear. I meant that I can't find the firmware-file on raspbian but it is working with raspbian and latest kernel and bluetooth-packages.
Sorry, wasn't as clear as I thought.

**Comment by stefansaraev** [comment]
no clue then. sorry. "hell it's broadcom" proprietary thing.. still, if you can find the missing hcd file somewhere - drop in .config/firmware/

**Comment by Shadowghost** [comment]
I'll search for it. But neither in /lib/firmware nor in /sys/* there is any broadcom-related BT-firmware-file, so I would appreciate if sb has an idear where I can found them. Even find and located aren't finding anything.

**Comment by vpeter4** [comment]
I think the missing file BCM20702A0-0a5c-21ec.hcd is got from Windows driver. Actually there is hex file which must be converted to hcd.
http://dchua.com/2014/07/23/configuring-your-bcm207020a0-bluetooth-dongle-with-hsp/
For this adapter the original hex file is BCM20702A1_001.002.014.1315.1419.hex.

**Comment by Shadowghost** [comment]
Did what you wrote:
dmesg: http://sprunge.us/jNZW
hcd: https://dl.dropboxusercontent.com/u/75458214/fw-0a5c_21ec.hcd
you must rename the file to BCM20702A0-0a5c-21ec.hcd and put it in .config/firmware/brcm/ or .config/firmware

As you can see, no problems in dmesg anymore, but it still isn't recognized by OE.

**Comment by vpeter4** [comment]
Can you point me to windows drivers for this device? I just look some random with this vid/pid.

**Comment by Shadowghost** [comment]
I just searched for BCM20702A1_001.002.014.1315.1419.hex and found a driver containing it.
But I can try to get it out of the windows-driver-disc which came with the dongle, but first I must find the CD.

**Comment by Shadowghost** [comment]
So here you go for the windows-driver:
http://www.inateck.com/de/download/inateck-bta-csr4b6-usb-bluetooth-4-0-adapter/

Sorry for delay, had a lot to do with school and forgot about it.

**Comment by vpeter4** [comment]
Try this fw: https://drive.google.com/file/d/0B4FdVu0-fJt6ZjNnRW11RWU4eFk/view?usp=sharing

If it doesn't work you are on your own.

**Comment by Shadowghost** [comment]
In that case I'll be in my own ;)
Seems like BT is now correctly recognized, layers got initialized and it should be working, no errors in dmesg, but still isn't showing up in OE.

**Comment by chewitt** [comment]
closing due to length of time with no update
