### ISSUE TITLE
Openelec 5 - RasPi - No keyboard on remote

### ISSUE THREAD

**Issue by Mousson** [OpenELEC/OpenELEC.tv#3743]
I use XBMC Remote on an iPhone to operate the Pi. On Ver. 4.2, whenever there is an input field in Openelec, the keyboard pops up on the iPhone. This does not happen with 5.0.

**Comment by chewitt** [comment]
https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md <= read / and we do not provide support on the XBMC remote app working against Kodi (Kodi team does)
