### ISSUE TITLE
Openelec 5 - does not turn on TV

### ISSUE THREAD

**Issue by Mousson** [OpenELEC/OpenELEC.tv#3745]
4.2 turns on my TV on boot. 5.0 does not.

**Comment by chewitt** [comment]
https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md <= read / and please use the forums for all future questions. This is a development bug tracker not a help channel.

**Comment by Mousson** [comment]
Christian

Thanks for your reply. I am sorry to post my questions at the wrong place. Will follow your advice in the future.
Many thanks for your great effort. Greatly appreciated.

M
