### ISSUE TITLE
No DTS-HD MA Audio passthrough on Zotac "Zbox Nano AQ01"

### ISSUE THREAD

**Issue by nuxxess** [OpenELEC/OpenELEC.tv#3750]
Hello :)

At first: my english is not the best, so please excuse my "bad" english ;)

The problem i have is the following:

There is no DTS-HD MASTER passthrough on Zotac "Zbox Nano AQ01" (no Sound - Receiver shows no signal). When passthrough is deactivated in options, audio is still available through PCM output (Receiver shows PCM 5.1 Audio).

With my other Zotac "Zbox Nano AD10", DTS-HD MA passthrough Audio works very well.
So - maybe the drivers are not implemented to openelec 5.0 at the moment for Zbox AQ01?
Do anyone have a solution to solve this problem?

I`ve tested OpenElec 4.x.x / 5.0 - no passthrough at DTS-HD MA Audio.

Thanks :)

**Comment by fritsch** [comment]
Driver bug -> it's filed upstream already, subscribe yourself there: https://bugs.freedesktop.org/show_bug.cgi?id=75064

I will close here.
