### ISSUE TITLE
Missing OE5.0 sources in OE mirror

### ISSUE THREAD

**Issue by InuSasha** [OpenELEC/OpenELEC.tv#3752]
Failed to build OE 5.0 from source, same sources in OE mirror are missing

http://sources.openelec.tv/5.0.0/boblightd-478.tar.xz
http://sources.openelec.tv/5.0.0/json-c-0645020.tar.xz
http://sources.openelec.tv/5.0.0/media_build-66f4030.tar.xz
http://sources.openelec.tv/5.0.0/opengl-mali-20130520.tar.xz
http://sources.openelec.tv/5.0.0/tinyxml2-78d450b.tar.xz
http://sources.openelec.tv/5.0.0/tvheadend-3.9.2182.tar.gz
http://sources.openelec.tv/5.0.0/vdr-epgsearch-29c174a.tar.xz
http://sources.openelec.tv/5.0.0/vdr-plugin-dvbapi-2617a7f.tar.xz
http://sources.openelec.tv/5.0.0/vdr-plugin-eepg-d7dc614.tar.xz
http://sources.openelec.tv/5.0.0/vdr-plugin-streamdev-40704cd.tar.xz
http://sources.openelec.tv/5.0.0/vdr-plugin-vnsiserver-a7cb405.tar.xz
http://sources.openelec.tv/5.0.0/vdr-plugin-xvdr-7f49bfa.tar.xz

**Comment by stefansaraev** [comment]
those are not supposed to be in 5.0.
boblight/tvheadend/vdr are for addons. those should be always built with OPENELEC_VERSION=devel

json-c is for pulseaudio. we dont support pulseaudio. same for media_build. opengl-mali is ATM unused

however. switch back to -devel

**Comment by InuSasha** [comment]
AH ok.
I think, we should change the PKG_URL for this packges, from $DISTRO_SRC/.. to http://sources.openelec.tv/devel.

**Comment by stefansaraev** [comment]
fixed serverside.
