### ISSUE TITLE
Transmission service daemon starts too early

### ISSUE THREAD

**Issue by giovaorama** [OpenELEC/OpenELEC.tv#3753]
Since openelec 4.2 in my opinion the (unsupported) transmission service starts too early. 

Specifically it starts before external units/drives are mounted. 

This means that if its working folders (incoming, watch, download) live on an external drive (this is very common on Raspberry pi systems) it can't find them and nothing work. 

Simply killing transmission-daemon fix the problem: systemd restarts it automatically but all the torrent are paused.  

I solve the problem forcing transmission service type to idle,  by adding the key

        Type=idle

to the [Service] section of service.downloadmanager.transmission.service. 

Other users have similar issue and solve following my solution. 

The boring thing,  is that we have to modify the file after every addon upgrade. 

Can this be fixed?

**Comment by stefansaraev** [comment]
this does not belong here. feel free to make a PR at https://github.com/OpenELEC/unofficial-addons
