### ISSUE TITLE
dvd.iso files are played choppy, using only sw mpeg2 decoding.

### ISSUE THREAD

**Issue by Karl-opec** [OpenELEC/OpenELEC.tv#3754]
I have problems to play ripped DVD.iso files on openelec kodi-helix. openelec uses ff-mpeg2video instead of using hw-accel mpeg2 decoding. This issue  is the same on my different hardware platforms: intel ion with GT610 nvidia hardware, e350 AMD zotac, and cuboxi4. Never is the hardware used for decoding:

log1 from cuboxi-4

21:25:28 T:1968074752  NOTICE: DVDPlayer: Opening: nfs://192.168.20.248//pool/iso/being_john_malkovich.iso
21:25:28 T:1968074752 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
21:25:28 T:1501066304  NOTICE: Thread DVDPlayer start, auto delete: false
21:25:28 T:1501066304  NOTICE: Creating InputStream
21:25:28 T:1501066304   ERROR: Error on dvdnav_menu_call(Title): No such menu or menu not reachable.
21:25:28 T:1501066304   ERROR: Error on dvdnav_menu_call(Root): No such menu or menu not reachable.
21:25:28 T:1501066304  NOTICE: DVDPlayer: playing a file with menu's
21:25:28 T:1501066304  NOTICE: Creating Demuxer
21:25:28 T:1501066304 WARNING: could not find codec parameters for nfs://192.168.20.248//pool/iso/being_john_malkovich.iso
21:25:28 T:1501066304  NOTICE: Opening stream: 0 source: 512
21:25:28 T:1501066304  NOTICE: Finding audio codec for: 0
21:25:28 T:1501066304   ERROR: Unsupported audio codec
21:25:28 T:1501066304 WARNING: CDVDMessageQueue(audio)::Put MSGQ_NOT_INITIALIZED
21:25:28 T:1501066304 WARNING: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED
21:25:28 T:1492677696  NOTICE: Thread BackgroundLoader start, auto delete: false
21:25:28 T:1501066304  NOTICE: Creating Demuxer
21:25:31 T:1947202624   ERROR: CAESinkALSA - snd_pcm_writei(-32) Broken pipe - trying to recover
21:25:31 T:1501066304  NOTICE: Opening stream: 0 source: 256
21:25:31 T:1501066304  NOTICE: Creating video codec with codec id: 2
21:25:31 T:1501066304  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: MPEG-2 video
21:25:31 T:1501066304  NOTICE: Creating video thread
21:25:31 T:1476412480  NOTICE: Thread RefClock start, auto delete: false
21:25:31 T:1501066304 WARNING: CDVDMessageQueue(audio)::Put MSGQ_NOT_INITIALIZED
21:25:31 T:1492677696  NOTICE: Thread DVDPlayerVideo start, auto delete: false
21:25:31 T:1492677696  NOTICE: running thread: video_thread
21:25:31 T:1501066304  NOTICE: Opening stream: 1 source: 256
21:25:31 T:1501066304  NOTICE: Finding audio codec for: 86019
21:25:31 T:1501066304  NOTICE: Creating audio thread
21:25:31 T:1476412480  NOTICE: Thread DVDPlayerAudio start, auto delete: false
21:25:31 T:1476412480  NOTICE: running thread: CDVDPlayerAudio::Process()
21:25:31 T:1492677696  NOTICE:  fps: 25.000000, pwidth: 720, pheight: 576, dwidth: 720, dheight: 405
21:25:31 T:1492677696  NOTICE: Display resolution ADJUST : 1920x1080 @ 50.00 - Full Screen (25) (weight: 0.000)
21:25:31 T:1968074752  NOTICE: Using GL_TEXTURE_2D
21:25:31 T:1968074752  NOTICE: GL: Selecting Single Pass YUV 2 RGB shader
21:25:31 T:1968074752  NOTICE: GL: NPOT texture support detected
21:25:31 T:1492677696  NOTICE:  fps: 25.000000, pwidth: 720, pheight: 576, dwidth: 720, dheight: 405
21:25:31 T:1492677696  NOTICE: Display resolution ADJUST : 1920x1080 @ 50.00 - Full Screen (25) (weight: 0.000)
21:25:31 T:1968074752  NOTICE: Using GL_TEXTURE_2D
21:25:31 T:1968074752  NOTICE: GL: Selecting Single Pass YUV 2 RGB shader
21:25:31 T:1968074752  NOTICE: GL: NPOT texture support detected
21:25:32 T:1476412480  NOTICE: Creating audio stream (codec id: 86019, channels: 6, sample rate: 48000, no pass-through)
21:25:36 T:1501066304  NOTICE: Opening stream: 1 source: 256
21:25:55 T:1968074752  NOTICE: CDVDPlayer::CloseFile()
21:25:55 T:1968074752  NOTICE: DVDPlayer: waiting for threads to exit
21:25:55 T:1501066304  NOTICE: CDVDPlayer::OnExit()
21:25:55 T:1501066304  NOTICE: Closing stream player 1
21:25:55 T:1501066304  NOTICE: Waiting for audio thread to exit
21:25:55 T:1476412480  NOTICE: thread end: CDVDPlayerAudio::OnExit()

ion with GT610

21:22:41 T:140567023445760  NOTICE: DVDPlayer: playing a file with menu's
21:22:41 T:140567023445760  NOTICE: Creating Demuxer
21:22:41 T:140567023445760 WARNING: could not find codec parameters for nfs://192.168.20.248//pool/iso/being_john_malkovich.iso
21:22:41 T:140567023445760  NOTICE: Opening stream: 0 source: 512
21:22:41 T:140567023445760  NOTICE: Finding audio codec for: 0
21:22:41 T:140567023445760   ERROR: Unsupported audio codec
21:22:41 T:140567023445760 WARNING: CDVDMessageQueue(audio)::Put MSGQ_NOT_INITIALIZED
21:22:41 T:140567023445760 WARNING: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED
21:22:41 T:140566508066560  NOTICE: Thread BackgroundLoader start, auto delete: false
21:22:41 T:140567023445760  NOTICE: Creating Demuxer
21:22:41 T:140567023445760  NOTICE: Opening stream: 0 source: 256
21:22:41 T:140567023445760  NOTICE: Creating video codec with codec id: 2
21:22:41 T:140567023445760  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: MPEG-2 video
21:22:41 T:140567023445760  NOTICE: Creating video thread
21:22:41 T:140566092314368  NOTICE: Thread RefClock start, auto delete: false
21:22:41 T:140567023445760 WARNING: CDVDMessageQueue(audio)::Put MSGQ_NOT_INITIALIZED
21:22:41 T:140566083921664  NOTICE: Thread DVDPlayerVideo start, auto delete: false
21:22:41 T:140566083921664  NOTICE: running thread: video_thread
21:22:41 T:140567023445760  NOTICE: Opening stream: 1 source: 256
21:22:41 T:140567023445760  NOTICE: Finding audio codec for: 86019
21:22:41 T:140567023445760  NOTICE: Creating audio thread
21:22:41 T:140566075528960  NOTICE: Thread DVDPlayerAudio start, auto delete: false
21:22:41 T:140566075528960  NOTICE: running thread: CDVDPlayerAudio::Process()
21:22:41 T:140566083921664  NOTICE:  fps: 25.000000, pwidth: 720, pheight: 576, dwidth: 720, dheight: 405
21:22:41 T:140566083921664  NOTICE: Display resolution ADJUST : HDMI-0: 1920x1080 @ 50.00Hz (19) (weight: 0.000)
21:22:42 T:140568479479680  NOTICE: Using GL_TEXTURE_2D
21:22:42 T:140568479479680  NOTICE: GL: Selecting Single Pass YUV 2 RGB shader
21:22:42 T:140568479479680  NOTICE: GL: NPOT texture support detected
21:22:42 T:140568479479680  NOTICE: GL: Using GL_ARB_pixel_buffer_object
21:22:42 T:140566075528960  NOTICE: Creating audio stream (codec id: 86019, channels: 6, sample rate: 48000, no pass-through)
21:22:48 T:140567023445760  NOTICE: Opening stream: 1 source: 256
21:23:04 T:140566508066560  NOTICE: Thread BackgroundLoader start, auto delete: false
21:23:11 T:140568479479680  NOTICE: Previous line repeats 2 times.

It seams kodi does ist not able to chosse hardware accel.

TV from vnsi plugin uses mpeg2 hardware accel on sd

Is there a way to force kodi to use the hardware mpeg2 decoder?

Best regards

**Comment by stefansaraev** [comment]
closing as not bug ;)
