### ISSUE TITLE
CEC stops working after upgrade from 4.2.1 to 5.0.0

### ISSUE THREAD

**Issue by imakowski** [OpenELEC/OpenELEC.tv#3757]
My Samsung Remote stops working after 20 seconds after reboot of system. Is there workaround for this? or nightly build ?

**Comment by chewitt** [comment]
https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md <= READ .. this is a development bug tracker not a help channel. Please use the forums for general questions.

**Comment by imakowski** [comment]
I'm also developer so I think this is a real BUG ;) Can you fix it?
