### ISSUE TITLE
Video stops, then resume menu is empty/invisible (5.0)

### ISSUE THREAD

**Issue by diegolaz** [OpenELEC/OpenELEC.tv#3758]
Since I updated to 5.0, some videos stopped, but cant be resumed or restarted because the "resume or restart" menu that pops up is empty...I guess it can be manually edited to remove the information about resume, but not very practical...does this happen to anyone else or its maybe a skin issue? (using Neon skin)

Thanks!

**Comment by stefansaraev** [comment]
please [read](https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md) first.
