### ISSUE TITLE
Upgrade driver for rtl8188eu (e.g TL-WN725N) to lwfinger 4.1.8

### ISSUE THREAD

**Issue by fanste** [OpenELEC/OpenELEC.tv#3760]
I've built OE 5.0.0 (commit 1b5a1ab) with the package "RTL8188EU" upgraded to the driver version 4.1.8 (commit 007b33ebde) from lwfinger.The device is working much more stable with a pretty good throughput of ~35MBits between my FritzBox 7362SL (mixed mode: bgn) and the wifi dongle TL-WN725N.
The patch that is contained in the package must be updated as well. 

iperf result for a file of 1.9GB (2040109465 Bytes) - OE, FB and laptop use 802.11n: 
 * OE to FB (iperf server):
  * time=480.4 seconds, bandwidth=34.0 Mbit/s
  * time=473.4 seconds, bandwidth=34.5 Mbit/s
  * time=458.0 seconds, bandwidth=35.6 Mbit/s
 * Laptop (wifi) over FB to OE (iperf server): 
  * time=1076.6 seconds, bandwidth=15.2 Mbit/s
  * time=1210.0 seconds, bandwidth=13.5 Mbit/s
  * time= 864.1 seconds, bandwidth=18.9 Mbit/s
 * OE over FB to Laptop (wifi, iperf server): 
  * time=1324.7 seconds, bandwidth=12.3Mbit/s
  * time=1437.1 seconds, bandwidth=11.4 Mbit/s
  * time=1326.2 seconds, bandwidth=12.3 Mbit/s

I forgot measuring the throughputs with the original driver (v4.1.4), but it was impossible to transfer some files, as the connection dropped after few MBs or got terrible slow.

Only known issues from my side:
 * No active activity LED on the dongle
 * I had one disconnect so I had to re-plug the dongle, but it is not reproducable right now.
 * High RX drop rate while TX drop rate is perfect.
```   
HTPC:~ # ifconfig wlan0
wlan0     Link encap:Ethernet  HWaddr xx:xx:xx:xx:xx:xx
          inet addr:192.168.178.37  Bcast:192.168.178.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4427769 errors:0 dropped:38815 overruns:0 frame:0
          TX packets:8498715 errors:0 dropped:1 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:254252027 (242.4 MiB)  TX bytes:2403488095 (2.2 GiB)
```
(because of overflow, add 4.0GiB to RX / 8.0GB to TX)

**Comment by CarlosMC** [comment]
Hi,

i've a question: with this driver it's possible to create a wifi access point correctly?

was already included in OE 5.0.3 ??

**Comment by stefansaraev** [comment]
@fanste it should go to kernel mainline. we have enough broken rtl 3rdparty nonsense already. 
@CarlosMC thanks for the extra spam. this is not place for questions

**Comment by mrdominuzq** [comment]
just got upgraded to latest on master

**Comment by fanste** [comment]
Still the version 4.1.4 if I'm not wrong. But I can't test the driver anymore, as I returned the dongle to the dealer, sorry.
