### ISSUE TITLE
Openelec 5.0 crashes with HDMI on Lenovo W520

### ISSUE THREAD

**Issue by cmug81** [OpenELEC/OpenELEC.tv#3771]
My Lenovo W520 works fine with OE 4.2.1 connected to a TV through DVI -> HDMI converter. Fresh install of OE5.0 does not; when the external display is connected the Internal laptop display blinks and then OE seems to freeze. Nothing is displayed on the TV and there is no DP-1 output device found in Video Device settings like there is in 4.2.1.

I reverted back to 4.2.1 and functionality restored, so there is some regression with 5.0.

I have attached log files to a forum post:
http://openelec.tv/forum/64-installation/74599-external-display-causing-openelec-to-crash

I obtained a second W520 to use as a debug machine, and I am able to reproduce the problem there. This time with a normal DVI connected external display. I think this is somehow caused by the nvidia drivers in OE?

Let me know if I can help test this further.

**Comment by heb81** [comment]
Hi
i had the same problem yesterday trying to boot on my dell Latitude with broken screen !
i see light in the screen but the external display won't light up, only if i reboot on the installing USB or regular windows the external display shows up.

i am gonna try the downgrade option and let you know !

**Comment by cmug81** [comment]
01:00.0 VGA compatible controller: NVIDIA Corporation GF106GLM [Quadro 2000M] (rev a1)

**Comment by stefansaraev** [comment]
Quadro 2000 is a "legacy" product. even nvidia doesnt want to support it in their new proprietary drivers. see http://www.nvidia.com/page/legacy.html

it may work with an i386 build, or may not. nothing we can do.

**Comment by cmug81** [comment]
Thank you,
I did not realize my hardware was already getting so old..

But luckily it looks like with i386 build it works as expected! Had to reboot after fixing the Video Output settings (device DP-2, blank other displays) but now only external display is active. I will change my living room machine to i386 generic later and start scavenging new hardware.

**Comment by mrdominuzq** [comment]
If fixed please Close :)
