### ISSUE TITLE
Videos divided into parts in rar files are taken as different files

### ISSUE THREAD

**Issue by brooc** [OpenELEC/OpenELEC.tv#3777]
I tried adding a TV series that its episodes are divided into multiple parts each in a rar file.
It looks like this:
Series.Name.S01E01.part01.rar
Series.Name.S01E01.part02.rar
...
Series.Name.S01E01.part25.rar

I have each episode show up 25 times.
This same TV series was scraped in XBMC Gotham and showed up fine.

**Comment by brooc** [comment]
Turns out the problem was with: Enable: Settings -> Appearance -> File lists -> Support browsing into archives

Was given a pointer to this: http://openelec.tv/forum/120-news-announcements/74374-openelec-5-0-released?start=180#127222

**Comment by stefansaraev** [comment]
sure it is. and next time pls [read](https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md) first
