### ISSUE TITLE
please consider packaging the XMLTV project

### ISSUE THREAD

**Issue by dekarl** [OpenELEC/OpenELEC.tv#3779]
I'm following leads from [my guide service](http://xmltv.spaetfruehstuecken.org/xmltv/)s' logfile which led me to believe that OpenELEC does not package the [XMLTV project](http://wiki.xmltv.org/index.php/Main_Page), but relies on downloads of premade files in XMLTV format instead.
Here are some users looking for help in [Germany](http://forum.kodi.tv/showthread.php?tid=135276) and [Sweden](http://openelec.tv/forum/79-tvheadend/73033-xmltv-grabber).
Please consider packaging the XMLTV project, so your users get easier access to their programme guide.

PS: It appears that this would be the first package based on Perl though.

**Comment by stefansaraev** [comment]
feel free to do so in unofficial addons. we keep core os as light as possible.

**Comment by BTopbas** [comment]
+1 for this feature. I have epg grabber script tv_grab_tr but script is not work. Need perl..

**Comment by stefansaraev** [comment]
as said, nobody from the dev team is going to package it in OE core. +1s wont help :)

feel free to package it for unofficial and support it for people who need/use it.

closing this
