### ISSUE TITLE
Lines on top and bottom in video

### ISSUE THREAD

**Issue by coolwormgit** [OpenELEC/OpenELEC.tv#3781]
Device: HummingBoard-i2eX
problem with video around the video, most on top and bottom!

log file: https://drive.google.com/file/d/0B_8TCbqBtgBIOExMcHJCdzNFN1U/view?usp=sharing

![oax1xx](https://cloud.githubusercontent.com/assets/10504401/5709441/9902f334-9aa2-11e4-937a-3d777d7451d7.jpg)
![fn95hz](https://cloud.githubusercontent.com/assets/10504401/5709448/ae9b559c-9aa2-11e4-92ee-7fc158805872.jpg)

**Comment by coolwormgit** [comment]
seems latest xbian devel with 13.2 xbmc doesnt have this problem...

any solution?? :(

**Comment by coolwormgit** [comment]
seems changing the gui 1280x720p have no problems..

**Comment by mrdominuzq** [comment]
Can You try compile from master and See if it does any Good ?

**Comment by coolwormgit** [comment]
sorry i dont know how.... i use img from website 

thanks

**Comment by mrdominuzq** [comment]
https://drive.google.com/file/d/0B-2ANc5gpRgBUldmTUE4SXlIZjg/view?usp=sharing

remember to take a backup

**Comment by coolwormgit** [comment]
ok. tested, the problem doesnt solved... :(

**Comment by mrdominuzq** [comment]
does it happen in all movies ?

**Comment by coolwormgit** [comment]
Yes with settings 1920x1080, if i change to 1280x720 have no problem.

**Comment by amak79** [comment]
I have experienced this issue with my Cubox-i4Pro since OE 5.0.0, which is the first version I installed.

Debug log: http://paste.debian.net/plainh/bf89a700

**Comment by fritsch** [comment]
Won't be fixed. Cubox decoding and rendering was fully reworked for v15. If the issue still appears with: https://dl.dropboxusercontent.com/u/55728161/OpenELEC-imx6.arm-devel-20150322143813-r20133-g890c4cc.tar open a bug at trac.kodi.tv
