### ISSUE TITLE
libhdhomerun - update needed

### ISSUE THREAD

**Issue by UmpPCPL** [OpenELEC/OpenELEC.tv#3786]
I was not able to compile from source. Had to update libhdhomerun  to new version.
Diff below:

mapnik@mapa:/mapnik/xbmc/OpenELEC.tv$ git diff
diff --git a/packages/multimedia/libhdhomerun/package.mk b/packages/multimedia/libhdhomerun/package.m
index 95250f1..a8faa3e 100644
--- a/packages/multimedia/libhdhomerun/package.mk
+++ b/packages/multimedia/libhdhomerun/package.mk
@@ -17,7 +17,7 @@
 ################################################################################

 PKG_NAME="libhdhomerun"
-PKG_VERSION="20140604"
+PKG_VERSION="20141210"
 PKG_REV="1"
 PKG_ARCH="any"
 PKG_LICENSE="LGPL"

**Comment by stefansaraev** [comment]
thanks
