### ISSUE TITLE
OpenELEC master to (optionally) use Kodi master

### ISSUE THREAD

**Issue by ksooo** [OpenELEC/OpenELEC.tv#3788]
By any chance, is it possible to add support for using Kodi master in OpenELEC master *very soon* - maybe as a user configurable option?

Tried to get it to work myself but failed miserably.

+ Built source tarball for latest Kodi using mkpkg_kodi. Worked.
+ Current Kodi patches almost apply fine. 
-- kodi-102-dont_really_depend_on_SDL_image.patch seems not to be needed anymore
-- kodi-995.01-fernetmenta.patch needs a small modification. There are two refenrences to "CStdString" which got replaced by "std::string" in Kodi master

+ But then, Kodi configure fails. It complains about not finding package "squish". I noticed that there were some related changes in Kodi last week that might cause this failure. I'm stuck at this point. Help would be appreciated.

**Comment by stefansaraev** [comment]
@ksooo 
https://github.com/stefansaraev/OpenELEC.tv/commit/d6f4bebf108093c59c91d74688c35688deced826
https://github.com/stefansaraev/OpenELEC.tv/commit/a3583b251f89e5f27dd39498f93af8d1583ecb56#diff-1b138ac11049d54eafc060cbecf6d7e8R30
https://github.com/stefansaraev/OpenELEC.tv/commit/a3583b251f89e5f27dd39498f93af8d1583ecb56#diff-1b138ac11049d54eafc060cbecf6d7e8R115
https://github.com/stefansaraev/OpenELEC.tv/commit/a3583b251f89e5f27dd39498f93af8d1583ecb56#diff-1b138ac11049d54eafc060cbecf6d7e8R120

**Comment by stefansaraev** [comment]
and I, personaly, am against adding KODI=master this time. I would like to have "stable" in -5.0 branch and kodi master in preparation for OE 6.0 + kodi I** in master

**Comment by ksooo** [comment]
@stefansaraev Thanks for the pointers to your master. Will try to cherrypick related stuff. :-) Regarding kodi build time option: I agree.
