### ISSUE TITLE
VDR/XVDR OE5 (x86_64 & rpi): slow Channel Switch (OSD Stall for some seconds)

### ISSUE THREAD

**Issue by the-dreamer** [OpenELEC/OpenELEC.tv#3795]
After updating my pc and my raspberry pi to OE5 i have a quite slower tv channel switch time. The new behaviour is that the gui is stalling (osd/channel info) on the old channel and show the new channel when the stream is starting. Until then no new new channel switch is possible. On the Raspberry pi this can be up to 5 seconds on pc less. If i press channel up/down during the stall, kodi seems to discarding the keys which are pressed. On the raspberry this can be lead to more than a 30 seconds stall of the gui. 

The OE4.2 didn't have this behaviour. i could pressed channel up/down many times besides the stream is started or not. So i could jump quickly from channel no 6 so 13 by pressing channel up in few seconds. This is now on x86_64 and rasperrypi not possible anymore.  

with enabled debug output from the pc.

VDR log level 3:
http://sprunge.us/HFhT

kodi with debug enabled:
http://sprunge.us/AFjR

in vdr log i can see, that the channel switch itself is quite fast. 

if more logs or information needed, please ask for it.
i am not sure if i am alone with this. maybe i have another problem and the logs shows this which i have not seen..

i have also opened a thread in the forum: http://openelec.tv/forum/87-vdr-addon/74752-vdr-slow-channel-switch-stall-4-5-secs-since-oe5

**Comment by stefansaraev** [comment]
re-test with vnsi

**Comment by the-dreamer** [comment]
i tested it already with vnsi on the x86-64 and it feelt like the same. tvheadend didn't have this issue at all.. 

i will try to test vnsi with logs

**Comment by the-dreamer** [comment]
vdr log=3:
http://sprunge.us/jMLS

kodi debug log:
http://sprunge.us/XAZa

**Comment by the-dreamer** [comment]
here a log from rpi kodi also with a long stall at the end:
http://sprunge.us/SQLC

**Comment by the-dreamer** [comment]
If i am right, you have updated the xvdr server plugin. I have tested this and the issue keep the same. 

But i have tested a bit more and saw the option in Live-TV in the meaning of "delay channel switch before actually doing it..." I have played around this and it seems that this option brings the OE 4.2 behaviour a little bit back. Are there changes in kodi? But it seems to be very buggy. Tested delays: 250 ms 500ms and also 1000ms. These delays will crash very soon kodi on x86_64. 

I have also saw changes on the xbmc/kodi side of the xvdr plugin. These have also changes regarding locking. I don't know if this could help...

**Comment by the-dreamer** [comment]
This issue is not fixed. Raspberry Pi channel switch is still painfull slow ( > 10 secs ). Stopping playback also takes many seconds. On x64 it feels also slow (Gui freeze). Even on 6.0 beta 1.

**Comment by fritsch** [comment]
I cannot reproduce. Neither on cubox i4, Raspberry Pi2, WetekPlay nor vaapi x64. Backend VDR and vnsi on the clients < 2 seconds. Using a digital devices card.

**Comment by the-dreamer** [comment]
iam not sure if rpi 1 B has issues due the slow cpu since OE5. Maybe that's the reason why you cannot reproduce it on your quite faster devices. 
Due the drop of xvdr support on openelec i am now also on vnsi. With OE 4.x channel switch was equal fast on x64 and rpi 1 B. 

Some days ago i had lost the data partition on the sd card and had to reinstall OE 5.0.8 on rpi but the slow channel switch is still there. It was a fresh install without backup. 
The vdr backend is running on the x64 machine. so this is not the reason for the slow channel switch. 

I have also tried to tweak the rpi: EPG limited to 2 days, disabled services, omxplayer/dvdplayer hw acceleration... no changes. Memory is used by 20-30%. Gui is Stalling during channel switch.

**Comment by the-dreamer** [comment]
After updating the rpi to OE 6.0 Beta 1 the problem seems to be gone. Channel switch is fast again. overall it is faster. But now i have other issues which don't belong to this report (got often an error msg 5 or 8 from vnsi after channel switch...- channel encrypted...  )
