### ISSUE TITLE
IT9135 recognized as Afatech 

### ISSUE THREAD

**Issue by partyajak** [OpenELEC/OpenELEC.tv#3800]
I had a it9135 dvbt usb stick and openelec load afatech instead of it9135. Tvheadend is not able to scan any mux.
lsmod: http://pastebin.com/fSWdsmhc
system log: http://pastebin.com/xTyvpf1e
hardware log: http://pastebin.com/y9rNcjrt

**Comment by stefansaraev** [comment]
known. and it should be that way. the drivers are merged into one, upstream. nothing we can do.

**Comment by partyajak** [comment]
Is it possible to add the old driver. In version 4.0.7 worked without a problem

**Comment by stefansaraev** [comment]
nope. you should report to https://bugzilla.kernel.org/describecomponents.cgi?product=v4l-dvb
