### ISSUE TITLE
bluetooth dongle (CSR8510 A10) not recognized 

### ISSUE THREAD

**Issue by OgreTransporter** [OpenELEC/OpenELEC.tv#3808]
I have a similar Problem like issue #3106. I've bought a LogiLink BT0015 (http://www.logilink.org/showproduct/BT0015.htm?seticlanguage=en) with CSR8510 chipset. The Adapter is not recognized on OpenELEC running on my Raspberry PI.

Logfiles: https://drive.google.com/file/d/0B_ao-CmdMTkSb3pqbmp4RkhHLU0/view?usp=sharing

Build: OpenELEC 5.0 (Git: 9b94010)

Btw, it's working on Ubuntu and Windows on a PC.

**Comment by mrdominuzq** [comment]
the stick is recognized at line 185 in hardware log

Bus 001 Device 006: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)

**Comment by OgreTransporter** [comment]
Yes, but it is not working on OpenELEC. I can't find any device.

**Comment by mrdominuzq** [comment]
can you try and run hcitool -i hci1 lescan 

and see if it finds anything.

**Comment by OgreTransporter** [comment]
```
OpenELEC:~ # hcitool -i hci1 lescan
Invalid device: No such device
```

**Comment by OgreTransporter** [comment]
```
OpenELEC:~ # lsusb
Bus 001 Device 005: ID 0eef:0001 D-WAV Scientific Co., Ltd eGalax TouchScreen
Bus 001 Device 007: ID 148f:5370 Ralink Technology, Corp. RT5370 Wireless Adapter
Bus 001 Device 006: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 001 Device 004: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9512 Standard Microsystems Corp. SMC9512/9514 USB Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
OpenELEC:~ # hcitool dev
Devices:
        hci0    00:1A:7D:DA:71:0E
OpenELEC:~ # hcitool -i hci0 lescan
LE Scan ...
```
10 minutes later: nothing
It looks like hcitool hang up.

Within the GUI I was able to find my laptop for a second (not during the SSH session). But if I try to connect it says:
> Bluetooth error
> No such file or directory

**Comment by chewitt** [comment]
closing due to length of time with no update

**Comment by aocana** [comment]
any update with this issue..? I have the same problem!
