### ISSUE TITLE
PS3 controller over bluetooth on RPI/IMX6 doesn't work, on x86 it does.

### ISSUE THREAD

**Issue by MisterAG** [OpenELEC/OpenELEC.tv#3810]
Hi,

I try to connect my ps3 controller over bluetooth to my RPI/Hummingboard (imx6) but fail to do so.
I see: 'connected: yes' in the menu but I can't navigate the menu.

I enabled logging and I can see log entries like below everytime I press a button on the controller:
17:14:42 T:3042406400   DEBUG: CLinuxInputDevice::KeyEvent: TranslateKey returned XBMCK_UNKNOWN from code(300)
17:14:42 T:3042406400   DEBUG: CLinuxInputDevice::KeyEvent: TranslateKey returned XBMCK_UNKNOWN from code(303)
17:14:42 T:3042406400   DEBUG: CLinuxInputDevice::KeyEvent: TranslateKey returned XBMCK_UNKNOWN from code(302)
17:14:42 T:3042406400   DEBUG: CLinuxInputDevice::KeyEvent: TranslateKey returned XBMCK_UNKNOWN from code(301)

I tried the same thing on a x86 box with OE 5.0, and the same PS3 controller works without a problem. It's a real PS3 controller by the way and not a fake one.

Best regards,
Jan

**Comment by lrusak** [comment]
There is no SDL support in kodi for arm platforms. This is because these platforms don't use xorg.

So it will connect, but it won't be able to navigate in kodi.

**Comment by MisterAG** [comment]
So there is no way to use bluetooth remotes/gamepads on arm devices?

**Comment by lrusak** [comment]
Bluetooth remotes should work, there is just no gamepad support in kodi for arm devices as they don't use xorg which means they don't use SDL.

**Comment by tunf** [comment]
Try lakka (lakka.tv) as an image if you would like to play games on unit.

**Comment by chewitt** [comment]
if you want to do idle chit-chat take it to the forums..
