### ISSUE TITLE
Auto resize is never called on master

### ISSUE THREAD

**Issue by Kivutar** [OpenELEC/OpenELEC.tv#3812]
I compiled the auto expandable image for RPi, branch master a few hour ago (commit https://github.com/OpenELEC/OpenELEC.tv/commit/f4c40cfaa6b1c77ac1f69ae2dc9328ef5690400b )
Auto-resize never happens. The storage partition stays at 34MB and the .please_rezise_me get never removed. Kodi is launched without reboot.

I think that it also affects other projects.

There is a systemd SKIP message about ordering cycle at boot, but I'm not sure if it has something to do with this bug.

**Comment by stefansaraev** [comment]
the ordering is now fixed. please retest.

**Comment by Kivutar** [comment]
The ordering message does not appear anymore, so it is fixed. However, the auto-resize is not fixed.

**Comment by stefansaraev** [comment]
gotcha. I can reproduce. thanks for reporting.
need to think a bit how to fix it "properly" so it doesnt break next systemd bump. give me few days ;)

**Comment by stefansaraev** [comment]
could you please test #3814 ? thanks.

**Comment by Kivutar** [comment]
I tried it, but it didn't work. No resize messages, no reboot, and kodi started. The partition was not resized. I saw a message 'failed to setup user config dirs'. But the tmpfiles got created.

**Comment by stefansaraev** [comment]
make sure to rebuld initrd
```
scripts/clean linux
```

**Comment by Kivutar** [comment]
Ok, fixed
