### ISSUE TITLE
Cubox-i4pro - openelec - tvheadend |Live TV HD - Crash 

### ISSUE THREAD

**Issue by prilly** [OpenELEC/OpenELEC.tv#3818]
so i have encounterd a problem with my cubox-i4pro with playing live tv from a tvheadend backend.

Cubox is crashing/freeze when i try playing HD channels from my tvheadend. (tvheadend is good, nothing wrong there)
this is a reproducable problem, SD content is 100% stable, but when i switch to a HD channel it feezes/crashes within seconds, for the few second it plays it does that without any artifacts.

cubox-i4pro
openelec 5.0 stable
kernel 3.14

No issues with tvheadend backend

http://openelec.tv/forum/144-usage/74856-cubox-i4pro-openelec-tvheadend-crash-hd#128855

**Comment by stefansaraev** [comment]
missing [logs](https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md) :)

**Comment by prilly** [comment]
i understand its missing logs, please describe how you intend to gather this logs? as described in the issue report "feezes/crashes" this is cousing the system to get unresponsive, its not possible to run "createlog" after this even has occured. 

after i reboot the cuboc (pulling the cord) the logs for that even is gone.

**Comment by fritsch** [comment]
Switch your backend to vdr and your client to vnsi. I use the very same
configuration (besides tvheadend) and don't have a single issue, with
neither HD nor SD nor 720p progressive TV content.

Does this one work:
http://solidrun.maltegrosse.de/~fritsch/1080i50_h264_mbaff.mp4 (vdr
recording)

2015-01-20 1:28 GMT+01:00 Prilly <notifications@github.com>:

> i understand its missing logs, please describe how you intend to gather
> this logs? as described in the issue report "feezes/crashes" this is
> cousing the system to get unresponsive, its not possible to run "createlog"
> after this even has occured.
>
> after i reboot the cuboc (pulling the cord) the logs for that even is gone.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3818#issuecomment-70584912>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by prilly** [comment]
Thank you for your notice. Switching to vdr is not something i want to do, vdr does not have the features i need for a backend tv server.

720p content is no problem to play at all. The problem with crashed cubox is mainly related to 1080i50 streams. (Deinterlacing turned of)

I will test your file latertoday.

Does vdr have android client? 
Is vdr capable of transcoding?
Can vdr generate a playlist liketvh does: http://server.com/playlist



-------- Opprinnelig melding --------
Fra: Peter Frühberger <notifications@github.com> 
Dato:20.01.2015  08:45  (GMT+01:00) 
Til: "OpenELEC/OpenELEC.tv" <OpenELEC.tv@noreply.github.com> 
Ko: Prilly <prilly@speedbox.me> 
Emne: Re: [OpenELEC.tv] Cubox-i4pro - openelec - tvheadend |Live TV HD -
  Crash  (#3818) 

Switch your backend to vdr and your client to vnsi. I use the very same
configuration (besides tvheadend) and don't have a single issue, with
neither HD nor SD nor 720p progressive TV content.

Does this one work:
http://solidrun.maltegrosse.de/~fritsch/1080i50_h264_mbaff.mp4 (vdr
recording)

2015-01-20 1:28 GMT+01:00 Prilly <notifications@github.com>:

> i understand its missing logs, please describe how you intend to gather
> this logs? as described in the issue report "feezes/crashes" this is
> cousing the system to get unresponsive, its not possible to run "createlog"
> after this even has occured.
>
> after i reboot the cuboc (pulling the cord) the logs for that even is gone.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3818#issuecomment-70584912>
> .
>



-- 
Key-ID: 0x1A995A9B
keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157 C81B DA07 CF63 1A99 5A9B

**Comment by fritsch** [comment]
I don't really care. I just want to find out - if it's backend related as I
cannot reproduce.

2015-01-20 9:00 GMT+01:00 Prilly <notifications@github.com>:

> Thank you for your notice. Switching to vdr is not something i want to do,
> vdr does not have the features i need for a backend tv server.
>
> 720p content is no problem to play at all. The problem with crashed cubox
> is mainly related to 1080i50 streams. (Deinterlacing turned of)
>
> I will test your file latertoday.
>
> Does vdr have android client?
> Is vdr capable of transcoding?
> Can vdr generate a playlist liketvh does: http://server.com/playlist
>
>
>
> -------- Opprinnelig melding --------
> Fra: Peter Frühberger <notifications@github.com>
> Dato:20.01.2015 08:45 (GMT+01:00)
> Til: "OpenELEC/OpenELEC.tv" <OpenELEC.tv@noreply.github.com>
> Ko: Prilly <prilly@speedbox.me>
> Emne: Re: [OpenELEC.tv] Cubox-i4pro - openelec - tvheadend |Live TV HD -
> Crash (#3818)
>
> Switch your backend to vdr and your client to vnsi. I use the very same
> configuration (besides tvheadend) and don't have a single issue, with
> neither HD nor SD nor 720p progressive TV content.
>
> Does this one work:
> http://solidrun.maltegrosse.de/~fritsch/1080i50_h264_mbaff.mp4 (vdr
> recording)
>
> 2015-01-20 1:28 GMT+01:00 Prilly <notifications@github.com>:
>
> > i understand its missing logs, please describe how you intend to gather
> > this logs? as described in the issue report "feezes/crashes" this is
> > cousing the system to get unresponsive, its not possible to run
> "createlog"
> > after this even has occured.
> >
> > after i reboot the cuboc (pulling the cord) the logs for that even is
> gone.
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/OpenELEC/OpenELEC.tv/issues/3818#issuecomment-70584912>
> > .
> >
>
>
>
> --
> Key-ID: 0x1A995A9B
> keyserver: pgp.mit.edu
> ==============================================================
> Fingerprint: 4606 DA19 EC2E 9A0B 0157 C81B DA07 CF63 1A99 5A9B
> --
> Reply to this email directly or view it on GitHub.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3818#issuecomment-70617303>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by prilly** [comment]
Ok m8, i will test that and report back.

 Have a nice day

 Regards
 Prilly
 January 20 2015 9:53 AM, skrev "Peter Frühberger" :  

	  
I don't really care. I just want to find out - if it's backend related as I
 cannot reproduce.

 2015-01-20 9:00 GMT+01:00 Prilly :

 > Thank you for your notice. Switching to vdr is not something i want to do,
 > vdr does not have the features i need for a backend tv server.
 >
 > 720p content is no problem to play at all. The problem with crashed cubox
 > is mainly related to 1080i50 streams. (Deinterlacing turned of)
 >
 > I will test your file latertoday.
 >
 > Does vdr have android client?
 > Is vdr capable of transcoding?
 > Can vdr generate a playlist liketvh does: http://server.com/playlist (http://server.com/playlist)
 >
 >
 >
 > -------- Opprinnelig melding --------
 > Fra: Peter Frühberger 
 > Dato:20.01.2015 08:45 (GMT+01:00)
 > Til: "OpenELEC/OpenELEC.tv" 
 > Ko: Prilly 
 > Emne: Re: [OpenELEC.tv] Cubox-i4pro - openelec - tvheadend |Live TV HD -
 > Crash (#3818)
 >
 > Switch your backend to vdr and your client to vnsi. I use the very same
 > configuration (besides tvheadend) and don't have a single issue, with
 > neither HD nor SD nor 720p progressive TV content.
 >
 > Does this one work:
 > http://solidrun.maltegrosse.de/~fritsch/1080i50_h264_mbaff.mp4 (http://solidrun.maltegrosse.de/~fritsch/1080i50_h264_mbaff.mp4) (vdr
 > recording)
 >
 > 2015-01-20 1:28 GMT+01:00 Prilly :
 >
 > > i understand its missing logs, please describe how you intend to gather
 > > this logs? as described in the issue report "feezes/crashes" this is
 > > cousing the system to get unresponsive, its not possible to run
 > "createlog"
 > > after this even has occured.
 > >
 > > after i reboot the cuboc (pulling the cord) the logs for that even is
 > gone.
 > >
 > > --
 > > Reply to this email directly or view it on GitHub
 > > <
 > https://github.com/OpenELEC/OpenELEC.tv/issues/3818#issuecomment-70584912 (https://github.com/OpenELEC/OpenELEC.tv/issues/3818#issuecomment-70584912)>
 > > .
 > >
 >
 >
 >
 > --
 > Key-ID: 0x1A995A9B
 > keyserver: pgp.mit.edu
 > ==============================================================
 > Fingerprint: 4606 DA19 EC2E 9A0B 0157 C81B DA07 CF63 1A99 5A9B
 > --
 > Reply to this email directly or view it on GitHub.
 >
 > --
 > Reply to this email directly or view it on GitHub
 > 
 > .
 >
 --
 Key-ID: 0x1A995A9B
 keyserver: pgp.mit.edu
 ==============================================================
 Fingerprint: 4606 DA19 EC2E 9A0B 0157 C81B DA07 CF63 1A99 5A9B

**Comment by prilly** [comment]
then i have done some more testing, your file works good on my cubox, issues is not reproducable with your recording.

I have found a interesting indication here, the crashes on the cubox appear exactly when tvheadend is reporting a Continues counter error:

 #1069 Continuity counter error (total 3)

My theory on this is that cubox failes upon reciving 1080i50 content from tvheadend backed when the stream has a intermidiate CCR issue, somehow its not recovering form this..

https://tvheadend.org/issues/2632

**Comment by prilly** [comment]
Updated by Jaroslav Kysela about 13 hours ago

It's client fault. We can probably drop the incomplete/malformed frames, but I don't think that's the right way, because partial information in these frames might be ok..

it seems the problem might be with the tvheadend plugin, i understand there has been some updates to it latly? is it possible that noe all of them has hit the kodi stable yet?

**Comment by tunf** [comment]
Please update also tvheadend. It was with an older version i had the same issues.

**Comment by fritsch** [comment]
tvheadend was moved to unofficial - feel free to post a PR for it.

**Comment by stefansaraev** [comment]
ha. this should be closed. too.
