### ISSUE TITLE
black screen after OpenELEC screen

### ISSUE THREAD

**Issue by S1X3R** [OpenELEC/OpenELEC.tv#3819]
So I just tried to set up my R Pi B+, used the NOOBS installer since everything else didn't work,
I came to the point where I had to choose the OS and I installed OpenELEC.
After installation the OpenELEC Bootscreen showed up, in the upper left hand corner it showed up the version, after this my screen turned black, nothing I could to, and after a few minutes my mouse and keyboard turned off too (they're illuminated, so i can tell) and nothing happened.
Any suggestions what to do=

**Comment by chewitt** [comment]
User support is provided via the forums. This is not a help channel.
