### ISSUE TITLE
 JPEG hardware VPU decoder support on Freescale i.MX6 Series

### ISSUE THREAD

**Issue by Hedda** [OpenELEC/OpenELEC.tv#3825]
[Feature Request]  JPEG hardware VPU image decoder offload support on Freescale i.MX 6 Series,  (and not just using NEON optimization).

Demo code https://community.freescale.com/thread/318147

Request idea copied from https://github.com/xbmc-imx6/xbmc/issues/77

Adding support for hw decode of JPEG decoding would be a nice addition to accelerate image / picture rendering inside Kodi / XBMC, this would be most beneficial when browsing large foto galleries but it could also assist loading of backdrops/covers/posters in the GUI, and for this to work the Linux distribution must make use of libraries that support utilize offloading to an hardware engine, which most SoC manufacturers offer.

HW decode of JPEG, GIF, and PNG still images / pictures could probably be done on the VPU or GPU of most embedded systems that OpenELEC support but this specific feature request is for JPEG HW decode on Freescale i.MX6 SoC Series.

i.MX 6 VPU also supports MJPEG (Motion JPEG) http://en.wikipedia.org/wiki/Motion_JPEG

See this cool media backgrounds concept http://forum.xbmc.org/showthread.php?tid=141442

Reference: http://hands.com/~lkcl/eoma/iMX6/VPU_API_RM_L3.0.35_1.1.0.pdf

• MJPEG Baseline Process Encoder and Decoder
• Baseline ISO/IEC 10918-1 JPEG compliance
• Support 1 or 3 color components
• 3 component in a scan (interleaved only)
• 8 bit samples for each component
• Support 4:2:0, 4:2:2, 2:2:4, 4:4:4 and 4:0:0 color format (max. six 8x8 blocks in one MCU)
• Minimum encoding size is 16x16 pixels

Also see Amlogic request https://github.com/OpenELEC/OpenELEC.tv/issues/3826

**Comment by chewitt** [comment]
I'm closing the ticket because this would need to be implemented upstream, so the correct place to make your request is http://trac.kodi.org.

**Comment by Hedda** [comment]
Sorry but you are wrong here, this is implemented in the Linux distro for the library dependencies that XBMC/Kodi uses, not inside the XBMC/Kodi core code itself.

Read comments from a XBMC/Kodi developer here https://github.com/xbmc-imx6/xbmc/issues/77

**Comment by Hedda** [comment]
@ chewitt, please re-open this feature request. It really belong in OpenELEC (Linux OS distro) and not upstream in XBMC/Kodi. The reason for this is that these you decide if dependency libraries utilize hardware acceleration or not.

**Comment by mzer0-yu** [comment]
@Hedda I found a decoding problem of JPEG files in OpenELEC and I get a reply from the Kodi team says it is because RPi cannot hardware decode JPEG files(http://forum.kodi.tv/showthread.php?tid=235860&pid=2084645#pid2084645). Can you leave a contact way for me(QQ/Email) to discuss about it?

**Comment by Hedda** [comment]
@mzer0-yu this request was/is for it on Freescale hardware, not Raspberry Pi (Broadcom).
