### ISSUE TITLE
 JPEG hardware image decoder support on Amlogic

### ISSUE THREAD

**Issue by Hedda** [OpenELEC/OpenELEC.tv#3826]
[Feature Request]  JPEG hardware image decoder offload support on Amlogic 8726-MX, (and not just using NEON optimization).

Amlogic references to hardware image decoder:
http://wenku.baidu.com/view/a71f0017f18583d04964592a.html
http://wenku.baidu.com/view/d538268be53a580216fcfe35.html

Adding support for hw decode of JPEG decoding would be a nice addition to accelerate image / picture rendering inside Kodi / XBMC, this would be most beneficial when browsing large foto galleries but it could also assist loading of backdrops/covers/posters in the GUI, and for this to work the Linux distribution must make use of libraries that support utilize offloading to an hardware engine, which most SoC manufacturers offer.

Amlogic SoC's integrated image decoder can hardware decode BMP, JPEG, GIF, PNG, and TIF still images.

HW decode of BMP, JPEG, GIF, PNG, and TIF still images / pictures could probably be done on the VPU or GPU of most embedded systems that OpenELEC support but this specific feature request is for JPEG HW decode on Amlogic SoC Series.

Also see Freescale iMX6 request https://github.com/OpenELEC/OpenELEC.tv/issues/3825

**Comment by chewitt** [comment]
I'm closing the ticket because this would need to be implemented upstream, so the correct place to make your request is http://trac.kodi.org.

**Comment by Hedda** [comment]
Sorry but you are wrong here, this is implemented in the Linux distro for the library dependencies that XBMC/Kodi uses, not inside the XBMC/Kodi core code itself.

Read comments from a XBMC/Kodi developer here https://github.com/xbmc-imx6/xbmc/issues/77

**Comment by Hedda** [comment]
@ chewitt, please re-open this feature request. It really belong in OpenELEC (Linux OS distro) and not upstream in XBMC/Kodi. The reason for this is that these you decide if dependency libraries utilize hardware acceleration or not.

**Comment by Hedda** [comment]
@chewitt Maybe you or someone could confirm with an Amlogic expert, like codesnake from WeTek?
