### ISSUE TITLE
Utilize CAAM hardware cryptographic engine CESA co-processor on Freescale i.MX6 SoC Series

### ISSUE THREAD

**Issue by Hedda** [OpenELEC/OpenELEC.tv#3828]
[Feature Request] Utilize CAAM hardware cryptographic engine CESA co-processor on Freescale i.MX6 SoC Series.

Freescale i.MX6 SoC Series contain an integrated CAAM (Cryptographic Acceleration and Assurance Module) hardware engine supporting ARM's TrustZone can be used to hardware accelerate cryptographic decryption decipher and encryption cipher.

Best real-world examples to advantage of hardware accelerators for this on Kodi/XBMC's Linux distros like OpenELEC are transparently for dependent libraries like OpenSSL, OpenSSH, GnuTLS, dm-crypt, kcryptd, dm-mod, and/or luks via cryptodev library API (caam drivers in kerne and openssl-cryptodev, etc. libraires).

This could also be useful for other applications and services running on OpenELEC, like for example descrabling channels in latest TVheadend with SAT>IP using AES over openssl lib, so utlizing cropto engine could mean less CPU load.

http://cryptodev-linux.org (Comparisons: http://cryptodev-linux.org/comparison.html )

Utilize hardware cryptographic engine CESA co-processor for hardware acceleration encryption / decryption crypto and ciphers calculations tasks such as SSL, SCP, SSH, AES, TLS, DES, 3DES, SHA / SHA-1, MD5, hashes, dm-crypt, luks, etc. (such as hardware decryption with OpenSSL, OpenSSH, and GnuTLS libraries via CryptoDev to offload cryptographic tasks from CPU and therefore every dependency module that XBMC utilizes which support CryptoDev cryptographic accelerator drivers via /dev/crypto).

Standard libraries do not have support so have to use via cryptodev or NCR API's
http://cryptodev-linux.org
http://cryptodev-linux.org/ncr.html

Freescale i.MX6 SoC  benchmarks http://forums.wandboard.org/viewtopic.php?f=12&t=109&p=543

The old CuBox usage example: http://www.solid-run.com/archive/phpbb/viewtopic.php?f=9&t=634

HW decrypt and encrypt could probably be done on most embedded systems that OpenELEC support but this specific feature request is for HW crypto on Freescale i.MX6 SoC Series.

**Comment by chewitt** [comment]
I'm closing the ticket because this would need to be implemented upstream, so the correct place to make your request is http://trac.kodi.org.

**Comment by Hedda** [comment]
Sorry but you are wrong here, this is implemented in the Linux distro for the library depencencies that XBMC/Kodi uses, not inside the XBMC/Kodi core code itself.

Reas comments from XBMC/Kodi developer here https://github.com/xbmc-imx6/xbmc/issues/84

**Comment by Hedda** [comment]
@ chewitt, please re-open this feature request. It really belong in OpenELEC (Linux OS distro) and not upstream in XBMC/Kodi. The reason for this is that these you decide if dependency libraries utilize hardware acceleration or not.
