### ISSUE TITLE
MuMuDVB PVR client addon for Kodi/XBMC on OpenELEC Linux?

### ISSUE THREAD

**Issue by Hedda** [OpenELEC/OpenELEC.tv#3829]
Feature Request - please create a MuMuDVB PVR client addon for Kodi/XBMC to use in OpenELEC! 

MuMuDVB (Multi Multicast DVB) by Brice Dubost is an open source "PVR backend" (TV tuner server software) application made for redistributing DVB television streams over a network. 

http://www.mumudvb.net

MuMuDVB is designed for embedded platforms and have a very low memory and CPU footprint, and of course also features IPTV and multicast support.  MuMuDVB difference itself from example Tvheadend or VDR as a "PVR backend" a few ways, and one is that MuMuDVB have cross-platform support so that it not only runs on Linux but it also runs natively on Android, on both on ARM and x86 embedded systems.

Are there any any C/C++ developers looking into creating a real Kodi/XBMC PVR client addon for the MuMuDVB (Multi Multicast DVB) PVR backend?

This would mean that with MuMuDVB and Kodi in OpenELEC on embedded systems as a stand-alone set-top boxwithout using a separate external PVR backend TV server under Linux. That is, the best thing would be having the MuMuDVB PVR backend run natively on OpenELEC and a matching MuMuDVB PVR client addon for Kodi/XBMC would be to have both the DVB TV tuner server part that is MuMuDVB PVR backend TV tuner server application running on the very same embedded platform box as the frontend Kodi/XBMC media player app.

MuMuDVB have GPLv2 open source licensed cross-platform C source code on GitHub: https://github.com/braice/MuMuDVB

MuMuDVB features an extended JSON API (webservices) which should make clients possible:
http://www.mumudvb.net/doc/mumudvb-2.0.0/WEBSERVICES.html

For reference, what "PVR backends" actually do for Kodi/XBMC and OpenELEC please see these wiki articles here http://kodi.wiki/view/PVR and and here http://kodi.wiki/view/PVR_backend

**Comment by Hedda** [comment]
FYI, found this tutorial in the OpenELEC wiki and forum about "How to make OpenELEC addon - on MuMuDVB sample"

http://wiki.openelec.tv/index.php?title=How_to_make_OpenELEC_addon_-_on_MuMuDVB_sample

http://openelec.tv/forum/20-development-discussion/15752-how-to-make-openelec-addon-on-mumudvb-sample

Three years old however and no updates, and you will still need a PVR client addon for Kodi/XBMC.

**Comment by mrdominuzq** [comment]
Added https://github.com/OpenELEC/unofficial-addons/commit/afd437edb0f3ee09ced08355c8683ce856cfb2bc

**Comment by stefansaraev** [comment]
it seems nobody is interested in adding this to openelec. so wont happen. closing.
