### ISSUE TITLE
MIPS port of OpenELEC and support for MIPS Creator CI20 development board

### ISSUE THREAD

**Issue by Hedda** [OpenELEC/OpenELEC.tv#3830]
Please port OpenELEC Linux distribution to MIPS processor architecture and se MIPS Creator CI20 development board from Imagination Technologies as your reference hardware platform (because as Kodi/XBMC for Linux is already being ported to this development board).

http://forum.kodi.tv/showthread.php?tid=210594
http://balintreczey.hu/blog/xbmc-from-debian-running-on-mips-ci20-dev-board/
http://en.wikipedia.org/wiki/MIPS_instruction_set

Imagination Technologies MIPS Creator CI20 is a new microcomputer development board with Linux and Android support that is now available to anyone for $65 (US) / £50 (UK)

http://store.imgtec.com/us/
http://store.imgtec.com/uk/

Imagination Technologies who bought MIPS Technologies last year now want kickstart a trend for cheap development boards based on MIPS computer architecture for Linux and Android to both attract/encourage developers and to compete with affordable ARM development boards like Raspberry Pi Model B and BeagleBone Black.

To do this they have they have begun this journey by announcing that their "MIPS Creator CI20" development board is now available to anyone to buy for $65 / £50.

This is the same MIPS Creator CI20 development board that they were previously only offered (for free) to a limited amount of selected accredited developers against their promise to work on either developing new killer apps software for it or port popular existing open source applications to it, (you can read more about that here http://blog.imgtec.com/powervr-developer...oid-debuts ).

It should however be noted that this MIPS Creator CI20 is still really only targerted at developers and hackers, and not even really meant for entusists or power-users. As their plan is to first try to get popular software ported to the platform, and only then release new similar board models and devices that will be both smaller and cheaper to mass produce so when subsidized by Imagination Technologies they can be sold at the same price range as Raspberry Pi Model B and BeagleBone Black, or perhaps just a little more costly considering the CI20 have a more modern hardware and higher specification which also includes integrated 8GB storage, Bluetooth 4.0 and Wi-Fi, as well as an IR-receiver and GPIO expansion headers.

http://www.cnx-software.com/2014/08/28/mips-creator-ci20-development-board-formally-announced-free-to-selected-developers/
http://www.cnx-software.com/2014/08/13/mips-development-board-linux-android/

MIPS Creator CI20 specifications is quite impressive today when compared if you look at Raspberry Pi Model B and BeagleBone Black as being their main competition:

    SoC – Ingenic JZ4780 dual-core MIPS32 (MIPSel) processor @ 1.2 GHz with Imagination PowerVR SGX540 GPU. 32kI + 32kD per core, 512K shared L2.
    IEEE754 Floating Point Unit
    System Memory – 1GB DDR3
    Storage – 4GB flash storage (NOR), 1x SD card slot, 1x SD card slot via expansion
    Video Output – HDMI 1.4b up to 1080p
    Audio I/O – AC97 audio In and Out via 3.5mm 4-pin input/output jack and HDMI connector
    Video Playback – Up to 1080p @ 60 FPS
    Connectivity – 10/100M Ethernet (wired RJ-45), 802.11 b/g/n WiFi + Bluetooth 4.0 module (IW8103)
    USB – 1x USB OTG, 1x USB 2.0 Host.
    Camera interface –ITU645 controller
    Expansions Headers – Access to 23x GPIOs, 2x SPI, 1x I2C, 7x ADC on header, including 5-wire touch and battery monitoring function, 1x UART, Transport Stream I/F.
    Debugging – UART, and 14-pin MIPS EJTAG header
    Misc – IR (infrared) receiver, power LED, and button
    Power Supply – 5V via 4mm/1.7mm barrel connector
    Dimensions – 90x95mm

Besides both Android 4.4 and Debian 7 already being officially supported by Imagination Technologies on the MIPS Creator CI20 development board, other operating systems are currently beeing ported to MIPS Creator CI20, including NetBSD, and Haiku inspired from the defunct BeOS. And different developers who was given their free board a few months ago have already ported many popular apps from several open source software applications projects to this MIPS Creator CI20 development board, including several games and of course XBMC/Kodi.

So this board / chipset and MIPS as an architecture could get very interesting now for XBMC/Kodi with the work that these guys are doing:

https://github.com/xbmc/xbmc/pull/5570
https://github.com/xbmc/xbmc/pull/5759
http://forum.kodi.tv/showthread.php?tid=207865

For more information and code for the CI20 board, including User Guides, Hardware and Software Technical documentation, Component specifications, schematics, Linux kernel, U-Boot sources forum and more:
http://elinux.org/MIPS_Creator_CI20
http://www.elinux.org/CI20_Dev_Zone
http://developer.mips.com
https://github.com/MIPS

**Comment by Hedda** [comment]
Porting OpenELEC Linux distribution to MIPS would could mean that you could later also add support for other MIPS based devices, such as many Enigma2 set-top boxes which like most such set-top boxes uses different derivative distro forks of OpenEmbedded-Linux.

FYI, Marusys set-top box manufacture have announced the availability of a XBMC/Kodi port for MIPS based Vu+ set-top boxes by Ceru

http://forum.kodi.tv/showthread.php?tid=213084

For those who do not know, Vu+ is a popular series of MIPSel based Linux-powered DVB satellite, terrestrial digital television receivers (set-top boxes) which OpenEmbedded-Linux based firmware is officially user-upgradable, and produced by Korean multimedia brand Ceru Company Ltd. (a subsidiary of Marusys Co. Ltd.),

Supported Vu+ set-top boxes are currently the ones based on Broadcom MIPS chipsets with VideoCore IV GPU, which are rthe newer which are SoloSe, Solo2, and Duo2 models:

Vu+ SoloSe (Vu Plus Solo Second Edition) features Broadcom BCM 7429 / BCM7429 chipset with 1.3 MHz Dual-Core MIPS CPU, 1 GB RAM, and VideoCore IV GPU
Vu+ Solo2 (Vu Plus Solo 2) features Broadcom BCM 7356 / BCM7356 chipset with 1.3 MHz Dual-Core MIPS CPU, 1 GB RAM, and VideoCore IV GPU
Vu+ Duo2 (Vu Plus Duo 2) eatures Broadcom BCM 7424 / BCM7424 chipset with 1.3 MHz Dual-Core MIPS CPU, 2 GB RAM, and VideoCore IV GPU

Support for older models will not be made due to lack of hardware resources

http://www.vuplus-community.net/board/threads/xbmc-soon-in-black-hole-image.20445/

**Comment by vpeter4** [comment]
And how many users will be with this new platform? 2? 3? 1000? 10.000?
I bet only few.

**Comment by Hedda** [comment]
MIPS processor architecture in general or the MIPS Creator CI20 development board from Imagination Technologies specifically?

MIPS processor architecture is huge in the embedded system market, and especially in the Linux based set-top box and digital media player market (example Dreambox, Vu+, and Sybas/CloudMedia Popcorn Hour and Popbox Network Media Tank series, and they all have sold millions of MIPS bases media players and set-top boxes).

As I said, Imagination Technologies bought MIPS Technologies last year now they want kickstart a trend for cheap development boards based on MIPS computer architecture for Linux and Android to both attract/encourage developers and to compete with affordable ARM development boards like Raspberry Pi Model B and BeagleBone Black.

To do this they have they have begun this journey by first announced their "MIPS Creator CI20" development board and is now offering it for cheap in the hope that open source developers will build a community around it that can develop new killer apps software for it or port popular existing open source applications to it, again same idea as for the Raspberry Pi and BeagleBone Black.

It should however be noted that this first MIPS Creator CI20 is really only targeted at developers, hackers, enthusiasts and power-users, as their plan is to first get popular software ported to the platform, and then release more models that will be smaller and cheaper to mass produce so when subsidized by Imagination Technologies it can be sold in the same price range as Raspberry Pi Model B and BeagleBone Black, or perhaps just a little more costly considering the CI20 higher specification which also includes integrated 8GB storage, WiFi, and Bluetooth.

http://elinux.org/MIPS_Creator_CI20
http://elinux.org/CI20_Dev_Zone

If the OpenELEC contacted Imagination Technologies then I bet that they would give you these CI20 developer boards for free against the promise of you posting OpenELEC to it.

**Comment by stefansaraev** [comment]
kodi has no mips support. yet. so nope.

**Comment by Hedda** [comment]
@stefansaraev please see links above to fork of Kodi with MIPS support and tested on CI20.

OpenELEC is famous for introducing experimental support before merged into upstream mainline. Just look at Freescale iMX.6 platform support for which OpenELEC began using a fork of Kodi before it was accepted into upstream mainline, and the same can be said for RetroPlayer support.

http://balintreczey.hu/blog/xbmc-from-debian-running-on-mips-ci20-dev-board/

Kodi already runs with with the MIPS patches that Bálint Reczey (rbalint) have submitted upstream

https://github.com/xbmc/xbmc/pull/5570

https://github.com/rbalint/xbmc/tree/mips

**Comment by rossbeazley** [comment]
+1

**Comment by alexvoica** [comment]
Guys, if anyone wants to take this one, we (Imagination Technologies) can provide tech support.

**Comment by stefansaraev** [comment]
I'd like to see PRs @alexvoica @Hedda 
and send devs some hardware.

**Comment by alexvoica** [comment]
We've sent hundreds of development boards to developers who've contacted us. Unfortunately I didn't see requests from OpenELEC but I can send you development boards since we now have them back in stock. How many would you need? 

We can also mention your work in PRs; for example, we've included a quote from Balint in our announcement (search for XBMC):
http://blog.imgtec.com/powervr/mips-creator-ci20-development-board-now-available
and promoted his work on AnandTech
http://anandtech.com/show/8775/imagination-launches-creator-ci20-development-board

**Comment by rbalint** [comment]
Debian already ships an XBMC version working on mipsel and will soon ship Kodi as well, so I think the XBMC/Kodi part is basically tested and done and OpenELEC could support MIPS easily. FFmpeg's support is missing for HW accelerated video playback on the board to have a fully working stack.

**Comment by Hedda** [comment]
@stefansaraev please see comment from @alexvoica about getting dev boards to OpenELEC devs.

@alexvoica is also offering to hook you up with inside connection at Imagination Technologies.

For Kodi pulls requests see XBMC projects pull request 5570 linked here https://github.com/xbmc/xbmc/pull/5570
It sounds as if those patches for Kodi will be merged into upstream Kodi mainline any day now.

Please see http://elinux.org/CI20_Dev_Zone and http://elinux.org/MIPS_Creator_CI20 for Linux.

Again, reason for CI20 is a powerful alternative to Raspberry Pi that's cheaper than ODROID-C1. And at the CI20 retail price of $65 / £50 with it OpenELEC will gain its users and developers support for a cheap and powerful development platform running MIPS.

PS: I myself have no association with  Imagination Technologies or MIPS, as I'm just a end-user.

**Comment by Hedda** [comment]
MIPS port patches tested on CI20 development board have now been merged into upstream Kodi/XBMC mainline master

https://github.com/xbmc/xbmc/pull/5570

This means that Kodi/XBMC now officially support running on MIPS SoC, so far only with software video decoding

**Comment by rossbeazley** [comment]
Would this port also include HDMI cec support using the built in HDMI port?

**Comment by stefansaraev** [comment]
it seems nobody is interested in adding this to openelec. so wont happen. closing.

**Comment by Arcko** [comment]
as far as I know, kodi on Loongson is working

**Comment by malaterre** [comment]
For anyone interested, here is my attempt at getting OpenELEC on Creator CI20 [here](https://github.com/malaterre/OpenELEC.tv).

**Comment by sraue** [comment]
@malaterre pm me via the forum or via email (stephan [at] openelec . tv] please
