### ISSUE TITLE
OpenELEC 5.0.0 starts Kodi before network is ready, breaks MySQL libraries

### ISSUE THREAD

**Issue by wolrah** [OpenELEC/OpenELEC.tv#3836]
I have a fresh install of OpenELEC 5.0.0 on a Gigabyte GA-C1007UN-D in my home theater.

I've previously used XBMCbuntu on this machine and have a long-standing shared MySQL database to keep my library in sync between this appliance, a few normal PCs, and a few Android sticks.

I have already updated the other machines and thus any library updates have already happened.

Using the following basically dead standard MySQL config entries in advancedsettings.xml

    <videodatabase>
      <type>mysql</type>
      <host>10.0.0.12</host>
      <port>3306</port>
      <user>xbmc</user>
      <pass>xbmc</pass>
      <name>xbmc_video</name>
    </videodatabase>
    <musicdatabase>
      <type>mysql</type>
      <host>10.0.0.12</host>
      <port>3306</port>
      <user>xbmc</user>
      <pass>xbmc</pass>
      <name>xbmc_music</name>
    </musicdatabase>

I get the following log spam (obviously a lot of other similar log entries removed because they're redundant to the point) on every single boot and my library does not work.

    15:40:06 T:140060025415552   ERROR: Unable to open database: xbmc_music48 [2003](Can't connect to MySQL server on '10.0.0.12' (101))
    15:40:06 T:140060025415552   ERROR: Unable to open database: xbmc_music47 [2003](Can't connect to MySQL server on '10.0.0.12' (101))
    15:40:06 T:140060025415552   ERROR: Unable to open database: xbmc_music46 [2003](Can't connect to MySQL server on '10.0.0.12' (101))
    15:40:06 T:140060025415552   ERROR: Unable to open database: xbmc_music45 [2003](Can't connect to MySQL server on '10.0.0.12' (101))

log spam (obviously a lot of other similar log entries removed because they're redundant to the point) on every single boot and my library does not work.

If I SSH in and "killall -9 kodi.bin" to restart it after networking is actually running I get

    15:42:31 T:139762596001664  NOTICE: Running database version xbmc_music48
    15:42:31 T:139762596001664  NOTICE: Running database version xbmc_video90

and everything works as intended.

---

I'm not sure what the best solution would be.  Since Kodi only tries for a bit and then gives up forever any solution I can see at the moment involves delaying launching Kodi if a network connection exists but is not ready, but obviously that is not desirable for anyone who may have a slow network but plays local media and thus doesn't care if the network is ready or not.

**Comment by fritsch** [comment]
OpenELEC addon -> wait for network.
Or wakeonlan.xml

this has been answered several thousand tims, btw.

2015-01-25 17:08 GMT+01:00 Sean Harlow <notifications@github.com>:

> I have a fresh install of OpenELEC 5.0.0 on a Gigabyte GA-C1007UN-D in my
> home theater.
>
> I've previously used XBMCbuntu on this machine and have a long-standing
> shared MySQL database to keep my library in sync between this appliance, a
> few normal PCs, and a few Android sticks.
>
> I have already updated the other machines and thus any library updates
> have already happened.
>
> Using the following basically dead standard MySQL config entries in
> advancedsettings.xml
>
> <videodatabase>
>   <type>mysql</type>
>   <host>10.0.0.12</host>
>   <port>3306</port>
>   <user>xbmc</user>
>   <pass>xbmc</pass>
>   <name>xbmc_video</name>
> </videodatabase>
> <musicdatabase>
>   <type>mysql</type>
>   <host>10.0.0.12</host>
>   <port>3306</port>
>   <user>xbmc</user>
>   <pass>xbmc</pass>
>   <name>xbmc_music</name>
> </musicdatabase>
>
> I get the following log spam (obviously a lot of other similar log entries
> removed because they're redundant to the point) on every single boot and my
> library does not work.
>
> 15:40:06 T:140060025415552   ERROR: Unable to open database: xbmc_music48 [2003](Can't connect to MySQL server on '10.0.0.12' (101))
> 15:40:06 T:140060025415552   ERROR: Unable to open database: xbmc_music47 [2003](Can't connect to MySQL server on '10.0.0.12' (101))
> 15:40:06 T:140060025415552   ERROR: Unable to open database: xbmc_music46 [2003](Can't connect to MySQL server on '10.0.0.12' (101))
> 15:40:06 T:140060025415552   ERROR: Unable to open database: xbmc_music45 [2003](Can't connect to MySQL server on '10.0.0.12' (101))
>
> log spam (obviously a lot of other similar log entries removed because
> they're redundant to the point) on every single boot and my library does
> not work.
>
> If I SSH in and "killall -9 kodi.bin" to restart it after networking is
> actually running I get
>
> 15:42:31 T:139762596001664  NOTICE: Running database version xbmc_music48
> 15:42:31 T:139762596001664  NOTICE: Running database version xbmc_video90
>
> and everything works as intended.
> ------------------------------
>
> I'm not sure what the best solution would be. Since Kodi only tries for a
> bit and then gives up forever any solution I can see at the moment involves
> delaying launching Kodi if a network connection exists but is not ready,
> but obviously that is not desirable for anyone who may have a slow network
> but plays local media and thus doesn't care if the network is ready or not.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3836>.
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by wolrah** [comment]
I'm an idiot, found the delay option right after posting this.
