### ISSUE TITLE
Apple Superdrive support

### ISSUE THREAD

**Issue by benrori** [OpenELEC/OpenELEC.tv#3839]
Would it be possible to allow use of an apple superdrive USB DVD drive as described for linux here:

https://christianmoser.me/use-apples-usb-superdrive-with-linux/

and here:

https://github.com/onmomo/superdrive-enabler

**Comment by lrusak** [comment]
That link offers a binary for either arm (rpi) or x86_64. Download one of them that is suitable for your hardware.

Then write a udev rule like he shows. If you need more help make a forum discussion as this is a place for bug reports.

**Comment by lrusak** [comment]
Please make a thread in the forums if you are having troubles with this.
