### ISSUE TITLE
OpenELEC 5.0 Poor FPS DVD Playback 

### ISSUE THREAD

**Issue by DBQATeam** [OpenELEC/OpenELEC.tv#3842]
This is most likely the same issue that is this post: https://github.com/OpenELEC/OpenELEC.tv/issues/3763

I’ve been holding out on updating my Arctic PC (http://www.arctic.ac/us_en/mc001.html) running Openelec 3.2.4 and decided to try the 5.0 update because I’ve been running into some newer mp4 files that were not playing.

I updated via the “Update” folder.
Mp4 files that weren’t playing began to play. I began to test other functions and got to the DVD player. Playback was choppy. I viewed the FPS as 15-17.  

I switch back to 3.4.2 and the FPS on the same DVD was 23-24.

PC:
Dual Core Intel Atom D525 (1.8GHz) CPU   
ATI Mobility Radeon HD 5430 GPU   
4GB DDR3 memory   
DVD-RW drive 24x

**Comment by mrdominuzq** [comment]
Did You try the build from #3763 ?:)

**Comment by fritsch** [comment]
Closed in favor of  https://github.com/OpenELEC/OpenELEC.tv/issues/3763

New reports won't help. Needs bisecting with users and their affected hardware.
