### ISSUE TITLE
Video settings reset to default on boot/resume

### ISSUE THREAD

**Issue by BostonVinnie** [OpenELEC/OpenELEC.tv#3845]
I am running OpenElec 5.0.0 on an Acer Revo Aspire R3600, connected to a Sony KDL40M4000 LCD TV. I am also using a  Pulse-Eight USB-CEC adaptor between the TV and nettop so I can use the TV remote to control OpenElec.

On installation, OpenElec sets the video output resolution at 1248x742p. Unfortunately, this is not ideal for the TV, and will generally result in an "Invalid Format" blue screen on boot, resume, or switching from TV to HDMI. I can generally get the OpenElec display back by pressing CTRL-ALT-F8 / CTRL-ALT-F1 several times, but this is inconsistent - sometimes OpenElec would appear for several seconds, then the display would switch back to the "Invalid Format" blue screen. 

This same issue occurred with this setup on previous versions of OpenElec (through 4.2.1), but if I was able to get the OpenElec display, I could resolve it by changing the resolution to 1360x768p, and the problem would not recur. 

However, starting with 5.0.0, the system will frequently reset the resolution to 1248x742p. Oddly, it does not happen all the time, but if it does I have to again cycle through CTRL-ALT-F8 / CTRL-ALT-F1 until I get back to OpenElec, then change the display back.

**Comment by lrusak** [comment]
Please SSH and post the URL that is output from the following command
```xrandr | paste```

**Comment by BostonVinnie** [comment]
MINI:~ # xrandr | paste
http://sprunge.us/ZNcF
MINI:~ #

**Comment by lrusak** [comment]
```echo "#!/bin/sh"```
```echo "xrandr --output HDMI-0 --mode 1920x1080 --rate 60.0" > /storage/.config/autostart.sh```

If then reboot, if that doesn't work, please make a post in the forums

**Comment by BostonVinnie** [comment]
Thanks, that seems to have done it (changing the mode to 1360x768, which is
the best resolution for this TV), rebooted a few times and it appears to
stick.

-- B.
