### ISSUE TITLE
Utilize CAAM hardware cryptographic engine CESA co-processor on on Amlogic ARM SoCs

### ISSUE THREAD

**Issue by Hedda** [OpenELEC/OpenELEC.tv#3846]
[Feature Request] Utilize CAAM hardware cryptographic engine CESA co-processor on Amlogic ARM SoC Series.

Amlogic ARM SoC series like the AML8726-MX family which OpenELEC supports contain an integrated CAAM (Cryptographic Acceleration and Assurance Module) hardware engine supporting ARM's TrustZone can be used to hardware accelerate cryptographic decryption decipher and encryption cipher.

Best real-world examples to advantage of hardware accelerators for this on Kodi/XBMC's Linux distros like OpenELEC are transparently for dependent libraries like OpenSSL, OpenSSH, GnuTLS, dm-crypt, kcryptd, dm-mod, and/or luks via cryptodev library API (caam drivers in kerne and openssl-cryptodev, etc. libraires).

This could also be useful for other applications and services running on OpenELEC, like for example descrabbling channels in latest TVheadend with SAT>IP using AES over openssl lib, so utilizing cropto engine could mean less CPU load.

http://cryptodev-linux.org (Comparisons: http://cryptodev-linux.org/comparison.html )

Utilize hardware cryptographic engine CESA co-processor for hardware acceleration encryption / decryption crypto and ciphers calculations tasks such as SSL, SCP, SSH, AES, TLS, DES, 3DES, SHA / SHA-1, MD5, hashes, dm-crypt, luks, etc. (such as hardware decryption with OpenSSL, OpenSSH, and GnuTLS libraries via CryptoDev to offload cryptographic tasks from CPU and therefore every dependency module that XBMC utilizes which support CryptoDev cryptographic accelerator drivers via /dev/crypto).

Standard libraries do not have support so have to use via cryptodev or NCR API's
http://cryptodev-linux.org
http://cryptodev-linux.org/ncr.html

HW decrypt and encrypt could probably be done on most embedded systems that OpenELEC support but this specific feature request is for HW crypto on Amlogic ARM SoC series.

To clarify, this feature eally belong here for OpenELEC (Linux OS distro) and not upstream in XBMC/Kodi core code. The reason for this is that these you in the Linux operating-system layer decide if dependency libraries utilize hardware acceleration or not. Read comments from XBMC/Kodi developer here https://github.com/xbmc-imx6/xbmc/issues/77

The old CuBox usage example implementation: http://www.solid-run.com/archive/phpbb/viewtopic.php?f=9&t=634

Example benchmarks for CAAM acceleration on similar ARM platform Freescale i.MX6 SoC  http://forums.wandboard.org/viewtopic.php?f=12&t=109&p=543

**Comment by Hedda** [comment]
Please confirm with an Amlogic expert, like codesnake from WeTek, before closing this

https://github.com/codesnake/OpenELEC.tv

And the same goes for pull request #3826 https://github.com/OpenELEC/OpenELEC.tv/issues/3826

**Comment by stefansaraev** [comment]
why you continue to open new requests? support wont happen automagicaly just because you demand it.

**Comment by fritsch** [comment]
He uses this reports as his notice book - after he has filed everything, he
will start to implement his first report.

:-)

2015-01-28 12:53 GMT+01:00 Stefan Saraev <notifications@github.com>:

> why you continue to open new requests? support wont happen automagicaly
> just because you demand it.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3846#issuecomment-71822974>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by sraue** [comment]
i am not sure if we can benefit from this (more then the NSA at least). If you can show use some data so we can see its really usefull we could decide todo this.
Also note we dont use OpenSSL, GnuTLS, dm-crypt, kcryptd, dm-mod, and/or luks in OpenELEC.

**Comment by Hedda** [comment]
OpenELEC does not use Trac for feature requests like Kodi does, and instead if you go to your website at http://openelec.tv and click the top drop-down menu for "DEVELOPMENT" it have a heading to "FEATURE REQUESTS" which links here to https://github.com/OpenELEC/OpenELEC.tv/issues

Based on that where do you expect that people will submit their feature request for OpenELEC?

**Comment by chewitt** [comment]
You are making requests in the correct place, but your requests are multi-page theory with no supporting evidence of actual benefit or any technical detail on how we should go about implementing support. Are you asking us for a one-line kernel config change, or to add twelve new heavily linked libraries to the core distro? Show clear benefit and provide proof and you might pique interest. Otherwise you are seen as someone asking for complexity in what is usually a marginal (if technically more elegant) performance gain. We are a small project with limited bandwidth so unless there's an obvious win, we will favour more generic low-complexity and low-maintenance capabilities.
