### ISSUE TITLE
Language inconsistencies

### ISSUE THREAD

**Issue by boghison** [OpenELEC/OpenELEC.tv#3847]
Hello! I have OpenELEC running on a RPi, connected via HDMI to a TV whose language is Russian. I turned off the automatic language recognition feature and everything worked flawlessly, until I stumbled across these small details:
![p_20150128_175022_hdr](https://cloud.githubusercontent.com/assets/7976283/5941138/8c0bce54-a717-11e4-9006-74c8734b1bb0.jpg)
![p_20150128_174734_hdr](https://cloud.githubusercontent.com/assets/7976283/5941149/98cac0a0-a717-11e4-8924-44165c8b6081.jpg)

Any ideas?

**Comment by chewitt** [comment]
I'm closing the ticket because this is a development bug tracker not a help channel for users, and OE is not responsible for upstream Kodi functionality related to languages or missing skin translations. Kodi forums is the appropriate place to investigate. Удачи!

**Comment by boghison** [comment]
@chewitt Oh, sorry. I thought this wasn't a Kodi issue, but an OpenElec one (since OE is the one that has the functionality to get the language from the TV). Спасибо!
