### ISSUE TITLE
Boxee compatibility

### ISSUE THREAD

**Issue by rudemoe** [OpenELEC/OpenELEC.tv#3852]
Dear Masters!
Please breathe new life into the boxee by porting your amazing software onto it.
The Dlink Boxee Box is a remarkable piece of hardware and should be salvaged.
When it was released, the technology was way ahead of it's time.
Today, some of us still use the Boxee Box and it can still be purchased at Bestbuy.
Thank you for your consideration.

**Comment by fritsch** [comment]
Thanks - but we have no interest in doing so.
