### ISSUE TITLE
IMX6, HummingBoard pro, iwlwifi > special build required

### ISSUE THREAD

**Issue by fanste** [OpenELEC/OpenELEC.tv#3853]
It would be nice, if you could add a special build for the HummingBoard pro, which has a mini PCIe slot that could be used with miniPCIe WIFI cards. Currently those cards do not work, because of the missing PCI support (kernel config: CONFIG_PCI, CONFIG_PCIEPORTBUS, etc). 

Additionally this is required for some WIFI driver modules, that are already part of the kernel. E.g. iwlwifi (CONFIG_IWLWIFI, etc) for Intel WIFI cards.

I've hacked it together and it is working. But as I don't have any experience with how to configure a kernel (which tools you should use, etc), I've done it directly in the option file and confirmed the missing options (many many options...) during the build process. So I can't provide my configuration.

Tested with an Intel Advanced-N 6205.

**Comment by chewitt** [comment]
No need for a special build when you can add the required config to the imx6 project. The "Generic" project supports the same cards if you want to compare the kernel configs to figure it out.

**Comment by fanste** [comment]
Isn't it problematic for IMX6 boards, that do not have PCI at all?

**Comment by chewitt** [comment]
It's harmless. If the hardware is not detected the kernel doesn't use the modules. The only impact is a small size increase to the KERNEL file (or whatever it's called on imx6).

**Comment by fanste** [comment]
I've created a patch based on the latest master and openelec-5.0 and will test them this weekend. If everything is okay, I will create a pull request.
