### ISSUE TITLE
Raspberry Pi 2 support

### ISSUE THREAD

**Issue by dagwieers** [OpenELEC/OpenELEC.tv#3860]
http://www.raspberrypi.org/raspberry-pi-2-on-sale/

**Comment by fritsch** [comment]
And please spam github. Enough people spamming our IRC channel at the moment. Raspberry PI 2 support is already done. Everything will be released in the next few hours.

**Comment by dagwieers** [comment]
This is not spam and you shouldn't assume I opened a feature request just to annoy you. If you are annoyed by the same question being asked over and over again, it's because people do not find the answer in the places they have looked (e.g. website, feature requests, commits).

What you could have done to reduce the number of requests (what you call spam ?) is to keep this open and e.g. tag it "Work-in-progress" until it is committed. At least that way some people would have seen it and probably didn't turn up on IRC to ask the same question when they cannot find information in the commits or in the issue-tracker.

**Comment by fritsch** [comment]
We changed the IRC topic to include it and everything was fine. User read the homepage not github.

**Comment by stefansaraev** [comment]
holy f***...
