### ISSUE TITLE
Request: driver support for rtl8192

### ISSUE THREAD

**Issue by rjdennison** [OpenELEC/OpenELEC.tv#3861]
Hey all.

I'd like to request support for the rtl8192 realtek wifi chipset. the updated drivers are available on github (https://github.com/pvaret/rtl8192cu-fixes), but with no apt-get, dkms, or git support in SSH on openelec, I can't install it myself.

this is a pretty popular chipset with Amazon selling this little Edimax EW-7811Un guy for US$9 (http://amzn.com/B003MTTJOY). I've got it up and running with an Ubuntu server solution and works great as long as you disable the power management (at least on my build). All those details are at the github site.

**Comment by vpeter4** [comment]
This driver is already included in Openelec as [RTL8192CU](https://github.com/OpenELEC/OpenELEC.tv/tree/master/packages/linux-drivers/RTL8192CU) package. Maybe this specific stick is not supported yet. What you get with command lsusb on Ubuntu?

**Comment by rjdennison** [comment]
It shows up as

ID 7392:7811 Edimax Technology Co., Ltd EW-7811Un 802.11n Wireless Adapter
[Realtek RTL8188CUS]

Oddly it didn't work until I updated the driver to 8192CU-fixes and
blacklisted the old driver, then turned off the power management. I guess
I'll dig in the wiki on how to install this package and see if that works.

Thanks.

**Comment by vpeter4** [comment]
This stick should work on 5.0. There is nothing to update.

**Comment by lrusak** [comment]
Mine is working just fine,
    Bus 001 Device 004: ID 7392:7811 Edimax Technology Co., Ltd EW-7811Un 802.11n Wireless Adapter [Realtek RTL8188CUS]
