### ISSUE TITLE
WLAN support For RTL8189RU (Alfa network AWUS036NHR)

### ISSUE THREAD

**Issue by ColinBarlow** [OpenELEC/OpenELEC.tv#3862]
Does anyone know if this chipset is fully supported? It's recognised on both PC and Raspberry Pi.  AP's can be seen in OpenELEC but an input/output error is shown when trying to establish a connection  both with secured or open access points.
 The adapter works find with a Ubuntu PC.
Any help will be gratefully received.

Colin.

**Comment by stefansaraev** [comment]
[see](https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md)
