### ISSUE TITLE
Separate audio output configuration per type of media 

### ISSUE THREAD

**Issue by apassemard** [OpenELEC/OpenELEC.tv#3865]
Hello, 
I use a raspberry pi with a hi-fi berry dac in it. It's great to listen to music but when I want to watch a movie I need to go to the setup and change the audio output to hdmi to be able to enjoy the Dolby digital or whatever multi channel I have. Then when done, if I want to listen to music again through the dac,  I have to go back in the setup,  etc, etc.. 

It would be great if in the drop Us,  the audio output could be set by media 
  Music - - > dac
  Video - - > dac
  Movie - - > hdmi
  Etc.. 

Thanks for considering. It seems many people are trying to find hacky solutions to that problem.

**Comment by apassemard** [comment]
"setup"  not "drop us".  Smartphones are to smart..

**Comment by chewitt** [comment]
I'm closing the ticket because the correct place for the request is http://trac.kodi.tv because anything related to audio routing in Kodi needs to be done upstream from us.
