### ISSUE TITLE
OpenELEC 5.0.1 Pi2 no I2S DAC driver

### ISSUE THREAD

**Issue by PeteAU** [OpenELEC/OpenELEC.tv#3868]
Using the new OpenElec 5.0.1 on a Raspberry Pi 2, there is no longer an option to use a I2S DAC.
I am unsure if this is a OpenElec (which drivers get bundled), Kodi (advancedsettings.xml) or Linux kernel issue.

# lsmod
Module                  Size  Used by
snd_soc_hifiberry_dac     2167  0 
snd_soc_pcm5102a        1463  0 
snd_soc_bcm2708_i2s     5975  0 
regmap_mmio             2050  1 snd_soc_bcm2708_i2s
snd_soc_core          104929  3 snd_soc_hifiberry_dac,snd_soc_pcm5102a,snd_soc_bcm2708_i2s
snd_compress            6924  1 snd_soc_core
snd_pcm_dmaengine       2811  1 snd_soc_core
snd_pcm                59952  3 snd_soc_core,snd_soc_hifiberry_dac,snd_pcm_dmaengine
snd_timer              15847  1 snd_pcm
snd                    38558  4 snd_soc_core,snd_timer,snd_pcm,snd_compress
bcm2708_rng              801  0 

AFAIK the bcm2709 is compatible with bcm2708 for I2S, but the Base address is different.
If this is an upstream kernel issue, I may be opening this ticket in the wrong place, sorry about that.

**Comment by MilhouseVH** [comment]
Read this:

https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README

**Comment by PeteAU** [comment]
On my fresh 5.0.1 installation /flash/overlays/README.TXT is 0 bytes and no other files in that dir. Is that normal?

I grabbed my own copy of hifiberry-dac-overlay.dtb off the 'net and it is working fine.

**Comment by MilhouseVH** [comment]
Yes on the README.TXT being 0 bytes, no on the overlays being empty.

**Comment by PeteAU** [comment]
I see, I thought the problem might be a Pi2 issue, but I was wrong.

So yes, /flash/overlays/ was an empty dir (besides README.TXT), after installing OpenELEC-RPi2.arm-5.0.1.tar.

**Comment by MilhouseVH** [comment]
I guess 5.0.1 will need an update. You can try a [test build](http://forum.kodi.tv/showthread.php?tid=211501) if you want, as these should populate the overlays folder.

**Comment by PeteAU** [comment]
Can confirm it's fixed in OpenELEC-RPi2.arm-Milhouse-20150203210258-r20194-gfa82a48. All the dtb files are present again.

This is what a fresh 5.0.1 install looks like:

OpenELEC:~ # find /flash/
/flash/
/flash/cmdline.txt
/flash/kernel.img
/flash/SYSTEM
/flash/bcm2709-rpi-2-b.dtb
/flash/bootcode.bin
/flash/config.txt
/flash/fixup.dat
/flash/LICENCE.broadcom
/flash/overlays
/flash/overlays/README.TXT
/flash/start.elf
/flash/openelec.ico
/flash/README.md
OpenELEC:~ #

**Comment by sraue** [comment]
should be fixed with https://github.com/OpenELEC/OpenELEC.tv/commit/2850f45a23491f3dcdf58bf31848254a357d369a

**Comment by PeteAU** [comment]
Same problem (no overlays) in 5.0.2.

**Comment by MilhouseVH** [comment]
It looks like the RPi base dtbs are missing, but the overlays are present (RPi2 looks OK on both countrs). Unfortunately, the current openelec-5.0 code is always going to fail when there is more than one base dtb, as is the case for the RPi (b and b-plus).

I [did say](https://github.com/OpenELEC/OpenELEC.tv/commit/1f2b668d48144b11c8b89d4b684da60afb3e3f4a#commitcomment-9631533) it wouldn't work. :(

Also, when updating to OpenELEC 5.0.2, it overwrites the users own config.txt with the stock config.txt - this happened on both a Pi1 and Pi2. I don't recommend anyone upgrade to OpenELEC 5.0.2 without a backup of their config.txt.

**Comment by MilhouseVH** [comment]
Just thinking that making a backup of config.txt before overwriting (intentionally or unintentionally) might be a _very_ good idea...

**Comment by PeteAU** [comment]
In all of Milhouse's unofficial builds, the overlays are there and work well, but not so in any official OpenELEC 5.0.x. thus far.

Is it a case of "wont fix", or shall I open a new report? Or a feature request?

**Comment by MilhouseVH** [comment]
The default kernel for OpenELEC 5.x is still 3.17.x, and this kernel doesn't support device tree.

RPi (Pi1) is built with the default 3.17.x kernel, so it has no device tree support. RPi2 on the other hand does have overlay support as it has to be built with kernel 3.18.9 (RPi2 doesn't support kernel 3.17.x).

So you have overlays in RPi2, but not RPi with official builds. This will change when official releases of OpenELEC move to a more recent kernel.

My unofficial builds are using 3.19.1 for both RPi and RPi2, so both have overlays and device tree support.

**Comment by fritsch** [comment]
OpenELEC use 3.18.x for the PI ...

2015-03-18 12:51 GMT+01:00 MilhouseVH <notifications@github.com>:

> The default kernel for OpenELEC 5.x is still 3.17.x, and this kernel
> doesn't support device tree.
>
> RPi (Pi1) is built with the default 3.17.x kernel, so it has no device
> tree support. RPi2 on the other hand does have overlay support as it has to
> be built with kernel 3.18.9 (RPi2 doesn't support kernel 3.17.x).
>
> So you have overlays in RPi2, but not RPi with official builds. This will
> change when official releases of OpenELEC move to a more recent kernel.
>
> My unofficial builds are using 3.19.1 for both RPi and RPi2, so both have
> overlays and device tree support.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/3868#issuecomment-82927128>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by MilhouseVH** [comment]
That doesn't appear to be the case in the OpenELEC 5.0 branch:

`RPi Options`: [default Linux](https://github.com/OpenELEC/OpenELEC.tv/blob/openelec-5.0/projects/RPi/options#L60)
`RPi2 Options`: [3.18 Linux](https://github.com/OpenELEC/OpenELEC.tv/blob/openelec-5.0/projects/RPi2/options#L60)
`Linux`: [default is 3.17.8](https://github.com/OpenELEC/OpenELEC.tv/blob/openelec-5.0/packages/linux/package.mk#L29)

So RPi in OpenELEC 5.0 is built with 3.17.8, but RPi2 is building with 3.18.9.

Both RPi and RPi2 master builds are using 3.19.1.

**Comment by fritsch** [comment]
The Op is talking about RPi2, which is shipped with 3.18.x - am I wrong here?

**Comment by MilhouseVH** [comment]
@PeterAU [stated](https://github.com/OpenELEC/OpenELEC.tv/issues/3868#issuecomment-82913462) "but not so in any official OpenELEC 5.0.x. thus far."

I merely explained why the overlays are not present in RPi releases, but are present in RPi2 releases. I'm not sure why he's suggesting they are also not present in RPi2 releases - I've looked in the 5.0.6 RPi2 tar, and the overlays are there.

**Comment by fritsch** [comment]
Exactly, your last sentence is what I thought, too - I was confused out of the same reason.

**Comment by PeteAU** [comment]
Sry, I drifted onto talking about the RPi 1. I'd like it to work on both.

For RPI 2, the overlays are in the tarball in 5.0.6, so I assume they will install and work now.
For RPi 1 it's a matter of waiting for the next major kernel upgrade taken in by OpenELEC? 5.2?

**Comment by lrusak** [comment]
@PeteAU Yes OE 5.2 will bring all the kernel version to be the same.
