### ISSUE TITLE
vdr-addon: missing  vdr-plugin-restfulapi  package

### ISSUE THREAD

**Issue by susisstrolch** [OpenELEC/OpenELEC.tv#3869]
The vdr-plugin-restfulapi isn't found during build:
`  GET      vdr-plugin-restfulapi`
`--2015-02-04 14:43:38--  https://launchpad.net/~yavdr/+archive/ubuntu/unstable-vdr/+files/vdr-plugin-restfulapi_20150117203925unstable-0yavdr0~trusty.tar.gz`
`Resolving launchpad.net (launchpad.net)... 91.189.89.222, 91.189.89.223`
`Connecting to launchpad.net (launchpad.net)|91.189.89.222|:443... connected.`
`HTTP request sent, awaiting response... 404 Not Found`

Same is true for the mirror site:
`--2015-02-04 14:43:39--  http://sources.openelec.tv/mirror/vdr-plugin-restfulapi/vdr-plugin-restfulapi_20150117203925unstable-0yavdr0~trusty.tar.gz`
`Resolving sources.openelec.tv (sources.openelec.tv)... 82.220.2.33`
`Connecting to sources.openelec.tv (sources.openelec.tv)|82.220.2.33|:80... connected.`
`HTTP request sent, awaiting response... 404 Not Found`

**Comment by stefansaraev** [comment]
@gdachs

**Comment by stefansaraev** [comment]
uploaded to mirror.
@gdachs if upstream deletes the files once a week, it should be repackaged and uploaded to $DISTRO_SRC. please take care.

**Comment by gdachs** [comment]
Sorry for that, it was replaced by a newer version. I will look for a better way to host it.

**Comment by stefansaraev** [comment]
can be hosted at sources.openelec.tv/deve/ like other vdr plugin sources but should probably be repackaged, 20150117203925unstable-0yavdr0~trusty doesnt make much sense ;)
