### ISSUE TITLE
OpenELEC 5.0.1 loses network after a while

### ISSUE THREAD

**Issue by gamaoyabun** [OpenELEC/OpenELEC.tv#3873]
Hi,
since my system updates to 5.0.1, it loses the network from time to time. A reboot is need to recover network access.
There is a topic about this behavior on the Pi forum, where we can see the problem on different types of configurations:
http://openelec.tv/forum/124-raspberry-pi/75103-openelec-5-0-1-loses-network-after-a-while

I use a Zotac ATOM/Ion motherboard with Ethernet and DHCP with MAC address reservation.

Thanks

Regards
Gamaoyabun

**Comment by stefansaraev** [comment]
test this connman patcn: http://sprunge.us/AQXb

**Comment by stefansaraev** [comment]
please [test](http://saraev.ca/OpenELEC-Generic.x86_64-devel-20150206013848-r20003-gc029552.tar)

**Comment by stefansaraev** [comment]
fixed in 82750bbd6a00615df85aeff676c02e54c4d2bc4b be36a89c519e83a1a2c5b2da102734658892ce51
