### ISSUE TITLE
trakt loading script error

### ISSUE THREAD

**Issue by sipaan** [OpenELEC/OpenELEC.tv#3877]
Raspberry pi 2
openelec 5.0.1

trakt scrip is getting an error: script failed: trakt. 

on my windows machine it's working fine with kodi. 
![img_20150206_192454](https://cloud.githubusercontent.com/assets/7147804/6085205/17d211f6-ae38-11e4-8b8d-8d57b17e5b04.jpg)

**Comment by vpeter4** [comment]
I think you need to enable debug in Kodi and post some logs.

**Comment by Razzeee** [comment]
it's working fine for me with openelec 5.0.1 and the latest script.trakt build. might want to check your installation of the plugin itself.

**Comment by sipaan** [comment]
did a reinstall of OPENELEC and it's working fine again.. don't know what the issue was.
