### ISSUE TITLE
RPi2 Add-ons list empty

### ISSUE THREAD

**Issue by czettnersandor** [OpenELEC/OpenELEC.tv#3879]
http://addons.openelec.tv/4.3/RPi2/arm/addons.xml returns with 404:

22:04:17 T:2897409088  NOTICE: ## OpenELEC Addon ## 0.5.8
22:04:19 T:2816472128   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 404
22:04:19 T:2816472128  NOTICE: CCurlFile::FillBuffer - Reconnect, (re)try 1
22:04:19 T:2816472128   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 404
22:04:19 T:2816472128   ERROR: CCurlFile::CReadState::Connect, didn't get any data from stream.
22:04:19 T:2816472128   ERROR: Open - failed to open source <http://addons.openelec.tv/4.3/RPi2/arm/addons.xml.md5>
22:04:20 T:2816472128   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 404
22:04:20 T:2816472128  NOTICE: CCurlFile::FillBuffer - Reconnect, (re)try 1
22:04:20 T:2816472128   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 404
22:04:20 T:2816472128   ERROR: CCurlFile::CReadState::Connect, didn't get any data from stream.
22:04:20 T:2816472128   ERROR: Open - failed to open source <http://addons.openelec.tv/4.3/RPi2/arm/addons.xml>
22:04:20 T:2816472128   ERROR: Repository [COLOR FF757677]Open[/COLOR][COLOR FF8ABEE2]ELEC[/COLOR] Mediacenter OS Add-ons returned no add-ons, listing may have failed

**Comment by ryang-cvv** [comment]
Addons are arch specific, and the RPi2 is ARMv7 - RPi is ARMv6.  Technically all ARMv6 addons will run fine on RPi2, but they are using different repos.

See http://forum.kodi.tv/showthread.php?tid=211501&pid=1917224#pid1917224 for some more info.

**Comment by stefansaraev** [comment]
force refresh now.

**Comment by czettnersandor** [comment]
I'm aware of that it will run. Now I'm not sure where to report this problem. I downloaded the RPi2 package from here:
http://openelec.tv/get-openelec
http://releases.openelec.tv/OpenELEC-RPi2.arm-5.0.1.img.gz

I burnt the image to an SD card and seems the repository is not accessible.

**Comment by czettnersandor** [comment]
Thanks, worked
