### ISSUE TITLE
AMD G series SoC Audio issues

### ISSUE THREAD

**Issue by ovidiu31** [OpenELEC/OpenELEC.tv#3882]
using an AMD g series soc microboard here.
AMD Embedded GX-412HC (4 x 1.2 GHz, L2 cache 2MB, 7 W)
sound via hdmi is jerky and with echo

Here is a dmesg if is needed
http://sprunge.us/RGSI

**Comment by fritsch** [comment]
Known upstream kernel bug, it is already filed at bugs.freedesktop.org - please see the DRM/Radeon section.
