### ISSUE TITLE
Hebrew result Searching  are opposite

### ISSUE THREAD

**Issue by ghost73** [OpenELEC/OpenELEC.tv#3883]
when you Searching for in hebrew,the result will get opposite.
e.g :Searching for "שר"  ,you get "רש"

**Comment by fritsch** [comment]
Thanks much for not reading the contributing link before using github -> forum.

**Comment by ghost73** [comment]
I don't understud?

**Comment by stefansaraev** [comment]
[see](https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md) :)
