### ISSUE TITLE
Add libmad/libmpg123, libfaad, libFLAC in OpenELEC 5 for Raspberry Pi

### ISSUE THREAD

**Issue by ldobl** [OpenELEC/OpenELEC.tv#3884]
Currently, these libraries (required for playback of mp3, aac and FLAC, e.g. by squeezelite/XSqueeze) are not part of the libs in the SYSTEM image, and adding them is pretty inconvenient, since it requires messing with mksquashfs.

Would it be possible to add them in a future release without going to too much trouble?

**Comment by stefansaraev** [comment]
rebuild your addons.
