### ISSUE TITLE
Feature request for tvheadend

### ISSUE THREAD

**Issue by Frank-NL** [OpenELEC/OpenELEC.tv#3890]
I know there is no official support on tvheadend anymore. Please forgive me :)

I see that Oscam now has the option to wait until the network is online (https://github.com/OpenELEC/unofficial-addons/commit/404c5fe601836a0896516746e0d7e46f3eb3986e).

Since OE 5.0.1, tvheadend is started so fast, that I don't have a working network IP (it's really a matter of 2 or 3 seconds) and tvheadend cannot find the hdhomerun device anymore (it's a network tuner as you might know). I have fixed this by adding sleep to the system.d unit file.
By adding the same cm-online option to tvheadend, it would be future proof again for network tuners.

Sorry to abuse the official issue tracker for this, but it would be great for me and other users if you could add this!

**Comment by stefansaraev** [comment]
feel free to send a PR to unofficial repo :)
