### ISSUE TITLE
HDMI-CEC Wake-up doesn´t work

### ISSUE THREAD

**Issue by misterjay** [OpenELEC/OpenELEC.tv#3892]
Hello

With OpenElec 4 it was possible to Wake-up the Mediaplayer with HDMI-CEC (on the TV switch to the Mediaplayer HDMI port)

Since OpenElec 5 this function doesn´t work anymore

The problem is the libcec version 2.2.0
In libcec 2.1.4 all works fine

see here: http://openelec.tv/forum/118-consumer-electronics-control-cec/74787-tv-does-not-wake-nuc-with-oe5-but-did-with-4-2#130998

**Comment by stefansaraev** [comment]
ppft.
