### ISSUE TITLE
Fresh install RP2 image "works" but hangs after reboot.

### ISSUE THREAD

**Issue by josja** [OpenELEC/OpenELEC.tv#3898]
After setting everything up on my new RP2 it worked until a skin froze my system, then I noticed any reboot fails, even with plain vanilla default settings. Reproduced it 5 times.

After install, no change in default settings:
![2015-02-10 13 17 10](https://cloud.githubusercontent.com/assets/5016263/6127213/c7c554cc-b128-11e4-82e5-be00a8d2b658.jpg)

- Reboot, shows OpenElec logo, shows top left OpenElec 5.0.1 version and an underscore on the next line (doesn't boot further, power & active LED are both on, not-blinking)
![2015-02-10 13 17 48](https://cloud.githubusercontent.com/assets/5016263/6127220/dca6ccc2-b128-11e4-9ac8-934b87782d51.jpg)

- Reboot again, shows OpenElec logo, shows top left: storage can't be mounted (doesn't boot further waits for input, only power LED is on)
![2015-02-10 13 23 02](https://cloud.githubusercontent.com/assets/5016263/6127151/2ac2edce-b128-11e4-8ab5-aada24fe4f9f.jpg)

Image used: OpenELEC-RPi2.arm-5.0.1
OpenElec 5.0.1, Kernel 3.18.5, Kodi 14.1 Git:b5dbdb5, compiled on 1 feb 2015

16GB SD created using DD on OSX 10.9.5

**Comment by popcornmix** [comment]
The "could not mount /dev/mmcblk0p2" suggests the sdcard is corrupted.
A reinstall would be recommended.

On linux you could try fixing the sdcard with e2fsck (there may be a version for OSX), but it's not always successful.

**Comment by josja** [comment]
But it seems to me that the rebooting results in corruption of the storage. Reinstalling works, but rebooting corrupts the install. But I see 5.0.2 just released. Going to reinstall for the 6th time trying to reproduce it, but now with 5.0.2.

**Comment by chewitt** [comment]
I'm closing the ticket because this is not a development issue and user-help is provided via the forums.

**Comment by PiLLoX** [comment]
Same issue for me on my RPi2 using OpenELEC-RPi2.arm-5.0.2 image. I'm using 16GB SD card, created using DD on OS X 10.10.2

Worked perfectly on my RPi1B+

**Comment by josja** [comment]
I just tried the same SanDisk 16GB Mobile Ultra card with 5.0.2, hanged when rebooting (right after partitioning step). But.... another 32GB SD I had laying around actually worked (with 5.0.2 image). Note: Disk Util didn't want to erase it but it managed to repartition it. Interesting to see how a seemingly correct installation doesn't guarantee to be rebootable. Might be a partitioning issue.
