### ISSUE TITLE
CEC not working on OE5.0.2 / RPi2

### ISSUE THREAD

**Issue by PiLLoX** [OpenELEC/OpenELEC.tv#3899]
After fresh install of OpenElec 5.0.2, OpenELEC-RPi2.arm-5.0.2 image on my new RPi2, I lost CEC support on my Panasonic TV, which I used to remote my former RPi1 with.

**Comment by fritsch** [comment]
This is not your personal place for spamming. Please read: https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md
