### ISSUE TITLE
Request: Driver Update for RTL8153 (R8152)

### ISSUE THREAD

**Issue by Bototski** [OpenELEC/OpenELEC.tv#3901]
There's a new update for Realtek's USB 3 to Gigabit adapter. Would be nice to add this on next build as it might have some improvements.

Driver Link: http://www.realtek.com.tw/downloads/downloadsView.aspx?Langid=1&PNid=13&PFid=56&Level=5&Conn=4&DownTypeID=3&GetDown=false

LINUX driver for kernel 3.x
ver: 2.0.3
update time: 2014/11/19

Current version (OpenElec 5.0.3 - Kernel 3.17.8):
![2015-02-11_022306](https://cloud.githubusercontent.com/assets/10951443/6140821/0feeb8f8-b195-11e4-8996-30d9aece7f10.jpg)

Thanks!

**Comment by chewitt** [comment]
I'm closing the ticket because we use the in-kernel driver module not the external binary. If/as/when realtek get their stuff together and push driver changes to the kernel we'll pick them up.
