### ISSUE TITLE
set DNS through command-line

### ISSUE THREAD

**Issue by redraw** [OpenELEC/OpenELEC.tv#3903]
Is it possible to set DNS through command-line (SSH)?
I'm using OpenELEC 5.0.1
I haven't got access to the Raspberry Pi and I need to do it through SSH.

In the forums they recommended to do it on the GUI because there was some connman magic happening behind. Plus, OpenELEC doesn't work like a normal linux and I can't do it inside /etc/resolv.conf

**Comment by stefansaraev** [comment]
please ask questions in forums or irc. this bugtracker is for bug reports and developments only.
https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md
