### ISSUE TITLE
VDR VNSI Client: commit for KODI missing

### ISSUE THREAD

**Issue by mglae** [OpenELEC/OpenELEC.tv#3904]
Commit d1538ebi "vnsi: only consider video and audio streams for playing time" is missing in "kodi" branch of opdenkamp/xbmc-pvr-addons. It is only included in "master" branch.

This updates VNSI client to 1.9.23, see #3775

**Comment by stefansaraev** [comment]
there is no "kodi" branch at opdenkamp/xbmc-pvr-addons. we build from "helix" branch. last commit there is a0a437e, exactly what is included in openelec.

we dont backport random commits from master to helix, your fix will be included in openelec when it lands in xbmc-pvr-addons helix branch
