### ISSUE TITLE
gpio not supported anymore for raspberry pi 2

### ISSUE THREAD

**Issue by just4fun73de** [OpenELEC/OpenELEC.tv#3908]
i use lirc for my remote control on raspberry pi 2. 

but with the new rasp lirc isnt supported anymore.

see: dmesg | grep lirc --> emtpy list

OpenELEC:~ # modprobe lirc_rpi
modprobe: ERROR: could not insert 'lirc_rpi': No such device

OpenELEC:~ # dmesg | grep lirc
[ 1033.769079] lirc_dev: IR Remote Control driver registered, major 248 
[ 1033.778591] lirc_rpi: module is from the staging directory, the quality is unknown, you have been warned.
[ 1033.780826] lirc_rpi: gpio chip not found!

Alex

**Comment by popcornmix** [comment]
You should use the forums for questions like this.
But, read: https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README

Add to config.txt
dtoverlay=lirc-rpi

**Comment by loisaidasam** [comment]
I experienced the same issue, and in case anyone else ends up here and doesn't know, `"config.txt"` refers to `/boot/config.txt`

(adding `dtoverlay=lirc-rpi` solved the issue for me :+1:)

**Comment by aHcVolle** [comment]
this did work! thanks
