### ISSUE TITLE
Corrupted USB Audio with Schiit Modi DAC [Raspberry Pi B+]

### ISSUE THREAD

**Issue by sanjibm** [OpenELEC/OpenELEC.tv#3913]
Schiit Modi USB DAC worked great on the Model B connected via a powered hub. Same setup on the Model B+ produces distorted/corrupted audio. The DAC is properly detected:

OpenELEC:~ # lsusb
Bus 001 Device 005: ID 0d8c:1319 C-Media Electronics, Inc. 
Bus 001 Device 004: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

OpenELEC:~ # aplay -l
**** List of PLAYBACK Hardware Devices ****
card 1: Device [Schiit USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

The audio runs too fast and crackles; can hardly recognise the music and its just mostly noise. Tested with MP3, WAV and FLAC files playing from local storage

**Comment by lrusak** [comment]
Please see, [Contributing](https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md)

**Comment by tunf** [comment]
@sanjibm Can you please upload your (debug) log files like mentioned by irusak?

**Comment by sanjibm** [comment]
Duplicate issue:
https://github.com/raspberrypi/linux/issues/888#
