### ISSUE TITLE
Raspberry Pi 2 HDMI CEC not working on Samsung TV

### ISSUE THREAD

**Issue by dbruynb** [OpenELEC/OpenELEC.tv#3920]
I have no idea where to look, just got my new Pi 2 but the CEC function does not work. Test with 3 different HDMI cables but no luck, then tested with my Pi 1 model B and its working fine so my TV and cables is good.

Have also tried selecting a different input source on the TV and then go back. None of the buttons is functioning, however audio and display resolution isn’t a problem.

Software wise I have done a Openelec upgrade from Pi 1 to Pi 2, then also wiped the SD card and load the Pi 2 version disk image from scratch.

Any suggestions?

**Comment by PiLLoX** [comment]
Same issue for me, w/ Panasonic TV, last OE and RPi2, works fine w/ RPi1 B+

Seems libCEC firmware has something to do w/ this issue, but don't know if we can downgrade, as RPi2 is pretty new...

**Comment by tunf** [comment]
works like a charm here. See also my other case with debug log and working cec in rpi2. Perhaps you have to setup anynet in your samsung to select other id/ source? there should be kodi in the list.
Also try other hdmi port....

**Comment by stefansaraev** [comment]
I am closing this because the reported did not follow the [rules](https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md)

**Comment by shamasis** [comment]
I understand that it is working for some and that the reporter did not make your life easy by providing logs, etc --- yet --- I have the exact same issue. 

Pi 1 B and B+ works just fine. Tested with a number of cables and switched source. Also reset TV firmware, etc. it's a latest Samsung TV though. 

Running latest OpenElec stable.

Will post more details when I get some time off work. 

PS: another issue I have (not sure if it's related,) if I overclock my Pi 2, increase any freq or voltage value in config.txt, my Pi crashes. I also have a robust 2.1A power supply - Sony CPAD2.
