### ISSUE TITLE
UPnP not possible for DVDs

### ISSUE THREAD

**Issue by t-echnics** [OpenELEC/OpenELEC.tv#3921]
When selecting a DVD by browsing the library via UPnP, you cannot play this video - neither on the client nor on the server. You just get an error message or nothing at all!

As a workaround, which ist not very comfortable, you can play a DVD via UPnP by directly choosing the files...

(all tested with OE 5.0.3 on RPI 1 and 2)

**Comment by lrusak** [comment]
Report to Kodi, we merely consume their application.

**Comment by chewitt** [comment]
I"m closing because this is upstream from us. Report this via Kodi forums.
