### ISSUE TITLE
Digital passthrough problem on RPi 2

### ISSUE THREAD

**Issue by dresco** [OpenELEC/OpenELEC.tv#3928]
Hardware is a Raspberry Pi 2 running OpenELEC 5.03, with Turtle Beach Audio Advantage Micro II USB audio adapter providing SPDIF connection into receiver.

If the primary audio adapter is left as the Pi HDMI output, and the USB adapter configured for passthrough, then there is no digital output. But if the primary audio is also set to use the USB adapter, then the passthrough works as expected. (I see this same behaviour with OSMC).

I have debug logs for both scenarios.

**Comment by dresco** [comment]
Was this labelled invalid due to the absence of logs? If so, have uploaded here..

http://sprunge.us/GAFR

**Comment by chewitt** [comment]
closing old tickets with no update.. should the issue still exist on a current release please start a forum thread, thanks.
