### ISSUE TITLE
CIR not loading on Intel NUC5i3RYH NUC Broadwell

### ISSUE THREAD

**Issue by xernaj** [OpenELEC/OpenELEC.tv#3930]
I'm running OE 5.02 x64 Generic.x86_64-5.0.2 on NUC5i3RYH Intel NUC (Broadwell) and the CIR does not load.

dmesg output shows nuvoton-cir has this error "IR PNP Port not valid!".

System log: http://sprunge.us/hJYW

Also reported in Intel Community forums as the error seems to be similar to the Haswell NUC issue that Intel and OpenElec apparently worked together to fix:
https://communities.intel.com/message/280190

**Comment by stefansaraev** [comment]
smells like a bios bug.

**Comment by fritsch** [comment]
Does this old workaround mentioned here: https://communities.intel.com/message/216302 still work?

**Comment by urandoma** [comment]
It does not. :(

**Comment by fritsch** [comment]
Then return your box to intel. It's something (again) they need to fix in their bios - gather other affected users and start a petition.

**Comment by stefansaraev** [comment]
https://communities.intel.com/message/288100#288100

from now on, openelec doesnt care about intel bios bugs ;).
