### ISSUE TITLE
Profie switching after stoping the music playback

### ISSUE THREAD

**Issue by Chingischan** [OpenELEC/OpenELEC.tv#3935]
Using Openelec 5.0.3. I have two profiles (A and B). Both using the same database settings. Profile A is chosen as auto login at the start of kodi. The bug appears when i start openelec and switch to my Profile B afterwards. When I  start some music on Profile B, I get automatically switched to Profile A when I stop the music Playback. Tested it on Raspberry B+ and CuboxTV. The issue appears on both systems.

**Comment by chewitt** [comment]
I'm closing the ticket because this is nothing to do with OpenELEC. Kodi issues should be reported to Kodi devs via their forums.
