### ISSUE TITLE
Raspberry Pi 2 Freezes

### ISSUE THREAD

**Issue by smille2** [OpenELEC/OpenELEC.tv#3940]
OpenELEC 5.0.3 (arm) Diskimage on RPi2

Changing to a (video-) directory (Samba) with >500 entries freezes the RPi2 (smaller directory on same server works fine)

Trying to install a new addon (sometimes by calling all addons or a subcategory) freezes the TPi2.

**Comment by fritsch** [comment]
Reason: https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md
