### ISSUE TITLE
Wifi dongle did not load when changing to newest version

### ISSUE THREAD

**Issue by NewTricks4OldGuy** [OpenELEC/OpenELEC.tv#3942]
I installed 4.xx first, and everything loaded fine. Then I went to 5.0..3 and my Raspberry Pie B+ did not load the Wifi dongle that worked on the older version.  I make a second image and moved the dongle to another USB port, but it still did not load. I checked the dongle in my PC, and the driver loaded automatically. I finished my install with a cable to my router/switch. 
Is there a better dongle that works more often than not?

Tnx for any feedback on this issue.

Joe KQ4BX

**Comment by chewitt** [comment]
End user support is provided via the forums. https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md
