### ISSUE TITLE
Error configuring Transmission Server

### ISSUE THREAD

**Issue by carlosyague** [OpenELEC/OpenELEC.tv#3944]
I am trying to configure Transmission Server on Raspberry Pi 2 Model B. I've installed this program using the programs list of available programs to install it.

When I configure this program, the transmission-daemon isn't running and if I try to re-configure this program I receive an error.

I've tried to configure this daemon using apt-get/yum command but it isn't possible on OpenELEC. 

Please, could you fix this error?
Is there any option to update/install components on OpenELEC? Is possible to install manually Transmission using a ZIP file?

Thank you in advance!

**Comment by lrusak** [comment]
End user support is provided via the forums.

Also, you should restart after you install the transmission addon ;)

**Comment by carlosyague** [comment]
Thank you, but your advice doesn't work for me.
![img_20150225_110137](https://cloud.githubusercontent.com/assets/1017882/6368535/f466c2ca-bcdd-11e4-9c08-aea172b21e45.jpg)
