### ISSUE TITLE
ATI AC97 VT8233 No Sound

### ISSUE THREAD

**Issue by delta360** [OpenELEC/OpenELEC.tv#3950]
With the VT8233 chipset there is no sound returned via the speakers, Alsa returns that there is no sound card even though the following outputs say otherwise.

LSMOD
Lakka:/ # lsmod
Module Size Used by
snd_intel8x0 24845 0
snd_ac97_codec 99286 1 snd_intel8x0
ac97_bus 1126 1 snd_ac97_codec
snd_pcm 60823 2 snd_ac97_codec,snd_intel8x0
p54pci 7500 0
p54common 23507 1 p54pci
mac80211 242411 1 p54common
cfg80211 192001 2 mac80211,p54common
k8temp 3119 0
firewire_ohci 26141 0
firewire_core 42605 1 firewire_ohci
crc_itu_t 1283 1 firewire_core

LSPCI
Lakka:/ # lspci | grep -A 20 Audio
00:11.5 Multimedia audio controller: VIA Technologies, Inc. VT8233/A/8235/8237 AC97 Audio Controller (rev 50)
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] K8 [Athlon64/Opteron] HyperTransport Technology Configuration
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] K8 [Athlon64/Opteron] Address Map
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] K8 [Athlon64/Opteron] DRAM Controller
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] K8 [Athlon64/Opteron] Miscellaneous Control
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RV350/M10 [Mobility Radeon 9600 PRO Turbo]

Alsa init just returns this:
Lakka:/ # alsactl init
alsactl: sysfs_init:48: sysfs path '/sys' is invalid
alsactl: init:1758: No soundcards found...

I would be grateful is anyone would be able to help me with this. Thanks in advance.

**Comment by lrusak** [comment]
What is the output of
```
aplay -l | paste
```

**Comment by delta360** [comment]
OpenELEC:~ # aplay -l | paste
aplay: device_list:268: no soundcards found...
http://sprunge.us/GXgV

**Comment by lrusak** [comment]
not supported, https://github.com/OpenELEC/OpenELEC.tv/blob/master/projects/Generic/linux/linux.x86_64.conf#L3047

sorry
