### ISSUE TITLE
Raspberry Pi 2 with USB device ID 148f:5370 wireless adaptor - Kodi restarts when trying to connect to wireless network

### ISSUE THREAD

**Issue by andrum99** [OpenELEC/OpenELEC.tv#3952]
I have a wireless USB adaptor with the above device ID. It has a Ralink 5370 chip. On my Raspberry Pi 2, Kodi shows me a list of wireless networks in the OpenELEC app. When I press "connect" Kodi restarts.

The adaptor works fine in Raspbian on the same Pi. I am using the official 2A power supply.

**Comment by fritsch** [comment]
Thanks for ignoring: https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md

**Comment by andrum99** [comment]
I have uploaded my log files to http://sprunge.us/WIRK.

OpenELEC version: 5.0.3
OpenELEC build: don't know where to find this. The git hash of Kodi is b5dbdb5. The result of uname -a is Linux OpenELEC 3.18.6 #1 SMP PREEMPT Tue Feb 10 19:26:14 CET 2015 armv7l GNU/Linux
OpenELEC arch: RPi2.arm

**Comment by andrum99** [comment]
It is working OK now. I have been having some odd problems with my new Raspberry Pi 2 and this is one of them. Sorry to have troubled you.
