### ISSUE TITLE
Render Capture implementation on Amlogic for Ambilight addons

### ISSUE THREAD

**Issue by Hedda** [OpenELEC/OpenELEC.tv#3953]
Please implement CRenderCapture support for Amcodec/Amplayer on Amlogic to enable Ambilight addons like Boblight as requested here

http://forum.kodi.tv/showthread.php?tid=219563

Looks like Davilla/Pivos have already done some work on this as linked here below which could maybe be backported?

https://github.com/davilla/boblight-1

https://github.com/Pivosgroup/boblight

https://github.com/Pivosgroup/TOFU-XS-Android-TOFUApp

**Comment by stefansaraev** [comment]
we do not (officialy) support (yet) any amlogic boxes. so not going to happen (right now).
btw, it was already implemented by memphiz in kodi master. and is done in our boblight addon, too. so when OE switches to kodi 15 - it is there.
