### ISSUE TITLE
Cubox-i4pro, OpenELEC 5.0.4: eth0 failing

### ISSUE THREAD

**Issue by brendan-pike** [OpenELEC/OpenELEC.tv#3957]
Wireless will worth most the time but not ethernet. If I reboot 20 times I may get it work once.
cuboxiPro4:~ # dmesg | grep eth
[    1.085496] 2188000.ethernet supply phy not found, using dummy regulator
[    1.096987] fec 2188000.ethernet eth0: registered PHC device 0
[    6.039117] fec 2188000.ethernet eth0: Freescale FEC PHY driver [Generic PHY] (mii_bus:phy_addr=2188000.ethernet:00, irq=-1)
[    6.039290] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready

If I assign an IP it will be ping-able but if I then disable wlan0, eth0 fails also. This criples the devices since wlan0 isn't fast enough for much at all.

I'm happy to help debug and/or provide direct access.

**Comment by chewitt** [comment]
I'm closing the ticket as end user support is provided via the forums.

**Comment by brendan-pike** [comment]
Could you tell me how you are certain this is not a software bug?
