### ISSUE TITLE
Unable to open initial console.

### ISSUE THREAD

**Issue by rwss** [OpenELEC/OpenELEC.tv#3958]
I've recently updated OpenElec v5.0.3 to v5.0.4 on my Raspberry Pi 2. Now i get a massage after the rainbow splash screen that says: Unable to open initial console. After that message OpenElec starts for the rest as normal up.

**Comment by chewitt** [comment]
I'm closing the ticket because end user support is provided through the forums.

**Comment by HiassofT** [comment]
Looks like commit 5928cb1 bumped the kernel version to 3.18.7, but packages/linux/patches/3.18.6 hadn't been renamed to 3.18.7.

So all the kernel specific patches, including linux-003-no_dev_console.patch, might be missing in the 5.0.4 RPi2 build.
