### ISSUE TITLE
OpenElec 5.0.4: Raspberry Pi 2: wifi connection does work

### ISSUE THREAD

**Issue by walnutoats** [OpenELEC/OpenELEC.tv#3961]
I installed the openelec 5.0.4 on Raspberry Pi 2 that has RaLink 5370 wifi adapter with dongle.
The wifi does not connect. When I try to connect the status on "Connect" tab changes to association->configuration then it goes to Idle and stays at that status.

I tested using another Rasbian OS the wifi works for that on the same motherboard. When I change it back to openelec does not work. I don't have ethernet connection to tested wired.

Please help.

Thanks,
Prasad

**Comment by fritsch** [comment]
You are fully wrong here: https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md

**Comment by walnutoats** [comment]
I am not sure how you can say I am fully wrong here. While I have tested it completely.

Are you sure the Openelec 5.0.4 build works on Ralink 5370 wifi adapter.

I had posted the same question on both Openelec Forum and IRC chat. None of them answered. Actually I saw someone having the same issue with wifi connection the same release of Opoenelec for same Ralink 5370 adapter. This was my last resort to report on the Github.

I have two: Raspberry Pi B+, and Raspberry Pi 2. Both have Openelec 5.0.4 build.
The wifi works on B+ model and it does Not work on Pi 2 model. As I explained in my issue report on Pi 2, it tries to connect but goes to idle. I have made sure the network connection credentials are all correct as I have been using that connection for years now.

For Raspsberry Pi 2 I changed the OS to use Rasbian using a separate microsd card the Wifi works on that OS. That tells me the wifi adapter and motherboard is working fine.

The only variable from above testing is Openelec on Pi 2 model that needs to be resolved. I am a software engineer I know how development and testing works along with bug reports.

Until you show me that it works somewhere this problem is not resolved. There is no terminal window in this OS to take a look at the logs.

Regards,
Prasad

**Comment by fritsch** [comment]
I said, you did not read the contributing link and you did not provide a single thing that link told you to provide.

RPi2 5.0.4 is broken, as all our kernel patches and changes for wlan and so on are not included. Downgrade.

**Comment by walnutoats** [comment]
Okay I understand. I could not access the logs files as the wifi connection did not work. And could not ssh to the Pi 2 from my laptop. Otherwise I would have given you the logs. 

BTW, do you want to me to downgrade to a version 5.0.3?

Thanks,
Prasad

**Comment by chewitt** [comment]
The only thing we want, is for you to take your Q&A spam to the forums .. where it should be.
