### ISSUE TITLE
prob avermedia a835b green eco

### ISSUE THREAD

**Issue by bibiyanki** [OpenELEC/OpenELEC.tv#3963]
hello: i m french so sorry for my poor english

i have buy avermedia green HD eco but i have see on the net, model a835 work on linux but a835b does'nt work (model eco not hd)

it's detected on debian/ubuntu lsusb and dmesg dvb, tell me it's connect and work
w-scan work but don't find any thing...
and openelec it's the same result on raspberry...

please help me friend

**Comment by chewitt** [comment]
I'm closing the ticket because end-user Q&A support is provided via the forums.
