### ISSUE TITLE
Request: Plex Server version of OpenElec (without XMBC/Kodi)

### ISSUE THREAD

**Issue by blackley** [OpenELEC/OpenELEC.tv#3964]
Hi there,

I would like to request a version of your fantastic platform with Plex Media Server in place of XBMC/Kodi.

**Comment by fritsch** [comment]
Will never happen, check a bit the history of those two projects.

**Comment by blackley** [comment]
Ok is OpenELEC available without XMBC/Kodi installed that people can create their own custom configuration

**Comment by fritsch** [comment]
Of course - all is opensource. github.com/OpenELEC.tv - you can start hacking exactly now.

**Comment by stefansaraev** [comment]
nope ;)
