### ISSUE TITLE
Update OpenELEC 5.0.5 on Pi1 overwrites existing config.txt 

### ISSUE THREAD

**Issue by bohni** [OpenELEC/OpenELEC.tv#3965]
see https://github.com/OpenELEC/OpenELEC.tv/issues/3893

I rebooted my Rasperry and the 5.0.5 Update gotisntalled. After the update all mysettings in config.txt were lost.

**Comment by lrusak** [comment]
Nothing changed that would have caused this.

See, https://github.com/OpenELEC/OpenELEC.tv/compare/5.0.4...5.0.5

**Comment by chewitt** [comment]
a) why open another ticket for the same issue???? .. b) end-user support is done via the forums

**Comment by bohni** [comment]
a) Can't locate a "Reopen Issue" Button
b) Did not need support -got it running on my own again. But I would help by giving an bug report. 

Thanks for the "nice" welcome. Will no more report any bugs/errors. Bye bye...
