### ISSUE TITLE
System freeze just after startup E-Machines ER1401

### ISSUE THREAD

**Issue by mattybrown1985** [OpenELEC/OpenELEC.tv#3968]
I haven't used this product for a couple of years, but I was recently recommended to take another look by LeeDroid.

After installing OpenELEC 5.0.5 (x86_64) and rebooting, the PC gets to the Welcome to OpenELEC screen and then starts flashing and corrupting.  Pressing keys and moving the mouse makes no difference to the display.  The PC seems to be locked up and unresponsive.

I reinstalled and rebooted a couple of times, just as a sanity check.  Still the same.

I then tried the OpenELEC 5.0.5 (i386) version.  The display issue is gone in this build.

NVIDIA GeForce 9200.

**Comment by stefansaraev** [comment]
not supported.

**Comment by stefansaraev** [comment]
btw, say "hi" to lee from me ;)

**Comment by chewitt** [comment]
Your ancient GPU is not supported by the nvidia driver in the x86_64 build. It is supported by the older driver we deliberately use in the i386 build. So everything is working as designed. Issue closed.
