### ISSUE TITLE
Using TVheadend add-on, hangs both RPI & RPI 2 with versions above 4.2.1

### ISSUE THREAD

**Issue by lcseh** [OpenELEC/OpenELEC.tv#3970]
I would appreciate some hints on what and how to diagnose when an issue like the one depicted in the title occurs.
Actually after 4.2.1 all releases I have tried have this "sudden death" issue. I use TVheadend server with approx 200 channels (IPTV (multicast and udp over http), DVB-T and DVB-S).
With 4.2.1 I only have a slow-down effect after a while, which requires the RPI to be restarted once or twice per day.

However with releases after 4.2.1 it hangs during streaming, or even just browsing the channels.
Has anyone looked into this already?

Setup is default, OE installed from scratch, and only tvh addon is configured.

**Comment by fritsch** [comment]
tvheadend is an unofficial addon and currently not supported by the OpenELEC team. We will start to support it again after a stable version with upstream support is released.
