### ISSUE TITLE
w1-gpio w1-therm as modules

### ISSUE THREAD

**Issue by andyb2000** [OpenELEC/OpenELEC.tv#3975]
I'm using Dallas 1-wire temperature sensors to provide a 'temperature sensor network' and using raspberry PI's since they are already in most rooms works great.
I've self-compiled adding in these modules to kernel options:
CONFIG_W1=m
CONFIG_W1_MASTER_GPIO=m
CONFIG_W1_SLAVE_THERM=m

Which works great, so wondering if this was something that would be considered into master/official to permit simple 1-wire sensors to be used on these devices that are potentially already deployed in many locations for end-users.

Thanks for looking into this.

**Comment by qistoph** [comment]
Thanks for adding these modules!
