### ISSUE TITLE
Delete movies + subtitles from OE (?)

### ISSUE THREAD

**Issue by Haris1977** [OpenELEC/OpenELEC.tv#3986]
I know i can delete a movie from my database (local/samba server, i assume from nfs server too even though i haven't try it) by enabling system->appearance->file lists->Allow file renaming and deletion .

But it only deletes movie file (e.g *.avi) but not subtitle file (e.g *.srt). Any future thoughts about kodi release that would also delete subtitles? This would be nice..

**Comment by Haris1977** [comment]
Why invalid?

**Comment by lrusak** [comment]
@Haris1977 not our issue, please report upstream to kodi.
