### ISSUE TITLE
DVBSky S592 no longer working with kernel 3.19

### ISSUE THREAD

**Issue by ksooo** [OpenELEC/OpenELEC.tv#3988]
OpenELEC:~ # dmesg | grep -i dvb
[   13.853208] CORE cx23885[0]: subsystem: 4254:0952, board: DVBSky S952 [card=50,autodetected]
[   15.103867] cx23885_dvb_register() allocating 1 frontend(s)
[   15.103873] cx23885[0]: cx23885 based dvb card
[   15.142874] DVB: registering new adapter (cx23885[0])
[   15.142884] cx23885 0000:03:00.0: DVB: registering adapter 0 frontend 0 (Montage M88DS3103)...
[   15.171316] DVBSky S952 port 1 MAC address: 00:17:42:54:09:52
[   15.171322] cx23885_dvb_register() allocating 1 frontend(s)
[   15.171336] cx23885[0]: cx23885 based dvb card
[   15.236197] DVB: registering new adapter (cx23885[0])
[   15.236204] cx23885 0000:03:00.0: DVB: registering adapter 1 frontend 0 (Montage M88DS3103)...
[   15.264260] DVBSky S952 port 2 MAC address: 00:17:42:54:09:53
[   25.512945] i2c i2c-2: m88ds3103: downloading firmware from file 'dvb-demod-m88ds3103.fw'
[   26.436985] cx23885 0000:03:00.0: DVB: adapter 1 frontend 0 frequency 0 out of range (950000..2150000)
[   26.454559] i2c i2c-3: m88ds3103: downloading firmware from file 'dvb-demod-m88ds3103.fw'
[   27.379062] cx23885 0000:03:00.0: DVB: adapter 0 frontend 0 frequency 0 out of range (950000..2150000)

BTW: 3.17.8 works fine

**Comment by stefansaraev** [comment]
from your log, I see its perfectly working.

**Comment by ksooo** [comment]
OpenELEC:~ # dvblast -a 0 -n 0 -f 11361750 -s 22000000 -m psk_8 -v 18
DVBlast 2.2 (git-5.0.0-52-gb98bf41-dirty)
warning: restarting
debug: using linux-dvb API version 5
debug: Frontend "Montage M88DS3103" type "QPSK (DVB-S/S2)" supports:
debug:  frequency min: 950000, max: 2150000, stepsize: 0, tolerance: 5000
debug:  symbolrate min: 1000000, max: 45000000, tolerance: 0
debug:  capabilities:
debug:   INVERSION_AUTO
debug:   FEC_1_2
debug:   FEC_2_3
debug:   FEC_3_4
debug:   FEC_4_5
debug:   FEC_5_6
debug:   FEC_6_7
debug:   FEC_7_8
debug:   FEC_8_9
debug:   FEC_AUTO
debug:   QPSK
debug:   2G_MODULATION
debug:   FE_CAN_RECOVER
debug: frequency 11361750 is in Ku-band (lower)
debug: configuring LNB to v=18 p=0 satnum=0
debug: tuning QPSK frontend to f=11361750 srate=22000000 inversion=-1 fec=999 rolloff=35 modulation=psk_8 pilot=-1
warning: failed opening CAM device /dev/dvb/adapter0/ca0 (No such file or directory)
debug: setting filter on PID 0
debug: setting filter on PID 16
debug: setting filter on PID 17
debug: setting filter on PID 18
debug: setting filter on PID 19
debug: setting filter on PID 20
error: no config file
debug: new SDT actual tsid=1011 version=1 onid=1
debug:   * service sid=11110 eit_schedule eit_pf running=4
debug:     - desc 48 service type=0x19 provider="ZDFvision" service="ZDF HD"
debug:   * service sid=11130 eit_schedule eit_pf running=4
debug:     - desc 48 service type=0x19 provider="ZDFvision" service="zdf_neo HD"
debug:   * service sid=11140 eit_schedule eit_pf running=4
debug:     - desc 48 service type=0x19 provider="ZDFvision" service="zdf.kultur HD"
debug: end SDT
debug: new PAT tsid=1011 version=0
debug:   * NIT pid=16
debug:   * program number=11110 pid=6100
debug:   * program number=11130 pid=6300
debug:   * program number=11140 pid=6400
debug: end PAT
debug: frontend has acquired signal
debug: frontend has acquired carrier
debug: frontend has acquired stable FEC
debug: frontend has acquired sync
info: frontend has acquired lock
frontend has acquired lock
debug: - Bit error rate: 0
debug: - Signal strength: 65535
debug: - SNR: 168

I think you are right. Closing the issue.

**Comment by ksooo** [comment]
@perexg Thought it was linux, but seems to be a serious tvheadend problem with linux 3.19?!
