### ISSUE TITLE
OpenELEC add-on naming mis-match ("missing files")

### ISSUE THREAD

**Issue by twi252** [OpenELEC/OpenELEC.tv#3990]
Hello,

Running OpenELEC v5.0.5 on an Intel NUC.

I've been working with the author of the Bello add-on to troubleshoot a problem installing it from GitHub (it's not yet published on the official repo's, not for Helix, yet.)

Downloading and installing from the author's GitHub (https://github.com/Nessus85100/Bello/) and selecting "Install from ZIP" in Kodi shows the Skin failed to install due to "missing files".

The following is from the Kodi debug log:

```
10:24:04 T:140491238729472   DEBUG: FileManager: copy zip://%2fstorage%2fdownloads%2fBello-master.zip/Bello-master/shortcuts/overrides.xml -> special://home/addons/Bello-master/shortcuts/overrides.xml
10:24:04 T:140491238729472   DEBUG: FileManager: copy zip://%2fstorage%2fdownloads%2fBello-master.zip/Bello-master/shortcuts/pictures.DATA.xml -> special://home/addons/Bello-master/shortcuts/pictures.DATA.xml
10:24:04 T:140491238729472   DEBUG: FileManager: copy zip://%2fstorage%2fdownloads%2fBello-master.zip/Bello-master/shortcuts/settings.DATA.xml -> special://home/addons/Bello-master/shortcuts/settings.DATA.xml
10:24:04 T:140491238729472   DEBUG: FileManager: copy zip://%2fstorage%2fdownloads%2fBello-master.zip/Bello-master/shortcuts/tvshows.DATA.xml -> special://home/addons/Bello-master/shortcuts/tvshows.DATA.xml
10:24:04 T:140491238729472   DEBUG: FileManager: copy zip://%2fstorage%2fdownloads%2fBello-master.zip/Bello-master/shortcuts/videos.DATA.xml -> special://home/addons/Bello-master/shortcuts/videos.DATA.xml
10:24:04 T:140491238729472   DEBUG: FileManager: create folder special://home/addons/Bello-master/sounds
10:24:04 T:140491238729472   DEBUG: FileManager: copy zip://%2fstorage%2fdownloads%2fBello-master.zip/Bello-master/sounds/sounds.xml -> special://home/addons/Bello-master/sounds/sounds.xml
10:24:04 T:140491238729472    INFO: ADDON: cpluff: 'Could not read plug-in directory /usr/lib/kodi/addons: No such file or directory'
```

After a little troubleshooting i tracked it down to being an OpenELEC issue (people running OpenELEC have reported this, and non-OpenELEC users dont seem affected).

It seems when the directory-name in ~/.kodi/addons doesnt match the 'addon id' in addons.xml it throws the above error.

```
<addon id="skin.bello" version="3.0.5" name="Bello" provider-name="Nessus">
```

Renaming the unzipped GitHub master directory from Bello-master to skin.bello allowed it to install without errors.

Thanks.

**Comment by stefansaraev** [comment]
> It seems when the directory-name in ~/.kodi/addons doesnt match the 'addon id' in addons.xml it throws the above error.

this is by design, and how it should be. and is NOT openelec specific

**Comment by twi252** [comment]
Hey Stefan,

Understood.. Might just need a more descriptive error then (by the Kodi folks).

Sometimes, especially when a new major release of Kodi comes out, and the add-on writers haven't yet officially released a new version of their add-on, people try updating from the author's GitHub and run into this issue (as GitHub checkouts usually have the directory structure <addon>-<branch>), as i have.

The error it throws (both in the log and gui) is confusing (missing files equating to a discrepancy in the add-on directory naming), so i might open a ticket with the Kodi folks to make that a bit more transparent.

Thanks for the correction.

**Comment by stefansaraev** [comment]
well dont know.
the point is, people can't throw random stuff in addons/ and expect all to work. addon dirs must have unique names. the only way to guarantee that a name is unique, is to match addon id, to me - it's obvious :)
