### ISSUE TITLE
[Build failure] RPi patch file for linux conflicts

### ISSUE THREAD

**Issue by InuSasha** [OpenELEC/OpenELEC.tv#3991]
APPLY PATCH (project)   /home/jenkins/OpenElec/master/projects/RPi/patches/linux/linux-01-RPi_support.patch
[...]
patching file kernel/time/ntp.c
Hunk #1 FAILED at 634.
1 out of 1 hunk FAILED -- saving rejects to file kernel/time/ntp.c.rej

EDIT: this part was applied upsteam, so can easy drop.
(same RPi2)

Sascha

**Comment by sraue** [comment]
fixed in https://github.com/OpenELEC/OpenELEC.tv/commit/536b36dce7d02acd0cc5306035d6ffcacd35ec3f

**Comment by InuSasha** [comment]
Thanks,
where you get this patch collection?
So i can report there, next time.
