### ISSUE TITLE
OE Generic x64 5.0.5 freeze + black screen on beginning of playback (during display refresh switch)

### ISSUE THREAD

**Issue by tergo** [OpenELEC/OpenELEC.tv#4005]
When I play a video, sometimes it freezes immediately during the display refresh rate change. Black screen, no audio (sometimes audio plays for a few seconds before freezing). The issue is frequent and I can reproduce it just by stopping/starting videos for a few minutes. 

dmesg | pastebinit output
http://sprunge.us/Ecec

Log:
https://www.dropbox.com/s/bbn3hfjb3dl0mwc/log-2015-03-13-17.52.58.zip?dl=0
(it happens around 17:51 when playing American.Hustle)

Software:
OE Generic 5.0.5 x64

Hardware:
Zotac Ion ITX-B-E (Intel Atom 230 + Nvidia Ion1) 

It is a fresh, clean install with no extra addons. The only thing I did after the clean install was to add my video source and configure my playback/output settings. 

I checked all stable OE Generic x64 5.0.x releases and this issue also occurs with all of them. Previously I used OE Generic x64 4.2.1 which did not have the issue.

**Comment by tergo** [comment]
I reproduced it again with dmesg | pastebinit output
http://sprunge.us/Ecec

https://www.dropbox.com/s/bbn3hfjb3dl0mwc/log-2015-03-13-17.52.58.zip?dl=0
(this time it happens around 17:51 when playing American.Hustle)
Audio played for a few seconds before it froze

**Comment by tergo** [comment]
Update - still occurs with 5.0.6 x64

http://sprunge.us/bNYc

https://www.dropbox.com/s/7lf96u670hynk1a/log-2015-03-14-15.58.12.zip?dl=0
(freeze occurs at 15:55)

**Comment by tergo** [comment]
Problem seems related to "adjust display refresh rate to match video" as I cannot reproduce it with this setting disabled

**Comment by soder82** [comment]
I got this on my generic x64 to. Also during refresh rate adjustment.

**Comment by be11aml** [comment]
I also have this issue with OE 5.0.6 (generic 32 bit) using emachines ER1402.

Are there any development builds with a fix included that I can test?

**Comment by fritsch** [comment]
No and nobody is working on it. With good luck next nvidia driver can make it work again.

**Comment by tergo** [comment]
Update - still occurs with OE Generic x64 5.0.7

**Comment by be11aml** [comment]
I have just wiped my system and started from a clean install of 4.2.1. 

All is working perfectly again. 

At some point I will get a Raspberry Pi 2 and give OE 5.x another try. 

It seems that older nvidia hardware has reached the end of its life, had to move to 32 bit at version 4 due to requiring the legacy drivers. 

So much for supporting older hardware

**Comment by tergo** [comment]
I cannot replicate this on OpenELEC-Nvidia_Legacy.x86_64-5.95.3  

Problem seems related to 5.x drivers so the solution is to stay on 4.2.1 or move to new Nvidia Legacy build. 

Closing.
