### ISSUE TITLE
Unable to build menu 

### ISSUE THREAD

**Issue by thegreatdan** [OpenELEC/OpenELEC.tv#4011]
I need your support. My OpenElec @ rPi2 keeps showing up this issue when I use the Aeon Skin:
http://xbmclogs.com/pgo5xlowi

When browsing in main menu a popup pops up and tells "Failed to write menu".

I don't have a clear view what might cause this behavior, could you help?

**Comment by stefansaraev** [comment]
user support is done via forums or irc.
