### ISSUE TITLE
libGL.la defective on build machine

### ISSUE THREAD

**Issue by chemstar** [OpenELEC/OpenELEC.tv#4012]
when compiling against libGL an error appear because of non-valid signs in libGL.la from SYSROOT/usr/lib folder.
there are equal ('=') symbols in the dependency_libs part of .la-file before the path to libs was given.
maybe it's only an issue  on my machine but it appear already second time after complete clean-up.

**Comment by stefansaraev** [comment]
gentoo ?

**Comment by chemstar** [comment]
its on ubuntu

**Comment by stefansaraev** [comment]
uninstall ALL -dev packages. keep only libc6-dev libncurses5-dev libstdc++6-4.7-dev libtinfo-dev linux-libc-dev and retry

if it doesnt help @sraue s your best friend here.

**Comment by mrdominuzq** [comment]
a word of advise. Do your compiling in a virtual machine with only whats needed. Takes a bit longer but you dont mess with Your system :)

**Comment by mrdominuzq** [comment]
@chemstar any news on this ? :)

**Comment by chemstar** [comment]
can be closed, didn't have this problem for long time
