### ISSUE TITLE
Network driver for TL-WN727N V4 request

### ISSUE THREAD

**Issue by muromdx** [OpenELEC/OpenELEC.tv#4013]
Request to add the driver for the TL-WN727N V4 wireless network adapter:
http://www.tp-link.com/en/support/download/?model=TL-WN727N&version=V4
The chip is MT7601U and it works in Raspbian on RPi

**Comment by lrusak** [comment]
There is no driver on that page for linux.

Most likely the driver is
http://www.mediatek.com/en/downloads/mt7601u-usb/

**Comment by stefansaraev** [comment]
driver requests for wifi dogles are absolutely no-go.

vendors should send their drivers mainline. period.

**Comment by mrdominuzq** [comment]
there's already a PR for the driver
https://github.com/OpenELEC/OpenELEC.tv/pull/3494

but i go with @stefansaraev just to many drivers out there :)

**Comment by muromdx** [comment]
Thank you all. I will follow the instructions in #3494.
