### ISSUE TITLE
Addon features unresponsive using MySQL and multiple profiles

### ISSUE THREAD

**Issue by nem2k** [OpenELEC/OpenELEC.tv#4016]
I posted the issue on the kodi forum here:
http://forum.kodi.tv/showthread.php?tid=221541

Basically, I'm using MySQL to sync multiple profiles to different databases. However, on my pi2, once mysql sync is enabled and a 2nd profile gets created, none of the addon features work on either profile (e.g. check for updates is unresponsive, addon list is empty etc)

To recreate this:
1. Update openelec to latest (kodi 14.2 RC1) on the pi2
2. Create an advancedsettings.xml file for the master profile and have it sync to a mysql database on another network machine. At this point, the addon menu items should work fine.
3. Create a second profile (without its own advancedsettings.xml). Use fresh settings (dont copy from default). Go to addons > check for update doesnt work, get addons list is empty
4. Adding an advancedsettings.xml for the new profile (placing it in userdata/profiles/<user>), pointing at a different db, does not solve the problem either

This is only a problem on the pi2. Everything is fine on 2 windows machines (Kodi 14.2 beta 1) that I have tested this on.

**Comment by lrusak** [comment]
We simply consume the Kodi application. Please report Kodi issues upstream.
