### ISSUE TITLE
Support for bcm43143 WiFi dongle in xmbc raspberry pi

### ISSUE THREAD

**Issue by dtkwan** [OpenELEC/OpenELEC.tv#4018]
It appears the firmware for the Broadcom bcm43143 WiFi dongle is not installed in /lib/firmware/brcm.  

$ git clone --depth 1 git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git

The bcm43143 firmware is available in .../linux-firmware/brcm
  brcmfmac43143.bin
  brcmfmac43143-sdio.bin

Reference: http://www.raspberrypi.org/forums/viewtopic.php?f=63&t=88688&p=623433&hilit=43143#p623433

**Comment by stefansaraev** [comment]
why is this not a PR ?

**Comment by dtkwan** [comment]
Hi Stefan,
Sorry.  What is a PR?  
I am not familiar which the OpenSource development process so I don't all the terminologies.
Basically, I did some debugging and found that the host driver for the device was loaded properly but the firmware for the device was missing.  
Thanks, --David 
 


     On Wednesday, March 18, 2015 2:40 AM, Stefan Saraev <notifications@github.com> wrote:
   

 why is this not a PR ?—

**Comment by stefansaraev** [comment]
pull request. here: https://github.com/OpenELEC/wlan-firmware

however. ping @sraue 
//cc @chewitt as you are familiar with bcms

**Comment by dtkwan** [comment]
Guys,
Let me know how I can help.  Like I said, I am not familiar with this opensource development process but I have a bcm43143 that I can help test.
Thanks, --David


     On Wednesday, March 18, 2015 1:10 PM, Stefan Saraev <notifications@github.com> wrote:
   

 pull request. here: https://github.com/OpenELEC/wlan-firmwarehowever. ping @sraue 
//cc @chewitt as you are familiar with bcms —

**Comment by chewitt** [comment]
no objections to adding the firmware .. submit a PR and we will merge
