### ISSUE TITLE
OpenELEC Wiki Has Incorrect Directions for Tvheadend Backend

### ISSUE THREAD

**Issue by FastEddieAustin** [OpenELEC/OpenELEC.tv#4025]
The wiki for OpenELEC does not allow anyone to correct information that is frustrating scores of users.  Someone needs to update the wiki for changes being made by the project or reconfigure the wiki so others can correct.  On the wiki page below it states "OpenELEC currently ships with Tvheadend 3.4 backend software".  This is not correct and needs to be updated.  I lost HOURS of my life trying to make this all work based on the wiki saying the software was there...

http://wiki.openelec.tv/index.php/Configuring_Tvheadend states that tvheadbackend

**Comment by stefansaraev** [comment]
you can ask @sraue in irc for wiki account.
