### ISSUE TITLE
SiS163 Wireless Chipset

### ISSUE THREAD

**Issue by imgreenman** [OpenELEC/OpenELEC.tv#4026]
Hi,

would it be possible to have this SiS163 SiS163U driver added to openelec on raspberry pi?
It would be grat but unsure if possible. If there is a way to manually add it into the filesystem that would do the trick. 

Thank you

**Comment by chewitt** [comment]
No, because there is no native Linux driver. You can use NDISWrapper on a conventional distro to load the Windows driver but are not a conventional distro and have no desire to implement that approach.
