### ISSUE TITLE
No sound upon resume - Need to run commands after CEC commands are sent

### ISSUE THREAD

**Issue by josh4trunks** [OpenELEC/OpenELEC.tv#4038]
Hello, thank you for such a clean and fine-tuned product!

**Situation**
* After resuming from suspend, my OpenELEC machine wakesup my Receiver and TV using a USB CEC adapter.

**Problem**
* Occasionally, sound is no longer working upon resume. I believe this is because my receiver took a little too long to wakeup, but I'm not 100% sure if this is the cause.
* I can always fix this issue by running the below commands
    *  DISPLAY=:0 /usr/lib/kodi/kodi-xrandr --output HDMI1 --off
    *  DISPLAY=:0 /usr/lib/kodi/kodi-xrandr --output HDMI1 --auto

**Solutions I have tried**
* Set a hardcoded EDID for Intel. I confirmed my machine is using the edid.bin from dmesg but this doesn't make a difference. I still occasionally lose sounds after a resume.

* Resume Script. I am close to getting this working but have run into some issues.
    * If I run the 2 commands from above I get a blue screen upon resume because neither my Receiver or TV are available to connect to immediately upon resume.
    * If I add a "wait 10" to this script, resume takes an extra 10 seconds and I still get a blue screen. I believe OpenELEC runs the script before sending the CEC wakeup commands so my Receiver and TV are not available regardless of how long I wait.

**Comment by lrusak** [comment]
try
```
#!/bin/sh
case "$1" in
  pre)
    ;;
  post)
    ( sleep 2;
    DISPLAY=:0 /usr/lib/kodi/kodi-xrandr --output HDMI1 --off;
    DISPLAY=:0 /usr/lib/kodi/kodi-xrandr --output HDMI1 --auto ) &
    ;;
esac
```

**Comment by josh4trunks** [comment]
It worked! Thanks!
I actually tried that yesterday with 10/15 seconds, but for some reason waiting 2 seconds is the sweet spot.

I know it worked because sound was gone, I suspended my system, and upon wakeup sound was back! =]
