### ISSUE TITLE
sample xorg.conf for enabling 1st Gen AppleTV composite output fails

### ISSUE THREAD

**Issue by Open-Elec-RU** [OpenELEC/OpenELEC.tv#4040]
1st Gen AppleTV running latest OpenELEC (no CrystalHD)
Copied and installed teh sample xorg.conf file from http://wiki.openelec.tv/index.php/AppleTV#tab=Composite__26_Component_Video

Connected via the Green component output to the Yellow RCA input on TV
Trying to boot, get a BLACK AND WHITE  openelec logo with the following text:

[***] A start job is running for Xorg Server (xx s/1 min 33s)

and then this appears:

[FAILED] Failed to start Xorg Server.
See 'systemctl status xorg.service' for details
[DEPEND] Dependency failed for Fluxbox Window Manager.
[OK] Reached target graphical interface.
   Starting XBMC user autostart script...
[OK] Started XBMC user autostart script.
Starting XBMC Media Center...
[OK] Started XBMC Media Center.
[OK] Reached target XBMC Mediacenter interface.

Then it's stuck for a couple of minutes and then the display goes blank

Changing the video system from NTSC-M to PAL-M or many others did not help.

The TV is a modern plasma - I was using it to test the setup before installing it in my car using RCA inputs.

**Comment by stefansaraev** [comment]
atv is not supported anymore
