### ISSUE TITLE
Randomly freezes during playback

### ISSUE THREAD

**Issue by WedgeSparda** [OpenELEC/OpenELEC.tv#4041]
Hi, i'm using OpenELEC 5.0.6 and since a few days ago i'm suffering random freezes during playback. 
Sometimes it tooks a few minutes and sometimes can play a complete TV show without problems. Kodi doesn't respond to my TV Remote when this happens, so I can't stop and resume playback.

A few minutes ago happened two times in a short time period. I looked in the KODI.log and found this line, but I don't know if it's the cause.

    08:18:10 T:1800401984 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer

After this line, the log file has a bunch of NUL (that's what I see with Sublime Text).

Is this a local network issue or something else? I have my media files in a Synology NAS connected with two ethernet cables and through a hub and my router.

This is my log since my playback started and the bunch of NUL started

![Log](https://dl.dropboxusercontent.com/u/320023/log.png)

Thanks

**Comment by fritsch** [comment]
Is it really so hard to read: https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md and post relevant logfiles?

**Comment by WedgeSparda** [comment]
Sorry, i didn't see those instructions.
Here are my logs
[Log](https://dl.dropboxusercontent.com/u/320023/log-2015-03-25-08.25.30.zip)

**Comment by fritsch** [comment]
That's a raspberry PI - nice that you did not mention that at all, while you jumped into an x86 ALSA bugreport ...

**Comment by WedgeSparda** [comment]
Ok, whatever

**Comment by fritsch** [comment]
@popcornmix Do you have an idea what causes this - I cannot see anything in the other logs.

**Comment by WedgeSparda** [comment]
I found out it is a local network problem, not an OpenELEC issue.

Thanks for your time.
