### ISSUE TITLE
Feature Request: do not start backup if storage space is insufficient

### ISSUE THREAD

**Issue by endlessterror** [OpenELEC/OpenELEC.tv#4043]
I do not know if it is already implemented, it could be a serious issue especially on small installations like OE on SD/CF cards. Please consider adding some sort of disk space check (something like a du -sk on directories to be backed up), *before* starting the backup. If there is no space available, inform the user of the situation. Possibly advise removal of old backups.

**Comment by chewitt** [comment]
closing as a fix has been merged in https://github.com/OpenELEC/service.openelec.settings/commit/9ec83fa48b89ad9493f251e31975b909cae26d68
