### ISSUE TITLE
Boblight stops working during playing a movie or episode

### ISSUE THREAD

**Issue by soder82** [OpenELEC/OpenELEC.tv#4053]
Since a couple of week, during the latest 2-3 updates of OE, I've noticed my Boblight sometimes doesn't work.

It stops working during a movies, without me doing anything, and sometimes I think, also during idle.

It works for at least one hour sometimes, and also with pauses, and pauses and screen saver going in, and then on play it works. But then it just stops...

Log files can be added..

**Comment by soder82** [comment]
I just this package (the hardward). http://lightpack.tv/
OE x64

**Comment by soder82** [comment]
Can I upload a log somewhere in here?

**Comment by chewitt** [comment]
closing due to length of time with no update

**Comment by soder82** [comment]
Update in what way? Still stops...

**Comment by chewitt** [comment]
This is a development bug tracker and your issue report is neither related to ongoing development nor contains anything factual that a developer could investigate the issue from. General user troubleshooting and Q&A help is provided via the forums.
