### ISSUE TITLE
small and large Freeze live tv DVB-S

### ISSUE THREAD

**Issue by tomtomclub** [OpenELEC/OpenELEC.tv#4054]
small and large freeze live tv AS rock J1900 - skystar2 HD
when I'm in the movies put C7 on then the picture will freeze on C1 it works well
if I switch to Gotham and put C7 on it works well kernel 3.16 
http://postimg.org/gallery/i7td525s/29cff64e/

**Comment by fritsch** [comment]
Switch your powersupply! and come back with _real_ logfiles. I think I told that now four times ... I have nothing seen for now.

Also I provided a 3.16 build back at that time with kodi. What results did you get?

**Comment by tomtomclub** [comment]
http://pastebin.com/h80yQn5x

**Comment by fritsch** [comment]
I see you bypassing the VAAPI Render and your hw not catching up with doing
1080i50 + deinterlace properly. In the middle I see some broken data coming
in - more I don't see.

Is your TV card connected to the same host?

2015-03-29 14:58 GMT+02:00 tomtomclub <notifications@github.com>:

> http://pastebin.com/h80yQn5x
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4054#issuecomment-87408672>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by tomtomclub** [comment]
Yes tv card connected to the same host on the motherboard

**Comment by fritsch** [comment]
i think it interfers with the C7 state. Basically we already receive broken data in that log ... not much we can do on kodi side afterwards.

**Comment by chewitt** [comment]
closing old tickets with no update.. should the issue still exist on a current release please start a forum thread, thanks.
