### ISSUE TITLE
kodi crashes when enabling live tv with xvdr plugin after update to 5.0.7

### ISSUE THREAD

**Issue by andreasgebel** [OpenELEC/OpenELEC.tv#4055]
After update from 5.0.6 to 5.0.7 kodi hangs in splash screen when "live tv" and the "xvdr plugin" are enabled.
there does not appear anything in kodi.log
System is Raspberry Pi2

**Comment by MilhouseVH** [comment]
Why not post a link to the log anyway, just in case you missed something?

**Comment by stefansaraev** [comment]
@MilhouseVH no need. it's obvious whats wrong... unbelievable.

**Comment by hornisse** [comment]
I have the same issue on generic 64bit builds.
Is there a solution?

**Comment by stefansaraev** [comment]
yes there is. downgrade. +1's dont help.
