### ISSUE TITLE
OE 5 doesnt recognize external 4TB HDD

### ISSUE THREAD

**Issue by Roby77ita** [OpenELEC/OpenELEC.tv#4057]
On my chromebox with 5.06 and now 5.0.7 can't be recognized external usb 3 hard disk 4tb ntfs (only one partion)

Here are my log

OpenELEC (official) Version: 5.0.6
OpenELEC:~ # journalctl -b 0 --no-pager | paste
sprunge.us/FPjF
OpenELEC:~ # parted -l | paste
sprunge.us/DfKZ

And here a log after connecting/disconnecting
sprunge.us/CXXb

thank you

**Comment by stefansaraev** [comment]
Mar 18 22:27:52 OpenELEC udevil[756]: The NTFS partition is in an unsafe state. Please resume and shutdown
Mar 18 22:27:52 OpenELEC udevil[756]: Windows fully (no hibernation or fast restarting), or mount the volume
Mar 18 22:27:52 OpenELEC udevil[756]: read-only with the 'ro' mount option.

**Comment by Roby77ita** [comment]
Sorry i'm a newbie so how can i solve ? i can't mount cause i don't see it also in system hardware
in windows it works perfectly

thank you!

**Comment by fritsch** [comment]
Boot windows and safely eject the drive. Don't just pull the cable out.

2015-03-30 17:30 GMT+02:00 Roby77ita <notifications@github.com>:

> Sorry i'm a newbie so how can i solve ? i can't mount cause i don't see it
> also in system hardware
> in windows it works perfectly
>
> thank you!
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4057#issuecomment-87723394>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by Roby77ita** [comment]
Solved, thank for your support!
