### ISSUE TITLE
Pi B2 not responding to CEC

### ISSUE THREAD

**Issue by maaraneasi** [OpenELEC/OpenELEC.tv#4058]
I have replaced my Raspberry B+ with B2 and noticed that even the cec module is configured and started after the system startup, the raspberry b2 is not responding to the commands, like the older b+ did.

**Comment by fritsch** [comment]
Thanks for not reading: https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md

**Comment by maaraneasi** [comment]
Which of the logfiles contains informations benefitial for resolving this issue?

I am obviously not the only person having such issues so closing the issue is not the best way getting this sorted out...

**Comment by fritsch** [comment]
> It is also importent to provide logs for debugging. A zip file can be found in the logfiles samba share, this will contain all the logs needed.

**Comment by maaraneasi** [comment]
In that case I am sorry - I thought that this issue was closed and will be not opened again so I raised #4061 containing the CEC debug log etc.
