### ISSUE TITLE
Video stutter with RPi2 5.0.7

### ISSUE THREAD

**Issue by rasberryrabbit** [OpenELEC/OpenELEC.tv#4059]
I had update 5.0.7 on my rasberrypi2, I got stutter video playing.
It happen everytime right after GUI menu access, it keep stuttering video playing for a while(few minutes or more). After downgrading 5.0.6, it's ok.

Step to reproduce:
1. Playing video (ex. Youtube addon)
2. Close UI and press UI Home Menu Button.
3. Navigate UI Menus while playing, Video start stuttering but sound is ok.
4. Back to video playing, but video still stutters a while.

My RPi2 setup is
1. 1 USB wifi 802.11n (realtek chipset)
2. 1 Mouse
3. USB Soundcard.

**Comment by HiassofT** [comment]
Same here when using dvdplayer, both on RPi and RPi2.

Sample video: http://www.horus.com/~hias/tmp/openelec-testvideos/stutter.mp4
Debug log (fresh 5.0.8 RPi install): http://sprunge.us/agiH

The video starts fine but after 5 seconds heavy stuttering starts.

Rolling back to the 5.0.6 firmware (f1b6b1c, Mar 10) seems to fix stuttering. More precisely, firmware 3b750d3 (Mar 16) seems to be OK, stuttering starts with firmware 151e6e5 (Mar 22).

The last few Milhouse builds up to 0331 also stuttered, but build 0401 seems to be OK.

A quick test indicates that this newclock4 commit also fixes stuttering with 5.0.7/5.0.8
https://github.com/popcornmix/xbmc/commit/b2f2b5088f329f8b391606d5570ffff938f7fdb3

**Comment by fritsch** [comment]
Thanks! for this detailed analysis and the solution. @sraue ping.

**Comment by popcornmix** [comment]
Don't grab https://github.com/popcornmix/xbmc/commit/b2f2b5088f329f8b391606d5570ffff938f7fdb3 yet - it needs more testing (there are a couple of regressions reported for latest Milhouse build).

For low bitrate videos you can push a lot of frames into the HW codec, and dvdplayer doesn't handle that well (i.e. when you get a few seconds of video buffered in decoder dvdplayer gets confused and thinks its running behind and requests frames to be dropped).

I guess this firmware change "firmware: video_decode: increase the number of userdatas" has made the issue more apparent (the number of headers allowed in decoder was increased from 32 to 64), as it seemed a shame to waste memory in decoder due to a lack of available headers.

**Comment by rasberryrabbit** [comment]
I got also video stuttering in 5.0.8.

"WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer" is logged when start to stuttering.

05:06:21 T:1657795648  NOTICE: Opening stream: 0 source: 1024
05:07:09 T:1802978368  NOTICE: Thread BackgroundLoader start, auto delete: false
05:07:09 T:1594881088 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
05:07:29 T:1969283072 WARNING: Previous line repeats 1 times.
05:07:29 T:1969283072   ERROR: Control 120 in window 10153 has been asked to focus, but it can't
05:07:29 T:1802978368  NOTICE: Thread JobWorker start, auto delete: true
05:07:29 T:1692390464  NOTICE: Thread LanguageInvoker start, auto delete: false
05:07:30 T:1692390464  NOTICE: -->Python Interpreter Initialized<--
05:07:46 T:1692390464  NOTICE: Thread LanguageInvoker start, auto delete: false
05:07:46 T:1692390464  NOTICE: -->Python Interpreter Initialized<--
05:07:47 T:1657795648  NOTICE: Closing stream player 3
05:07:47 T:1657795648  NOTICE: Opening stream: 0 source: 1024
05:08:08 T:1594881088 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
05:08:52 T:1802978368 WARNING: Previous line repeats 13 times.
05:08:52 T:1802978368  NOTICE: Thread JobWorker start, auto delete: true
06:15:50 T:1865225280  NOTICE: Thread RSSReader start, auto delete: false
06:16:08 T:1802978368  NOTICE: Thread JobWorker start, auto delete: true
06:16:16 T:1594881088 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
06:16:39 T:1692390464 WARNING: Previous line repeats 2 times.
06:16:39 T:1692390464  NOTICE: Thread LanguageInvoker start, auto delete: false
06:16:39 T:1692390464  NOTICE: -->Python Interpreter Initialized<--
06:16:40 T:1594881088 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
06:16:40 T:1969283072 WARNING: Previous line repeats 4 times.
06:16:40 T:1969283072   ERROR: Control 1000 in window 13001 has been asked to focus, but it can't
06:16:40 T:1594881088 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
06:17:11 T:1535091776 WARNING: Previous line repeats 4 times.
06:17:11 T:1535091776  NOTICE: Thread JobWorker start, auto delete: true
06:17:11 T:1594881088 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
06:18:17 T:1657795648 WARNING: Previous line repeats 1 times.
06:18:17 T:1657795648  NOTICE: CDVDPlayer::OnExit()
06:18:17 T:1657795648  NOTICE: DVDPlayer: eof, waiting for queues to empty
06:18:17 T:1657795648  NOTICE: Closing stream player 1
06:18:17 T:1657795648  NOTICE: CDVDMessageQueue(audio)::WaitUntilEmpty

**Comment by popcornmix** [comment]
Could you test latest Milhouse nightly?
http://forum.kodi.tv/showthread.php?tid=211501

**Comment by rasberryrabbit** [comment]
Thank you for link.
nightly 0402-gc899f74 works fine :)

**Comment by HiassofT** [comment]
Thanks, popcornmix!
The new firmware ab9e773 fixes stuttering on OpenELEC 5.0.8
