### ISSUE TITLE
HDMI CEC broke after 5.0.7 update

### ISSUE THREAD

**Issue by remav** [OpenELEC/OpenELEC.tv#4060]
Hi, I updated yesterday my RPi B+ to 5.0.7 and I have an issue with HDMI CEC connection. If I activate from TV the CEC (I have an LG tv) after Kodi is starting at first push on TV remote control for navigate in Kodi menu I lost the video signal on tv. RPi seem to still working, I see activity on wireless adapter and the green LED also have activity. Now I deactivate the CEC control from tv and I use an wireless keyboard to control the Kodi. Before update all was working fine.
Anyone had this problem?

**Comment by fritsch** [comment]
Use has not read: https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md
