### ISSUE TITLE
CEC remote not working on RPi2

### ISSUE THREAD

**Issue by maaraneasi** [OpenELEC/OpenELEC.tv#4061]
Openelec 5.0.7 for Raspberry B 2 is not responding to the CEC control from a Sony Bravia tv.
The B+ version I have been using previously was working as expected on builds 5.0.x (can't test anymore).
When my tv is searching for connected devices, RPi is not getting found.
Connecting to a different HDMI port makes no difference.

CEC debug log (can't use sprunge on my device due to the network connection):
http://pastebin.com/2LT3pXEB

If you need me to provide any additional logs, please let me know.
Thanks

**Comment by maaraneasi** [comment]
Zipped logs:
https://drive.google.com/file/d/0B5-DvM2o5dM9bUdtQm1iMTQySkE/view?usp=sharing

**Comment by ronakg** [comment]
I'm having the same issue. When OE boots up, I get a messages about CEC configuration and that the TV was connected. But my RPi2 doesn't respond to any remote commands.

When I open Settings->System->Input Devices->Peripherals, there are no devices there.

**Comment by inspector71** [comment]
FWIW: I'm using an Rpi2 with OE 5.0.8 on a Sony Bravia and CEC is working fine.

I do have a custom remote.xml file in place. The remote/CEC wouldn't work without it.

Details:

(TV) Home -> Settings -> Setup - Product Information:

```
1. KDL-32W5500
2. 1382512
3. 1.428AA
```
(Kodi) Home -> Settings -> System -> Input Devices -> Peripherals:

```
CEC Adapter
Product ID: 1001   Vendor: 2708
Class: cec
```

**Comment by DaveTBlake** [comment]
I am also experiencing this problem on my new system. Openelec 5.95.2 for Raspberry Pi 2 is not responding to the CEC control from a Sony Bravia tv (KD-55W895).

When my tv is searching for connected devices, RPi is not getting found.
Connecting to a different HDMI port makes no difference. 
New CEC enabled cable makes no difference.
When OE boots up, I get a messages about CEC configuration and that the TV was connected - the RPi can see the TV but the TV does not detect the presence of the RPi. 
The TV does detect the presence of other possible CEC devices e,g when a Chromcast device is plugged in.

Will submit logs if someone will tell me how.

**Comment by chewitt** [comment]
closing old tickets with no update.. should the issue still exist on a current release please start a forum thread, thanks.
