### ISSUE TITLE
Video Playlist crashes after a few hours (OpenElec + raspberry B+)

### ISSUE THREAD

**Issue by X86Blade** [OpenELEC/OpenELEC.tv#4062]
I use the raspberry pi B+ wirh OpenElec to run a infoscreen in a Store, but after a few hours, the video player blocking and i hafe to reboot OpenElec. 
which may be the reason for this?

**Comment by X86Blade** [comment]
stefansaraev Invalid?

**Comment by popcornmix** [comment]
Did you read https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md ?

**Comment by chewitt** [comment]
closing old tickets with no update.. should the issue still exist on a current release please start a forum thread, thanks.
