### ISSUE TITLE
Raspberry Openelec Joystick Support

### ISSUE THREAD

**Issue by seppeltheflash** [OpenELEC/OpenELEC.tv#4066]
Hello,

Openelec and Raspberry is my dream team. Openelec recognize and pair the original PLAYSTATION(R)3 Controller. Unfortunately there is no input in the xmb menu support. Please ad these support in the next release. U make the retrogamers, like me, very very happy.

Seppeltheflash

**Comment by stefansaraev** [comment]
this has been discussed hundreds of times. joysticks are not supported on rpi. nothing we can do.
