### ISSUE TITLE
Bluetooth audio support

### ISSUE THREAD

**Issue by bszafko** [OpenELEC/OpenELEC.tv#4070]
It would be great to have a full bt audio support in openelec, that means you could use for example Bluetooth headphones,  speakers or other audio accessories to play sound from openelec/kodi. Ithis should also work the other way so fo example let's say you have an android device with some sort of a player (Spotify or other) and choose to play audio over your bt enabled  openelec. 

Currently i have a rpi 2 with a nano bt device but it's good only for obex.

Unless i'mmissing something? 

BTW: you guys are doing great work,  openelec is so much better for media center than normal distro with additions. Keep up the good work!

**Comment by chewitt** [comment]
I'm closing the ticket because you are missing the ability to read the 500+ forum posts on the same topic. Sorry to sound blunt, but I am not making that number up.

**Comment by chewitt** [comment]
http://openelec.tv/forum/64-installation/74598-bluetooth-problem#136640

**Comment by bszafko** [comment]
Thanks I couldnt find this piece with Google otherwise I would not bother
you.

Sorry for being a pain in the ass ;)

**Comment by Whoopie** [comment]
xbian uses a2dp-alsa for bluetooth alsa, see https://github.com/xbianonpi/a2dp-alsa and https://github.com/belese/xbian-package-a2dp.
This works great and removes the pulseaudio dependency.

**Comment by stefansaraev** [comment]
not with bluez5.
