### ISSUE TITLE
cubox-i4 [imx6] OSD transparency not working

### ISSUE THREAD

**Issue by stormrev** [OpenELEC/OpenELEC.tv#4072]
During playback, opening the OSD shows gradient bars that are not transparent.
This regression is present on branch openelec-5.0 since after commit of  bc792c35dab0bf4f5c5897e364b705e7864fec36 (projects/imx6/patches/kodi: update imx6 patches)

see screenshot 
https://www.dropbox.com/s/ajiig82n4wt74r9/kodi-osd.jpg?dl=0

**Comment by fritsch** [comment]
Especially: dmesg | pastebinit please

**Comment by stormrev** [comment]
yes, indeed I had since long ago 16bpp in uEnv.txt
changed to 32bpp fixed the issue
thank you!
