### ISSUE TITLE
OE 5.0.8: VDR is crashing/closing continuously when recording is active when using XVDR

### ISSUE THREAD

**Issue by the-dreamer** [OpenELEC/OpenELEC.tv#4080]
back to 5.0.6 vdr is working as expected. I am suspecting the XVDR kodi addon version switch.

here is a debug vdr log: http://sprunge.us/fiGG

if more info/logs needed please let me know.

**Comment by stefansaraev** [comment]
last two xvdr commits must be reverted.

**Comment by stefansaraev** [comment]
xvdr is no more.
