### ISSUE TITLE
Airplay not working from OSX

### ISSUE THREAD

**Issue by jerlich** [OpenELEC/OpenELEC.tv#4084]
When i select Kodi 
![screen shot 2015-04-08 at 12 43 43 pm](https://cloud.githubusercontent.com/assets/2465395/7039004/eb0e77ce-ddec-11e4-9fab-db2380f68a21.png)
I get a dialog that pops up on my Mac:

This AirPlay device is not compatible with this software
Please update the AirPlay device to a newer version.

![screen shot 2015-04-08 at 12 43 50 pm](https://cloud.githubusercontent.com/assets/2465395/7039009/f898b0c6-ddec-11e4-8075-3308a7a25a50.png)

Running OpenElect 5.0.8 on a Raspi 2.0

I can airplay audio from my iPhone5 (iOS 8.2)

**Comment by lrusak** [comment]
Report upstream to Kodi, we simply consume their application

**Comment by stefansaraev** [comment]
this is not a big. you'd better call apple care ;)
