### ISSUE TITLE
Video play stalled at uncertain time.

### ISSUE THREAD

**Issue by rasberryrabbit** [OpenELEC/OpenELEC.tv#4087]
Stream video play stall uncertain time. Cannot continue to play in test build 0410.

12:31:49 20599.992188 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 21
12:31:51 20602.083984 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:32:06 20617.632812 T:1580201024  NOTICE: Previous line repeats 604 times.
12:32:06 20617.632812 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 4 packets of duration 21
12:32:15 20625.841797 T:1580201024  NOTICE: Previous line repeats 2 times.
12:32:15 20625.841797 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:32:15 20625.843750 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 4 packets of duration 21
12:32:15 20625.847656 T:1580201024  NOTICE: Previous line repeats 2 times.
12:32:15 20625.847656 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 2 packets of duration 21
12:32:15 20625.910156 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:32:15 20625.931641 T:1580201024  NOTICE: Previous line repeats 1 times.
12:32:15 20625.931641 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 21
12:34:42 20773.611328 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:34:42 20773.613281 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 4 packets of duration 21
12:45:03 21394.458984 T:1580201024  NOTICE: Previous line repeats 6 times.
12:45:03 21394.458984 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:45:03 21394.460938 T:1580201024  NOTICE: Previous line repeats 1 times.
12:45:03 21394.462891 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 21
12:45:04 21394.871094 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:45:04 21394.873047 T:1580201024  NOTICE: Previous line repeats 1 times.
12:45:04 21394.873047 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 21
12:45:06 21397.392578 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:45:21 21411.736328 T:1580201024  NOTICE: Previous line repeats 542 times.
12:45:21 21411.736328 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 21
12:45:21 21411.742188 T:1580201024  NOTICE: Previous line repeats 1 times.
12:45:21 21411.742188 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:45:21 21411.744141 T:1580201024  NOTICE: Previous line repeats 1 times.
12:45:21 21411.744141 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 21
12:45:21 21411.751953 T:1588589632 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
12:45:21 21411.763672 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 21
12:45:21 21411.802734 T:1588589632 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
12:45:21 21411.808594 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 2 packets of duration 21
12:45:21 21411.871094 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 21
12:45:36 21427.593750 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:45:36 21427.632812 T:1580201024  NOTICE: Previous line repeats 10 times.
12:45:36 21427.632812 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 21
12:45:39 21430.117188 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:46:06 21457.621094 T:1588589632  NOTICE: Previous line repeats 1073 times.
12:46:06 21457.621094 T:1588589632 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
12:46:07 21458.148438 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:46:07 21458.148438 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 4 packets of duration 21
12:46:07 21458.152344 T:1580201024  NOTICE: Previous line repeats 3 times.
12:46:07 21458.152344 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 3 packets of duration 21
12:46:07 21458.191406 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:46:07 21458.212891 T:1580201024  NOTICE: Previous line repeats 9 times.
12:46:07 21458.212891 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 21
12:46:07 21458.511719 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:46:07 21458.517578 T:1580201024  NOTICE: Previous line repeats 2 times.
12:46:07 21458.517578 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 21
12:46:07 21458.521484 T:1580201024  NOTICE: Previous line repeats 1 times.
12:46:07 21458.521484 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:46:07 21458.525391 T:1580201024  NOTICE: Previous line repeats 1 times.
12:46:07 21458.525391 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 21
12:46:07 21458.539062 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:46:07 21458.541016 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 21
12:46:07 21458.576172 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:46:07 21458.597656 T:1580201024  NOTICE: Previous line repeats 1 times.
12:46:07 21458.597656 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 21
12:46:08 21459.384766 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:46:08 21459.390625 T:1580201024  NOTICE: Previous line repeats 2 times.
12:46:08 21459.390625 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 21
12:46:13 21464.656250 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:47:06 21517.429688 T:1580201024  NOTICE: Previous line repeats 1321 times.
12:47:06 21517.505859 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 21
12:47:06 21517.507812 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:47:06 21517.509766 T:1580201024  NOTICE: Previous line repeats 3 times.
12:47:06 21517.509766 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 21
12:47:15 21526.011719 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:47:15 21526.015625 T:1580201024  NOTICE: Previous line repeats 4 times.
12:47:15 21526.015625 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 21
12:47:15 21526.019531 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:47:15 21526.023438 T:1580201024  NOTICE: Previous line repeats 3 times.
12:47:15 21526.023438 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 21
12:47:16 21527.214844 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:47:34 21545.242188 T:1563423808  NOTICE: Previous line repeats 279 times.
12:47:34 21545.242188 T:1563423808  NOTICE: Thread JobWorker start, auto delete: true
12:47:35 21546.199219 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:48:21 21591.904297 T:1588589632  NOTICE: Previous line repeats 838 times.
12:48:21 21591.904297 T:1588589632 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
12:48:22 21593.625000 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:48:24 21594.904297 T:1563423808  NOTICE: Previous line repeats 41 times.
12:48:24 21594.904297 T:1563423808  NOTICE: Thread BackgroundLoader start, auto delete: false
12:48:24 21594.943359 T:1478480960  NOTICE: Thread JobWorker start, auto delete: true
12:48:25 21596.224609 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:49:11 21642.107422 T:1588589632  NOTICE: Previous line repeats 881 times.
12:49:11 21642.107422 T:1588589632 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
12:49:11 21642.580078 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:49:11 21642.582031 T:1580201024  NOTICE: Previous line repeats 1 times.
12:49:11 21642.582031 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 21
12:49:14 21645.080078 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:49:22 21652.818359 T:1588589632  NOTICE: Previous line repeats 214 times.
12:49:22 21652.818359 T:1588589632 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
12:49:23 21654.400391 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:49:35 21665.908203 T:1588589632  NOTICE: Previous line repeats 108 times.
12:49:35 21665.908203 T:1588589632 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
12:49:35 21666.611328 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:49:47 21678.296875 T:1588589632  NOTICE: Previous line repeats 217 times.
12:49:47 21678.296875 T:1588589632 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
12:49:47 21678.636719 T:1580201024 WARNING: Previous line repeats 1 times.
12:49:47 21678.636719 T:1580201024  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 21
12:50:50 21740.787109 T:1516237888  NOTICE: Previous line repeats 2322 times.

**Comment by fritsch** [comment]
User failed to read the documentation when filing this report, which worthless.
