### ISSUE TITLE
Rpi build fails for linux.c

### ISSUE THREAD

**Issue by richardfstam** [OpenELEC/OpenELEC.tv#4088]
Cross compiling Openelec for Rpi on Ubuntu 14.04 fails.
Something seems to go wrong with macro expansion of _sycall5 in linux.c. See output below.
I start the build with:  PROJECT=RPi ARCH=arm make release.
I build from the archive version. I have not (yet) adapted sourcecode, I was planning to build a fix for my hifiberry digi, but first want to see the fresh build working :-(

The build error:
  CC       arch/linux.lo
/home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/parted-3.2/libparted/arch/linux.c:1699:23: error: unknown type name 'llseek'
 static _syscall5(int, llseek,
                       ^
/home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/parted-3.2/libparted/arch/linux.c:1700:32: error: unknown type name 'fd'
                  unsigned int, fd,
                                ^
/home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/parted-3.2/libparted/arch/linux.c:1701:33: error: unknown type name 'offset_high'
                  unsigned long, offset_high,
                                 ^
/home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/parted-3.2/libparted/arch/linux.c:1702:33: error: unknown type name 'offset_low'
                  unsigned long, offset_low,
                                 ^
/home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/parted-3.2/libparted/arch/linux.c:1703:27: error: unknown type name 'result'
                  loff_t*, result,
                           ^
/home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/parted-3.2/libparted/arch/linux.c:1704:32: error: unknown type name 'origin'
                  unsigned int, origin)
                                ^
/home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/parted-3.2/libparted/arch/linux.c: In function '_device_seek':
/home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/parted-3.2/libparted/arch/linux.c:1736:17: warning: implicit declaration of function 'llseek' [-Wimplicit-function-declaration]
                 return llseek (arch_specific->fd, pos, SEEK_SET) == pos;
                 ^
Makefile:1359: recipe for target 'arch/linux.lo' failed
make[4]: *** [arch/linux.lo] Error 1
make[4]: Leaving directory '/home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/parted-3.2/.i686-linux-gnu/libparted'
Makefile:1381: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/parted-3.2/.i686-linux-gnu/libparted'
Makefile:1265: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/parted-3.2/.i686-linux-gnu'
Makefile:1188: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/parted-3.2/.i686-linux-gnu'
make: *** [release] Error 2

**Comment by vpeter4** [comment]
What you get by running this in openelec folder?
´´grep ac_cv_sizeof_off_t build.OpenELEC-RPi.arm-*/parted-*/.armv6zk-openelec-linux-gnueabi/config.log´´
llseek is not used on my build.

**Comment by richardfstam** [comment]
file not found (or something similar).
seach for a config.log which has parted in the path gives me: ./build.OpenELEC-RPi.arm-devel/parted-3.2/.i686-linux-gnu/config.log
i686 seems the wrong architecture. Anything I missed in configuration?

**Comment by vpeter4** [comment]
So it even doesn't compile for host. What is the value in this file then?
Or `grep ac_cv_sizeof_off_t build.OpenELEC-RPi.arm-*/parted-*/.*/config.log`

**Comment by richardfstam** [comment]
Forgot to save the config.log. I pulled a new openelec-5.0 copy from github. And retried build, now it even fails sooner.
Really puzzled now.


/home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/toolchain/bin/host-gcc -std=gnu99  -I. -I/home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/m4-1.4.16/lib     -O2 -Wall -pipe -I/home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/toolchain/include -Wno-format-security -MT execute.o -MD -MP -MF .deps/execute.Tpo -c -o execute.o /home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/m4-1.4.16/lib/execute.c
In file included from /home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/m4-1.4.16/lib/gettext.h:185:0,
                 from /home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/m4-1.4.16/lib/c-stack.c:44:
./string.h:680:16: error: expected identifier or '(' before '__extension__'
 _GL_FUNCDECL_SYS (strndup, char *, (char const *__string, size_t __n)
                ^
Makefile:1399: recipe for target 'c-stack.o' failed
make[4]: *** [c-stack.o] Error 1
make[4]: *** Waiting for unfinished jobs....
mv -f .deps/close-hook.Tpo .deps/close-hook.Po
In file included from /home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/m4-1.4.16/lib/clean-temp.c:30:0:
./string.h:680:16: error: expected identifier or '(' before '__extension__'
 _GL_FUNCDECL_SYS (strndup, char *, (char const *__string, size_t __n)
                ^
Makefile:1399: recipe for target 'clean-temp.o' failed
make[4]: *** [clean-temp.o] Error 1
In file included from /home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/m4-1.4.16/lib/gettext.h:185:0,
                 from /home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/m4-1.4.16/lib/execute.c:34:
./string.h:680:16: error: expected identifier or '(' before '__extension__'
 _GL_FUNCDECL_SYS (strndup, char *, (char const *__string, size_t __n)
                ^
Makefile:1399: recipe for target 'execute.o' failed
make[4]: *** [execute.o] Error 1
make[4]: Leaving directory '/home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/m4-1.4.16/.i686-linux-gnu/lib'
Makefile:1196: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/m4-1.4.16/.i686-linux-gnu/lib'
Makefile:1131: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/m4-1.4.16/.i686-linux-gnu'
Makefile:1084: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/papa/OpenELEC.tv/build.OpenELEC-RPi.arm-devel/m4-1.4.16/.i686-linux-gnu'
make: *** [release] Error 2

**Comment by richardfstam** [comment]
grep ac_cv_sizeof_off_t build.OpenELEC-RPi.arm-*/parted-*/.*/config.log Gives:
grep: build.OpenELEC-RPi.arm-*/parted-*/.*/config.log: No such file or directory

find -name config.log Gives:

/build.OpenELEC-RPi.arm-devel/m4-1.4.16/.i686-linux-gnu/config.log
./build.OpenELEC-RPi.arm-devel/sed-4.2.2/.i686-linux-gnu/config.log
./build.OpenELEC-RPi.arm-devel/ccache-3.1.8/.i686-linux-gnu/config.log
./build.OpenELEC-RPi.arm-devel/pkg-config-0.28/.i686-linux-gnu/glib/config.log
./build.OpenELEC-RPi.arm-devel/pkg-config-0.28/.i686-linux-gnu/config.log
./build.OpenELEC-RPi.arm-devel/make-4.0/.i686-linux-gnu/config.log
./build.OpenELEC-RPi.arm-devel/gettext-0.19.4/.i686-linux-gnu/config.log
./build.OpenELEC-RPi.arm-devel/gettext-0.19.4/.i686-linux-gnu/examples/config.log
./build.OpenELEC-RPi.arm-devel/xz-5.2.1/.i686-linux-gnu/config.log

So again it seems, it doesn't build for arm, but for i686.

**Comment by vpeter4** [comment]
Some packages are build for host too.
Check for enough free space also try to remove ccache folder ($HOME/.ccache-openelec).

**Comment by InuSasha** [comment]
have you make a clean build?
("make clean" executed before build)

i have tested master build for rpi(1) on debian jessie: is working

**Comment by richardfstam** [comment]
Removing ccache seems to have helped. Just wondering: Should cleaning this dir, not be part od make clean?
My CPU gets easily overheated, and during one of the previous attempts it crashed my PC.
Last night I placed my laptop on an icepack. That controlled the temp. 
When time allows I will install the image on an SD and test if the build works. Then I'll continue with the rest of my experiment (replacing the hifiberry-digi module code with a fix) 
Thanks for your help so far. Will let you know if the build really produced a working image.

**Comment by vpeter4** [comment]
ccache must be removed manually.

**Comment by richardfstam** [comment]
Tested the build. It seems to work normally. Going to proceed with the experiment
No issue.
