### ISSUE TITLE
[RPi2] failed to apply RPi2 patch on kodi

### ISSUE THREAD

**Issue by InuSasha** [OpenELEC/OpenELEC.tv#4090]
Commit (master): https://github.com/OpenELEC/OpenELEC.tv/commit/6dcc19b32d3cb8ab117d8cf9d0bea2fadb58b210

Log File:
https://dl.inusasha.de/openelec/logs/consoleText.unpack.256

**Comment by stefansaraev** [comment]
remove or rebase it.
