### ISSUE TITLE
no kodi crashlogs with latest master

### ISSUE THREAD

**Issue by ksooo** [OpenELEC/OpenELEC.tv#4093]
$subject

**Comment by MilhouseVH** [comment]
Seems to be working fine with my latest Pi/Pi2 test builds... although my builds are using latest Kodi master:

http://sprunge.us/giaR

Any particular arch/project for your build? I can test Generic later.

**Comment by ksooo** [comment]
Generic x86_64

**Comment by MilhouseVH** [comment]
A Generic/x86_64 build based on Kodi master is working for me:

http://sprunge.us/HePF

However this is *not* pure OpenELEC master as the Kodi package is latest master, as are a few other packages. It will take a few more hours to build a pure nightly unless someone has a download already available. I can upload my own build if you like (works fine on Revo3700/ION2).

To test, I'm executing `kill -SEGV $(pidof kodi.bin)`

**Comment by stefansaraev** [comment]
wth is this.
