### ISSUE TITLE
Bad 3D handling when VDPAU is enabled

### ISSUE THREAD

**Issue by DasMarx** [OpenELEC/OpenELEC.tv#4094]
I have some 3d files that are handled strange when hardware acceleration is enabled. This only happens for movies, where the tags are correctly applied.

Ive added a full log starting 2 files, one with wrong 3d tags, so the file is handled like a 2d file and kodi menus are not in 3d. The next file does have correct tags and is therefore handled as a 3d file. The image quality is horrible as if the file is downscaled and upscaled.

I can even see this, by selecting original size, where i get a realy small version shown on my screen.

This bug is also mentioned in the forum:
http://openelec.tv/forum/67-display/70510-bad-sbs-3d-autodetect

Here are my logs:
https://www.dropbox.com/s/8fn2lipdvoo80ks/log-2015-04-13-07.53.08.zip?dl=0

For correct handling of the files, i have to disable hardware acceleration.

System specs:
ZOTAC ZBOX PLUS ID84
http://www.zotac.com/de/products/mini-pcs/zbox/intel/product/intel/detail/zbox-id84-plus/sort/starttime/order/DESC/amount/10/section/specifications.html

**Comment by fritsch** [comment]
Thanks for your report. This is an upstream kodi bug, OE cannot fix. Open a bug at trac.kodi.tv - btw. currently no one is working on 3D video playback on non RPi hardware at all - therefore chances are not good that this gets fixed right away.

**Comment by DasMarx** [comment]
It is not on RPi hardware, but pretty normal hardware. I opened the bug here, as i have seen this information in trac.kodi.tv:

Bad 3D autodetect mode
http://trac.kodi.tv/ticket/15092

Bad 3D SBS playback in stereoscopic mode
http://trac.kodi.tv/ticket/15075

I think, i should add my logs to the 2nd bug.

**Comment by fritsch** [comment]
I said: There is no work ongoing in that regard, besides on the RPi where this kind of stuff works perfectly.

**Comment by DasMarx** [comment]
Sorry, misunderstood you there by overreading the "non".

**Comment by chewitt** [comment]
closing as this is an upstream issue
