### ISSUE TITLE
3D Stopped working after updating to 5.0.8 on imx6

### ISSUE THREAD

**Issue by renatoriolino** [OpenELEC/OpenELEC.tv#4098]
I have a CuBox i2ex and after updating Openelec to 5.0.8 (previous I was running with 5.0.5 without problems) 3d stopped working.  Tried with a new fresh install using a dev-build from 04/10/2015 and the problem is still there.

The Problem: When kodi switches to 3d mode (in my case, SBS) both left and right side of the movie are been played at the left side (leaving the right side blank.

I have posted a screenshot at openelec's forum:
http://openelec.tv/media/kunena/attachments/22630/IMG_20150415_180231.jpg

The kodi log is here:
http://pastebin.com/5mje18qf

Let me know if any new information is needed.

Thanks

**Comment by fritsch** [comment]
Downgrade to 5.0.5 - it's currently not on my list of fixing things. This
code was never meant to end up in 5.0.x stable tree.

2015-04-16 20:10 GMT+02:00 renatoriolino <notifications@github.com>:

> I have a CuBox i2ex and after updating Openelec to 5.0.8 (previous I was
> running with 5.0.5 without problems) 3d stopped working. Tried with a new
> fresh install using a dev-build from 04/10/2015 and the problem is still
> there.
>
> The Problem: When kodi switches to 3d mode (in my case, SBS) both left and
> right side of the movie are been played at the left side (leaving the right
> side blank.
>
> I have posted a screenshot at openelec's forum:
> http://openelec.tv/media/kunena/attachments/22630/IMG_20150415_180231.jpg
>
> The kodi log is here:
> http://pastebin.com/5mje18qf
>
> Let me know if any new information is needed.
>
> Thanks
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4098>.
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by stefansaraev** [comment]
@sraue FYI

**Comment by stefansaraev** [comment]
shitload of stuff needs reverting

**Comment by renatoriolino** [comment]
Just FYI, tried yesterday with OE 6.0 beta.  3D is still not working, but now the behave is a little different: the GUI is switched to the 3D mode and the movie is kept on the left side while it should be expanded to the full screen.  (sorry for bad english, screenshot here: http://openelec.tv/media/kunena/attachments/22630/IMG_20150516_000910.jpg )

**Comment by fritsch** [comment]
Where can I find a sample to test that?

**Comment by fritsch** [comment]
Will be fixed after: https://github.com/xbmc/xbmc/pull/7159

**Comment by fritsch** [comment]
That will not fix it. On a second look, something concerning the x position should change, this would do something special for vertical splitting. Long weekend will come :-)

**Comment by fritsch** [comment]
https://dl.dropboxusercontent.com/u/55728161/OpenELEC-imx6.arm-6.0-devel-20150524214718-r20909-gca4344d.tar

Can you test this? Please make sure to upgrade from OE6 beta1

**Comment by renatoriolino** [comment]
fritsch, it worked!

Video and GUI is showing correctly now (tried with SBS and TAB).  Just one issue still:  when using subtitle on SBS mode, the subtitle is duplicated on both sides (as expected) but the X offset is wrong (as if it was centered relative to the screen size, not the "half screen" size).

![sbs_subtitle](https://cloud.githubusercontent.com/assets/6033308/7800853/466b59c8-02f2-11e5-9590-74b1e872c2b0.jpg)

**Comment by fritsch** [comment]
Anything better:
https://dl.dropboxusercontent.com/u/55728161/OpenELEC-imx6.arm-6.0-devel-20150525205103-r20909-gca4344d.tar
with that one?

2015-05-25 20:25 GMT+02:00 renatoriolino <notifications@github.com>:

> fritsch, it worked!
>
> Video and GUI is showing correctly now (tried with SBS and TAB). Just one
> issue still: when using subtitle on SBS mode, the subtitle is duplicated on
> both sides (as expected) but the X offset is wrong (as if it was centered
> relative to the screen size, not the "half screen" size).
>
> [image: sbs_subtitle]
> <https://cloud.githubusercontent.com/assets/6033308/7800853/466b59c8-02f2-11e5-9590-74b1e872c2b0.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4098#issuecomment-105285144>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by fritsch** [comment]
Nope - forget the last thing. I am clueless and asked a dev colleague for help.

**Comment by fritsch** [comment]
https://dl.dropboxusercontent.com/u/55728161/OpenELEC-imx6.arm-6.0-devel-20150526161736-r20909-gca4344d.tar

Here SBS should work, including subtitles. The Top / Bottom mode I don't have a clue yet on howto fix yet.

**Comment by renatoriolino** [comment]
Hi,

I confirm that now SBS is working (gui + subtitles).  On TAB only the TOP is showing, but the subtitle is working (showing on both top and bottom).

On the first test you post here, TAB was working (both gui and subtitles), only SBS subtitles weren't.

Let me know if you need more info / tests.

Thank you very much!

**Comment by fritsch** [comment]
The subtitles is the big issue :-) and we already found a bug in rendermanager ... still processing.

**Comment by fritsch** [comment]
https://dl.dropboxusercontent.com/u/55728161/OpenELEC-imx6.arm-6.0-devel-20150527224115-r20932-g08f6036.tar

Here. This one should work, it should even do something "reasonable" for 2D.

What I did not get working was: Transform SBS to TAB - that won't really work. But you should be able to watch TAB files now.

**Comment by fritsch** [comment]
https://dl.dropboxusercontent.com/u/55728161/OpenELEC-imx6.arm-6.0-devel-20150528085357-r20932-g08f6036.tar <- Oki, this is the final version we are merging.

Only issue left: One does not get auto transformed from SBS to Top / Bottom. But this does not really make sense anyways.

**Comment by renatoriolino** [comment]
Hi fritsch, it's working as expected now!! Thank you so much.  

About the transformation from SBS <-> TAB, I think no one uses this, because you will lose half horizontal and half vertical resolution doing so.

Thanks again!
