### ISSUE TITLE
DSD Playback with OE 5.0.8 on Raspberry pi Model B with Wilson Audio Card

### ISSUE THREAD

**Issue by maestroji** [OpenELEC/OpenELEC.tv#4100]
The playback of 24B192K flac and wav files is seamless, however output of SACD (dsf and dff) files is choppy and staggered.
Is this to be expected from Raspberry pi 'B'?
Thank you.

**Comment by fritsch** [comment]
Most likely yes. A debuglog will tell.

2015-04-18 13:15 GMT+02:00 maestroji <notifications@github.com>:

> The playback of 24B192K flac and wav files is seamless, however output of
> SACD (dsf and dff) files is choppy and staggered.
> Is this to be expected from Raspberry pi 'B'?
> Thank you.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4100>.
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by fritsch** [comment]
Please ask your question on the forum, this is a dev space and not some twitter replacement. Thanks very much.

**Comment by maestroji** [comment]
Thank you sir.
