### ISSUE TITLE
5.0.8 RPi2 Switching Preferred Technologies in connmanctl results in idle eth0 connection

### ISSUE THREAD

**Issue by ngodber** [OpenELEC/OpenELEC.tv#4102]
Switching preferred technologies in connman  main.conf in order to deal with internet connection issue (eth0 connected NAS and wifi connected internet lead to timeout) resulted in the the eth0 connection remaining idle with ip/netmask unassigned. Attempting to assign via connmanctl or interface in Kodi did not work. 

Only ip/netmask could only be assigned via ifconfig. 

Further information regarding this bug and present work around can be found at http://openelec.tv/forum/88-wlan/76534-wlan-is-ignored-if-lan-port-is-connected#138285

**Comment by ngodber** [comment]
logs can be found at https://drive.google.com/file/d/0B80PFF3u-fmoeU1zUHQySUpOeXM/view?usp=sharing

**Comment by lrusak** [comment]
I'm interested to know more about your setup. I assume your wifi connection connects to an access point that is your DHCP server? Does the ethernet connect straight to you NAS? or is there another DHCP server in between? I'm curious to know how your NAS gets a DHCP lease.

Not sure why you would set it up like this.

**Comment by ngodber** [comment]
There are two different networks one wireless and another wired. 

The only internet access in the household is via the the mobile phone. The RPi and home computer access the internet through the mobile personal hot spot.

The desktop is the file host and is connected to the RPi via a switch and therefore there is no DHCP server on this network hence requiring a manual setup. 

Bridging the two networks is not an option as the DHCP server is the mobile phone and therefore the network would not function (I believe?) if the mobile was not connected.

**Comment by stefansaraev** [comment]
this is not a bug. simultaneous use of wifi + ethernet is not supported. get a router.

**Comment by stefansaraev** [comment]
@cnewitt here is your custom main.conf thingie. amazing...

**Comment by ngodber** [comment]
No problem. The work around is perfectly functional at the end of the day. Just logged on the off chance devs would be interested. I did see a old forum post from a few years ago stating duel networks were unsupported. Was not sure if that was still the case, apparently so!

**Comment by stefansaraev** [comment]
btw, the behaviour is documented in connman docs. no dev (there is only one who efectively fixes network bugs, so...) is interested, as we really, really dont want to support such edge cases, really.

**Comment by ngodber** [comment]
No problem, completely understand. Thanks for all the work you guys do.
