### ISSUE TITLE
Intel® NUC Kit DN2820FYKH + OE 5.0.8 auto-boot???

### ISSUE THREAD

**Issue by Haris1977** [OpenELEC/OpenELEC.tv#4106]
This is a "strange" issue i am having 5-6 days now..My setup:

Intel® NUC Kit DN2820FYKH with Kingston KVR16LS11/4 (4 GB) Ram. In usb ports (back) i have attached:

1) Flirc controller (flirc.tv/)
2) TRANSCEND TS8GJF780 JETFLASH 780 8GB USB3.0 FLASH DRIVE BLACK (with OE 5.0.8 latest version).

I never had this problem but this "strange" one started when i ONLY did 2 things (and nothing else: havent touched my setup, havent removed/added/played with anything):

1) Updated bios from 041 to 050
2) Updated OE from 5.0.7 to 5.0.8

Problem is that the nuc boots on its own (usually the next day i have shut it down). So I got back to 041 bios (as the first idea that came to my mind was that the new bios was faulty). Problem still persists though (it remains with other bios too). Intel's enginners answer was:

"This looks like some kind of grounding or operating system related
issue, since the BIOS itself do not have a reason to turn on the system
on its own unless it is set on the BIOS to do so at a specific time, but
been a random issue, I do not think it is a BIOS issue"

Since i havent touched anything (so it cant be grounding problem) the only thing remaining is OE version (5.0.8). Could it be my problem?? Anyone is experiencing the same behavior?

**Comment by stefansaraev** [comment]
questions should be asked in forums / irc.
