### ISSUE TITLE
accessing shares from a windows 10 file server fails

### ISSUE THREAD

**Issue by rickdotw** [OpenELEC/OpenELEC.tv#4107]
using any build of windows 10 including the current one (10061) openelec which is on the lastet build (5.0.8) is unable to access the shares for my media. using the same username and password windows 8.1 and windows 7 machines have no problem. the administrator account is unuasual, andrewtaylor.zom@gmail.com so i dont know if that has something to do with it?

i have also reported the issue to microsoft so hopfully between everyone we should get to the bottom of the issue.

**Comment by chewitt** [comment]
user help is provided via the forums
