### ISSUE TITLE
BD, DVD not mounted any more

### ISSUE THREAD

**Issue by ksooo** [OpenELEC/OpenELEC.tv#4108]
In 5.0 (and earlier), DVDs and BDs got automatically mounted by OE. Seams, that this is no longer the case with 5.2 and current master. This breaks Kodi 14 and 15 (at least BD) autoplay, as Kodi relies on mounted disk for detecting the disk type properly.

**Comment by stefansaraev** [comment]
try now with 30d43e1. make sure to do PROJECT=xx ARCH=yy scripts/clean udevil first

**Comment by ksooo** [comment]
Seems to work again. Thx.

**Comment by stefansaraev** [comment]
thanks for reporting.

btw, next time, please logs. this time it was easy, because you already found and commented on the offending commit ;)
