### ISSUE TITLE
Urllib2 not supporting IPv6

### ISSUE THREAD

**Issue by paalsteek** [OpenELEC/OpenELEC.tv#4111]
Urllib2, which is used by many plugins, does not use IPv6. This can be tested by the following python script:

```python

import urllib2
opener = urllib2.build_opener()
request = urllib2.Request("http://ismyipv6working.com/")
response = opener.open(request)
print(response.getcode())
print(response.read())
```

This does work on my ArchLinux system with python 2.7.9 and urllib2 2.7

**Comment by stefansaraev** [comment]
it works perfectly fine here. doublecheck your network setup

**Comment by stefansaraev** [comment]
FYI, when a dns server returns both A and AAAA records, on OpenELEC, ipv4 is preferred, for a very good reason, and that wont change. see etc/gai.conf. 
but urllib2 (and everything else) is perfectly fine with accessing v6-only hosts. try urllib2.Request("http://[::1]/") and do a capture dump if you want.

**Comment by paalsteek** [comment]
Is there any way to change that behaviour without compiling your own image? I have native IPv6 here and IMHO it's a shame not to use it.

**Comment by stefansaraev** [comment]
feel free to use bind-mount a modified gai.conf

**Comment by paalsteek** [comment]
Thanks for the tip. creating an empty `/storage/gai.conf` and adding `mount -o bind /storage/gai.conf /etc/gai.conf` to my `/storage/.config/autostart.sh` "fixes" the problem. Is there any documentation on why IPv4 is preferred?

**Comment by stefansaraev** [comment]
it was a decision taken long time ago. as said, it wont change.
