### ISSUE TITLE
Cannot build pvr.hts anymore with latest OE master

### ISSUE THREAD

**Issue by ksooo** [OpenELEC/OpenELEC.tv#4113]
kai@kso-desktop:~/src/openelec/OpenELEC.tv$ PROJECT=Generic ARCH=x86_64 ./scripts/create_addon pvr.hts
  BUILD    pvr.hts (target)
-- HTS_VERSION=2.1.8
CMake Error at /home/kai/src/openelec/OpenELEC.tv/build.OpenELEC-Generic.x86_64-devel/toolchain/x86_64-openelec-linux-gnu/sysroot/usr/lib/kodi/addon-helpers.cmake:80 (include):
  include could not find load file:

    UseMultiArch
Call Stack (most recent call first):
  CMakeLists.txt:34 (build_addon)

-- Configuring incomplete, errors occurred!
See also "/home/kai/src/openelec/OpenELEC.tv/build.OpenELEC-Generic.x86_64-devel/pvr.hts-4bf1a97/.x86_64-openelec-linux-gnu/CMakeFiles/CMakeOutput.log".

===> https://github.com/xbmc/xbmc/commit/0e243bc650551cc8f9892fd38ba4f60f7ce5b103 ???

BTW: cp ./build.OpenELEC-Generic.x86_64-devel/kodi-15.0-beta1-7dacc6e/project/cmake/scripts/linux/UseMultiArch.cmake ./build.OpenELEC-Generic.x86_64-devel/toolchain/x86_64-openelec-linux-gnu/sysroot/usr/lib/kodi/ fixes it.

**Comment by stefansaraev** [comment]
> ===> xbmc/xbmc@0e243bc ???

yes.
however, already reported. https://github.com/xbmc/xbmc/commit/008d4637abc035f14d96019098c09e299d9c15d4#commitcomment-10906317

ping @wsnipex

**Comment by MilhouseVH** [comment]
It's not just pvr.hts, it's every binary addon, including the audioencoders/decoders (building RPi/RPi2).

Reverting https://github.com/xbmc/xbmc/pull/6897 is at least a temporary fix and allows builds to complete.

**Comment by wsnipex** [comment]
please try https://github.com/xbmc/xbmc/pull/7032

**Comment by stefansaraev** [comment]
fixed in 197b4dd
