### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by Karl-opec** [OpenELEC/OpenELEC.tv#4118]
Trying to build the latest master Branch leads to the following error
message on my Suse 13.2 System:

[code]
make[3]: Entering directory '/pool/md1/download/ftp/openelec/master/build.OpenELEC-Generic.x86_64-devel/kodi-15.0-beta1-7dacc6e/tools/depends/native/TexturePacker/native'
/pool/md1/download/ftp/openelec/master/build.OpenELEC-Generic.x86_64-devel/toolchain/bin/host-g++ -DTARGET_POSIX -DUSE_LZO_PACKING  -O2 -Wall -pipe -I/pool/md1/download/ftp/openelec/master/build.OpenELEC-Generic.x86_64-devel/toolchain/include -Wno-format-security -llzo2 -ljpeg -lgif  -L/pool/md1/download/ftp/openelec/master/build.OpenELEC-Generic.x86_64-devel/toolchain/lib -lpng16 -lm -lz -lm  -L/pool/md1/download/ftp/openelec/master/build.OpenELEC-Generic.x86_64-devel/kodi-15.0-beta1-7dacc6e/tools/depends/native/libsquish-native/squish-install/lib -lsquish  -static -Wl,-rpath,/pool/md1/download/ftp/openelec/master/build.OpenELEC-Generic.x86_64-devel/toolchain/lib -L/pool/md1/download/ftp/openelec/master/build.OpenELEC-Generic.x86_64-devel/toolchain/lib -o TexturePacker md5.o XBTFWriter.o TexturePacker.o DecoderManager.o decoder/PNGDecoder.o decoder/JPGDecoder.o decoder/GifHelper.o decoder/GIFDecoder.o XBTF.o  -llzo2 -ljpeg -lgif  -L/pool/md1/download/ftp/openelec/master/build.OpenELEC-Generic.x86_64-devel/toolchain/lib -lpng16 -lm -lz -lm  -L/pool/md1/download/ftp/openelec/master/build.OpenELEC-Generic.x86_64-devel/kodi-15.0-beta1-7dacc6e/tools/depends/native/libsquish-native/squish-install/lib -lsquish 
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lm
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lm
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lm
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lm
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
Makefile:423: recipe for target 'TexturePacker' failed
make[3]: *** [TexturePacker] Error 1
make[3]: Leaving directory '/pool/md1/download/ftp/openelec/master/build.OpenELEC-Generic.x86_64-devel/kodi-15.0-beta1-7dacc6e/tools/depends/native/TexturePacker/native'
Makefile:313: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/pool/md1/download/ftp/openelec/master/build.OpenELEC-Generic.x86_64-devel/kodi-15.0-beta1-7dacc6e/tools/depends/native/TexturePacker/native'
Makefile:43: recipe for target 'native/TexturePacker' failed
make[1]: *** [native/TexturePacker] Error 2
make[1]: Leaving directory '/pool/md1/download/ftp/openelec/master/build.OpenELEC-Generic.x86_64-devel/kodi-15.0-beta1-7dacc6e/tools/depends/native/TexturePacker'
Makefile:9: recipe for target 'release' failed
make: *** [release] Error 2
[/code]

Building other branches 5.0 etc doesn't show this.

Any Idea?

**Comment by stefansaraev** [comment]
on fedora. install glibc-static and libstdc++-static.
