### ISSUE TITLE
cannot find -lm

### ISSUE THREAD

**Issue by steeevieee** [OpenELEC/OpenELEC.tv#4126]
For the last few weeks, my Jenkins builds for RPi and RPi2 have failed because they can't link to libm when compiling kodi. I've tried copying libm from elsewhere in the buildroot but that doesn't resolve the problem...

/usr/bin/ld: cannot find -lm
collect2: ld returned 1 exit status
Makefile:423: recipe for target 'TexturePacker' failed
make[3]: *** [TexturePacker] Error 1
make[3]: Leaving directory '/storage/dev/jenkins/workspace/openelec-rpi/build.OpenELEC-RPi.arm-devel/kodi-15.0-beta1-d1a2c33/tools/depends/native/TexturePacker/native'

**Comment by stefansaraev** [comment]
dup #4118 read the docs
