### ISSUE TITLE
OE 5.95.1 - No sound after a resume

### ISSUE THREAD

**Issue by FuNK3Y** [OpenELEC/OpenELEC.tv#4133]
This new release is great. I just noticed a small set back.

If I put the computer to sleep & wake it afterward I lose the sound. 

I do have an Onkyo AVR connected to an nvidia card GT 630 over HDMI. I am using the x64 release (not the legacy one)

Rebooting the PC solves the issue

FInd the logs:
http://www.filedropper.com/log-2015-05-07-205128
http://www.filedropper.com/log-2015-05-07-210254

**Comment by FuNK3Y** [comment]
I noticed that this bug is triggered only when I hardcode the EDID (http://wiki.openelec.tv/index.php?title=Config_EDID_nvidia)

I do have to do that because of another bug: https://github.com/Pulse-Eight/libcec/issues/50

This was working fine until now (5.0.x).

**Comment by fritsch** [comment]
Yeah - new nvidia driver - new problems. Let's hope the next blob will fix it. If you want to help us, try to rebuild OE with a downgraded nvidia driver, matching the version we had in 5.0.x

Thanks much.

**Comment by FuNK3Y** [comment]
I tried to revert to 340.76, but it does not compile. I suspect that this might be related to the new kernel 4.0.

349.16 seems to get through, I will report back once is tested

**Comment by FuNK3Y** [comment]
It works totally fine with 349.16; you were right. Something was definitively fishy with the 346.59 (even when the sound was working, the name of the AVR was not properly displayed under system > audio device after resume).

From now on, I would suggest using that version

**Comment by fritsch** [comment]
@sraue @lrusak ping

2015-05-08 22:59 GMT+02:00 FuNK3Y <notifications@github.com>:

> It works totally fine with 349.16; you were right. Something was
> definitively fishy with the 346.59 (even when the sound was working, the
> name of the AVR was not properly displayed under system > audio device
> after resume).
>
> From now on, I would suggest using that version
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4133#issuecomment-100362999>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by lrusak** [comment]
hmmm, 
340.76 is the old long lived branch
349.16 is part of the short lived branch
346.59 is the new long lived branch

I really don't want to downgrade because we will lose support for new GPU's, but I don't know if it is a good idea to switch to the short lived branch. If it works and there are no other bugs then we can use it, but we cannot bump it or change it once 6.0 is released.

**Comment by stefansaraev** [comment]
no downgrade. no switching to short lived. what it is, that is.

**Comment by fritsch** [comment]
Roling a dice, next bump in that series might get better (or worse) for
others - the game of bumping, welcome.

Don't forget to report to nvidia.

2015-05-09 10:14 GMT+02:00 Stefan Saraev <notifications@github.com>:

> no downgrade. no switching to short lived. what it is, that is.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4133#issuecomment-100446880>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by FuNK3Y** [comment]
Still broken on the new 346.72. I will check with nvidia

**Comment by stefansaraev** [comment]
352.21

**Comment by FuNK3Y** [comment]
I did test and it worked (I did compile the 5.95.1 myself, with this driver as the only difference).

Thanks!

**Comment by stefansaraev** [comment]
cool. thanks ;)
