### ISSUE TITLE
[feature request] Reconnect smb on resume from suspend

### ISSUE THREAD

**Issue by xbmchermit** [OpenELEC/OpenELEC.tv#4158]
Currently, when I bring the box out of suspend, there is a less than 50% chance that I will be able to access the files on my server.  Most of the time, I get the "this file no longer exists on the server, would you like to remove it from the library?" message, and I have to reboot to reconnect smb.

It would be great if, when resuming from suspend, the system would automatically reconnect/log into the established smb shares.

**Comment by fritsch** [comment]
How high is the chance when just powerdown the box and boot it up again?

**Comment by sraue** [comment]
would be great to have some logs like "dmesg" after wakeup... does this happen too if you suspend only for a short time?

**Comment by xbmchermit** [comment]
If i power it down fully, it always reconnects the SMB when it starts up.  The problem is, my hardware doesn't seem to want to allow me to use the remote to power the machine up from OFF, so I have to use Suspend.

Here is the dmesg: http://pastebin.com/E4LuhH2T

If I suspend it for only a minute or two, I can usually access the smb share directly.  Any appreciable amount of time (such as if I get busy and it times out and I come back 30 min later) and I will have to reboot the machine.

**Comment by chewitt** [comment]
closing old tickets with no update.. should the issue still exist on a current release please start a forum thread, thanks.
