### ISSUE TITLE
 Realtek8192SU Chipset 

### ISSUE THREAD

**Issue by ShaneSheppard** [OpenELEC/OpenELEC.tv#4162]
Please can you provide support for this chipset to Openelec out of the box as this chipset can speed up wireless performance.

**Comment by stefansaraev** [comment]
you should send an email to realtek for supporting their chip ootb in linux mainline kernel :)

**Comment by ShaneSheppard** [comment]
They have a driver for linux already its just not standard with Openelec on install

**Comment by mrdominuzq** [comment]
Has been replaced upstream with another driver http://cateee.net/lkddb/web-lkddb/R8712U.html

**Comment by mrdominuzq** [comment]
Edit not upstream just in kernel :p

**Comment by mrdominuzq** [comment]
so what stick are we talking about ?

**Comment by ShaneSheppard** [comment]
Stick:
EDUP 300Mbps Wireless-N Usb Mini Adapter - EP-N1528

**Comment by mrdominuzq** [comment]
And We The logs :)

**Comment by mrdominuzq** [comment]
Need*

**Comment by mrdominuzq** [comment]
any news on those logs @ShaneSheppard ?

**Comment by chewitt** [comment]
closing due to lack of update

**Comment by ShaneSheppard** [comment]
Replaced the wifi dongle as all methods would not work.
