### ISSUE TITLE
MCE IR remote not recognized at boot

### ISSUE THREAD

**Issue by htpcBeginner** [OpenELEC/OpenELEC.tv#4167]
Guys, please do not close this issue as invalid. 

Here is the original issue raised: https://github.com/OpenELEC/OpenELEC.tv/issues/3589

Here is the forum thread where many people have reported the same problem: http://openelec.tv/forum/103-infared-remotes/73522-usb-mce-ir-remote-not-recognized-at-boot

Here is another example of a user reporting the same problem: http://www.htpcbeginner.com/simple-cheap-raspberry-pi-remote-control/#comment-4189

There is definitely an issue. 

@thedecibelkid

**Comment by mrdominuzq** [comment]
and still no logs...

**Comment by htpcBeginner** [comment]
@mrdominuzq I will get you logs. I never done it before. So I need to figure it out. Link to a page that describes how to get the logs would be much appreciated.

**Comment by mrdominuzq** [comment]
http://wiki.openelec.tv/index.php/OpenELEC_FAQ#Support

**Comment by fritsch** [comment]
That just proofs, that you did not take - even a second(!) - time to read https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md which you are presented when opening an issue report ...

**Comment by htpcBeginner** [comment]
@mrdominuzq @fritsch Sorry. Read and understood now. I do not have any running OpenELEC installs. Give me few days for me (or someone else) to get the logs to you.

**Comment by fritsch** [comment]
When logfile are ready, edit your first post and reply here. I will then reopen.
