### ISSUE TITLE
OpenELEC keyboard layout setting can not be changed with Russian interface.(OE 6.0 beta). 

### ISSUE THREAD

**Issue by dibor** [OpenELEC/OpenELEC.tv#4172]
Hello.
Keyboard layout can be changed under "System" > "OpenELEC" > "System"  > Keyboard.
But if you change language to Russian "System" > "Settings" > "Appearance" > "International" > "Language" (I do not checked with others languages).
Make Reboot. (very important to do restart)
Go to keyboard layout setting  place - you can not now to make any changes!
 
Best regards.

**Comment by stefansaraev** [comment]
thanks for reporting. fixed in b301e0ab80f1989a525134677f53785f15f5f55e
