### ISSUE TITLE
No SMB 2 client support (needs samba package >=4.1)

### ISSUE THREAD

**Issue by pointoforder** [OpenELEC/OpenELEC.tv#4174]
I'm trying to connect to an SMB server that only supports SMB 2+. I'm using OpenELEC 5.0.8 on a Rapberry Pi 2 (RPi2.arm-5.0.8).

As discussed on the [forums](http://openelec.tv/forum/76-network-filesystems/76816-no-smb-2-connectivity), OE is using Samba 3.6.25, and since Samba first added SMB 2 client support later (in 4.1), OE currently doesn't support connecting to an SMB2-only server.

With Windows 8, SMB 1.0 support is an optional feature ("SMB 1.0/CIFS File Sharing Support" in Windows Features/Turn Windows features on or off). Without this legacy feature enabled, I'm unable to connect from OE to file shares on this PC. (I'm also unable to connect from this PC to the OE file shares as well; I suspect, but have not yet confirmed, a samba package update would fix that problem as well.)

There's quite a bit more background/investigation details in the forum post. I'm happy to put more of it in the bug if you like; for now, I'll avoid duplicating that content. I can also post a sanitized version of my log file if that's needed, though I suspect that's not essential for this kind of package update request.

I think this bug boils down to a request to upgrade samba to 4.1 or higher (the latest is currently 4.2.2). You'll probably want at least 4.2 due to cross-compilation problems in Samba 4.1 - the forum post has links to the relevant Samba bugs and release history.

**Comment by stefansaraev** [comment]
samba wont be upgraded to 4.1 (due to their buildsystem switch to waf) we stick with latest one that is autoconf based.

> You'll probably want at least 4.2 due to cross-compilation problems in Samba 4.1 - the forum post has links to the relevant Samba bugs and release history

how is samba 4.2 different in terms of cross-compilation? doesnt it still use waf? qemu is not an option for us.

**Comment by sraue** [comment]
besides of this... Kodi is not prepared and tested together with samba-4.x, so this will be investigated after kodi includes samba-4 support officially

**Comment by pointoforder** [comment]
@stefansaraev, From the samba [bug history](https://bugzilla.samba.org/show_bug.cgi?id=10128), it sounds like they have non-qemu cross-compilation working:

>I have finally had some success with:
>http://buildroot.uclibc.org/
>in generatin 4.1.x and 4.2.x ARM binaries without using the QEMU method !

And they say buildroot is currently using cross-compilation successfully as well:
>http://git.buildroot.net/buildroot/tree/package/samba4/samba4.mk

@sraue, Thanks, good to know. I'll try to ask the Kodi folks what their plans are for official samba-4 support.

**Comment by sraue** [comment]
closing for now, will be updated when samba 4 support is in kodi
