### ISSUE TITLE
Openelec will not answer to IGMPv2 Query

### ISSUE THREAD

**Issue by nightwatcher74** [OpenELEC/OpenELEC.tv#4175]
I want to use Openelec in my company. The Network works with multicast very well. On Windows PCs I can see all multicast channels without problems but with openelec the stream will stop after 2 minutes.
Facts:
- I use the actuall beta from openelec
- I switched to igmp version 2

net.ipv4.conf.all.force_igmp_version = 2
net.ipv4.conf.all.igmpv2_unsolicited_report_interval = 10000
net.ipv4.conf.all.igmpv3_unsolicited_report_interval = 1000
net.ipv4.conf.default.force_igmp_version = 2
net.ipv4.conf.default.igmpv2_unsolicited_report_interval = 10000
net.ipv4.conf.default.igmpv3_unsolicited_report_interval = 1000
net.ipv4.conf.eth0.force_igmp_version = 2
net.ipv4.conf.eth0.igmpv2_unsolicited_report_interval = 10000
net.ipv4.conf.eth0.igmpv3_unsolicited_report_interval = 1000
net.ipv4.conf.lo.force_igmp_version = 2
net.ipv4.conf.lo.igmpv2_unsolicited_report_interval = 10000
net.ipv4.conf.lo.igmpv3_unsolicited_report_interval = 1000

and i tested it with tvheadend, udpxy and the kodi internal IPTV plugin.

When I with windows I can see IGMP Membership query from the Network and IGMP Membership Reports from the windows Workstation (Win7) and VLC as Application. 
With Openelec on my Raspi B I see only the membership Query from the network but no answer from the device (all checked with tcpdump) so the TV Channel is working for 120 seconds and stop with a freeze of the channel. When I start again (only channel select, no reboot) it works again for 120 sec.
So it looks like that IGMPv3 is working well but not IGMPv2!

can anyone help me with tips or is this a bug?

Thanks

Frank.

**Comment by stefansaraev** [comment]
this is working just fine. it is not different than any other linux distro. double check your network setup.

**Comment by nightwatcher74** [comment]
I double checked all!
With windows it is working (as you can see in the image I attached.
![igmp windows](https://cloud.githubusercontent.com/assets/12713048/7934975/d1332258-092c-11e5-8c49-2ff7ab0aac9d.jpg)
 and on openelec you can see the joun to the channel but no answer that belong to the query:

09:21:22.851394 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 32, options (RA))
    10.4.111.80 > 239.228.245.127: igmp v2 report 239.228.245.127
        0x0000:  46c0 0020 0000 4000 0102 855f 0a04 6f50  F.....@...._..oP
        0x0010:  efe4 f57f 9404 0000 1600 049b efe4 f57f  ................
09:21:22.892016 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.3.10.2 > 224.0.0.1: igmp query v2
        0x0000:  0001 0800 4500 001c 0000 0000 0102 c5da  ....E...........
        0x0010:  0a03 0a02 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:21:22.968075 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 32, options (RA))
    10.4.111.80 > 239.228.245.127: igmp v2 report 239.228.245.127
        0x0000:  46c0 0020 0000 4000 0102 855f 0a04 6f50  F.....@...._..oP
        0x0010:  efe4 f57f 9404 0000 1600 049b efe4 f57f  ................
09:21:22.994584 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.3.150.2 > 224.0.0.1: igmp query v2
        0x0000:  0096 0800 4500 001c 0000 0000 0102 39da  ....E.........9.
        0x0010:  0a03 9602 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:21:23.094720 IP (tos 0xc0, ttl 1, id 0, offset 0, flags [DF], proto IGMP (2), length 32, options (RA))
    10.4.111.80 > 239.228.245.127: igmp v2 report 239.228.245.127
        0x0000:  46c0 0020 0000 4000 0102 855f 0a04 6f50  F.....@...._..oP
        0x0010:  efe4 f57f 9404 0000 1600 049b efe4 f57f  ................
09:22:10.868142 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.111.2 > 224.0.0.1: igmp query v2
        0x0000:  0137 0800 4500 001c 0000 0000 0102 60d9  .7..E.........`.
        0x0010:  0a04 6f02 e000 0001 1164 ee9b 0000 0000  ..o......d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:22:10.904501 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.112.2 > 224.0.0.1: igmp query v2
        0x0000:  0138 0800 4500 001c 0000 0000 0102 5fd9  .8..E........._.
        0x0010:  0a04 7002 e000 0001 1164 ee9b 0000 0000  ..p......d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:22:10.905611 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.131.2 > 224.0.0.1: igmp query v2
        0x0000:  014b 0800 4500 001c 0000 0000 0102 4cd9  .K..E.........L.
        0x0010:  0a04 8302 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:22:10.934256 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.132.2 > 224.0.0.1: igmp query v2
        0x0000:  014c 0800 4500 001c 0000 0000 0102 4bd9  .L..E.........K.
        0x0010:  0a04 8402 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:22:10.993091 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.211.2 > 224.0.0.1: igmp query v2
        0x0000:  019b 0800 4500 001c 0000 0000 0102 fcd8  ....E...........
        0x0010:  0a04 d302 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:22:10.994210 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.212.2 > 224.0.0.1: igmp query v2
        0x0000:  019c 0800 4500 001c 0000 0000 0102 fbd8  ....E...........
        0x0010:  0a04 d402 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:22:10.995348 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.231.2 > 224.0.0.1: igmp query v2
        0x0000:  01af 0800 4500 001c 0000 0000 0102 e8d8  ....E...........
        0x0010:  0a04 e702 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:22:11.024980 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.232.2 > 224.0.0.1: igmp query v2
        0x0000:  01b0 0800 4500 001c 0000 0000 0102 e7d8  ....E...........
        0x0010:  0a04 e802 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:22:22.885043 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.3.10.2 > 224.0.0.1: igmp query v2
        0x0000:  0001 0800 4500 001c 0000 0000 0102 c5da  ....E...........
        0x0010:  0a03 0a02 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:22:23.129114 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.3.150.2 > 224.0.0.1: igmp query v2
        0x0000:  0096 0800 4500 001c 0000 0000 0102 39da  ....E.........9.
        0x0010:  0a03 9602 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:23:10.826874 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.111.2 > 224.0.0.1: igmp query v2
        0x0000:  0137 0800 4500 001c 0000 0000 0102 60d9  .7..E.........`.
        0x0010:  0a04 6f02 e000 0001 1164 ee9b 0000 0000  ..o......d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:23:10.906988 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.112.2 > 224.0.0.1: igmp query v2
        0x0000:  0138 0800 4500 001c 0000 0000 0102 5fd9  .8..E........._.
        0x0010:  0a04 7002 e000 0001 1164 ee9b 0000 0000  ..p......d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:23:10.908098 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.131.2 > 224.0.0.1: igmp query v2
        0x0000:  014b 0800 4500 001c 0000 0000 0102 4cd9  .K..E.........L.
        0x0010:  0a04 8302 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:23:10.934622 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.132.2 > 224.0.0.1: igmp query v2
        0x0000:  014c 0800 4500 001c 0000 0000 0102 4bd9  .L..E.........K.
        0x0010:  0a04 8402 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:23:10.995804 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.211.2 > 224.0.0.1: igmp query v2
        0x0000:  019b 0800 4500 001c 0000 0000 0102 fcd8  ....E...........
        0x0010:  0a04 d302 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:23:10.996998 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.212.2 > 224.0.0.1: igmp query v2
        0x0000:  019c 0800 4500 001c 0000 0000 0102 fbd8  ....E...........
        0x0010:  0a04 d402 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:23:10.998110 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.231.2 > 224.0.0.1: igmp query v2
        0x0000:  01af 0800 4500 001c 0000 0000 0102 e8d8  ....E...........
        0x0010:  0a04 e702 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:23:11.032868 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.232.2 > 224.0.0.1: igmp query v2
        0x0000:  01b0 0800 4500 001c 0000 0000 0102 e7d8  ....E...........
        0x0010:  0a04 e802 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:23:22.908736 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.3.10.2 > 224.0.0.1: igmp query v2
        0x0000:  0001 0800 4500 001c 0000 0000 0102 c5da  ....E...........
        0x0010:  0a03 0a02 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:23:22.999280 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.3.150.2 > 224.0.0.1: igmp query v2
        0x0000:  0096 0800 4500 001c 0000 0000 0102 39da  ....E.........9.
        0x0010:  0a03 9602 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:24:10.847748 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.111.2 > 224.0.0.1: igmp query v2
        0x0000:  0137 0800 4500 001c 0000 0000 0102 60d9  .7..E.........`.
        0x0010:  0a04 6f02 e000 0001 1164 ee9b 0000 0000  ..o......d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:24:10.909043 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.112.2 > 224.0.0.1: igmp query v2
        0x0000:  0138 0800 4500 001c 0000 0000 0102 5fd9  .8..E........._.
        0x0010:  0a04 7002 e000 0001 1164 ee9b 0000 0000  ..p......d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:24:10.910154 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.131.2 > 224.0.0.1: igmp query v2
        0x0000:  014b 0800 4500 001c 0000 0000 0102 4cd9  .K..E.........L.
        0x0010:  0a04 8302 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:24:10.936990 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.132.2 > 224.0.0.1: igmp query v2
        0x0000:  014c 0800 4500 001c 0000 0000 0102 4bd9  .L..E.........K.
        0x0010:  0a04 8402 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:24:10.997509 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.211.2 > 224.0.0.1: igmp query v2
        0x0000:  019b 0800 4500 001c 0000 0000 0102 fcd8  ....E...........
        0x0010:  0a04 d302 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..
09:24:10.998621 IP (tos 0x0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 28)
    10.4.212.2 > 224.0.0.1: igmp query v2
        0x0000:  019c 0800 4500 001c 0000 0000 0102 fbd8  ....E...........
        0x0010:  0a04 d402 e000 0001 1164 ee9b 0000 0000  .........d......
        0x0020:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0030:  0000                                     ..



I think its working with IGMPv3 because German telecom uses IGMPv3 and this is the most used Multicast Protocol (IGMPv3) but IGMPv2 is not working! I also tested this in another company network wich is based on MPLS but Multicast on all clients and devices is würking but not on openelec!

**Comment by nightwatcher74** [comment]
PS: no firewall active

OpenELEC:~ # iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
OpenELEC:~ #

**Comment by stefansaraev** [comment]
again. double check your network set up. use forums or irc for support questions. and pastebin or sprunge.us for logs. the log you posted makes no sense.

and one last time. openelec is no different than any other linux distro

**Comment by chewitt** [comment]
closing because this is not a support channel .. we have forums for support issues
