### ISSUE TITLE
Impossible to  change order of virtual keyboard.

### ISSUE THREAD

**Issue by dibor** [OpenELEC/OpenELEC.tv#4179]
Hello.
Settings do not have any way to  change order of virtual keyboard.
 Every time English layout is first (if you do not have Arabic, Bulgarian or Danish layouts).
Works in  Abc order .
 How can we change order ?

 Best Regards.

**Comment by stefansaraev** [comment]
https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md

**Comment by dibor** [comment]
Hi.
I'm sorry, but this is was not a question.
May by this is not OpenELEC problem but Kodi doesn't has any instrument for setting virtual  keyboard order!
Try set English and Russian, Spanish or other - English always will be first!.
