### ISSUE TITLE
Provided examples reference incorrect commands

### ISSUE THREAD

**Issue by thisisnotmyrealname** [OpenELEC/OpenELEC.tv#4185]
The files

~/.config/system.d/cifs.mount.sample and nfs.mount.sample (in the same directory) at the end say

# command 'servicectl enable storage-music2.mount'

servicectl is not a valid command. it should be systemctl instead.

The web page at http://wiki.openelec.tv/index.php?title=Mounting_network_shares lists the correct command to use.

**Comment by stefansaraev** [comment]
this is not a bug. 7d474250581ea38e4e34f044cd5971045e073be2
