### ISSUE TITLE
rtl8192DU driver needs updated.

### ISSUE THREAD

**Issue by miigotu** [OpenELEC/OpenELEC.tv#4187]
Included version is about a year old, and there are about 55 new commits. It now has a more complete kernel 4.0/4.1 fix than the current patch, so `packages/linux-drivers/RTL8192DU/RTL8192DU-kernel-4.0.patch` will be no longer needed, 5G fixes, and more.

Recently switched to an 8192DU dongle and cannot connect to n-only, nor 5Ghz.

https://github.com/lwfinger/rtl8192du

**Comment by stefansaraev** [comment]
why is this not a PR ?

**Comment by miigotu** [comment]
I'm not sure how to do PR for packages that need uploaded to the package server. If I just changed the package.mk and removed the RTL8192DU-kernel-4.0.patch it would fail to build because the package wouldnt be on the server.

Anyways, Milhouse has made a package for it and it is updated in his current #0608b+ builds, so I think a PR can be made soon as he has more understanding/access to how this scenario plays out here.
