### ISSUE TITLE
OE 6.0 Beta 1: PVR Addon is not loading always

### ISSUE THREAD

**Issue by the-dreamer** [OpenELEC/OpenELEC.tv#4188]
http://sprunge.us/OWcH

ERROR: SQL: Abort due to constraint violation
ERROR: PVR - Load - failed to load channel groups

deleting pvr & epg db sometimes helped. If not then only a restart is helping. 

VDR with VNSI.

**Comment by stefansaraev** [comment]
pls report to kodi trac.

**Comment by chewitt** [comment]
closing as this should be reported upstream

**Comment by the-dreamer** [comment]
http://trac.kodi.tv/ticket/16031

;-)
