### ISSUE TITLE
Update u-boot for Cubox-i/HummingBoard

### ISSUE THREAD

**Issue by linux4kix** [OpenELEC/OpenELEC.tv#4190]
The latest u-boot has been updated to fix some memory issues regarding the GPU as well as add support for the 4GB version of the Cubox-i.  It would good to include it in the next OpenElec release.

https://github.com/SolidRun/u-boot-imx6

Thanks

**Comment by sraue** [comment]
done in https://github.com/OpenELEC/OpenELEC.tv/commit/95844b49a252d45676e19fff53aaa71cdcbafe1b and will be avaible with OpenELEC-6.0 beta2. many thanks
