### ISSUE TITLE
sidplay-libs PKG_URL is broken

### ISSUE THREAD

**Issue by dhead666** [OpenELEC/OpenELEC.tv#4191]
sidplay-libs PKG_URL is broken, ATM I'm not building OE so no PR.

https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/audio/sidplay-libs/package.mk#L25

**Comment by vpeter4** [comment]
Works at my place.

**Comment by dhead666** [comment]
alright, so it's just the quotation mark that's out of place :)

**Comment by vpeter4** [comment]
Didn't even noticed that. Because there is no space in actual URL it works.
But yes, one quotation mark is at wrong place.

**Comment by stefansaraev** [comment]
7f6b2a4cd854ab3ff53a0293051e85e41a305e5e
