### ISSUE TITLE
Request: pls update to latest VNSI-Server version (git hash 1c63a8a)

### ISSUE THREAD

**Issue by the-dreamer** [OpenELEC/OpenELEC.tv#4205]
reference http://forum.kodi.tv/showthread.php?tid=229990

**Comment by stefansaraev** [comment]
53b012d

you should not be using dummydevice. at all.

**Comment by the-dreamer** [comment]
thx. as written already in forum. if not using dummydevice i had problem with recordings and watching tv...

**Comment by stefansaraev** [comment]
you should not be using dummydevice. fix your tuners instead.

**Comment by the-dreamer** [comment]
i will look into this. 

As far as i can remember there was problems of selecting the next free tuner. either starting a recording did not start of "busy tuner" or vdr couldn't start a second recording because of "busy tuners" while i was watching. in one of this constellation vdr should start the recording because the usb tuner was actually free.

dummy device solved this. i have two usb 461e tuners.
