### ISSUE TITLE
Unable to switch sound to a bluetooth headset

### ISSUE THREAD

**Issue by swfiua** [OpenELEC/OpenELEC.tv#4210]
I have been able to use a bluetooth dongle to pair a Sony MDR ZX550BN headset with kodi running on OpenElec on a raspberry pi 2.

However, I cannot find a way to select the headset as the output.

I tried on a raspbian image too, but ran into problems with bluez and pulseaudio versions not being compatible in this respect.

On fedora I am able to pair the headset and use the gnome sound configuration to select the headset.  It gets a bit messy and periodically dies on me, but mostly works ok.   I also have to select A2DP rather than HSP/HFP.

I will post more info as I am able to gather it.

**Comment by stefansaraev** [comment]
[here](https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md)

bluetooth audio is not supported.

**Comment by swfiua** [comment]
Thanks -- pointed me at this in the wiki would be helpful -- I am trying to help here

http://wiki.openelec.tv/index.php/Bluetooth_Audio

Sounds like the real problem is like of bluetooth support in Alsa.  Good to know.
