### ISSUE TITLE
RPi/RPi2: Since 5.95.2 stereoscopic 3D TAB (top and bottom) broken - black picture. SBS works fine

### ISSUE THREAD

**Issue by infinity85** [OpenELEC/OpenELEC.tv#4213]
First of all: 
The below described issue doesn't occur on 5.95.1 build!

Using 5.95.2 on a Raspberry Pi 2 (also tested with RPi1 with same result). All 3D movies with TAB (top-and-bottom) encoding do have a black picture. SBS (side by side) 3D movies work perfectly. Note: But Audio, Subtitles (correctly in 3D TAB) and overlay OSD features are working properly while having black picture in background.

The behavior is like:

1. I start the movie
2. Kodi switches to preferred mode (TAB) [I set this automatic setting in preferences]
3. TV recognizes automatically the TAB flag and switches to TAB
4. The picture is completely black
5. But OSD and everything else is working and is 3D, so the TV switches properly to TAB, but just the picture is black,

Which files may I provide or what can I do to help you fixing this? I would like to help as best as possible :)

With best Regards
infinity

**Comment by popcornmix** [comment]
Is "Use full frame 3D modes" enabled in video/acceleration settings? If so try disabling.

**Comment by infinity85** [comment]
Thanks for the lightning fast reply :)

Enabling/Disabling of "Support MVC video (full frame 3D)" and/or "Use Full HD HDMI modes for 3D" does not change anything, unfortunately :/

**Comment by popcornmix** [comment]
See if you can spot anything that changes it from working correctly to working incorrectly.
I'd also be interested if the latest [Milhouse](http://forum.kodi.tv/showthread.php?tid=224025) build is more consistent.
That includes an update to the 3D switching logic as I had seen it behaving intermittently in some cases.

**Comment by infinity85** [comment]
Yep I noticed that you improved the overall 3D handling in Openelec 6. One thing that disturbed me since ever was the dropping out of 3D when I watched a movie in 24p (automatic framerate switch) opened an overlay-list of my movies (which stayed in 3D) and then closed this overlay. Then my TV switched off 3D and went to 60Hz menu-refreshrate of openelec. This meant, that I had to restart the movie to get back to stutterfree 24Hz playback in 3D.

Since I am using your 5.95.2 build the TV stays in 3D and 24p during these actions, which makes me very very happy, as this was the only glitch that I could find in my movie watching experience with OpenELEC. So i really appreciate your work and the newest aproaches :) Thanks a lot!!  

To my reported issue:
Well the more I think about it, the more I think it was something with my AV-Receiver/TV that made this issue, because it occured on an RPi1 as well as on an RPi2 with Beta 2 Build. But on the other hand it was working with Beta 1 and not on Beta 2 afterwards during testing. It's a bit strange... but now it works.

**Comment by infinity85** [comment]
so... I decided to try your Milhouse build: #0623, 23-Jun-2015: RPi2 ... and now I was able to reproduce the issue!

I get a black screen as long as the subsetting "Use Full HD HDMI modes for 3D" ist enabled. Having just "Support MVC video (full frame 3D) enabled does work properly.

But I also noticed another issue (worse behavior than before): Whenever I stop a movie (not pause) or when the movie ends, then my philips LCD (2012 model) makes a broken picture for round about 3 seconds. I took a picture of it:
https://www.dropbox.com/s/h9h8lugih49e14t/IMG_20150624_205227.jpg?dl=0

The thing is, that this occurs since I can think of OpenELEC. But with the new build it takes longer... as I described ~3-5s and before this build it took about 1-2 seconds. 

If I switch from 3D to 2D via TV remote control this doesn't happen, so I think that this is due to the "forced" switching off 3D via stopping the video or because of hitting the end of the file.
Actually I thought that this behavior is because of my TV (as Philips have a lot of software glitches) but now I saw that your milhouse build has a negative effect on this behavior, so may be there is even a more gentle way to get the TV to know about the end of a 3D, thus switching it off smoothly.

**Comment by infinity85** [comment]
Just wanted to confirm, that your recent testbuilds solved the issue (

#0630, 30-Jun-2015: 
The blackscreen with TAB-3D, while having subsetting "Use Full HD HDMI modes for 3D" enabled  is solved in your recent builds! Fantastic job... now everything works like a charm :)

**Comment by chewitt** [comment]
I'm closing this ticket due to ^^ resolved comment above. Thanks.
