### ISSUE TITLE
[RPI 1] Subtitles won't show if buffermode = 1

### ISSUE THREAD

**Issue by Ulrar** [OpenELEC/OpenELEC.tv#4216]
Hi,

I've been having this problem for years, and never figured out where it was comming from.
Just found a post on the kodi forum of a guy with the same problem saying it's comming from buffermode, tried it and it looks right (http://forum.kodi.tv/showthread.php?tid=186022).

As long as buffermode is set to 1 in the advancedsettings.xml file the external srt file rarely work (but sometimes they do). With buffermode to 0 it seems to always work. I usually use FTP, and everyone generally says that's the problem, so here is a debug log with buffermode set to 1 and I'm trying to use local subtitles stored in /storage/videos/video.en.srt : http://sprunge.us/iHGc

As you can see I go manually select the subtitle file and I get : 
> CFileCache::Open - opening </storage/videos/video.en.srt> using cache
> Open - Unhandled exception
> Open - Error opening /storage/videos/video.en.srt
> OpenStream - Unable to create subtitle parser

Looks like it's trying to get the file from cache but it hasn't been cached maybe ?
I get the exact same error if I'm playing files across FTP, SMB or whatever share you want. MKV files with included subtitles track do work perfectly though.

Thanks !

**Comment by stefansaraev** [comment]
should be reported upstream.

**Comment by chewitt** [comment]
I'm closing the ticket because this is not an OE specific issue. It should be reported to Kodi devs via the Kodi forums.
