### ISSUE TITLE
Issue + Question / RPI 2 + OE v5.95.2 / Remote Control

### ISSUE THREAD

**Issue by Vodka2014** [OpenELEC/OpenELEC.tv#4218]
Hi All

I have tried to updated and it just sits on the logo screen of Kodi. Is there something I need to change or remove to get this to work.

I rolled back to v5.0.8 and it is working 100%.

Also what is the best Remote to use for this unit that will work with the new version.

Thanks

**Comment by chewitt** [comment]
This is a development bug tracker. User support is provided via the forums.
