### ISSUE TITLE
5.95.2: RPi2: USB Audio issues - HDMI used when not selected

### ISSUE THREAD

**Issue by ant-thomas** [OpenELEC/OpenELEC.tv#4224]
Currently running 5.95.2 on an RPi2.

I have a USB soundcard CM108 based
`Bus 001 Device 005: ID 0d8c:013c C-Media Electronics, Inc. CM108 Audio Controller`

In System -> Audio Output -> Audio Output Device is changed to the ALSA: USB PnP Sound Device Analog.

When playing any videos or LiveTV the USB device isn't used and the audio is played through HDMI.
When playing music the audio is played through the USB device.

If I change it to Pi Analogue the audio doesn't come out of the HDMI any more.

Debug log - http://sprunge.us/BeSH

**Comment by popcornmix** [comment]
OMXPlayer doesn't support ALSA audio devices, but is being used.
Make sure you have MMAL enabled in video/acceleration settings. I suspect you have disabled that.

**Comment by ant-thomas** [comment]
Spot on. Disabled OMX and enabled MMAL and it's working.

It's also working well with the Dual Audio Output build to output across both HDMI and USB which was my eventual aim. Thanks.
