### ISSUE TITLE
vdr-plugin-xvdr can't open large files on RPi2

### ISSUE THREAD

**Issue by frankr612** [OpenELEC/OpenELEC.tv#4229]
Watching recordings using xvdr will only work with file sizes <2GB on Rpi2. Was able to fix it by changing the Makefile of the vdr-plugin-xvdr:

DEFINES += -DPLUGIN_NAME_I18N='"$(PLUGIN)"' -DXVDR_VERSION='"$(VERSION)"' -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE

**Comment by chewitt** [comment]
closing due to #4230
