### ISSUE TITLE
Openelec partition too small

### ISSUE THREAD

**Issue by thelightning87** [OpenELEC/OpenELEC.tv#4232]
Hello,

I manage several OpenElec setups at friends. I can do this quite easily because i just create a Kodi setup, zip the profile and put the zip on the Openelec installer USB disk.
After install, i remove /storage/.kodi and unzip the file from the USB stick to /storage.

With latest OpenElec versions, the FAT partition has been limited to only 255MB. Not leaving enough space for my profile causing me to have to carry other storage device for the profile and not bieng able to script anything handy.

Is there a specific reason the partition has been limited?

**Comment by chewitt** [comment]
Closing because user support is provided via the forums. This is a development team bug tracker.

**Comment by vpeter4** [comment]
You can put backup.tar.bz2 or backup.zip on installer disk and it will be automatically unpacked when installed to target disk.

https://github.com/OpenELEC/OpenELEC.tv/blob/05d1c76b9f6ed9ec24d3ea872d7f931e1e17b5fd/packages/tools/installer/scripts/installer#L359

**Comment by thelightning87** [comment]
Thank you for the information vpeter4.
Unfortunately, the FAT partition is still to small (only 150MB or so available) and my profiles are almost 400MB.
