### ISSUE TITLE
Intel NUC DN2820FYKH: A start job is running for OpenSSH server daemon (1min30sec)

### ISSUE THREAD

**Issue by thelightning87** [OpenELEC/OpenELEC.tv#4233]
Openelec 5.95.2 running fine on a laptop of mine.
Used the same USB stick installer on my Intel NUC. After install the system boots and shows the following message:

A start job is running for OpenSSH server daemon (1min30sec)

After the timer, Kodi continues to boot but there is no SSH access (ssh daemon not running)

Workaround:
Install Openelec without SSH
Disable wireless networks from the Openelec config tool
Enable SSH

Oddly; When SSH is enabled during install, Wireless networks is disabled by default.

Only thing i can find that might be related:
dmesg: 
[    3.368433] wl: module license 'MIXED/Proprietary' taints kernel.
[    3.368439] Disabling lock debugging due to kernel taint

**Comment by chewitt** [comment]
the wl messages are irrelevant.

**Comment by thelightning87** [comment]
Same problem is present in 5.9.3

Also: SSHd seems to be starting way to late.
In my autostart.sh file i have an SCP command which worked fine for Openelec 4.0.3 but in 5.95.3 the screen shows a cursor for almost 5 minutes and then continues to boot. The SCP command never ran fully. As soon as i remove the command the system starts again right away.

**Comment by thelightning87** [comment]
Error from journal:

Jul 17 19:25:26 Mediacenter sh[483]: ssh_dispatch_run_fatal: Connection to 1.2.3.4: Broken pipe

**Comment by chewitt** [comment]
I'm closing this ticket - please open a topic in the forums for further support providing a 'paste' URL link to a copy of the journal from boot, and a 'paste' link to your autostart.sh
