### ISSUE TITLE
[5.0.8 RPi2/ARMv7] Wait for USB HDD to spin up on boot

### ISSUE THREAD

**Issue by abdulmueid** [OpenELEC/OpenELEC.tv#4241]
I have a Raspberry Pi 2 with a 5TB Seagate Expansion Drive with it's own power. Pi2 is powered by a 2A power adapter.

I have a small 16GB EXT4 partition on my external drive that I would like to mount at /storage. After changing the commandline.txt to use the external drive partition, I get the following error on boot and get thrown into debugging shell:

**Error in mount_storage: mount_common: could not mount UUID=xxxx....**

Once in the debugging shell, I can mount the drive at /storage just fine and continue running Kodi with it, just like I want. But I would like to automate this and not attach a keyboard to the device every time I reboot.

Now, the drive is one of those power efficient ones which only start spinning up once USB ports are ready. I believe there are other drives from Seagate and Western Digital that behave the same way.

I have tried the following methods to delay the boot so the drive can get a chance to initialize:
1. Added *rootwait* and *rootdelay* parameters to commandline.txt - didn't work
2. Added *boot_delay* to config.txt - didn't work

If the bootloader can somehow wait a few seconds before trying to mount the drives, it would solve this problems.

Any suggestions, or possible fixes I can look into?

**Comment by chewitt** [comment]
Closing because user help is provided via the forums. This is a development bug tracker.
