### ISSUE TITLE
Need to be able to set IP, mask and gateway on Wireless Networks

### ISSUE THREAD

**Issue by Maxispark** [OpenELEC/OpenELEC.tv#4242]
I use OpenELEC on a Raspberry Pi 2.

I have a Wifi dongle plugged in and I am unable to connect because I cannot set a static IP address as required by my network. 

On attempting connection State goes to association then configuration and then fails.

Bottom line - I don't want to mess with an entire network to get one device working on DHCP and I don't want to have to drag 10m of cabling from my file server to the Pi.

**Comment by stefansaraev** [comment]
I closed this because:
1. you've been told in irc, that your use case is not, and will not be supported.
2. you ignored our [guidelines for contributing ](https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md)
