### ISSUE TITLE
distutils Python package removal can break Python modules

### ISSUE THREAD

**Issue by trisk** [OpenELEC/OpenELEC.tv#4243]
I understand that the standard `distutils` Python package was removed in 5.0, presumably to prevent people from attempting to use it to install modules manually and encourage add-ons to package their dependencies correctly.
It turns out the `distutils.util` utility functions are used by some Python modules at runtime (for non-install purposes) and this means any Kodi add-ons using these modules must be modified specifically for OpenELEC, replacing functionality from the `distutils.util` API. It adds unnecessary maintenance overhead for writing add-ons.

I suggest keeping at least a stub `distutils.util` module to preserve compatibility with the distutils API.

**Comment by stefansaraev** [comment]
really? no add-on should use distutils at runtime.

can you give an example of such addon ?

**Comment by trisk** [comment]
The add-ons I've seen that depend on `distutils.util` are AUDO and the Google Music add-on. Both have packages that include the package resources API from setuptools. That implementation uses `distutils.util.get_platform` (the semantics are different from `sys.platform`).

**Comment by stefansaraev** [comment]
using distutils.util.get_platform is pure bull**** if you ask me. 

up to @sraue if he agrees to revert distutils. I dont mind.

**Comment by trisk** [comment]
Just removing the [`distutils.core` module](https://docs.python.org/2/distutils/apiref.html) should be enough to prevent `setup.py` and `easy_install` from being used.
```diff
diff --git a/packages/lang/Python/package.mk b/packages/lang/Python/package.mk
index c32acd0..2124b35 100644
--- a/packages/lang/Python/package.mk
+++ b/packages/lang/Python/package.mk
@@ -136,7 +136,7 @@ makeinstall_target() {
 }
 
 post_makeinstall_target() {
-  EXCLUDE_DIRS="bsddb curses idlelib lib-tk lib2to3 msilib pydoc_data test unittest distutils"
+  EXCLUDE_DIRS="bsddb curses idlelib lib-tk lib2to3 msilib pydoc_data test unittest"
   for dir in $EXCLUDE_DIRS; do
     rm -rf $INSTALL/usr/lib/python*/$dir
   done
@@ -149,6 +149,7 @@ post_makeinstall_target() {
   rm -rf $INSTALL/usr/lib/python*/config/install-sh
   rm -rf $INSTALL/usr/lib/python*/config/makesetup
   rm -rf $INSTALL/usr/lib/python*/config/python.o
+  rm -rf $INSTALL/usr/lib/python*/distutils/core.*
 
   if [ ! -f $INSTALL/usr/lib/python*/lib-dynload/_socket.so ]; then
     echo "sometimes Python dont build '_socket.so' for some reasons and continues without failing,"                                              
```
