### ISSUE TITLE
OpenELEC 6.0 Beta 2/3/4 crashes with hardware acceleration enabled (intel chipset)

### ISSUE THREAD

**Issue by slipx06** [OpenELEC/OpenELEC.tv#4245]
If I enable hardware acceleration kodi restarts itself every time I try play video content. The audio starts and the screen goes black and then kodi crashes. I'm using an onboard Intel chipset. If I disable acceleration videos play but I notice occasional stuttering. No issues with the current stable build, same problem with beta 2.

Crash log pastebin.com/mNSNGsDT
Debug log pastebin.com/DjJLkTVV

**Comment by slipx06** [comment]
Maybe some more information will help.

Dmesg output

[   65.463500] [drm] GPU HANG: ecode 5:0:0x9ffdffff, in kodi.bin [641], reason: Ring hung, action: reset
[   65.463502] [drm] GPU hangs can indicate a bug anywhere in the entire gfx stack, including userspace.
[   65.463503] [drm] Please file a _new_ bug report on bugs.freedesktop.org against DRI -> DRM/Intel
[   65.463504] [drm] drm/i915 developers can then reassign to the right component if it's not a kernel issue.
[   65.463505] [drm] The gpu crash dump is required to analyze gpu hangs, so please always attach it.
[   65.463507] [drm] GPU crash dump saved to /sys/class/drm/card0/error
[   66.061518] drm/i915: Resetting chip after gpu hang
[   72.481807] [drm] stuck on render ring
[   72.485690] [drm] GPU HANG: ecode 5:0:0x9ffdffff, in kodi.bin [641], reason: Ring hung, action: reset
[   72.486050] [drm:i915_set_reset_status] *ERROR* gpu hanging too fast, banning!
[   73.292074] drm/i915: Resetting chip after gpu hang
[   73.573411] DVDPlayerVideo[852]: segfault at 11 ip 00007f3af7a6a266 sp 00007f3a5da39850 error 4 in libc-2.21.so[7f3af79f2000+194000]

**Comment by slipx06** [comment]
GPU crash dump https://dl.dropboxusercontent.com/u/9826301/error

**Comment by fritsch** [comment]
bugs.freedesktop.org, please -> this is clearly a kernel / mesa / drm
whatever bug

2015-08-25 23:17 GMT+02:00 slipx06 <notifications@github.com>:

> GPU crash dump https://dl.dropboxusercontent.com/u/9826301/error
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4245#issuecomment-134744393>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by slipx06** [comment]
I've tried running on multiple kernels (4.2rc8, 4.1, 4.01, 3.x) and I still get the crash with the new kodi builds. The last official openelec release and the last snapshot http://snapshots.openelec.tv/OpenELEC-Generic.x86_64-devel-20150503135715-r20764-gbfd3782.tar work fine. Are you sure this is kernel related? Any other advice on how to try trouble shoot this?

**Comment by slipx06** [comment]
15.1 running on kodibuntu runs without any crashes. This seems openelec specific

**Comment by qods** [comment]
Could you make a downgrade of your kernel version to the kernel version that is been used in kodibuntu and test if you still have the problems in openelec but not in kodibuntu when kernel version is just same?

**Comment by chewitt** [comment]
does this issue still exist on 6.0.0?

**Comment by chewitt** [comment]
Closing due to lack of update. If this is still an issue once OE 6.0.1 is released please create a forum thread (this is not a help channel) and/or update to a milhouse Jarvis build. Thanks.
