### ISSUE TITLE
Xorg: XSERVTransTransNoListen: unable to find transport: tcp

### ISSUE THREAD

**Issue by chewitt** [OpenELEC/OpenELEC.tv#4251]
I'm not sure if this is a problem but in looking at the systemd log I noticed the following error messages appearing in 5.95.3 builds. I see it on two systems (Ultra2 and ATV) which use nvidia GPU's (one with 352.21 and the other with 304.125):

Jul 27 06:12:25 Xtreamer Xorg[489]: ### starting Xorg with ' vt01 -s 0 -noreset -allowMouseOpenFail -config /storage/.config/xorg.conf -ignoreABI' ###
Jul 27 06:12:25 Xtreamer systemd[1]: Started configure Xorg Server for nvidia.
Jul 27 06:12:25 Xtreamer xorg-launch[438]: Starting Xorg server with: "/usr/bin/Xorg vt01 -s 0 -noreset -allowMouseOpenFail -config /storage/.config/xorg.conf -ignoreABI"_XSERVTransTransNoListen: unable to find transport: tcp
Jul 27 06:12:25 Xtreamer xorg-launch[438]: Failed to disable listen for tcp transport

I did a little Googling but didn't spot anything obvious or comprehensible. Please close the ticket if this is something unimportant that can be be ignored.

**Comment by stefansaraev** [comment]
this is not a problem
it happens because there is "-nolisten tcp" passed by xorg-launch-helper as xorg start parameter, but xorg is compiled with --disable-tcp-transport

**Comment by stefansaraev** [comment]
http://cgit.freedesktop.org/xorg/xserver/commit/?id=cc59be38b7eff52a1d003b390f2994c73ee0b3e9

so, it's a feature :)
