### ISSUE TITLE
RPi: ffmpeg failing to build, libdcadec not found

### ISSUE THREAD

**Issue by cpswan** [OpenELEC/OpenELEC.tv#4257]
Here's what I'm seeing when I `PROJECT=RPi ARCH=arm make release` on the latest commit:

```
  INSTALL    mediacenter (target)
      BUILD    ffmpeg (target)
ERROR: libdcadec not found
 
If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
make: *** [release] Error 1
```

The last build that worked was 1180ed3, so something that changed since then (my script had been hanging waiting for user input, and it took me a while to notice). I'm guessing 477d15f is the culprit.

**Comment by dolorosus** [comment]
For me this was gone after clean and starting the build from scratch:

PROJECT=RPi ARCH=arm make clean
PROJECT=RPi ARCH=arm make release
