### ISSUE TITLE
xvdr is gone without a good alternative

### ISSUE THREAD

**Issue by kenzodeluxe** [OpenELEC/OpenELEC.tv#4258]
I am using OpenElec for streaming of TV data over the network (not locally). Not sure whether VNSI is a good alternative when used via loopback, however in my deployment it s***s.
I was also a little surprised since I couldn't find any hint that pointed me to any good reason why xvdr should be discontinued; is it due to maintenance overhead? Would it help to have a fork with xvdr included where main pulls from?

**Comment by kenzodeluxe** [comment]
Not even a short comment?

**Comment by stefansaraev** [comment]
nope. not even a short comment. this is a bugtracker. and you are not reporting a bug.

**Comment by kenzodeluxe** [comment]
Well, that's a matter of definition. Where would you like me to report this instead?

**Comment by stefansaraev** [comment]
questions you can ask in irc or forum. I dont want you to report this anywhere. because it's not a bug.

**Comment by stefansaraev** [comment]
here a [definition](https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md)
