### ISSUE TITLE
Intel i3-3225 (HD4000) and PCH transcoder A FIFO underrun

### ISSUE THREAD

**Issue by Monter** [OpenELEC/OpenELEC.tv#4274]
After the update OpenELEC v4 (XBMC) to v5.0.8 (Kodi) and the processor G530 to i3-3225 while turning the player I get the error "PCH transcoder A FIFO underrun." i3-3225 has a built-HD4000 graphics card. I searched Google and OpenELEC forum but did not find a solution. I don't have a TV tuner. Despite the error playback is operating normally. How can I fix this error?

**Comment by fritsch** [comment]
Fix: Ignore it.

**Comment by Monter** [comment]
Hmmm. I found information suggesting that the problem is the kernel 3.15: https://forum.manjaro.org/index.php?topic=15083.0
After changing OpenELEC on the beta version 5.95.3 problem persists despite the fact that there is a lot newer kernel.
In the Linux 3.14.x series this is probably not happening. Which version OpenELEC contains the 3.14 kernel and where can I download it?

**Comment by fritsch** [comment]
A 3.14 kernel won't even run correctly on your hardware ... you need at least 3.18.3 to not run into the GPU hangs ...

**Comment by chewitt** [comment]
I'm closing this down as part of a general cleanup of tickets with no specific issue or update. Thanks.
