### ISSUE TITLE
Auto fetching creates corrupted image files in cache

### ISSUE THREAD

**Issue by Bonhomme08** [OpenELEC/OpenELEC.tv#4278]
So, I'm having this problem since a while and I was wondering if I was alone.

I've few banners, posters, fanarts and episode thumbnais that just do not appear. So, I investigated a bit for fun. What I found is: some files in /storage/.kodi/userdata/Thumbnails/... are corrupted. I can not even open them with any image viewer on Windows. To solve the problem, I can go on thetvdb.com, find the right image, manually replace it and reboot. Obviously. I won't do it because I've pretty a lot of files to do so.

I've Kodi on a Surface and it works perfectly with all the images. So, I assume the problem is in OpenElec and not Kodi.

The problem only happens with my Animes. I know the community is pretty elitist on the images quality. So may be the problem is from some uncommon image compression or I don't know.

I've even a sample for you guys:

Corrupted images:
http://thetvdb.com/banners/episodes/82099/374291.jpg
http://thetvdb.com/banners/episodes/85249/501751.jpg
http://thetvdb.com/banners/episodes/263688/4427023.jpg
http://thetvdb.com/banners/episodes/272074/4629083.jpg
http://thetvdb.com/banners/episodes/279804/4833785.jpg

Fine Images
http://thetvdb.com/banners/episodes/188551/2771921.jpg
http://thetvdb.com/banners/episodes/219181/3433451.jpg
http://thetvdb.com/banners/episodes/240291/3905081.jpg
http://thetvdb.com/banners/episodes/267440/4516067.jpg
http://thetvdb.com/banners/episodes/272074/4671255.jpg

I must admit that I am confused of what could cause that the image works or not...

Anyway, any pointers about all this?

**Comment by MilhouseVH** [comment]
You can re-cache artwork using the [Texture Cache Maintenance Utility](http://forum.kodi.tv/showthread.php?tid=158373) - if the re-cached artwork continues to show evidence of corruption then that might be interesting and worthy of further investigation, but discussion of your issue shouldn't take place on github as this is a development team bug tracker.

Start a new thread in the OpenELEC or Kodi forums, as this is where end-user support issues are handled.

**Comment by chewitt** [comment]
closing .. please take discussion to forums
