### ISSUE TITLE
latest openssh breaks ssh login

### ISSUE THREAD

**Issue by mcaptur** [OpenELEC/OpenELEC.tv#4280]
openssh: update to openssh-7.0p1 

can no longer login via ssh using root/openelec
login as: root
root@192.168.1.7's password:
Access denied
root@192.168.1.7's password:
Access denied

**Comment by MilhouseVH** [comment]
Root password disabled.
Also dss keys disabled.

The following patch (from @stefansaraev on #irc) should fix it:

http://sprunge.us/ReNj
