### ISSUE TITLE
umlaute not working on openelec 5.0.8 on rpi2 with logitech k400

### ISSUE THREAD

**Issue by chiefdome** [OpenELEC/OpenELEC.tv#4282]
Hi I just saw there was an invalid labeled isssue for openelec 5.0.3.
I can only say that there is no change at all with the issue of not striking umlaute for the logitech k400 keyboard with german layout. If you press the letters ä  ö or ü they arent showing up instead the american layout is involved and [ ] and @ is showing in the search bar by pressing it.
I ve read that with the use of an rpi2 no xorg-server is involved to change the layout.
So it must build into the kodi-application. I really tried all settings to get it therefore i used global german settings, the german layout on keyboard settings and the layout of the virtual keyboard which shows the umlaute. Would like to get involved to code the specific problem asap.
Therefore I need help with the developers which solutions they would recommend.

**Comment by stefansaraev** [comment]
and this should be labeled invalid, too ;)

**Comment by qods** [comment]
This have been fixed in recent OpenELEC 6.0 version. The on-screen keyboard language can be configured in the Kodi settings. The physical keyboard layout have to be configured in Settings->OpenELEC.

**Comment by chewitt** [comment]
is this still an issue on OE 6.0.0?

**Comment by chewitt** [comment]
Closing due to lack of update. Thanks.
