### ISSUE TITLE
6.0 Beta 4: Dolby Digital Passthrough broken

### ISSUE THREAD

**Issue by the-dreamer** [OpenELEC/OpenELEC.tv#4293]
kodi.log Beta 4: http://sprunge.us/EgCW
aplay -l Beta 4: http://sprunge.us/MAOQ
dmesg Beta 4: http://sprunge.us/UaMA

Beta 2 has no problems:
kodi.log Beta 2: http://sprunge.us/SHOV
aplay -l Beta 2 http://sprunge.us/TjLX
dmesg Beta 2 http://sprunge.us/RdeJ

**Comment by the-dreamer** [comment]
btw: with nvidia it is working.

**Comment by chewitt** [comment]
closing old tickets with no update.. should the issue still exist on a current release please start a forum thread, thanks.
