### ISSUE TITLE
Openelec 5.95.3 - CEC loose connection with LG TV - (libcec 3.0.1 seems to solve the issue)

### ISSUE THREAD

**Issue by tillstaff** [OpenELEC/OpenELEC.tv#4294]
Hello,
I'm using Openelec 5.95.3 on my Raspberry Pi 2 and I have some trouble with CEC. I have a LG TV and it's working fine with a fresh boot. But after two days of inactivity, the Raspberry can't be seen anymore by the TV, so I have to reboot the Raspberry every time I don't use it too often.
After investigating, I found that libcec 3.0.1 solve this bug. So I installed an Openelec testbuild with libcec 3.0.1 and all was working ok. (http://forum.kodi.tv/showthread.php?tid=231092&pid=2044074#pid2044074)
I just installed Openelec 5.95.4 but I expect the same behavior, so could you update libcec version in the next beta?
Thanks in advance
Tillstaff

**Comment by qods** [comment]
OpenELEC would bump to anything newer then 3.0.1 when its released.

You can read about that here: https://github.com/OpenELEC/OpenELEC.tv/pull/4362

**Comment by attaxia** [comment]
I tried this with 3.0.1 using Rasplex (based on OpenELEC). It does not fix the issue. For my TV (LG 49LB550V) this is a 100% way to reproduce the issue:

1. Use OpenELEC/Rasplex with HDMI-CEC
2. Switch to TV channel (issue does not occur if TV is left on HDMI channel)
3. Switch TV off (standby)
4. Wait 15 minutes
5. Turn on TV
6. Switch to HDMI channel

Now HDMI-CEC remote control forwarding will not work. Turning Simplink on and off in the settings will fix the issue without reboot.

**Comment by dcolens** [comment]
Can you try launching cec-client while kodi is running on the same box ? For me it somehow helps my TV to connect.

Did

**Comment by attaxia** [comment]
Hi,

Yes I did, but it didn't help. I did see the information flow between tv and client though.

**Comment by sraue** [comment]
please report to https://github.com/Pulse-Eight/libcec
