### ISSUE TITLE
BluRay Menu Errors

### ISSUE THREAD

**Issue by islipfd19** [OpenELEC/OpenELEC.tv#4299]
When attempting to play a BluRay DVD over NFS (unencrypted BluRay) having 'Show Blu-Ray Menu' selected under 'System' > 'Video' > 'Discs', play back stops when audio is supposed to start. This is a compiled build from the latest master - r21241-g494f51d

http://filebin.ca/2EGronXa4EC1

**Comment by islipfd19** [comment]
The original title didn't seem to fit so I've updated the issue with the new one. I've also provided more logs. The original logs were attempting to play the BluRay menu for 'Band Of Brothers' which would be quite different than the standard movie. The new log tries to play the BluRay menu from 'Start trek' but end and continues playing to the next available DVD which happens to be 'Star Trek Into Darkness'. The log once again shows ALSA errors, but not be related...? Line 15582 to 15905 shows what's happening.

http://filebin.ca/2F3Z240Pcn0m

**Comment by islipfd19** [comment]
After looking through the latest logs and trying to make sense of things. I found that CDVDInputStreamBluray was looking for two files in the AACS directory of the movie; Unit_Key_RO.inf and MKB_RO.inf. I created the first file it called for "Unit_Key_RO.inf" and the Bluray menu still did not play. I added the second file (also empty) "MKB_RO.ing" and Kodi crashes and restarts. Not sure what should be in those files which may be causing Kodi to crash.

I should also mention that this and all my DVD's/BluRay's are unprotected.

http://filebin.ca/2F3ndoASQUPh

**Comment by islipfd19** [comment]
Copying the original files Unit_Key_RO.inf and MKB_RO.inf from the Disc to the proper directory where the movie is stored didn't help either.

I'm now currently building the latest version but with 0.6.1 version of libbluray to determine with anything was introduced between versions 0.6.1 and 0.8.1. As I recall, BluRay menus worked fine in OE 5.0.8.

**Comment by islipfd19** [comment]
Well, alright; the latest build from the master tree with libbluray 0.6.1 did not resolve the issue of the BluRay menus showing. I tried both scenarios, with and without AACS protected content. I did however find this error in the log ''14:02:00 238.225479 T:1824519232   DEBUG: CDVDInputStreamBluray::Logger - bluray.c:1246: Title 1: BD-J not compiled in
14:02:00 238.225555 T:1824519232   DEBUG: CDVDInputStreamBluray::Logger - bluray.c:2870: Can't play BD-J title 1"

Looking at the requirements for each package when I googled the error, the package version are greater than what they need to be but looking into it further, it seems that java must be installed... Well this is a bummer.

**Comment by stefansaraev** [comment]
bdj is not supported.

**Comment by islipfd19** [comment]
Yea, I see that. Is this planned in the future at some point? Is it even possible?

**Comment by stefansaraev** [comment]
I dont think so.

**Comment by islipfd19** [comment]
OK, is it a limitation on java or just not included during the build process? If it's a java limitation, I can understand because of licensing of the embedded version. If it's because it isn't included in the build process, I'd like to attempt to build that supports it. If not either of the two, I'll just move along; unfortunately this is just a bad end user experience.

**Comment by stefansaraev** [comment]
move along. it's not bad ux. users better avoid bluray at any cost. or go ubuntu, I dont really care. I am done with this.
