### ISSUE TITLE
LiveTV crash with default RPi2 settings

### ISSUE THREAD

**Issue by CvH** [OpenELEC/OpenELEC.tv#4300]
Fresh install of OE 6.0 b4 RPi2, installed Tvh server + pvr.hts. (vdr + vnsi identical)
After playing TV for ~<30secs picture + kodi freeze, audio keeps playing.

***WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer***

This behaviour which could easily reproduced even with the latest Millhouse jarvis builds (MMAL is default).

If I switch from MMAL to omxplayer at settings everything works like expected.
I don't know if this is the expected behaviour.

I makes no difference if I play interlaced videos or not.
log http://pastebin.com/JCKghPL1

if more logs (special logs ...) are needed just ask

**Comment by popcornmix** [comment]
Can you reproduce the problem with a recording? Is so a sample file would be useful.

**Comment by CvH** [comment]
To double check that I made no "mistake" I completely delete the sd card and installed the redownloaded 5.95.4 image again (Win32DiskImager -> sd card). I installed only the necessary addons and paste the vdr conf in to be able to watch tv. Whole video/audio/system settings set to default.

The same problem as before. If Kodi crash the recordings are fine (beside the artefacts due to errors in stream which also only occur at the rpi2 - tvh/vdr same problem). 
I got Sat>IP box which is reported working without any problem (identical setup) at the RPi2 also with all 4 tuners activated at Tvh -> more then 1 tuner creates a endless error stream at my RPi2 (is working without any problem at my 2 other OE x86).

I recognized that every crash is at such an error at the stream but it won't crash every time at the same position. [Recording + debug link](https://onedrive.live.com/redir?resid=824E2A794E35269F!5152&authkey=!ALpkgzYzXiA74ZM&ithint=folder%2c)

If I watch the recording it looks like it doesn't crash, If I seek at the stream it happens relatively quick.

(I forgot about boblight, but it changes nothing if I delete it)

**Comment by popcornmix** [comment]
Are you saying the crash only occurs with boblight enabled?

**Comment by CvH** [comment]
After disabling ***only*** boblight the tv streams didn't have the streaming errors any more also MMAL works like expected. I had the same boblight conf at my normal htpc and these was working for years (the RPi2 is a interim replacement due a hardware failure at the x64 htpc). Boblight (from OE repo) is also not working at all at the RPi2 for me.

**Comment by polojoe** [comment]
I've same problem with livetv on some channels when backend (tvheadend or vdr) on same rpi 2. When I was using the same configuration on x86_64 machine, there were no problems. I'm not using boblight at all. Could it be a usb limitation on pi?

**Comment by chewitt** [comment]
@CvH - can we close this ticket?

**Comment by CvH** [comment]
@chewitt it looks like it is a boblight problem but it is unclear (looks like only very few with that problem)

**Comment by InuSasha** [comment]
I have find out: the boblight-client-addon has a memory leak, when the boblight backend is not available.
After deinstall ot the client-addon and reboot, it was working fine on my systems.
