### ISSUE TITLE
6.0 Beta 5 Cubox-i CEC not working

### ISSUE THREAD

**Issue by buliwyf42** [OpenELEC/OpenELEC.tv#4302]
After Updating to 6.0 Beta 5 on my Cubox-i CEC is not working anymore with my Samsung TV.

**Comment by manofthepeace** [comment]
Cec working for me on 6.0 Beta5 with cubox-i4 pro + samsung tv.

**Comment by chewitt** [comment]
closing old tickets with no update.. should the issue still exist on a current release please start a forum thread, thanks.
