### ISSUE TITLE
Mouse Wheel for RPi (upstream kodi commit # included)

### ISSUE THREAD

**Issue by yhdezalvarez** [OpenELEC/OpenELEC.tv#4303]
Mouse wheel is not supported as 6.0 beta5. There is a commit in kodi's github page (https://github.com/xbmc/xbmc/commit/061c93608091ee51bcfeb03bd4016e742acf26f7) fixing the use of the wheel in X11-less linux distros... Said fix was done on jul 10. At the moment it doesn't seem included in the latest beta. (no change show for xbmc/input/linux/LinuxInputDevices.cpp in https://github.com/OpenELEC/OpenELEC.tv/compare/5.95.1...5.95.5#files_bucket)
Will it be included in OpenELEC 6.0?

**Comment by popcornmix** [comment]
That should be present on Pi from isengaurd_rbp_backports branch:
https://github.com/OpenELEC/OpenELEC.tv/commit/6c82a7ffbb5b8543830e59a7647abf518bd19376#diff-3ce22f6305254f75b2f60d3d7ec6cbb4R5723
Have you tested it?

**Comment by yhdezalvarez** [comment]
No I haven't. How should I test it?

**Comment by popcornmix** [comment]
I assume you have tested with the 5.95.5 build?
It should work on spinners in UI and lists with scroll bars.

If it doesn't work on 5.95.5 build, then have you had it working on any other build (e.g. a nightly/Milhouse build)?

**Comment by popcornmix** [comment]
I've just done a clean install of 5.95.5 and mouse scroll wheel works.

**Comment by yhdezalvarez** [comment]
No, I haven't tested on 5.95.5... last build I tested was 5.95.2, (from before Jul 10). But I looked up on the changes between both versions (https://github.com/OpenELEC/OpenELEC.tv/compare/5.95.2...5.95.5#files_bucket, 222 files changes) and ... oops, you are right... the change was hidden behind a view button... I will download the image tonight I will tell you tomorrow...

**Comment by stefansaraev** [comment]
@yhdezalvarez 

> No, I haven't tested on 5.95.5... last build I tested was 5.95.2, (from before Jul 10)

dude. you are on github..

https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md

**Comment by yhdezalvarez** [comment]
@popcornmix. 
You are right. It's working ok. I even changed the keymaps to use the wheel to change volume and it works. Thanks... And I am sorry for my mistake ;-)

@stefansaraev
Sorry dude ;-) I use git at work and somehow I assumed that comparing versions on github worked like git diff (without hiding big changes behind a button, that is)... Now I know better.
