### ISSUE TITLE
Typo in german locale

### ISSUE THREAD

**Issue by thegcat** [OpenELEC/OpenELEC.tv#4304]
I noticed a typo in the setup wizard for the current stable in the german help text.

On the very first screen, "Assisitent" should be "Assistent".

A quick GitHub search in this repo yielded no result, so I'm not quite sure where I could fix this and submit a pull request. Could anyone point me in the right direction? Thanks!

**Comment by eldingraho** [comment]
if it's in the setup wizard it should be here:
https://github.com/OpenELEC/service.openelec.settings/blob/master/language/German/strings.po

seems fixed.

**Comment by thegcat** [comment]
It seems it is, thanks!
