### ISSUE TITLE
Miracast support

### ISSUE THREAD

**Issue by RichardEb** [OpenELEC/OpenELEC.tv#4306]
I would like to see miracast support included in the low-level drivers of OpenELEC if at all possible. There is a github repo here https://github.com/codemonkeyricky/piracast that got it working on raspbian. I have a RPi 2 with the WiFi adaptor the project requires and I would be happy to use this feature.

This would be nice thing for Rasplex as well. See: https://github.com/RasPlex/RasPlex/issues/359

**Comment by RichardEb** [comment]
Why the hell is the issue closed without any comment?

**Comment by fritsch** [comment]
No interest in a protocol where not a single working implementation exists and most driver don't want to cooperate. https://archive.fosdem.org/2014/schedule/event/miracast/attachments/slides/504/export/events/attachments/miracast/slides/504/openwfd_presentation_slides.pdf

**Comment by chewitt** [comment]
It only supports a single wireless driver (and that driver is realtek which guarantees further issues) and the git repo you referenced has no commits in a year which indicates a project that is stalled or dead.

**Comment by RichardEb** [comment]
Miracast is a common thing...Every Android phone support it out of the box. The google chromecast uses miracast as well. And I think the chromecast has a linux based OS.

**Comment by RichardEb** [comment]
Unit now I thougt chromecast uses miracast. But it seems that chromecast is a little bit different, but in the end it provides the same functionality. So a "chromecast" implementation would be as fine as miracast

**Comment by fritsch** [comment]
chromecast is proprietary shit, same as apple's airplay - won't happen.
