### ISSUE TITLE
openelec is more shit then chromecast. Won't happen  that I use openelec.

### ISSUE THREAD

**Issue by RichardEb** [OpenELEC/OpenELEC.tv#4307]
openelec is more shit then chromecast. Won't happen  that I use openelec.

https://github.com/OpenELEC/OpenELEC.tv/issues/4306

**Comment by RichardEb** [comment]
https://github.com/lanceseidman/PiCAST

**Comment by fritsch** [comment]
@RichardEb Thanks for your public statement. We keep it listed here for future reference.

**Comment by fritsch** [comment]
@RichardEb and even this you got wrong: https://github.com/lanceseidman/PiCAST/blob/old/README.md You have no clue of anything ... besides 35 dollars too much for a Pi.
