### ISSUE TITLE
jsconcpp source tarball has disappeared

### ISSUE THREAD

**Issue by MilhouseVH** [OpenELEC/OpenELEC.tv#4308]
```
  GET      jsoncpp
--2015-09-09 16:07:44--  http://garr.dl.sourceforge.net/project/jsoncpp/jsoncpp/0.5.0/jsoncpp-src-0.5.0.tar.gz
Resolving garr.dl.sourceforge.net (garr.dl.sourceforge.net)... failed: Name or service not known.
wget: unable to resolve host address 'garr.dl.sourceforge.net'
--2015-09-09 16:07:44--  http://sources.openelec.tv/mirror/jsoncpp/jsoncpp-src-0.5.0.tar.gz
Resolving sources.openelec.tv (sources.openelec.tv)... 82.220.2.33
Connecting to sources.openelec.tv (sources.openelec.tv)|82.220.2.33|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-09-09 16:07:44 ERROR 404: Not Found.
```

`http://garr.dl.sourceforge.net` no longer resolves to anything.

Could someone upload a copy of `jsoncpp-src-0.5.0.tar.gz` to `sources.openelec.tv`?

Many thanks.

**Comment by islipfd19** [comment]
Seems to have been moved to github. I believe the URL just needs to be updated since sourceforge indicates that this project has moved.

https://github.com/open-source-parsers/jsoncpp

**Comment by chewitt** [comment]
http://sources.openelec.tv/devel/jsoncpp-1.6.5.tar.xz .. update the URL to use the usual dev sources location and use this version. It builds fine - I used it to create the official repo for ATV recently.

**Comment by islipfd19** [comment]
I updated package.mk with your info. Just needs to be reviewed and merged.

**Comment by sraue** [comment]
fixed in https://github.com/OpenELEC/OpenELEC.tv/commit/3890176041bc55e4ec19f251ea2ddfdb70c5642c
