### ISSUE TITLE
OE 5.95.5: kodi is killed by systemd when terminating

### ISSUE THREAD

**Issue by mglae** [OpenELEC/OpenELEC.tv#4313]
When terminating kodi (when shutdown/reboot or manually stopping) the
process is often killed by systemd due to timeout. I looked at this
because there have been some state and configuration save problems.

For this report my netbook installation was soft reset and configured
with mxrvt plugin only.

In addition I did set TimeoutStopSec=15 in kodi.service and activated
persistent journal.

After reboot the logs are:

kodi.old.log: http://sprunge.us/gPUH
journalctl -b -1: http://sprunge.us/VSQS

Plese tell if any other logs are needed.

**Comment by stefansaraev** [comment]
tell no one. this is not an openelec bug. if kodi fails to save it's settings and exit cleanly in 5 seconds. it's kodi (or crap addon) fault. 

raising timeut to > 5sec is not acceptable

**Comment by chewitt** [comment]
closing old tickets with no update.. should the issue still exist on a current release please start a forum thread, thanks.
