### ISSUE TITLE
Support for 'DiBcom 7000PC' broken in rpi2 builds

### ISSUE THREAD

**Issue by Carlo-Avit** [OpenELEC/OpenELEC.tv#4317]
Hello! 

I recently tried to migrate from the "old" rpi1 to the new rpi2. All hardware is connected through a self-powered hub, to get around the annoying USB current limitations of the pi. 

I thoroughly tested it during the last two afternoons now. The DiBcom 7000 DVB-T hardware, namely a DVB-T Hauppauge Nova-T stick, is freezing after first initial frequency set on the rpi2 build of OpenELEC. Hardware is working fine on the OpenELEC rpi1 build. Hardware is working fine on the OpenELEC x64 build (NUC). 

To make sure it is not a tvheadend / HTSP Client issue, I tried different DVB-T sticks on the offending rpi2 build, namely a MSI Digit Vox II (AF9015) as well as a no-name RealTek (rtl28xxu) device. Both work well on the OpenELEC rpi2 build. 

ssh dmesg output is not helping much, since you only get a last message of freq. 0 failing to set. That's the last message you get until you disconnect. Reconnecting is not possible and will be not recognized until reboot. Here is the dmesg output, offending hardware is connected @ boot:

OpenELEC-Pi2:~ # dmesg |grep usb
[    0.000000] Kernel command line: root=/dev/ram0 rdinit=/init BOOT_IMAGE=/kernel.img usbcore.autosuspend=-1 dma.dmachans=0x7f35 bcm2708_fb.fbwidth=1824 bcm2708_fb.fbheight=984 bcm2709.boardrev=0xa01041 bcm2709.serial=0x5853756d smsc95xx.macaddr=B8:27:EB:53:75:6D bcm2708_fb.fbswap=1 bcm2709.disk_led_gpio=47 bcm2709.disk_led_active_low=0 sdhci-bcm2708.emmc_clock_freq=250000000 vc_mem.mem_base=0x3dc00000 vc_mem.mem_size=0x3f000000  boot=/dev/mmcblk0p1 disk=/dev/mmcblk0p2 quiet
[    0.930346] usbcore: registered new interface driver usbfs
[    0.930443] usbcore: registered new interface driver hub
[    0.930568] usbcore: registered new device driver usb
[    1.200953] usbcore: registered new interface driver rtsx_usb
[    1.202715] usbcore: registered new interface driver dm9601
[    1.202838] usbcore: registered new interface driver smsc95xx
[    1.604335] dwc_otg bcm2708_usb: DWC OTG Controller
[    1.604383] dwc_otg bcm2708_usb: new USB bus registered, assigned bus number 1
[    1.604426] dwc_otg bcm2708_usb: irq 32, io mem 0x00000000
[    1.604725] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    1.604744] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.604759] usb usb1: Product: DWC OTG Controller
[    1.604774] usb usb1: Manufacturer: Linux 3.18.10 dwc_otg_hcd
[    1.604788] usb usb1: SerialNumber: bcm2708_usb
[    1.606455] usbcore: registered new interface driver uas
[    1.606615] usbcore: registered new interface driver usb-storage
[    1.653937] usbcore: registered new interface driver usbhid
[    1.653946] usbhid: USB HID core driver
[    1.972558] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    2.152939] usb 1-1: New USB device found, idVendor=0424, idProduct=9514
[    2.152970] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.432736] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    2.526240] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[    2.526265] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.572291] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-bcm2708_usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:53:75:6d
[    2.652549] usb 1-1.2: new high-speed USB device number 4 using dwc_otg
[    2.746366] usb 1-1.2: New USB device found, idVendor=2040, idProduct=7060
[    2.746388] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.746398] usb 1-1.2: Product: Nova-T Stick
[    2.746408] usb 1-1.2: Manufacturer: Hauppauge
[    2.746418] usb 1-1.2: SerialNumber: 4028647390
[    5.611778] dvb-usb: found a 'Hauppauge Nova-T Stick' in cold state, will try to load a firmware
[    5.637278] dvb-usb: downloading firmware from file 'dvb-usb-dib0700-1.20.fw'
[    6.212744] dvb-usb: found a 'Hauppauge Nova-T Stick' in warm state.
[    6.214140] dvb-usb: will pass the complete MPEG2 transport stream to the software demuxer.
[    6.593709] usb 1-1.2: DVB: registering adapter 0 frontend 0 (DiBcom 7000PC)...
[    7.133240] input: IR-receiver inside an USB DVB receiver as /devices/platform/bcm2708_usb/usb1/1-1/1-1.2/rc/rc0/input0
[    7.133529] rc0: IR-receiver inside an USB DVB receiver as /devices/platform/bcm2708_usb/usb1/1-1/1-1.2/rc/rc0
[    7.133704] dvb-usb: schedule remote query interval to 50 msecs.
[    7.133724] dvb-usb: Hauppauge Nova-T Stick successfully initialized and connected.
[    7.134063] usbcore: registered new interface driver dvb_usb_dib0700
[    8.610018] usb 1-1.2: DVB: adapter 0 frontend 0 frequency 0 out of range (48000000..860000000)

 Best regards, keep up the good work on OpenELEC.

**Comment by lrusak** [comment]
Please avoid posting log snippets, use sites like pastebin. You can use sites like pastebin for long logs or you can simply pipe the log to the 'paste' command like `dmesg | paste`

Nothing looks to me like the dvb adapter isn't working properly. Does it not show up in tvheadend or does it disappear completely from `lsusb` and `lsdvb`?

Also are you using the exact same builds for each system? (rpi1, rpi2, x86_64)

**Comment by Carlo-Avit** [comment]
Hi Lukas,

thank you for your quick reply. Sorry for the snippet, my little son just got awake during writing, so I just copied it fast. ;) Your questions:

Yes, I use the current beta (5.95.5) on all mentioned devices. It all works quite well, except for the 'DiBcom 7000PC' support on the rpi2 build. As said, the offending hardware works fine on the 5.95.5 rpi1 build as well as on the NUC's with 5.95.5 x64 build.

Yes, It shows up like it is working properly (tvheadend as well as kernel) but DVB-T hardware "freezes" after the frequency is set once. If you remove the hardware physically after that, it is not removed properly (not from tvheadend nor from kernel).

I had some more time for testing yesterday. First, I tried the current rpi2 stable (5.0.8) to look for differences. Same behaviour, 'DiBcom 7000PC' support does not work.

Looked odd enough to me to challenge the hardware setup for errors. As I am using OpenWRT on our router, I compiled the available brcm2709 target (kernel 3.18) with dvb and media support, along with tvheadend.

Leaving the hardware as is, after inserting the OpenWRT SD and setting up tvheadend, I can watch DVB-T on all the devices in the house. If I insert the SD containing OpenELEC rpi2 build 5.95.5 (or 5.08, no difference), support for 'DiBcom 7000PC' does not work properly.

I believe I can sort out a hardware problem after this test. I will stay with OpenWRT for now as it does what I want (and keeps the peace for the family to watch TV). Of course, using Kodi on the device is non-functional this way, but for our guest room TV this is ok for now.

If you have a new beta out, I will be happy to test the 'DiBcom 7000PC' rpi2 build support again.

Best regards, and keep up the good work on OpenELEC!

**Comment by chewitt** [comment]
does this problem still exist in 6.0.0?

**Comment by chewitt** [comment]
Closing due to lack of update. Thanks.

**Comment by Carlo-Avit** [comment]
I am on holiday from Dec. 21. I will be back home on the 4th of January  
and happy to test the new build.

We're visiting town today and I found your request.

There is no Wifi up here in the mountains, and I am happy about it. :)

Happy new year to you!

I will report back to you as soon as checked it on the 6.0 build.

Regards,


Am 23.12.2015, 12:43 Uhr, schrieb Christian Hewitt  
<notifications@github.com>:
