### ISSUE TITLE
[SOLVED] 5.0.8 and 5.95.5 unmount USB drive while browsing the GUI

### ISSUE THREAD

**Issue by chonps** [OpenELEC/OpenELEC.tv#4321]
Hardware: RaspberryPi model B 512 MB.
Version: OE 5.95.5
Issue: with a LaCie (Seagate) 1TB USB 3.5'' (power supplied) mounted, is possible to reproduce any videos of any length with no problem. But, when browsing the GUI and selecting the submenu (not browsing System - Video (i.e.) but inside the Subtitles option [in the right side of the screen in the confluence skin]) the external hard drive is ejected and then, a few seconds later, mounted again. 
Here is the dmesg output:
http://sprunge.us/jDXh
and the logs:
http://sprunge.us/MadC
In 5.0.x version, the unmount/remount issue is worst and occurs in the paused video screen too. Then starts once and once again. Needed stop the video and start again. Or exit the menus and wait for the cycle to stop or reboot.
Here is the dsmeg output:
http://sprunge.us/KCJD
and the logs:
http://sprunge.us/WbQY with a Verbatim 2TB hard disk mounted as sdb1

**Comment by stefansaraev** [comment]
it is npot "umounting". it's usb reset. it's the hardware that's broken.

**Comment by chonps** [comment]
El 14/09/15 a las 08:55, Stefan Saraev escribió:
> it is npot "umounting". it's usb reset. it's the hardware that's broken.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4321#issuecomment-139979492>.
> 
Maybe, but it's strange that issue occurs with 5 different drives, both
Verbatim and LaCie, between 500GB and 2TB, and never, never, never
happens during video playing (it doesn't matter the file extension, the
codec, resolution or file size) or inactive, ONLY browsing the GUI (and
in 5.0.x, during video pause too).
I think this is a strange hardware break, isn't it?

**Comment by qods** [comment]
Video playback is been done by GPU. Browsing in the GUI is CPU based(as i remember). Maybe some power issues.

You can prove the problem to be openelec related by using totaly other hardware (for example pi2 or pi model a).
If you have some original Samsung usb-adapter (Samsung EP ...10...) with 2A output it would be also intereresting if you see same problem with that power supply.

**Comment by stefansaraev** [comment]
> Maybe, but it's strange that issue occurs with 5 different drives,

I did not say it's your harddrive. nothing strange here.

**Comment by popcornmix** [comment]
Almost certainly a power supply issue.
http://elinux.org/R-Pi_Troubleshooting#Troubleshooting_power_problems

**Comment by chonps** [comment]
Hello, everyone.
Finally, 4 days later (I'm so sorry), I made some tests about the power supply:
I have a RS-Online unit. It gives 1.2 A but, yes, cable is very thin. Voltage in the board seems correct, but it's no possible change the cable due it's attached to the power unit, no USB port.
Then i tried a Sony-Ericsson and a BQ cell-phone chargers with different cables (1 A only). This issue reproduces in all cases. BUT

**Comment by fritsch** [comment]
https://www.raspberrypi.org/help/faqs/#power <- Retry ... 

cite:
```
We have found that purchasing a 1.2A (1200mA) power supply from a reputable retailer will provide you with ample power to run your Raspberry Pi for most applications, though you may want to get a 2.5A (2500mA) if you want to use all 4 USB ports on the Models B+/2B without using an external powered USB hub.
```

**Comment by chonps** [comment]
I'm not sure what you mean exactly. In theory, 1200mA is enough for model B, but obviously there are some issues with the RS-Online power supply (model HNP06-050). I think the case that removing wifi dongle to cause proper behaviour probes that power consumption is unable to be fed by this unit.
I read the previous article about cables and saw that mine is so much thinner and longer than the mobile charger (i.e.) one. That's why I said that, when possible, I will do more tests.

**Comment by fritsch** [comment]
1200 mW is enough for the PI itself, the very moment you attach stuff to USB you will need more. 2.5A is safe - it's an upper  soft limit.

**Comment by stefansaraev** [comment]
as this is neither software, nor openelec issue, please close it. thanks.

**Comment by chonps** [comment]
Ok, closed then.
Again, thank you all.
