### ISSUE TITLE
5.95.5: Audio issues with AMD R9 390

### ISSUE THREAD

**Issue by ep0ch78** [OpenELEC/OpenELEC.tv#4323]
Openelec audio is broken with my AMD R9 390.

When playing normal (stereo) audio the sound echos significantly until the feedback is unbearable.
Using passthrough (DTS/Dolby) causes the sync issues with the amp and no sound is played.

Other users have similar issues with different AMD cards:
http://openelec.tv/forum/68-audio/74351-audio-echo-on-ati-hdmi#147764

Here's my alsa-info output:
sprunge.us/biOH

Please can someone kindly fix this as I love openelec :)

**Comment by lrusak** [comment]
I'm surprised it works at all.

Support for these cards won't come until at least linux 4.2 and mesa 11.0, even then support is minimalt

**Comment by ep0ch78** [comment]
Thanks! Any idea if these are on the roadmap?

**Comment by fritsch** [comment]
Ask in #radeon channel on irc freenode - Alex and christian are working on it.

**Comment by qods** [comment]
@lrusak 
Thats wrong. What you are talking about is the Radeon Fury and Fury X. The AMDGPU Driver would also support the tonga based R9 285 GPU(hopefully with reclocking) and the same based tonga R9 380.
The R9 390 is the same thing like the R9 290. Those are one of the best supported GPUs under linux you can get for money! They are perfectly supported by the radeonsi driver.
The Hawaii/Grenada GPUs are the best you can get for linux. 

@ep0ch78 
You also have those problems with "@@@" inside the soundcard? Have you tried other recent linux OS? Any problems there?

**Comment by ep0ch78** [comment]
qods, i haven't tried any Linux distros yet, if you can suggest one i will try it, otherwise i will go with Mint

**Comment by fritsch** [comment]
I would really, really wonder if Mint would work (out of the box). 

The OP has a different bug, that is filed since a long time on freedesktop on radeonsi cards and to my knowledge there exists no solution yet. OpenELEC ships a 4.1.x kernel + latest stable mesa - so driver support wise we are far ahead of every ubuntu derivative out there.

Though if I remember it correctly - the card might work correctly with pulseaudio - cause PA opens the device in a different mode as kodi does via ALSA. <- but I can't remember correctly anymore.

**Comment by qods** [comment]
@ep0ch78 
To follow the things that fritsch told, you can try lubuntu. Why? Because lubuntu use also ALSA instead of pulseaudio.

Take lubuntu 15.10 daily image. Its for testing, so most recent software is important in this case:
http://cdimage.ubuntu.com/lubuntu/daily-live/current/

**Comment by fritsch** [comment]
@qods you got that wrong. ALSA has the issue - PA works by accident.

**Comment by qods** [comment]
@fritsch 
Thats why he should test if he have the same problem with recent daily version of lubuntu. If its still there, its a upstream problem as you told.
The recent daily use more recent kernel then openelec (it use 4.2, openelec use 4.1) and some other things are different there. Thats why its interesting to know if there is the same problem.

**Comment by fritsch** [comment]
Afaik it would make more sense to install drm nightly kernel - cause I am not sure the hdmi rework by Alex has made it fully into 4.2

**Comment by ep0ch78** [comment]
lubuntu nightly
16/09/2015
kodi 15.1

With GUI sounds enabled, navigating the menu causes echo.
Passthrough to surround amp does not work at all.
Playing a 5.1 movie without passthrough causes slight audio clipping/distortion when in fullscreen
Same movie but changing so GUI overlay is showing (i.e. tab button) the sound is fine(!) - NO distortion/echo.
A stereo movie behaves the same.


Openelec - various versions 5.95.5, 5.08 and http://fritsch.fruehberger.net/openelec/ builds
Passthrough rarely syncs for more than a split second
All movies cause severe echo - much worse than lubuntu
GUI overlay makes no difference unlike lubuntu

**Comment by fritsch** [comment]
Yeah - that I call fully broken HW support :-)

Now install those kernels, please:
http://kernel.ubuntu.com/~kernel-ppa/mainline/drm-intel-nightly/current/

You need the three files: all, image 64 and headers 64, then install with sudo dpkg -i

**Comment by qods** [comment]
And maybe later the recent 4.3 version:

http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.3-rc1-unstable/

**Comment by ep0ch78** [comment]
i was running from livecd/usb so i'll try these later when i find a spare disk. thanks

**Comment by ep0ch78** [comment]
both the drm and 4.3rc1 version have the following behaviours:

Again, the GUI sounds cause echo.
Passthrough is not working
No clipping/crackling sound when movies played in fullscreen and no GUI overlay used.
Slight crackling when using GUI overlay and navigating menus (even with GUI sounds switched off)

Can't say I noticed any difference between the drm and 4.3rc1 version

**Comment by fritsch** [comment]
bugs.freedesktop.org is your place to file a bug then

**Comment by chewitt** [comment]
is this still an issue in OE 6.0.0 or current milhouse Jarvis builds? (now on 4.4 kernel)

**Comment by chewitt** [comment]
I'm closing this ticket due to lack of update. Thanks.
