### ISSUE TITLE
No visual with Wetek and OE > 5.95.2

### ISSUE THREAD

**Issue by Kurisutian** [OpenELEC/OpenELEC.tv#4326]
When running OpenELEC greater than 5.95.2 from SD Card on a Wetek Play the HDMI output will only give you a green screen. The audio works and the system is running but the screen stays all green. This happens on upgrades to all versions after 5.95.2 as well as on fresh installations of these versions. 

Tested with various SD Cards and HDMI Cables to rule out any HW issues. So far the result is the same. And all works with the Wetek Play Android System as well as with OE 5.95.2

**Comment by islipfd19** [comment]
This doesn't sound like a software issue. Try using a different HDMI cable and/or changing the order of turning your components on.

**Comment by Kurisutian** [comment]
I already did that with the same result.

**Comment by Kurisutian** [comment]
I checked again with version 6.0. I downloaded the WeTek SD Card image and created a SD Card under Linux by using dd to put the img file on the card. Well, the result was the same and depite of a different green color I still have no visual screen but the system is running. Sound are noticable when pressing buttons on the remote and I also can power off the system. So it is strictly a visiual issue existing even when starting fresh with the newest version.

**Comment by Kurisutian** [comment]
OK, I tested it again differently today and installed the working version (5.95.2) and upgraded to the stable release. Since this worked flawless I am now closing this issue as there seemed to be something else which is wrong. Well, if I find out something more I will open a new issue if I can recreate this behavior a bit more. Thanks!
