### ISSUE TITLE
5.95.4 & 5.95.5 issue with network on resume

### ISSUE THREAD

**Issue by karlshea** [OpenELEC/OpenELEC.tv#4332]
I'm having an issue with both beta 4 and beta 5 on two Asus Chromeboxes. When they are suspended and then woken up, it seems like there's a problem with how the network comes back up. The weather information says "busy" and the PVR recordings aren't refreshed. I can play items and network requests succeed, but it seems like the skins/pvr aren't getting poked about the network being available.

I have "wait for network" set at 10 seconds, and it works when rebooting, but not waking. This wasn't an issue in the last version of OpenELEC/Kodi.

Here's a debug log: http://sprunge.us/TajN
And dmesg: http://sprunge.us/EQBE

I rebooted, waited for Myth to update everything, and then slept/woke the device to make sure the log captured everything. The OnWake (20:42:17 T:139669477906304) is when I'm getting the "busy" message for weather in the skin and Myth isn't able to update.

There are a lot of "host is unknown" messages in the log as it's resuming, but if I try and do anything over the network as soon as I can control the box everything is successful, and "nslookup [myth host]" works just fine over SSH.

Eventually the skin will try and update the weather again and succeed, but until I reboot I can't delete a show out of Myth without a "backend doesn't support this method" message, new shows don't appear, and the "next recording" doesn't update.

**Comment by karlshea** [comment]
I also tried to copy /etc/connman/main.conf to /storage/.config/connman_main
.conf and set the FallbackNameservers to the actual DNS server, just in case there was some issue with DHCP, but that didn't help.

**Comment by karlshea** [comment]
This is definitely an issue with name resolution as the network is coming up. I changed the MythTV backend setting from a hostname to an IP and Myth says "Connection restored" when I suspend/resume. 

Here's a debug log where Myth has an IP: http://sprunge.us/HAEZ

**Comment by chewitt** [comment]
End user help is provided via the OE forums - this is a development bug tracker. Start a thread in the right place and I will explain the purpose of /storage/.config/hosts.conf.

**Comment by karlshea** [comment]
To be clear, one of the moderators of the OE forums suggested I post here when I asked on IRC.

**Comment by karlshea** [comment]
http://openelec.tv/forum/69-network/78256-5-95-4-5-95-5-issue-with-network-on-resume

**Comment by fritsch** [comment]
Does: ```systemctl restart kodi``` fix your issue after resume?

**Comment by karlshea** [comment]
Yes, but so does rebooting. Name resolution works as soon as Kodi is up and running, it's just not working during the resume, which is when Myth/everything else tries to reconnect.
