### ISSUE TITLE
remove v86d - its broken for long time and thats not a problem at all because unused

### ISSUE THREAD

**Issue by qods** [OpenELEC/OpenELEC.tv#4335]
https://github.com/OpenELEC/OpenELEC.tv/tree/master/packages/sysutils/v86d

This is broken for long time. There is no file:
http://dev.gentoo.org/~spock/projects/uvesafb/archive/v86d-0.1.10.tar.bz2

This does not seem to be used for longer time. It should be removed.

**Comment by vpeter4** [comment]
I don't know if is really needed or not but currently it is still used:
https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/tools/plymouth-lite/package.mk#L36
And source file is on OpenElec mirror:
http://sources.openelec.tv/mirror/v86d/v86d-0.1.10.tar.bz2

**Comment by stefansaraev** [comment]
v86d is needed for uvesafb

**Comment by sraue** [comment]
v86d is needed

**Comment by vpeter4** [comment]
@qods: Did you even compile openelec with all the changes you commit?

**Comment by chewitt** [comment]
@qods: It is nice to see new faces contributing to the project, but no more random package bump PR's please unless you are providing clear statements on what issues are being fixed, and that changes have been thoroughly tested (not just compiled). OE has 400k+ active users so we need to be conservative in our approach towards package changes.
