### ISSUE TITLE
Feature request : Show IP when Openelec is connected during boot

### ISSUE THREAD

**Issue by cffm** [OpenELEC/OpenELEC.tv#4340]
Hi,

so I am installing Openelec for friends. And starting it at their place, auto discover doesn't always work so I have to cycle thru IPs to be able to control Openelec. It would be so much easier if it would display the IP it gets. I see the OK or whatever it says while waiting for an IP. JUst flash the IP for half a second (it is just the last number anyway). Cannot be a huge dev task, no?

thanks!

PS I still don't know if that is the proper way to suggest a feature. The forum said do it here. github said I should do a pull request (what?) and then had to compare branches (hu?). I was lost... ;)

**Comment by vpeter4** [comment]
You have network data including IP address under System menu on main Kodi screen (System info, Network).

**Comment by chewitt** [comment]
You can also use DHCP reservations in the router to control the IP that will be allocated. Ticket closed.

**Comment by cffm** [comment]
‎Ok, I have the problem of connecting an app to control kodi so I cannot go to the info screen. All I want is to see the IP so I can add it manually to yatse or whatever is used as remote.                                                                                                                                                                                                                 From: Peter V.Sent: Thursday, September 24, 2015 9:04 PMTo: OpenELEC/OpenELEC.tvReply To: OpenELEC/OpenELEC.tvCc: cffmSubject: Re: [OpenELEC.tv] Feature request : Show IP when Openelec is connected during boot (#4340)You have network data including IP address under System menu on main Kodi screen (System info, Network).

—Reply to this email directly or view it on GitHub.

**Comment by cffm** [comment]
I am at a friend's house. They are not tech savvy and I will not ask him to setup reserved DHCP. Whatever router it is (not all offer that). Simple quick display of the IP and I can manually set yatse and all is good.                                                                                                                                                                                                                 From: Christian HewittSent: Thursday, September 24, 2015 9:04 PMTo: OpenELEC/OpenELEC.tvReply To: OpenELEC/OpenELEC.tvCc: cffmSubject: Re: [OpenELEC.tv] Feature request : Show IP when Openelec is connected during boot (#4340)You can also use DHCP reservations in the router to control the IP that will be allocated. Ticket closed.

—Reply to this email directly or view it on GitHub.

**Comment by fritsch** [comment]
Yatse only works anyways when kodi is up and running - just navigate to System -> System Info there you find the IP adress. Yatse without a running kodi makes no sense at all.
