### ISSUE TITLE
RPi2: version/update system message

### ISSUE THREAD

**Issue by alexa2** [OpenELEC/OpenELEC.tv#4344]
Hello.
Help me please. I built OpenELEC for Rpi-2 from the master branch (5fec628e2a).
Previously, when the start/upgrade the system, a message appears in the upper left corner of the screen (the version of the system ...). Now there is no such messages.
That I have a problem, or must be so?

Sorry for my English

**Comment by chewitt** [comment]
User help/support if provided via the forums - please create a thread there, thanks.
