### ISSUE TITLE
Openelec asking for password when adding a share via SMB.

### ISSUE THREAD

**Issue by robins80** [OpenELEC/OpenELEC.tv#4345]
I have Openelec 5.0.2 installed on my raspberry pi 2 model b.  I have an external drive connected to a linux box on the same network as the pi.  That drive has a shared folder with videos I want to stream. Whenever I try to add that folder to the library, I am being asked for a username and password to lock the preferences.  Trouble is, I have no idea what username/password it wants. It isn't the combo for my linux box.  What is it looking for?

**Comment by fritsch** [comment]
Thanks for not reading: https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md

Go to the forum, please. This is dev space.
