### ISSUE TITLE
Please upload libssh-0.7.2.tar.xz to openelec own mirror

### ISSUE THREAD

**Issue by qods** [OpenELEC/OpenELEC.tv#4363]
The download server is temporary down: https://red.libssh.org/projects/libssh/files

If some of the developer have already the file in their sources, please upload it to:
http://sources.openelec.tv/mirror/libssh/

Thanks

**Comment by stefansaraev** [comment]
but but. openelec mirror does not support https.

well.. uploaded.

**Comment by stefansaraev** [comment]
@qods would you trust the file I jut uploaded ?

**Comment by CvH** [comment]
@stefansaraev tx for spamming us with your childish nonsense

**Comment by fritsch** [comment]
@CvH: A big thank you to you for identifying what you call bullshit and sending me another email.

**Comment by stefansaraev** [comment]
@CvH you are very welcome. feel free to unsubscribe. or read other PRs too.

**Comment by fritsch** [comment]
Closing - cause it's uploaded.

**Comment by qods** [comment]
@stefansaraev 

You start to know me. Thanks :)
Yes, it would be great when letsencrypt is fully up and we can use then free and great CA for openelec mirrors.
Thanks to https://wiki.debian.org/ReproducibleBuilds and when openelec gets compatible with it, i would not have to trust you ;)
