### ISSUE TITLE
Support for DVB-S tuner idle mode

### ISSUE THREAD

**Issue by 5amSmith** [OpenELEC/OpenELEC.tv#4368]
I would appreciate that openelec with VDR backend supports to send the DVB-S tuners into idle mode, when LiveTV is not in use.
This is important for power saving reasons.
For example my SAT multiswitch doesn't go into standby because the Wetek Openelec box doesn't set the DVB-S tuners into idle mode.

**Comment by stefansaraev** [comment]
not possible with vdr. but you may use tvheadend.

**Comment by 5amSmith** [comment]
Yes, with tvheadend it's possible, but tvheadend doesn't support VPS/PDC. So tvheadend is no option for me.

After googling some time I read the VDR plugin dynamite supports tuner idle mode.
But dynamite isn't supported from openelec.
Is it possible to integrate dynamite into openelec?

**Comment by stefansaraev** [comment]
dynamite is not going to be re-added to OE I think. as it conflicts with other well supported vdr plugins (dvbapi is one of them).

**Comment by 5amSmith** [comment]
Not good.
Any suggestions what I can do now?
I have a Wetek OE box and need Kodi LiveTV with VPS/PDC and tuner idle mode.
Is there any possible solution?

**Comment by chewitt** [comment]
I'm closing this because this is not something our current VDR version supports. The correct place to request VDR feature changes is the VDR (upstream) forums or github. Thanks.
