### ISSUE TITLE
scripts/checkdeps does not check for dosfstools

### ISSUE THREAD

**Issue by vitalogy** [OpenELEC/OpenELEC.tv#4375]
note: edited the hole thing, after my asininity is gone

I get this error:

    scripts/mkimage: line 109: mkfs.vfat: command not found

I ran into this months ago, so i had manual installed dosfstools and i had to add sudo command before `mkfs.vfat` in `scripts/mkimage`.

From `scripts/mkimage` runs the command `parted` without the addition of sudo, but why i had to add it before `mkfs.vfat`? Should `scripts/checkdeps` not also check if `mkfs.vfat` and `parted` are available?

Using here an up-to-date gentoo (x86_64).

**Comment by lrusak** [comment]
Humm, I just updated the gentoo deps, but perhaps I missed some (I don't use gentoo fulltime) so if we need to add ```dosfstools``` and ```parted``` to the deps then that is ok.
see, https://github.com/OpenELEC/OpenELEC.tv/blob/master/scripts/checkdeps#L47


As for sudo, the entire mkimage script is run as sudo
see https://github.com/OpenELEC/OpenELEC.tv/blob/master/scripts/image#L324

**Comment by vitalogy** [comment]
by running the normal build command `$ PROJECT=imx6 ARCH=arm make image`
i get this

    Parallel mksquashfs: Using 4 processors
    Creating 4.0 filesystem on /home/michael/workspace/OpenELEC.tv/target/OpenELEC-imx6.arm-6.0-devel-20151018001514-r21418-g3f21054.system, block size 131072.
    <snip>
    mkimage: boo. now root access (sudo) is required...
    mkimage: see scripts/image and scripts/mkimage if you dont trust us :)
    image: creating image: /home/michael/workspace/OpenELEC.tv/target/OpenELEC-imx6.arm-6.0-devel-20151018001514-r21418-g3f21054.img...
    292+0 records in
    292+0 records out
    306184192 bytes (306 MB) copied, 0.218713 s, 1.4 GB/s
    image: creating partition table on /home/michael/workspace/OpenELEC.tv/target/OpenELEC-imx6.arm-6.0-devel-20151018001514-r21418-g3f21054.img...
    image: creating part1 on /home/michael/workspace/OpenELEC.tv/target/OpenELEC-imx6.arm-6.0-devel-20151018001514-r21418-g3f21054.img...
    image: creating part2 on /home/michael/workspace/OpenELEC.tv/target/OpenELEC-imx6.arm-6.0-devel-20151018001514-r21418-g3f21054.img...
    image: creating filesystem on part1...
    scripts/mkimage: line 109: mkfs.vfat: command not found
    image: mounting part1 on /tmp/tmp.swc9n1idoa...
    mount: /dev/loop1 is write-protected, mounting read-only
    mount: wrong fs type, bad option, bad superblock on /dev/loop1,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
    <snip>


???

**Comment by vitalogy** [comment]
Opened #4380 to fix some gentoo deps.
Should a check for dosfstools (mkfs.vfat), parted and squashfs (mksquashfs) also made for all distros?

**Comment by lrusak** [comment]
Hmmm, not sure why we don't check for these tools. Maybe many distros come with these already, but I see no harm in checking for them anyway.
maybe @stefansaraev has a reason?

**Comment by stefansaraev** [comment]
parted and mksquashfs are in our toolchain, compiled as host tools. one could also add dosfstools:host or require host OS to install it. whatever you think is better.

yea. gentoo is kind of special. honestly, I dont care much for gentoo. if one builds on gentoo, I expect more  than dosfstools to be broken.

**Comment by vitalogy** [comment]
Ahhh, thanks for the info ... will have a look
so close this
