### ISSUE TITLE
"Ambilight“ on the wetek openelec box. OE-Edition

### ISSUE THREAD

**Issue by Newan** [OpenELEC/OpenELEC.tv#4377]
Hello,

I’d like to run „ambilight“ on the wetek openelec box.
I tried to use „boblight“ (including the bob light plugin) which worked but pushed the CPU load to 100% and made the Video stutter.
Therefore I tried running hyperian. The installation was done without any issues but unfortunately the daemon does not run.
It stops with the following error message:

/storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json
/storage/hyperion/bin/hyperiond: error while loading shared libraries:
libbcm_host.so: cannot open shared object file: No such file or directory

I found a thread with a similar problem where installing libusb-1.0-0 seemed to be the solution.
since there is no „apt“ on openelec I don’t know how to do this.
I hope someone can help.

**Comment by chewitt** [comment]
Closing because user support is provided via the forums (this is a development tracker). Please start a forum thread for your problem. Thx.
