### ISSUE TITLE
IPRoute2 is missing VETH in Kernel.

### ISSUE THREAD

**Issue by bitlite** [OpenELEC/OpenELEC.tv#4381]
Hello all,

I am in need of having the VETH to be available in OpenELEC.  Can you create future versions of OpenELEC with CONFIG_VETH=y please?

I am in need of the VETH0 and VETH1 creating the following scenario.
- Setup my Wireless adapter into Adhoc mode.
- Statically configure the WLAN0 to only connect to my Wifi adapter (what file do I need to modify to do this?)
- Bridge it between the Wireless and Virtual Ethernet adapter (WLAN0 <-> VETH0 <-> VETH1).
- Be able to have the VETH1 considered as the wired network for OpenELEC to use.

My goal is to setup my Raspberry Pi to automatically connect to my Cellular Phone (Nokia N95 8GB using JoikuSpot which is Ad-Hoc 802.11b network).  With the current setup, I can not connect with my Ad-Hoc network via OpenELEC.  I can create a manual connection via SSH which I confirmed working with my Cell Phone but I can not seem to get it visible within OpenELEC.  Therefore, I would like to statically configure the WLAN0 as a Bridge to VETH0 and have VETH0 endpoint to VETH1 and have VETH1 visible in the Wired Network section.  

Please compile the kernel with 
CONFIG_VETH=y
So those with older cell phones with JoikuSpot can use OpenELEC with some minor modifications.  Since my older phone has Unlimited Internet (Grandfathered plan), I would be able to finally keep my children at bay and have them watching their favourite cartoons without the need to connect to Netflix or download via SD/USB Drives.

**Comment by stefansaraev** [comment]
I think, for your edge case, you need a general purpose distribution.

**Comment by stefansaraev** [comment]
we dont even have iproute2. ip comes from busybox. and is missing lot more.

**Comment by lrusak** [comment]
see #4273

**Comment by chewitt** [comment]
I'm closing this down because it's a niche use-case and OE has no plans to support complex bridging arrangements. You are welcome to self-build OE with the changes required. Thanks.
