### ISSUE TITLE
Cubox i2 Freezes

### ISSUE THREAD

**Issue by polarbear2** [OpenELEC/OpenELEC.tv#4388]
My Cubox used to work OK on previous stable versions of Openelec. But when I installed version 5.95.5, my Cubox started to freeze every hour or so. I thought that perhaps one of my plugins is incompatible or faulty, so I made a fresh new install with no plugins whatsoever, and almost no change in the initial settings (except connecting to wifi, enable SSH etc.) The freezes persisted even though the Cubox was idle all that time.
Please also see this thread: http://openelec.tv/forum/144-usage/78512-cubox-i2w-freezes#149838

**Comment by chewitt** [comment]
Closing because this is not an end-user support forum.

**Comment by polarbear2** [comment]
I didn't ask for support. I just wanted to report a bug in the beta versions of Openelec. As you can see in the link above, I'm not the only one who have this problem.

**Comment by fritsch** [comment]
It is a known bug and was known the same day - some Vivante / whatever binaries were bumped from the working state they had in 5.0.8. If you can use 5.0.8 base and compile kodi 15.2 for it ... and all should be fine again.

**Comment by vpeter4** [comment]
I build 6.0.0 image with older libraries as used in OpenELEC 5.0.8:
* gpu-viv-bin-mx6q 3.10.17-1.0.0-1
* gpu-viv-g2d 3.10.17-1.0.2
* imx-vpu 3.10.17-1.0.0
* libfslvpuwrap 1.0.46

The problem didn't go away. Also with disabled CEC.
