### ISSUE TITLE
Mistake at compilation of OPENELEC in UNUNTU 15.10

### ISSUE THREAD

**Issue by ed68** [OpenELEC/OpenELEC.tv#4390]
./scripts/image release

 =================================================================================
 Configuration for OpenELEC (unofficial)
 =================================================================================

 Buildoptions:
 ======================================================
 - CPU (ARCH):                           x86-64 (x86_64)
 - FLOAT:
 - FPU:
 - SIMD support:                         yes
 - Optimizations:                        size
 - LTO (Link Time Optimization) support: yes
 - GOLD (Google Linker) Support:         yes
 - LLVM support:

 Graphic configuration:
 ======================================================
 - Xorg Graphic Drivers:                 nvidia-legacy
 - XORG Composite support:
 - WindowManager:                        fluxbox
 - OpenGL (GLX) support (provider):      yes (mesa)
 - OpenGLES support (provider):          no (no)
 - uvesafb support:                      yes

 Hardware decoder configuration:
 ======================================================
 - Kodi Player driver:                   default
 - VAAPI Support:
 - VDPAU Support:                        yes
 - DCA decoder Support:                  yes

 Input device configuration:
 ======================================================
 - Remote support:                       yes
 - ATV Remote support:                   yes
 - CEC Adapter support:                  yes
 - IRTrans support:                      yes
 - Kodi Joystick support:                yes

 Misc. hardware configuration:
 ======================================================
 - ALSA support:                         yes
 - Bluetooth support:                    yes
 - LCD drivers:                          irtrans,imon,imonlcd,mdm166a,MtxOrb,lis,dm140,hd44780,CFontz,SureElec,vlsys_m428,serialVFD,shuttleVFD
 - Include driver:                       RTL8192CU
 - Include driver:                       RTL8192DU
 - Include driver:                       RTL8188EU
 - Include driver:                       RTL8812AU
 - Include driver:                       dvbhdhomerun
 - Include driver:                       bcm_sta
 - Include firmware:                     misc-firmware
 - Include firmware:                     wlan-firmware
 - Include firmware:                     dvb-firmware
 - Include firmware:                     iwlwifi-firmware

 Network service configuration:
 ======================================================
 - Avahi (Zeroconf) support:             yes
 - NFS mounting support:                 yes
 - SAMBA mounting support:               yes
 - SAMBA server support:                 yes
 - SFTP server support:                  yes

 OS configuration:
 ======================================================
 - OEM Support:                          no
 - Default ROOT Password:                openelec
 - Bootloader:                           syslinux
 - UDevil support:                       yes
 - Installer support:                    yes

 Misc. Filesystems:
 ======================================================
 - Swap Support:                         no
 - exFAT Support (via Fuse):             yes
 - NTFS Support (via Fuse):              yes
 - Install HFS Tools:                    yes

 Kodi configuration:
 ======================================================
 - Kodi version:                         kodi
 - Kodi nonfree support:                 yes
 - Kodi Blu-Ray support:                 yes
   - Bluray BD+ support:                 yes
   - Bluray AACS support:                yes
 - Kodi DVDCSS support:                  yes
 - Kodi Airplay support:                 yes
 - Kodi Airtunes support:                yes
 - Kodi NFS support:                     yes
 - Kodi MySQL support:                   yes
 - Kodi Optical Drive support:           yes
 - Kodi SAMBA client support:            yes
 - Kodi SSH client support:              yes
 - Kodi UPNP support:                    yes
 - Kodi Webserver support:               yes
 - Include Skin:                         Confluence
 - Default Skin:                         Confluence
 - Include extra fonts:                  yes

 =================================================================================
 End Configuration for OpenELEC
 =================================================================================

**** Your system lacks the following tools needed to build OpenELEC ****
md5deep
**** You seem to use a ubuntu system ****
would you like to install the needed tools ? (y/n) y
[sudo] password for hcefm:
Reading package lists... Done
Building dependency tree
Reading state information... Done
md5deep is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
**** The following packages were not installed correctly ****
md5deep
********
Makefile:9: ошибка выполнения рецепта для цели «release»
make: *** [release] Ошибка 1

md5deep is present

best regards
Edvard F. Mjagi

**Comment by stefansaraev** [comment]
stupid buntu. they decided to NOT install md5deep / sha1deep / sha256deep .. (hashdeep is a multi-call binary) after transition to hashdeep. 
```
sudo ln -sf /usr/bin/hashdeep /usr/local/bin/md5deep
```

you better report this to ubuntu.

**Comment by ed68** [comment]
Thanks. 

23 октября 2015 г. 13:31:19 GMT+03:00, Stefan Saraev <notifications@github.com> пишет:
>stupid buntu. they decided to NOT install md5deep / sha1deep /
>sha256deep .. (hashdeep is a multi-call binary) after transition to
>hashdeep. 
>```
>sudo ln -sf /usr/bin/hashdeep /usr/local/bin/md5deep
>```
>
>you better report this to ubuntu.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenELEC/OpenELEC.tv/issues/4390#issuecomment-150538348

--
Простите за краткость,
создано в K-9 Mail

**Comment by stefansaraev** [comment]
or, you may test this patch: http://sprunge.us/NLhh on top of current openelec master.

**Comment by ed68** [comment]
Thanks, all works. 1 variant. Edward.

23 октября 2015 г. 13:48:56 GMT+03:00, Stefan Saraev <notifications@github.com> пишет:
>or, you may test this patch: http://sprunge.us/NLhh on top of current
>openelec master.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/OpenELEC/OpenELEC.tv/issues/4390#issuecomment-150541763

--
Простите за краткость,
создано в K-9 Mail

**Comment by stefansaraev** [comment]
cool. thanks for reporting and testing the fix.

**Comment by ed68** [comment]
ALL OK. Compiling and Working.

 

Bye.

Edvard Mjagi.
