### ISSUE TITLE
WeTeK CeC broke button "OK"

### ISSUE THREAD

**Issue by NoNaMe-Lviv** [OpenELEC/OpenELEC.tv#4400]
changes in the Oct 24, 2015 , broke WeTeK control over the TV remote control that is button "OK"

**Comment by lrusak** [comment]
@sraue perhaps this is because @84b94d118824f6d620bd1cda36ea98270e8139f3 ?

**Comment by NoNaMe-Lviv** [comment]
As it turned out there inaccuracies in the native WeTek remote.
"with this last update I lost some keyboard shortkeys access.
When I press the EPG key on the remote it doesn't do anything. When I press the (*) key, is opens my favourites instead of the channel list.The screen resize key (the top right key) that was used to resize the video, now just goes back to the main menu.
I tried to replace the keyboard.xml with my previous one, but it didn't work.
"

**Comment by NoNaMe-Lviv** [comment]
CEC button "OK" or SELECT fix on Commits Oct 29, 2015 
thanks

**Comment by sraue** [comment]
fixed in https://github.com/OpenELEC/OpenELEC.tv/commit/f6dc1f24922fda39c7f4bba9004765f1f1b165c0
