### ISSUE TITLE
Several keys of the Rii mini i8+ remote not working on 5.0.8 and 5.95.5

### ISSUE THREAD

**Issue by rtega** [OpenELEC/OpenELEC.tv#4401]
I guess fixing this on 5.95.5 is going to be the most pressing. The following keys don't work:
- search: CLinuxInputDevice::KeyEvent: TranslateKey returned XBMCK_UNKNOWN from code(217)
- home: CLinuxInputDevice::KeyEvent: TranslateKey returned XBMCK_UNKNOWN from code(144)
- weird circled play button: CLinuxInputDevice::KeyEvent: TranslateKey returned XBMCK_UNKNOWN from code(171)

**Comment by lrusak** [comment]
Please see https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md

We will not answer unless you provide the proper information

**Comment by rtega** [comment]
Hello,

This is on Openelec version 5.95.5 and 5.0.8 both on build Rpi and architecture ARM. The codes are from the kodi.log file obtained using debug logging. Do you need any other information? If you really want I can include a full log but I guess that wouldn't be much use.

**Comment by rtega** [comment]
BTW, kodi version is 15.1 git:f4dda26 compiled sep. 4 2015.

**Comment by lrusak** [comment]
I can fix, what would you like each key to do?

**Comment by rtega** [comment]
Thanks, maybe you could give them a proper keycode, I'd remap them afterwards anyway. I guess though that is not possible and you have to give them a certain name? In that case I think "search_key", "home_key" and "power_key" would be the best choice.

**Comment by rtega** [comment]
Turns out that another key marked "e" (probably garnered from internet explorer) maps to the home key. Maybe "email" or something else.

**Comment by rtega** [comment]
some extra info from evtest when pressing these keys:
Event: time 1446123564.136050, type 4 (EV_MSC), code 4 (MSC_SCAN), value c0183
Event: time 1446123564.136050, type 1 (EV_KEY), code 171 (KEY_CONFIG), value 1
Event: time 1446123564.136050, -------------- SYN_REPORT ------------
Event: time 1446123564.328062, type 4 (EV_MSC), code 4 (MSC_SCAN), value c0183
Event: time 1446123564.328062, type 1 (EV_KEY), code 171 (KEY_CONFIG), value 0
Event: time 1446123564.328062, -------------- SYN_REPORT ------------
Event: time 1446123566.808406, type 4 (EV_MSC), code 4 (MSC_SCAN), value c0221
Event: time 1446123566.808406, type 1 (EV_KEY), code 217 (KEY_SEARCH), value 1
Event: time 1446123566.808406, -------------- SYN_REPORT ------------
Event: time 1446123567.000430, type 4 (EV_MSC), code 4 (MSC_SCAN), value c0221
Event: time 1446123567.000430, type 1 (EV_KEY), code 217 (KEY_SEARCH), value 0
Event: time 1446123567.000430, -------------- SYN_REPORT ------------
Event: time 1446123567.768534, type 4 (EV_MSC), code 4 (MSC_SCAN), value c0194
Event: time 1446123567.768534, type 1 (EV_KEY), code 144 (KEY_FILE), value 1
Event: time 1446123567.768534, -------------- SYN_REPORT ------------
Event: time 1446123567.976567, type 4 (EV_MSC), code 4 (MSC_SCAN), value c0194
Event: time 1446123567.976567, type 1 (EV_KEY), code 144 (KEY_FILE), value 0
Event: time 1446123567.976567, -------------- SYN_REPORT ------------

**Comment by sraue** [comment]
KEY_FILE and KEY_SEARCH added in https://github.com/OpenELEC/OpenELEC.tv/commit/481609c5a2297bb9a23916a9229e1caea2375cab and https://github.com/OpenELEC/OpenELEC.tv/commit/4b5b447711bc2f7ca70b8df5611dd3c8bd0176ff

**Comment by rtega** [comment]
Thanks!
