### ISSUE TITLE
Mail key from PC Remote or Sanoxy remote doesn't work

### ISSUE THREAD

**Issue by rtega** [OpenELEC/OpenELEC.tv#4403]
The e-mail key on the sanoxy remote doesn't work. This is on arch arm build 5.95.5 RPi. The log says:
KeyEvent: TranslateKey returned XBMCK_UNKNOWN from code(155)

**Comment by anoma** [comment]
What would you expect the e-mail key to do?

**Comment by rtega** [comment]
Have a unique identifier so it can uniquely be bound to some action. I guess launch_mail would be in order.

**Comment by sraue** [comment]
is this remote regonized with evtest:
via ssh:
```systemctl stop kodi```
```systemctl stop eventlircd```
```evtest```
before you must install evtest from our unofficial addons/program addons, then reboot. after starting evtest you will see a list with renotes where you select the right one. please paste the output you get while pressing this button

**Comment by rtega** [comment]
Event: time 1446123233.670014, type 4 (EV_MSC), code 4 (MSC_SCAN), value c018a
Event: time 1446123233.670014, type 1 (EV_KEY), code 155 (KEY_MAIL), value 1
Event: time 1446123233.670014, -------------- SYN_REPORT ------------
Event: time 1446123233.870022, type 4 (EV_MSC), code 4 (MSC_SCAN), value c018a
Event: time 1446123233.870022, type 1 (EV_KEY), code 155 (KEY_MAIL), value 0
Event: time 1446123233.870022, -------------- SYN_REPORT ------------

**Comment by sraue** [comment]
is this remote used by irw? (restart and simply run ```irw```)

**Comment by rtega** [comment]
when I restart and run irw I get no output at all even when pressing keys.

**Comment by sraue** [comment]
ok, thanks will work on something to support this

**Comment by anoma** [comment]
For reference is this the remote

![SANOXY® Wireless USB PC Remote Control Mouse for PC](http://imgur.com/z4KhkrH)

**Comment by rtega** [comment]
As far as I know it looks exactly the same. The manufacturer id is 1d57 and product name is ad02.

**Comment by rtega** [comment]
BTW, can I use hid_mapper to fix this manually or does hid_mapper not work on rpi?

**Comment by sraue** [comment]
you need the rpi or rpi2 build to test?

**Comment by rtega** [comment]
rpi build. Turns out I can manually remap them with hid_mapper though I
have to stick to the key-names that are already known to kodi.

2015-10-29 16:00 GMT+01:00 Stephan Raue <notifications@github.com>:

**Comment by sraue** [comment]
can you please try http://snapshots.openelec.tv/OpenELEC-RPi.arm-6.0-devel-20151029164012-r21466-g0847aae.tar asap and test the email, search und file key (the config key i still not have added) with kodi.log output and maybe with using "launch_mail", "browser_search" and "launch_file_browser" in keyboard.xml

**Comment by rtega** [comment]
Hey Stephan,

Do I just copy the files to the SD-card?

2015-10-29 17:34 GMT+01:00 Stephan Raue <notifications@github.com>:

**Comment by sraue** [comment]
yes the tar file to the update samba share or via ssh/scp to /storage/.update and reboot

**Comment by rtega** [comment]
Hi Stephan,

Seems to map nicely to the right key. I get this in the log file:
18:31:02 413.744446 T:1967689728   DEBUG: Keyboard: scancode: 0x9b, sym:
0x00b4, unicode: 0x0000, modifier: 0x0
18:31:02 413.744995 T:1967689728   DEBUG: OnKey: launch_mail (0xf0be)
pressed, action is

I can't seem to bind it to an action though. The app.xml-file is loaded
without any error and looks like:
<keymap><global><appcommand>
                        <launch_mail>Pause</launch_mail>
                </appcommand>
</global></keymap>

What could be wrong?

2015-10-29 18:06 GMT+01:00 Stephan Raue <notifications@github.com>:

**Comment by sraue** [comment]
can you copy and use keyboard.xml in /storage/.kodi/userdata/keymaps see http://kodi.wiki/view/Keymap#Keyboards and use the keyboard section

**Comment by rtega** [comment]
Hi Stephan,

That seems to do it. It works. Thanks! In the process I discovered a
separate bug in the same remote where one key initiates two key-events. I
guess I should file a separate bug?

Reinaert

2015-10-29 18:39 GMT+01:00 Stephan Raue <notifications@github.com>:

**Comment by sraue** [comment]
no, explain or post the output... its ok some buttons are two events

**Comment by sraue** [comment]
added in https://github.com/OpenELEC/OpenELEC.tv/commit/4a72228a2eb7d0f7b932c56afead39692b3b2f35

**Comment by rtega** [comment]
Hi Stephan,

Well some key generates i.e. mod-0 mod-e event. Another key generates a mod-0 event. This results in the action coupled to the second key being called when the first key is being triggered. Rather annoying.

**Comment by sraue** [comment]
give the evtest output please

**Comment by rtega** [comment]
Hi, sorry for the late reply:
the windows key generates:
Event: time 1448639743.364603, type 4 (EV_MSC), code 4 (MSC_SCAN), value 700e7
Event: time 1448639743.364603, type 1 (EV_KEY), code 126 (KEY_RIGHTMETA), value 1
Event: time 1448639743.364603, -------------- SYN_REPORT ------------
Event: time 1448639743.612622, type 4 (EV_MSC), code 4 (MSC_SCAN), value 700e7
Event: time 1448639743.612622, type 1 (EV_KEY), code 126 (KEY_RIGHTMETA), value 0
Event: time 1448639743.612622, -------------- SYN_REPORT ------------

The open folder key:
Event: time 1448639781.313650, type 4 (EV_MSC), code 4 (MSC_SCAN), value 700e0
Event: time 1448639781.313650, type 1 (EV_KEY), code 29 (KEY_LEFTCTRL), value 1
Event: time 1448639781.313650, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70012
Event: time 1448639781.313650, type 1 (EV_KEY), code 24 (KEY_O), value 1
Event: time 1448639781.313650, -------------- SYN_REPORT ------------
Event: time 1448639781.545669, type 4 (EV_MSC), code 4 (MSC_SCAN), value 700e0
Event: time 1448639781.545669, type 1 (EV_KEY), code 29 (KEY_LEFTCTRL), value 0
Event: time 1448639781.545669, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70012
Event: time 1448639781.545669, type 1 (EV_KEY), code 24 (KEY_O), value 0
Event: time 1448639781.545669, -------------- SYN_REPORT ------------

I guess we won't be able to change latter. Could we change the former?
