### ISSUE TITLE
WeTeK original remote buttons broken

### ISSUE THREAD

**Issue by NoNaMe-Lviv** [OpenELEC/OpenELEC.tv#4405]
Of those that worked previously broken:
Resize
Epg
____________

I also used a small file for super easy use remote:
  <?xml version="1.0" encoding="UTF-8" ?> 
< keymap >
< FullscreenLiveTV >
< keyboard >
< menu>OSD< /menu > 
 < f6>ActivateWindow(pvrosdchannels)< /f6> 
 < f2>ActivateWindow(tvguide)< /f2> 
< /keyboard >
< /FullscreenLiveTV >
< /keymap> 

The file is now in .kodi\userdata\keymaps\ is not working.

**Comment by sraue** [comment]
the buttonnames are remapped now, you find the names in kodi.log if you enable debugging and press the buttons
