### ISSUE TITLE
[Release] OpenELEC 6.0 RPi 2 CEC not working properly

### ISSUE THREAD

**Issue by spec1re** [OpenELEC/OpenELEC.tv#4412]
After updating to 6.0 final on my RPi 2 CEC is not working properly anymore with my Samsung TV. It's losing connection and the remote isn't working, need to switch sources to get it back again. My Philips TV is woking fine, no CEC problems there.

**Comment by lrusak** [comment]
Please see https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md

**Comment by MilhouseVH** [comment]
http://openelec.tv/forum/120-news-announcements/78713-release-openelec-6-0-released?start=90#151104

Bumping to libcec 3.0.1 seems to help fix some problems being experienced by Samsung users - any particular reason why OE6 remains on 3.0.0?

**Comment by JimmyS83** [comment]
Voting for that.. I confirm that 3.0.0 cause malfunction of CEC with using some buttons and my Samsung. With libcec 3.0.1 problems disappears.

**Comment by stefansaraev** [comment]
sadly. this is not a place where people can vote for bumps :)

but in case someone wants to bump libcec. please also pick https://github.com/Pulse-Eight/libcec/commit/678739a0d8aa5897fa1906a8fdeeb67b83f7d1e9 :)

**Comment by endlessterror** [comment]
Just wanted to confirm the same findings here.

@lrusak : I saw your link. If I understand correctly, your patch proposal has not been merged into OE yet, correct? Do you believe it will be accepted for the next OE version?

**Comment by JimmyS83** [comment]
@ET: yes. About next version I am curious too. Because actual stabel has 15.2 Kodi, and when I tried to upgrade just libcec 3.0.1, I got compile errors from Kodi/periph. etc. So I think, that there must be some changes in Kodi sources according to libcec (which is propably made already on master).
