### ISSUE TITLE
Mounts Missing after 5.95.xxx to 6.0.0 upgrade

### ISSUE THREAD

**Issue by milkmansson** [OpenELEC/OpenELEC.tv#4413]
Situation:
sda = 4TB GPT Hard Disk, Ext4, Data Only
sdb = 4TB GPT Hard Disk, Ext4, Data Only
sdc = 4TB GPT Hard Disk, Ext4, Data Only
sdd = 4TB GPT Hard Disk, Ext4, Data Only
sde = 4TB MBR Hard Disk, 4x partitiions, dual boot with Ubuntu, OE and OEDATA partitions on this disk.

After automatic upgrading to 6.0.0, sde was the only remaining mounted hard disk.  Automatic mounting for previous 4 disks did not work.  Soft resetting Openelec also did not help any.  Successful manual mounting of those 4 disks' partitions was possible using SSH.  These were also immediately visible in GUI (File Manager).

The following logs/troubleshooting were retrieved (thanks to IRC, Klojum and 0mmand) using pastebinit
parted -l [at] http://sprunge.us/JhON
blkid | [at] http://sprunge.us/LTLj
mount [at] http://sprunge.us/BBgW
dmesg [at] http://sprunge.us/FQYX
cat /storage/.kodi/temp/kodi.log [at] http://sprunge.us/aXjg

Solution for now was to put manual 'mount' commands into autostart.sh like:
mount -t ext4 /dev/sda1 /var/media/sda1
(followed the good instructions at http://wiki.openelec.tv/index.php?title=Autostart.sh)
... this has allowed me to get on and reconfigure my install (from scratch sadly!!)

Whilst the autostart gets me going, if anyone working on this trouble ticket wishes to get further attention or test any fixes on my hardware, I would be happy to oblige. :)

**Comment by lrusak** [comment]
Seems to be an issue with the gpt partition tables. I just tested this and didn't have any issues.

Can you post the output of the following commands
```
udevadm info -q all -a /dev/sda1 | paste
```
```
udevadm info -n /dev/sda1 | paste
```
```
udevadm info -n /dev/sda | paste
```

Also can you try to mount the disk via the following command
```
udevil mount /dev/sda1
```
post the output if it is anything other than something similar to
```
Mounted /dev/sdc1 at /media/sdc1-usb-Generic_Flash_Di
```

**Comment by milkmansson** [comment]
Hi Lrusak;
udevadm info -q all -a /dev/sda1 | paste [Went To] http://sprunge.us/LKiH
udevadm info -n /dev/sda1 | paste [Went To] http://sprunge.us/eXZS
udevadm info -n /dev/sda | paste [Went To] http://sprunge.us/gPYU

Working on the unmounted element - had to remove from autostart.sh and reboot as unmount not in the OE distro.. ;) 2 tix

**Comment by milkmansson** [comment]
ok this is much more interesting: Result of udevil mount /dev/sdd1
mms:~ # udevil mount /dev/sdd1
udevil: denied 73: fstype 'zfs_member' is not an allowed type

I thought I wiped these disks properly after recovering them from a ZFS based home server distro.  Whilst I can put my hands up and say 'my fault!!' they did work on the 5.95.xx betas.  So I am guessing this is my issue only?

**Comment by lrusak** [comment]
the command is ```umount``` not ```unmount``` ;)

anyways, seems there is some lingering file system ;)
```ID_FS_TYPE=zfs_member```

No idea why it worked before. see if you can try and force the mount via
```
udevil mount -t ext4 /dev/sda1
```

Other than that, you can either use your autostart workaround (not recommended) or you can cleanup your disks

**Comment by milkmansson** [comment]
Thanks for the help. Now we know its old legacy stuff, I will do the disks again, but I have to wait for another 4GB disk to become free. :(  I hope Mr S Raue won't mind buying you a beer. Greets from New Zealand. :)

**Comment by chewitt** [comment]
closing old tickets..
