### ISSUE TITLE
OE6 pvr.hts not updated

### ISSUE THREAD

**Issue by grin1** [OpenELEC/OpenELEC.tv#4416]
Wiith Kodi 15.2 pvr.hts was updated to 2.1.18. I've updated to OE6 yesterday and still have pvr.hts version 2.1.16. It seems like you build the add-on from master branch (https://github.com/kodi-pvr/pvr.hts/commits/master). In the Isengard branch of pvr.hts (https://github.com/kodi-pvr/pvr.hts/commits/Isengard) 2.1.18 is the latest version.

**Comment by grin1** [comment]
Any comments?

**Comment by FuNK3Y** [comment]
I am facing the same problem with OE 6.0.0. 2.1.18 fixed a nasty bug with time shifting (fixes random skipping to the beginning of recordings).

From my understanding, pvr addons are not shipped with OE anymore. It should update directly from the kodi repository.

I'll try to play around tonight with my installation.

**Comment by CvH** [comment]
It looks like that the latest stable version isn't uploaded to the OE repo ping @sraue @lrusak !?

This problem is known since the day of release - I don't know if it is intentional to not update it.
I compiled them some time ago goo.gl/BbvIml - but this ***shouldn't*** be the fix to install out of repo versions for stable addons!

**Comment by chewitt** [comment]
It's not intentional.. and we are aware of the need to refresh things a little. It is, err, being looked at :)

**Comment by FuNK3Y** [comment]
Any idea when this would be addressed?

There is no urgency for me, but it would be convenient to have an ETA.

**Comment by chewitt** [comment]
I'm closing the ticket because this needs to be reported to Kodi devs not us. They have bumped addons in their Jarvis branch but haven't done changes for Isengard. If they do - we will pick them up and push newer addon versions to our 6.0 repo. Thanks.

**Comment by Jalle19** [comment]
This one also seems to have gotten wrongly closed. Kodi itself has the latest version of all respective addons, it's just the OE repositories that haven't been updated.
