### ISSUE TITLE
Totaly broken VDR in OpenELEC 6.0

### ISSUE THREAD

**Issue by odc2** [OpenELEC/OpenELEC.tv#4417]
I tought in 5.95.5 it were more then broken as reported here: https://github.com/OpenELEC/OpenELEC.tv/issues/4351

But on 6.0 its finally totaly broken (more broken then in the beta!).
I am completely not able to enable VDR + VNSI. I can go as often i like into the configuration of VDR backend and VNSI client and set them to default. Its impossible for me to enable VDR. 
I made 3 reboots. I disabled TV, set VDR and VNSI to default and enabled it - not working. I reboot then - still not enabled. I set them to default while TV enabled - not working. I disabled TV, turned off, turned on, set VDR and VNSI to default, reboot, turned TV on - not working.

Logfile: http://xbmclogs.com/prk3gohik

**Comment by odc2** [comment]
With turned on debugging: bootup, disable tv, set vdr to default, set vnsi to default, enable tv - not working:
http://xbmclogs.com/payi4ewyp

**Comment by fritsch** [comment]
User support is given with the forum. Consider this as a last warning - if you open yet again another bug-report without fulfilling our reporting policy - you are banned of this github place.

You don't have vdr installed and it is not running ... sorry it seems OpenELEC is not made for you - go and use something else, but stop going on the nerves of people.

**Comment by sraue** [comment]
dup of https://github.com/OpenELEC/OpenELEC.tv/issues/4351
