### ISSUE TITLE
Openelec 6: OpenELEC reset to defaults: counts from 100% to 0% and its done - that does not make sense

### ISSUE THREAD

**Issue by odc2** [OpenELEC/OpenELEC.tv#4421]
When i go to OpenELEC settings and do a "Hard reset" it starts then to count from 100% to 0% and it restart then.
That does not make any sense. When something is ready it normaly 100%. Not 0%.

**Comment by stefansaraev** [comment]
really? stop opening new tickets!!

**Comment by fritsch** [comment]
If you delete data then it is 100% full at the start and 0% full at the end ...
