### ISSUE TITLE
RPi2 build Error

### ISSUE THREAD

**Issue by JustMev** [OpenELEC/OpenELEC.tv#4424]
.arm-6.0-devel/toolchain/include -Wno-format-security -MT DecoderManager.o -MD -MP -MF $depbase.Tpo -c -o DecoderManager.o DecoderManager.cpp &&\
mv -f $depbase.Tpo $depbase.Po
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-std=c++11"
Makefile:444: recipe for target 'md5.o' failed
make[3]: *** [md5.o] Error 1
make[3]: *** Waiting for unfinished jobs....
Makefile:444: recipe for target 'DecoderManager.o' failed
make[3]: *** [DecoderManager.o] Error 1
Makefile:444: recipe for target 'XBTFWriter.o' failed
make[3]: *** [XBTFWriter.o] Error 1
Makefile:444: recipe for target 'TexturePacker.o' failed
make[3]: *** [TexturePacker.o] Error 1
make[3]: Leaving directory '/home/justme/OpenELEC.tv/build.OpenELEC-RPi2.arm-6.0-devel/kodi-16.0-beta1-9a5ddf5/tools/depends/native/TexturePacker/native'
Makefile:313: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/justme/OpenELEC.tv/build.OpenELEC-RPi2.arm-6.0-devel/kodi-16.0-beta1-9a5ddf5/tools/depends/native/TexturePacker/native'
Makefile:43: recipe for target 'native/TexturePacker' failed
make[1]: *** [native/TexturePacker] Error 2
make[1]: Leaving directory '/home/justme/OpenELEC.tv/build.OpenELEC-RPi2.arm-6.0-devel/kodi-16.0-beta1-9a5ddf5/tools/depends/native/TexturePacker'
make: *** [image] Error 2
justme@justme:~/OpenELEC.tv$

**Comment by stefansaraev** [comment]
upgrade your host compiler. gcc 4.4 is too old.
