### ISSUE TITLE
OpenElec 6.x Rapsberry PI 2 - shutdown.sh not invoked at shutdown or reboot command

### ISSUE THREAD

**Issue by xmayeur** [OpenELEC/OpenELEC.tv#4429]
Hello,
since the upgrade to Openelec version 6 on a Raspberry PI 2,  the "/storage/.config/shutdown.sh" script is not longer called  when a shutdown, reboot or halt command is issued.
Does something changed with this feature?
Regards,

**Comment by vpeter4** [comment]
It is still called as before. Your script is problematic.

**Comment by xmayeur** [comment]
Here a copy of the script - It always worked before the upgrade.
the script also works perfectly from a command line, as root.

From the log file, I see that the script starts indeed being executed, but it is as is the 'scp' command is not executed when I launch a shutdown or halt command. The 'rpi.off' file is never copied over the other system in that context. The "Stopped" message does not appear in the log file neither.
Is it possible that the system is effectively stopped before the scp command can execute ?

<shutdpwn.sh>
case "$1" in
  halt|poweroff)
    (
    date
    /usr/bin/scp ~/rpi.off root@192.168.0.16:/mnt/array1/share/telldus 2>&1
    echo "Stopped"
    ) |  tee -a /storage/shutdown.log
    ;;
  reboot)
    date >> /storage/shutdown.log
    echo "Reboot" >> /storage/shutdown.log
    ;;
  *)
    # your commands here
    ;;
esac

**Comment by vpeter4** [comment]
Maybe the script takes to much time - it can run only for a few seconds.

**Comment by tociek** [comment]
Actually I have the same issue as @xmayeur. My scripts takes only 1-2 seconds to run (its only an invocation of hyperion-remote.sh)

**Comment by fritsch** [comment]
Those shutdown scripts are not meant to do anything network like - it is also not guaranteed at all that network is still existing at this point of view. When it worked before - it was pure luck.

Kodi cannot cope with networking outage and suspend / resume is not supported at all. If it works by luck - you can be lucky - if not - it's sad.

**Comment by tociek** [comment]
Probably is a question to Kodi forum and not here, but I will ask anyway :) Is there a way to execute such script from "Kodi level" before the network goes down? Something like onShutdown() event?

**Comment by fritsch** [comment]
If you hack kodi - yes - of course. That's what I said: kodi initiates the suspend, but that's all it can do. Hacking a kodi that does what you want from within kodi is no issue at all :-) - but doing it in a generic way is.

**Comment by tociek** [comment]
Ok, thanks for info. I need to find different solution then...

**Comment by xmayeur** [comment]
OK, thanks as well. I was not aware of that limitation and I found another solution.
