### ISSUE TITLE
Raspberry Pi 1: update from 5.0.8 to 6.0.0 fails if remote MySql server is configured

### ISSUE THREAD

**Issue by twein** [OpenELEC/OpenELEC.tv#4431]
I have a Raspberry Pi running version 5.0.8 with a remote MySql server configured in advancedsettings.xml. When updating to version 6.0.0 (and 5.95.5 also), Kodi keeps restarting the splash screen forever.

The last lines in the log file are:

XX:XX:XX T:XXXX   ERROR: SQL: The table does not exist
                                            Query: SELECT idVersion FROM version

**Comment by chewitt** [comment]
End user support is provided via the forums, please start a thread there.
