### ISSUE TITLE
Bug in MyMusicNav.xml (Raspberry PI2)

### ISSUE THREAD

**Issue by noxx2015** [OpenELEC/OpenELEC.tv#4432]
following code dont work in OpenELEC-RPi2.arm-6.0-Milhouse-20151107210218-#1107-ge1c98c8

			<control type="image">
				<description>Cd Disc</description>
				<left>10</left>
				<top>0</top>
				<animation effect="slide" start="-118" end="0" time="900" tween="cubic" easing="out" delay="1000">WindowOpen</animation>
				<animation type="WindowClose">
					<effect type="slide" start="0" end="-114" time="800" tween="cubic" easing="in" delay="0"/>
					<effect type="fade" start="100" end="0" time="1300"/>
					<condition type="!Player.Playing"/>
				</animation>
				<animation effect="rotate" end="-360" center="auto" time="2000" loop="true" reversible="false" condition="!Player.Paused">Conditional</animation>
				<width>200</width>
				<height>200</height>
				<left>0</left>
				<top>0</top>
				<texture fallback="cdart\default.png">$INFO[Player.FolderPath]cdart.png</texture>
				<aspectratio align="bottom">keep</aspectratio>
				<visible>Skin.HasSetting(CdArtHome)</visible>
			</control>
			<control type="image">
				<description>Cover image</description>
				<left>10</left>
				<top>470</top>
				<width>150</width>
				<height>150</height>
				<aspectratio aligny="bottom">keep</aspectratio>
				<texture diffuse="masks/music_mask.png" fallback="DefaultAlbumCover.png">$INFO[Player.Art(thumb)]</texture>
				<bordersize>5</bordersize>
			</control>					
			<control type="label">
				<description>Album Label</description>
				<left>200</left>
				<top>490</top>
				<height>25</height>
				<width>1000</width>
				<label>$INFO[MusicPlayer.Artist,, - ]$INFO[MusicPlayer.Album]$INFO[musicplayer.discnumber, - $LOCALIZE[427]:]</label>
				<align>left</align>
				<aligny>center</aligny>
				<font>font45_title</font>
				<textcolor>blue</textcolor>
				<animation effect="slide" start="0,0" end="75,0" time="0" condition="Skin.HasSetting(CdArtHome)">Conditional</animation>
				<animation effect="slide" start="-20" end="0" time="900" tween="cubic" delay="900">WindowOpen</animation>
			</control>
			<control type="label">
				<description>Title label</description>
				<left>200</left>
				<top>530</top>
				<height>30</height>
				<width>1000</width>
				<label>$INFO[MusicPlayer.Title]</label>
				<align>left</align>
				<aligny>center</aligny>
				<font>font35_title</font>
				<textcolor>blue</textcolor>
				<animation effect="slide" start="0,0" end="60,0" time="0" condition="Skin.HasSetting(CdArtHome)">Conditional</animation>
				<animation effect="slide" start="-20" end="0" time="900" tween="cubic" delay="900">WindowOpen</animation>
			</control>
			<control type="label">
				<description>Time Label</description>
				<left>200</left>
				<top>585</top>
				<height>30</height>
				<width>300</width>
				<label>$INFO[Player.Time]$INFO[Player.Duration,[COLOR=blue] / [/COLOR]]</label>
				<align>left</align>
				<aligny>center</aligny>
				<font>font24_title</font>
				<textcolor>blue</textcolor>
				<animation effect="slide" start="0,0" end="35,0" time="0" condition="Skin.HasSetting(CdArtHome)">Conditional</animation>
				<animation effect="slide" start="-20" end="0" time="900" tween="cubic" delay="900">WindowOpen</animation>
			</control>
		</control>

**Comment by fritsch** [comment]
Hint: https://github.com/MilhouseVH

**Comment by popcornmix** [comment]
Actually the thread you got the *custom* build from would be the right place to report issues:
http://forum.kodi.tv/showthread.php?tid=231092
