### ISSUE TITLE
MCE remotes not working properly with Openelec 6.0.0 on Cubox-i

### ISSUE THREAD

**Issue by darioteixeira** [OpenELEC/OpenELEC.tv#4433]
I've updated a Cubox-i (iMX6) to Openelec 6.0.0 (was previously running 5.0.8).  After the upgrade, the MCE remote (it's actually a clone, not an original MCE remote) stopped working properly.  To be more precise, some of the buttons were not recognised any more, though others still worked.

I'm pretty sure this is related to bug #4157, which was perhaps closed prematurely.  The hack of linking `/storage/.config/system.d/eventlircd.service` to `/dev/null` gave me back some buttons, though others seem to have been remapped, and holding down a button results in jerky motion.

For now, the only real fix was downgrading back to 5.0.8.

**Comment by sraue** [comment]
if its not a MCE remote, then we need the exact infos about the remote and logs (cat /proc/bus/input/devices; evtest and irw output of the "wrong" mapped buttons)

**Comment by darioteixeira** [comment]
`/proc/bus/input/devices:`
```
I: Bus=0003 Vendor=05a4 Product=9881 Version=0110
N: Name="HID 05a4:9881"
P: Phys=usb-ci_hdrc.1-1/input0
S: Sysfs=/devices/soc0/soc.1/2100000.aips-bus/2184200.usb/ci_hdrc.1/usb2/2-1/2-1:1.0/0003:05A4:9881.0001/input/input0
U: Uniq=
H: Handlers=sysrq kbd event0
B: PROP=0
B: EV=120013
B: KEY=e080ffdf 1cfffff ffffffff fffffffe
B: MSC=10
B: LED=7

I: Bus=0003 Vendor=05a4 Product=9881 Version=0110
N: Name="HID 05a4:9881"
P: Phys=usb-ci_hdrc.1-1/input1
S: Sysfs=/devices/soc0/soc.1/2100000.aips-bus/2184200.usb/ci_hdrc.1/usb2/2-1/2-1:1.1/0003:05A4:9881.0002/input/input1
U: Uniq=
H: Handlers=kbd mouse0 event1
B: PROP=0
B: EV=17
B: KEY=1f0000 0 2020000 3878 d801d001 1e0000 0 0 0
B: REL=103
B: MSC=10

I: Bus=0019 Vendor=0001 Product=0001 Version=0100
N: Name="gpio_ir_recv"
P: Phys=gpio_ir_recv/input0
S: Sysfs=/devices/soc0/ir-receiver.23/rc/rc0/input2
U: Uniq=
H: Handlers=kbd event2
B: PROP=0
B: EV=100013
B: KEY=fff 0 0 200 108fc32e 2b76051 0 0 0 7 158000 4192 4001 9e9680 0 0 10000000
B: MSC=10

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="MCE IR Keyboard/Mouse (gpio-rc-recv)"
P: Phys=/input0
S: Sysfs=/devices/virtual/input/input3
U: Uniq=
H: Handlers=sysrq kbd mouse1 event3
B: PROP=0
B: EV=100017
B: KEY=30000 0 7 ff87207a c14057ff febeffdf ffefffff ffffffff fffffffe
B: REL=3
B: MSC=10

I: Bus=0003 Vendor=05a4 Product=9881 Version=0110
N: Name="eventlircd"
P: Phys=/dev/input/event1
S: Sysfs=/devices/virtual/input/input6
U: Uniq=
H: Handlers=mouse2 event4
B: PROP=0
B: EV=7
B: KEY=10000 0 0 0 0 0 0 0 0
B: REL=3
```

**Comment by sraue** [comment]
please provide the "irw" and evtest output of the non working buttinsplease provide the "irw" and evtest output of the non working buttins

**Comment by darioteixeira** [comment]
I've just tried doing a fresh install of OpenELEC instead of doing the upgrade.  And now everything works fine!  Do you still want the output from `irw` and `evtest`?  The culprit probably lies somewhere else.

**Comment by chewitt** [comment]
Closing as the user ^^ indicated normal function after a clean install. Thanks.
