### ISSUE TITLE
fail the size check during manual update to 6.0.0

### ISSUE THREAD

**Issue by emcek** [OpenELEC/OpenELEC.tv#4437]
Since Xtreamer-Ultra2 had GT520M I've used: OpenELEC-Generic.x86_64-6.0.0.tar
I downloaded twice with regular link and via torrent and in both cases during updating, md5sum checking failed.

**Comment by MilhouseVH** [comment]
If the md5sum failed, why have you referenced "size check" (a completely different kind of error) in the title? Failing the size check means your primary partition is too small and you need to resize your partitions. Failing the md5sum check means your download is corrupt.

Although really you should discuss this on the forum, it's not a bug.

**Comment by emcek** [comment]
windows report:
size: 159 MB (167 270 400 bytes)
size on disk: 159 MB (167 270 400 bytes)

**Comment by emcek** [comment]
yes sorry my fault I need resize sda1 since it's only 177 MB instead 256 MB. Really old (before 3.0) openelec was preinstalled, up to now it wasn't issue.
