### ISSUE TITLE
Macmini wakeup from standby with apple remote is broken after upgrade to OpenELEC 6.0.0

### ISSUE THREAD

**Issue by jcjdammers** [OpenELEC/OpenELEC.tv#4440]
Hello,

After I upgraded from OpenELEC 5.0.8 to 6.0.0 the wakeup from standby with my apple remote is no longer working on my Macmini (late 2012 model).

It worked fine under v5 after applying the instructions discussed in this forum thread --> http://openelec.tv/forum/103-infared-remotes/67878-apple-remote-won-t-wake-macmini2011-from-suspend?start=15
Basically what I did was enable wakeup function for my apple ir receiver on mac mini (2-1.8.2 as listed in lsusb) by creating a udevrule -->
SUBSYSTEM=="usb", ATTR{idVendor}=="05ac", ATTR{idProduct}=="8242", RUN+="/bin/sh -c 'echo enabled > /sys/bus/usb/devices/2-1.8.2/power/wakeup'" 

However with OE v6 it is broken.
I noticed some differences after the upgrade:
- my apple ir receiver on mac mini was listed as 4-1.8.2 in lsusb, this used to be 2-1.8.2.
- cat /proc/acpi/wakeup command shows S4 state for all listed devices, and this used to be S3

When my Macmini is in standby and I press the apple remote then I notice that the little light on my Macmini stops blinking and stays on, but my screen stays black and it seems to be stuck (also connecting with ssh is then not possible anymore).

Can you help me? Any suggestions would be much appreciated.

Thanks and regards,

Jeroen Dammers
j.c.j.dammers@gmail.com
The Netherlands

**Comment by chewitt** [comment]
I'm closing this ticket - support can continue in the forum thread. Thanks.

**Comment by jcjdammers** [comment]
ok, hope you can help me.
would be much appreciated.

Jeroen

2015-12-27 9:57 GMT+01:00 Christian Hewitt <notifications@github.com>:
