### ISSUE TITLE
Tethering issue on 6.0.0 no work

### ISSUE THREAD

**Issue by senufo** [OpenELEC/OpenELEC.tv#4450]
View this threads : 
http://openelec.tv/forum/69-network/78785-tethering-issue-on-6-0-0
and this
http://openelec.tv/forum/88-wlan/78727-tethered-wireless-access-point-down

I found the problem. This is iptables compiled into static.
I you revert commit b1f7cbe66 where iptables is build in static mode, the tethering work fine.

Below patch file for iptables package.mk file :
@ -32,4 +32,4 @@ PKG_LONGDESC="Iptables is used to set up, maintain, and inspect the tables of IP
 PKG_IS_ADDON="no"
 PKG_AUTORECONF="yes"
 
-PKG_CONFIGURE_OPTS_TARGET="--with-kernel=$(kernel_path) --enable-static --disable-shared"
+PKG_CONFIGURE_OPTS_TARGET="--with-kernel=$(kernel_path)"

**Comment by chewitt** [comment]
I built Generic and AppleTV images with this overnight and will have a test after work today.
