### ISSUE TITLE
No audio on Wetek in master

### ISSUE THREAD

**Issue by mcaptur** [OpenELEC/OpenELEC.tv#4451]
No audio in master on wetek play, RPi and x86 are fine. Also on wetek i cannot access sound settings, whne i try to go in audio settings, screen freezes for around 1 minute.

http://forum.kodi.tv/showthread.php?tid=247793&pid=2160817#pid2160817

**Comment by lrusak** [comment]
Please provide proper logs if you want us to help you 
http://wiki.openelec.tv/index.php/OpenELEC_FAQ#How_do_I_generate_support_logs.3F

**Comment by mcaptur** [comment]
http://pasted.co/f0b9da84

**Comment by mcaptur** [comment]
will add more logs later on

**Comment by walterheisenberg** [comment]
Fixed with PR #4456, which reverts #4411 
see thread in the kodi-forums: http://forum.kodi.tv/showthread.php?tid=247793&pid=2166079#pid2166079

**Comment by chewitt** [comment]
closing ^^
