### ISSUE TITLE
update to latest libressl (stable)

### ISSUE THREAD

**Issue by sraue** [OpenELEC/OpenELEC.tv#4453]

**Comment by lrusak** [comment]
Is this a typo?

**Comment by sraue** [comment]
where?

**Comment by sraue** [comment]
libressl <-- typo

**Comment by sraue** [comment]
added in https://github.com/OpenELEC/OpenELEC.tv/commit/b2da1ab7dc757bd2982f9796bbbd1f9ede8cb52c
