### ISSUE TITLE
update to dbus-1.10

### ISSUE THREAD

**Issue by sraue** [OpenELEC/OpenELEC.tv#4454]
@lrusak you tried this already and there was a problem?

**Comment by lrusak** [comment]
I have not tried yet

**Comment by lrusak** [comment]
Tested briefly with the OE settings add-on and didn't notice anything wrong.

**Comment by sraue** [comment]
can you make a PR if you have something? so it can be tested more widely

**Comment by sraue** [comment]
added in https://github.com/OpenELEC/OpenELEC.tv/commit/1117dfc1bfe37d48c5eb35e2c044e4a155bcd9da
