### ISSUE TITLE
upgrade broken after 297af74 on cubox-i4 pro

### ISSUE THREAD

**Issue by manofthepeace** [OpenELEC/OpenELEC.tv#4460]
Hi everyone,
  Maybe its known, but I've built the latest trunk for imx6 and when I try to upgrade from official OE 6.0, my cubox restarts but I cannot see anything on the screen (HDMI). I cannot get logs also since I have no SSH connection possible, nothing booted.

Regards.

**Comment by vpeter4** [comment]
I assume bootloader problem:
```
U-Boot SPL 2013.10-rc4 (Nov 22 2015 - 09:22:12)
Boot Device: SD1

U-Boot 2013.10-rc4 (Nov 22 2015 - 09:22:12)

CPU:   Freescale i.MX6Q rev1.2 at 792 MHz
Reset cause: POR
Board: MX6-CuBox-i
DRAM:  2 GiB
MMC:   FSL_SDHC: 0
*** Warning - bad CRC, using default environment

data abort

    MAYBE you should read doc/README.arm-unaligned-accesses

pc : [<8ff79a4a>]          lr : [<8ff79677>]
sp : 8f76edf8  ip : 00000000     fp : 8f773128
r10: 000010b8  r9 : 8f770f38     r8 : 8f771180
r7 : 8f771188  r6 : 8f773128     r5 : 8f77312c  r4 : 8f774940
r3 : 00000000  r2 : 00000001     r1 : 80000000  r0 : 00000000
Flags: nZCv  IRQs off  FIQs off  Mode SVC_32
Resetting CPU ...

resetting ...
```

**Comment by vpeter4** [comment]
This patch helps in folder projects/imx6/patches/u-boot
https://raw.githubusercontent.com/schnitzeltony/meta-gumstix-community/master/recipes-bsp/u-boot/u-boot-overo/0013-arm-Switch-to-mno-unaligned-access-when-supported-by.patch

**Comment by manofthepeace** [comment]
Indeed, it worked with that patch! Kodi was super slow to start but that's probably not related to patch/cubox itself.

Many thanks.

**Comment by vpeter4** [comment]
@sraue: is patch I linked ok or something else is better? I'm asking this because you already added two patches in packages/tools/u-boot/patches/ I missed before.

**Comment by sraue** [comment]
@vpeter4 please PR if it works

**Comment by sraue** [comment]
@manofthepeace can you test and report back here?

**Comment by manofthepeace** [comment]
It updated properly with the official fix, but for some reason, I've lost most of my kodi settings, not sure what caused that. Looks like guisettings.xml got overwritten somehow. But I guess that's a separate issue.. with libxml maybe?

**Comment by mhueske** [comment]
I can confirm that the current master is working on imx again. My settings are all still there, nothing lost. Thanks.
