### ISSUE TITLE
[6.0.0 Stable] Half recognition USB CD/DVD drive (RPi2)

### ISSUE THREAD

**Issue by brindosch** [OpenELEC/OpenELEC.tv#4462]
Tested with clean OE install on RPi2

OE mounts the drive via smb, i could access it and play the movie files.
But in Kodi there is no "play disc" label in confluence main menu. Worked with OE 5.X and the milhouse Jarvis builds.
Please post if you need specific log/s. Thank you

**Comment by chewitt** [comment]
does this still/currently work in current milhouse Jarvis builds?

**Comment by chewitt** [comment]
I'm closing the ticket due to lack of update. Thanks.
