### ISSUE TITLE
OpenELEC 6.0.0 stopped playing mp3 audio

### ISSUE THREAD

**Issue by novoid** [OpenELEC/OpenELEC.tv#4463]
Hi!

I did start with some OpenELEC 5.x and updated to OpenELEC 6.0.0 (Raspberry Pi 2) a week ago in order to get rid of studdered video playback. The update did fix the video playback issue.

Kodi (15.2 Git:02e7013). Platform: Linux ARM 32-bit
OpenELEC (official) - Version: 6.0.0, kernel: Linux ARM 32-bit version 4.1.12

However, now my internet radio stations do not work any more and I can't play my local mp3 collection any more.

This log lines I get when trying to play an internet streaming radio:
```
17:14:06 376946.593750 T:1968201728   ERROR: Open - Unhandled exception
17:14:06 376946.593750 T:1968201728   ERROR: Open - Error opening http://pub8.radiotunes.com:80/radiotunes_pianojazz_aacplus
17:14:06 376946.593750 T:1968201728   ERROR: Init: Error opening file http://pub8.radiotunes.com:80/radiotunes_pianojazz_aacplus
17:14:06 376946.593750 T:1968201728   ERROR: CAudioDecoder: Unable to Init Codec while loading file http://pub8.radiotunes.com:80/radiotunes_pianojazz_aacplus
17:14:06 376946.593750 T:1968201728 WARNING: PAPlayer::QueueNextFileEx - Failed to create the decoder
17:14:06 376946.593750 T:1968201728   ERROR: Playlist Player: skipping unplayable item: 58, path [http://pub8.radiotunes.com:80/radiotunes_pianojazz_aacplus]
```

Or this:
```
17:06:52 376512.250000 T:1968201728   ERROR: Open - Unhandled exception
17:06:52 376512.250000 T:1968201728   ERROR: Open - Error opening http://streaming.radionomy.com/ABC-Lounge
17:06:52 376512.250000 T:1968201728   ERROR: Init: Error opening file http://streaming.radionomy.com/ABC-Lounge
17:06:52 376512.250000 T:1968201728   ERROR: CAudioDecoder: Unable to Init Codec while loading file http://streaming.radionomy.com/ABC-Lounge
17:06:52 376512.250000 T:1968201728 WARNING: PAPlayer::QueueNextFileEx - Failed to create the decoder
17:06:52 376512.250000 T:1968201728   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.audio.radio_de/station/10597]
```

Approximately 17 times (number of tracks/album?) I get this log messages when trying to play an mp3 file from my local library:
```
17:32:08 284.326355 T:1967882240   ERROR: Open - Unhandled exception
17:32:08 284.326508 T:1967882240   ERROR: Open - Error opening musicdb://albums/352/31029.mp3?albumid=352
17:32:08 284.326752 T:1967882240   ERROR: Init: Error opening file musicdb://albums/352/31029.mp3?albumid=352
17:32:08 284.326904 T:1967882240   ERROR: CAudioDecoder: Unable to Init Codec while loading file musicdb://albums/352/31029.mp3?albumid=352
17:32:08 284.327026 T:1967882240 WARNING: PAPlayer::QueueNextFileEx - Failed to create the decoder
17:32:08 284.327301 T:1967882240   ERROR: Playlist Player: skipping unplayable item: 0, path [musicdb://albums/352/31029.mp3?albumid=352]
```

Video Add-ons do work. My sound add-ons don't.

I'm not an insider but I found following sentence in the release notes:
```Beginning with Kodi 15 most audio encoder, audio decoder, PVR and visualisation ad-dons are no longer included in our base OS, but they are available via Kodi's add-on manager and must be installed from there, if needed.```

Is it possible that I am missing the mp3 decoder?

I could not find any mp3 decoder in the Kodi decoding add-on list though.

Help appreciated. Greetings from Graz/Austria!

**Comment by chewitt** [comment]
I'm closing the ticket here because mp3 works in 6.0.0 - I've just spent 4x days listening to Christmas music which was all mp3). Please clear Kodi config (soft reset or stop/rename .kodi to .kodi-backup, restart) and/or update to a current milhouse Jarvis build for testing. If the issue remains please open a thread in the OpenELEC forums (this is not a user-help forum). Thanks.

**Comment by novoid** [comment]
I was able to "fix" the issue only by completely wiping my system and setting it up from scratch. :-(
