### ISSUE TITLE
master: kodi doesn't start (libcrypto.so.32, libssl.so.32)

### ISSUE THREAD

**Issue by susisstrolch** [OpenELEC/OpenELEC.tv#4471]
commit 34c14d59bfad29ec67f2a20cf49f8113d67dd530
wpa_supplicant, sshd and kodi don't start anymore because of wrong references to libraries.
The build version is .35, but kodi, wpa_supplicant and sshd expect a .32 version.

**Comment by stefansaraev** [comment]
really? what about make clean ;)

**Comment by susisstrolch** [comment]
Yep - hickup in buildsystem.
Introduced by "git subsystem update" and failed compile because of ffmpeg duplicate.
Sorry...
