### ISSUE TITLE
the storage partition doesn't get unmounted cleanly on shutdown

### ISSUE THREAD

**Issue by gdachs** [OpenELEC/OpenELEC.tv#4475]
Installed a build of the master branch from yesterday to a sd card for the wetek play. After a shutdown it will boot into Android. If I put the sd card to a linux system the journal of the storage partition gets repaired and after this the wetek will boot into OpenELEC again.

 Gerald

**Comment by stefansaraev** [comment]
booting to android has absolutely nothing to do with not cleanly unmounted /storage. you have some other unrelated issue. probably hardware (u-boot fails to detect your sdcard etc..)

**Comment by gdachs** [comment]
Okay, and how does this explain why I can boot again after I repaired the file system on the second partition?

**Comment by gdachs** [comment]
Did it again for the unbelievers.
Installed OE 6.0 on another previously working SD card. Wetek reboots fine.
Updated to OE master. Wetek reboots fine.
Powered off OE master, powered it on again, Wetek boots into android.

Inserted SD card in Desktop:
```
[ 4024.480952] sd 8:0:0:0: [sdb] 31116288 512-byte logical blocks: (15.9 GB/14.8 GiB)
[ 4024.501228]  sdb: sdb1
[ 4024.781371] FAT-fs (sdb1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
```
Repaired SD card and OE boots again.

Reboots work all the time, but power off, power on does not, never.

**Comment by ashjohnuk** [comment]
https://github.com/ashjohnuk/autoexec.py/blob/master/autoexec.py
I don't know if this helps... but seems to work flawless !

**Comment by gdachs** [comment]
How should this help? This script is for mounting SMB shares. This bug is about local SD cards.

**Comment by mcaptur** [comment]
This issue is till happening see http://wetekforums.com/v/index.php?p=/discussion/304/openelec-development-builds#latest
