### ISSUE TITLE
RPi2 Restart 

### ISSUE THREAD

**Issue by Mor-endai** [OpenELEC/OpenELEC.tv#4476]
Hello,

I'm currently using a Raspeberry Pi 2 with OpenElec.
Sometimes the system restarts on its own without any warning or sign. (It occurs mainly when I stream but not all the time)

Is it a safe operation done by the RPi2 or is it coming from OpenElec?
Is there any solution to this problem?

Thank you in advance for your answers.

**Comment by popcornmix** [comment]
Use forum for support requests.
https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md
