### ISSUE TITLE
Add Gadmei analog USB TV tuner support

### ISSUE THREAD

**Issue by milanvidakovic** [OpenELEC/OpenELEC.tv#4478]
Hello,
I would like to watch Live TV with the Gadmei USB TV tuner on OpenElec installed on my Raspberry Pi2.

lsusb for this tuner gives: 1f71:3301

Best regards,

Milan Vidaković

**Comment by lrusak** [comment]
After looking at it, it should work as the kernel driver is already included. Have you tried setting up VDR or tvheadend yet?

**Comment by fritsch** [comment]
Not sure how that should work at all - if it is Analog ...

2015-12-06 0:58 GMT+01:00 Lukas Rusak <notifications@github.com>:

> After looking at it, it should work as the kernel driver is already
> included. Have you tried setting up VDR or tvheadend yet?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4478#issuecomment-162258167>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by CvH** [comment]
```diff
diff --git a/drivers/media/usb/usbtv/usbtv-core.c b/drivers/media/usb/usbtv/usbtv-core.c
index 29428be..3bbc77a 100644
--- a/usbtv-core.c
+++ b/usbtv-core.c
@@ -127,6 +127,7 @@ static void usbtv_disconnect(struct usb_interface *intf)
 
 static struct usb_device_id usbtv_id_table[] = {
 	{ USB_DEVICE(0x1b71, 0x3002) },
+	{ USB_DEVICE(0x1f71, 0x3301) },
 	{}
 };
 MODULE_DEVICE_TABLE(usb, usbtv_id_table);
```

http://linuxtv.org/wiki/index.php/Gadmei_USB_TVBox_UTV382_(id_0x1f71:0x3301) tells us
hwid from this revision is not upstream, as always :(

**Comment by milanvidakovic** [comment]
Hello all, I have spent some time and I am not sure that linuxtv guys are right regarding the changes to the usbtv-core.c file. I mean, I was able to modify the usbtv kernel driver on my RPI (just as CvH noticed), but on the Raspbian OS (I am doing experiments on the Raspbian OS). I have modified the usbtv-core.c as requested, built and copied the usbtv.ko file to the appropriate location.

After that, I have put the tuner into the USB port, and usbtv driver reacted (dmesg output was ex expected). However, it seems that usbtv driver supports only the S-video and composite inputs of the device. It seems that the tuner part is not supported at all. 

scantv program reports that there is no tuner. qv4l2 application displayed only S-video and composite items in the source combo box. It looks like the usbtv driver is not the best solution for this device, since it doesn't support the tuner.

The most similar driver I have found for the UTV382 could be the em28xx driver. Inside the em28xx-cards.c file, there are several Gadmei usb tv devices, but not this particular one. The most similar is:
[EM2861_BOARD_GADMEI_UTV330PLUS] = {
		.name         = "Gadmei UTV330+",
		.tuner_type   = TUNER_TNF_5335MF,
		.tda9887_conf = TDA9887_PRESENT,
		.ir_codes     = RC_MAP_GADMEI_RM008Z,
		.decoder      = EM28XX_SAA711X,
		.xclk         = EM28XX_XCLK_FREQUENCY_12MHZ,
		.input        = { {
			.type     = EM28XX_VMUX_TELEVISION,
			.vmux     = SAA7115_COMPOSITE2,
			.amux     = EM28XX_AMUX_VIDEO,
		}, {
			.type     = EM28XX_VMUX_COMPOSITE1,
			.vmux     = SAA7115_COMPOSITE0,
			.amux     = EM28XX_AMUX_LINE_IN,
		}, {
			.type     = EM28XX_VMUX_SVIDEO,
			.vmux     = SAA7115_SVIDEO3,
			.amux     = EM28XX_AMUX_LINE_IN,
		} },
	},
It has tuner, it has IR port, just like the UTV382.

I know this is analog tuner, which is quite deprecated to use, but I need it. Ia am willing to do the experiments if someone has the idea how to make it work.

**Comment by milanvidakovic** [comment]
Hi everyone, I have plugged in this tuner into the RPI2 with OpenElec, and here is the output from the dmesg:
[    3.972643] usb 1-1.5.3: New USB device found, idVendor=1f71, idProduct=3301
[    3.972672] usb 1-1.5.3: New USB device strings: Mfr=3, Product=4, SerialNumber=2
[    3.972687] usb 1-1.5.3: Product: USB TV Box
[    3.972703] usb 1-1.5.3: Manufacturer: Gadmei
[    3.972717] usb 1-1.5.3: SerialNumber: 330000000009

I have installed the tvheadend from the unofficial repository, and my tuner is not supported: I went to the http://<addr>:9981, and clicked on the: Configuration. There I can find DVB Inputs tab and there is the TV Adapters tab. There is the list of adapters, which is empty. It seems that OpenElec with tvheadend doesn't support my tuner.

I have found this link:
https://tvheadend.org/issues/1810
It seems that it is possible to use analog tv tuners with the tvheadend and OpenElec. I am interested in doing the same with my usb tv tuner.

**Comment by chewitt** [comment]
I'm closing this ticket down because we're happy to patch usb id's (submit a pull request and we will merge for the next release) but we don't write kernel drivers - and that looks to be what's required to support the device with back-end services. Thanks.
