### ISSUE TITLE
wifi works in live USB, but no networks available after install

### ISSUE THREAD

**Issue by nashjc** [OpenELEC/OpenELEC.tv#4479]
Version 5.0.8 running on Asus EEE 900 with 2 GB Ram, 20 GB SSD.  (I think Broadcom wifi card)

Tried this several times (more than 1 install, just in case). The install is to the SD card, which on this netbook can be booted, which is desirable, as the main SSD has an install I want to keep.

Wondering if others have seen similar behaviour.  I'm thinking of just installing a live image on the Asus SD card.

JN

**Comment by chewitt** [comment]
I'm closing the ticket because end user support is provided through the forums, thanks.

**Comment by nashjc** [comment]
It looks like the settings default to wifi NOT enabled. However, my
development tasks have moved on to other issues. (I'm more a
reviewer/bug-finder than end-user. This was for a public presentation on
OpenElec.)

JN

**Comment by lrusak** [comment]
> It looks like the settings default to wifi NOT enabled.
This is the desired behaviour.
