### ISSUE TITLE
Intel NUC D54250WYKH - Output resolution  3840 × 2160 much darker picture than 1920x1080

### ISSUE THREAD

**Issue by Bob-I** [OpenELEC/OpenELEC.tv#4480]
Hi,
I recently acquired a new 4K TV. I have now set my Intel NUC to 3840x2160 resolution. The problem is, the picture is much darker than at 1920x1080. I have tried the limited color space setting and it helps somewhat but it's not as good a picture. I can see the difference in the menu already. Is this enough info for you to investigate and hopefully fix?
I run OpenElec 6.0.

**Comment by chewitt** [comment]
this is a development bug tracker and end-user help is provided via the forums, thanks.
