### ISSUE TITLE
New Nvidia driver in OE 6.0.0 causes refresh rate problems

### ISSUE THREAD

**Issue by TWuerdemann** [OpenELEC/OpenELEC.tv#4481]
Setup:
Intel Atom 330 Board
PCIe Card GT610
Connected to Onkyo TX 636 receiver over HDMI
Connected to Samsung D6500 over HDMI

When using the "change refresh rate" while playing videos cannot change to 25/50hz correctly.
The image looks vertically compressed and flickers. 
Switching the Input back and forth on the receiver resolves the problem.

When using the "legacy" build of 6.0.0 I don't have these Problems. All videos switch the TV to the correct refresh rate.

I think because the Problem is fixed by a change of the SW, that this is most likely a driver issue.

Is this known? Maybe there is already a fix? If not, I can prepare all information you might need. Just ask.

Regards,
  Thomas

**Comment by chewitt** [comment]
I'm closing the ticket because end user support is provided through the forums, thanks.
