### ISSUE TITLE
Openelec screen is isn't displayed when TV starts up Openelec 6 (RPi 2)

### ISSUE THREAD

**Issue by iceknife** [OpenELEC/OpenELEC.tv#4485]
In previous versions (openelec 5) when openelec was powered on before the tv was powered, the tv would be able to display the kodi interface . Currently when this happens the tv doesn't detect openelec and I have to reboot my raspberry pi to for the interface to be displayed.

**Comment by popcornmix** [comment]
Support questions belong in the forum not here.
This behaviour hasn't changed. If you want this to be supported then:
http://kodi.wiki/view/Raspberry_Pi_FAQ#TV_is_not_detected_unless_powered_on_first
