### ISSUE TITLE
Hifiberry Digi+ not working, only silence and sometimes 'clicks'

### ISSUE THREAD

**Issue by PluueeR** [OpenELEC/OpenELEC.tv#4501]
Sound doesn't work with a Hifiberry Digi+ add-on. In OpenELEC 6.0 it works like charm. In my build the audio output device is named: ALSA: Default (snd_rip_hifiberry_digi Analog). While in OpenELEC 6.0 it's named ALSA: Default (snd_rpi_hifiberry_digi_S/PDIF). The line in /flash/config.txt is in both the same:

dtoverlay=hifiberry-digi

Included are log of 'aplay -l' and 'dmesg'.

The passthrough option does work. But I guess it is (as it says) passing through the raw data in the stream. Everything else which is not AC-3 or DTS (music, airplay, gui sounds etc. etc.) is silent. Sometimes you hear some clicks though.

[aplay.txt](https://github.com/OpenELEC/OpenELEC.tv/files/63962/aplay.txt)
[dmesg.txt](https://github.com/OpenELEC/OpenELEC.tv/files/63963/dmesg.txt)

**Comment by PluueeR** [comment]
The passthrough option does work. But I guess it is (as it says) passing through the raw data in the stream. Everything else which is not AC-3 or DTS (music, airplay, gui sounds etc. etc.) is silent. Sometimes you hear some clicks though.

**Comment by PluueeR** [comment]
Small update. Later today I tried Millhouse's last Kodi 16 OpenELEC build r1204 (http://forum.kodi.tv/showthread.php?tid=231092) with succes. In this build the device is called: snd_rpi_hifiberry_digi_S/PDIF in Kodi.

I started to check some things to find out the differences between Millhouse's build and mine. As the Kernel versions where both 4.3.0 I tried to run my build with Millhouse's kernel and all works fine. Somehow the kernel configs are different. I just compiled the master Branch.

**Comment by lrusak** [comment]
@MilhouseVH do you use a different kernel config? Any other ideas?

**Comment by MilhouseVH** [comment]
I think this is due to the i2s config included in https://github.com/MilhouseVH/OpenELEC.tv/commit/4b17a757c648f0a631f94fcecbc5c0940e9e99d9 and merged along with 4.3.2.

**Comment by PluueeR** [comment]
I did a diff on the kernel config of the master branch and the one in Millhouses image:

Jorans-MacBook-Pro:Slaapkamer joran$ diff linux.arm.conf linux.arm.millhouse.conf 
324d323
< CONFIG_BCM2708_GPIO=y
326d324
< CONFIG_BCM2708_SPIDEV=y
332d329
< CONFIG_BCM2709_DT=y
1536d1532
< CONFIG_HW_RANDOM_BCM2708=m
1611d1606
< CONFIG_SPI_BCM2708=m
1911d1905
< CONFIG_BCM2708_WDT=m
2537d2530
< CONFIG_SND_BCM2708_SOC_I2S=m
3109a3103
> CONFIG_DMA_BCM2835=y
3115d3108
< CONFIG_DMA_BCM2708_LEGACY=y

**Comment by lrusak** [comment]
@MilhouseVH maybe one or more of those options shouldn't have been removed in @4b17a757c648f0a631f94fcecbc5c0940e9e99d9 ?

**Comment by MilhouseVH** [comment]
> maybe one or more of those options shouldn't have been removed in @4b17a75 ?

No, they should be added - my reference to i2s may have been confusing.

The exact description of the [patch](http://nmacleod.com/public/oebuild/patches/00_kernel_4_3.txt) as I had/have it in my builds is: "Enable DMA_BCM2835, needed by i2s audio cards in 4.3 kernel".

This patch is now in #4492.

**Comment by PluueeR** [comment]
Do I understand correctly that if I re-clone the master branch and compile the problem is solved? 

I'm new to GitHub :-)

**Comment by lrusak** [comment]
So what are you saying? All is good and that he should try building again with a fresh ```git pull```?

**Comment by MilhouseVH** [comment]
> he should try building again with a fresh `git pull`?

That should work, yes.

**Comment by lrusak** [comment]
@PluueeR please pull latest changes from master and rebuild. Then close this if it works.

**Comment by PluueeR** [comment]
I will!

**Comment by PluueeR** [comment]
Rebuild and tested. Everything works fine.
