### ISSUE TITLE
pvr.vbox stuck at version 1.3.8

### ISSUE THREAD

**Issue by Jalle19** [OpenELEC/OpenELEC.tv#4503]
OE 6.0 ships with an old version, 1.3.9 contains a critical fix, without which the addons stops working after about one hour. 

Reference: http://forum.kodi.tv/showthread.php?tid=246312

**Comment by CvH** [comment]
pvr.stalker , pvr.hts, pvr.filemon?, pvr.mythTV are outdated too
also see https://github.com/OpenELEC/OpenELEC.tv/issues/4416

**Comment by chewitt** [comment]
I'm closing the ticket because this needs to be reported to Kodi devs not us. They have bumped addons in their Jarvis branch but haven't done changes for Isengard. If they do - we will pick them up and push newer addon versions to our 6.0 repo. Thanks.

**Comment by Jalle19** [comment]
That's not correct, 1.3.9 is the latest tagged release in the addon's Isengard branch.
