### ISSUE TITLE
Network connection drops while WiFi dongle do background scanning

### ISSUE THREAD

**Issue by mlade77** [OpenELEC/OpenELEC.tv#4504]
I am using Raspberry Pi2 with OpenELEC 6.0.0 and recently bought USB WiFi dongle ZYXEL NWD-2205.
Network connection drops occur, for a second or two, every time when WiFi does scan for networks.
According the default config of "connman" located at /etc/connman/main.conf, connman scans for new networks every 5min and since the partition is RO mounted, because it comes from squashfs, it is impossible to configure "BackgroundScanning" to false.
In fact according to me background scanning shouldn't create such issue and do not know if it is bug or no but it is very annoying while some movie is being watched or big mp3 stream listened

I managed to found one old thread for same problem but it ends with no solution for me. https://github.com/OpenELEC/OpenELEC.tv/issues/1956

**Comment by chewitt** [comment]
cp /etc/connman/main.conf /storage/.config/connman_main.conf .. edit as necessary and reboot

**Comment by mlade77** [comment]
Hello Christian,

I made what you suggested me and it fixed my issue.
Let me tell you now another problem that I faced.
When I mount, never-mind via NFS or SMB, shared directory to the KODI and issue reboot command, it takes around 3min.~5min. for KODI to restart if it restarts at all, cause sometimes it doesn't restart and I have to turn Raspberry off and on. Also because of that I noticed that the system clock is zeroed. This issue happens only when I am using WiFi, if I use cable it doesn't happens.
If you tell me how I could provide debug output to you so you can be oriented what is going on.

thanks

**Comment by chewitt** [comment]
this is not supposed to be a help channel.. please open threads in the forums, thanks.

**Comment by mlade77** [comment]
Hello  Christian,

Correct me if I am wrong but I think that last one which I replied at 
#4504 <https://github.com/OpenELEC/OpenELEC.tv/issues/4504>. is a issue.
I suppose that on reboot network is down before kodi umount network 
shares, some services can reach the shares and that causes the hang.

cheers
