### ISSUE TITLE
JMC250 PCI Express NIC support broken

### ISSUE THREAD

**Issue by lodagro** [OpenELEC/OpenELEC.tv#4508]
Long time OpenELEC user on my Shuttle XS35GTA V3 Mini-Barebone (Intel NM10 Express).
Up to now using version 3.2.4 (x86_64) all working fine, including wired network connection with the on board nic (Ethernet controller: JMicron Technology Corp. JMC250 PCI Express Gigabit Ethernet Controller (rev 03)).

Tried a new install to 6.0.0 (x86_64), install went fine - except the nic is not detected.
I also tried versions 4.2.1 (x86_64), 4.97.2 (x86_64) before and these had the same problem. See also my [post](http://openelec.tv/forum/69-network/74259-no-nic-detected-using-4-2-1-4-97-2-ok-for-3-2-4#125590) of about one year ago on the OpenELEC forum

So i re-installed 3.2.4 (x86_64) to get wired network running.

Details on my machine and network card, retrieved using version 3.2.4 (x86_64):
OpenELEC:~ # lspci -v | paste
[http://sprunge.us/HbME](http://sprunge.us/HbME)
OpenELEC:~ # dmesg | paste
[http://sprunge.us/jYiW](http://sprunge.us/jYiW)

**Comment by lrusak** [comment]
Looks like the driver is loaded and working fine.

Seems like you aren't getting an ipv4 address. Can you go into the OpenELEC settings addon and make sure you haven't disabled wired connections and that it is set to dhcp.

**Comment by lodagro** [comment]
Note that the 'paste' logs are on the version  3.2.4 (x86_64), which is working fine. For the other versions i tried there is no menu to select dhcp or manual ip address, since no network card is detected. I have not disabled wired connection.

**Comment by lrusak** [comment]
Ah. The kernel driver is still included. No idea what's happenin. 

Add ```debugging``` to the cmdline arguments and then get to a local console with ctrl+alt+f3. http://wiki.openelec.tv/index.php/Boot_Arguments

**Comment by lodagro** [comment]
Looks like a deadlock, i need a console to edit the boot arguments in order to get a console? What am i missing?

**Comment by lrusak** [comment]
You can plug the disk/usb stick into another computer and edit it.

**Comment by lodagro** [comment]
Changed the file syslinux.cfg to text below (adding ````debugging```` to boot line) and installed again. After install and startup, pressing ctrl+alt+f3 briefly shows the splash, next the screen goes black. Nothing happens any more.

````
SAY Press <TAB> to edit options
DEFAULT installer
TIMEOUT 50
PROMPT 1

LABEL installer
  KERNEL /KERNEL
  APPEND boot=UUID=0111-1006 installer quiet tty vga=current debugging

LABEL live
  KERNEL /KERNEL
  APPEND boot=UUID=0111-1006 live quiet tty vga=current debugging
````

**Comment by lrusak** [comment]
you haven't even installed OE yet?

**Comment by lodagro** [comment]
This is what i did:
First i plugged the install usb into another computer and searched a bit on where to set the boot arguments.  Did a guess and edited the file sysliux.cfg (see above). Is this the correct place to add the ````debugging```` boot argument? After the edit i installed OE on my HTTPC. Full install, reboot, xbmc running and next i tried ```ctrl+alt+f3```, after which screen goes black.

**Comment by lrusak** [comment]
you will have to set the boot arguments on the new install. They won't carry over.

**Comment by lodagro** [comment]
Isn't that what i did? I edited the install usb of version  6.0.0 (x86_64), after which i used it to install it. And after install i tried to enter debugging mode.

**Comment by lrusak** [comment]
No, you set the boot argument before the install, that won't work. You need to do so after you install it.

**Comment by lodagro** [comment]
Is there any documentation on how to do this?
I don't have a console on the httpc after install, and editing the boot argument on the usb before using it to install OE on the httpc does not work.

**Comment by lrusak** [comment]
Take the drive out and put it in another PC and edit it that way or use a serial cable.

**Comment by lodagro** [comment]
Oh, take the drive out, painfull.
Are there no debug builds available?

**Comment by lrusak** [comment]
Or you can boot another live distribution (not openelec) and do it on the same computer

**Comment by chewitt** [comment]
```sudo ethtool -s eth0 speed 100 duplex full```

^^ add "tty" to kernel boot params so you can bring up a console using CTRL+ALT+F3 and run the above command. Does this get the NIC working?

**Comment by chewitt** [comment]
I'm closing this ticket due to lack of update. If the OP responds it can be reopened. Thanks.
