### ISSUE TITLE
audio and video output

### ISSUE THREAD

**Issue by harisj16** [OpenELEC/OpenELEC.tv#4511]
hi
i have installed openelec 6.0 on my m8 2gb box. installation went fine. but the video output is 720p. i was unable to change it to 1080p. when i go to video output setting it is fixed in 720p . i got no option to change. audio was same thing stuck at spdif. when i play audio no audio either. then i install olderversions of openelec 5.95 and 5.08. now the audio is comong but the video resolution remains 720p. i couldnt change anything . audio is playing but the setting still locked.
can some one please help me

**Comment by lrusak** [comment]
Sorry, m8 device is unsupported by us. User support is provided via the forums. Please ask wherever you downloaded the build.

**Comment by chewitt** [comment]
AMLogic support: http://tinyurl.com/amlogic-issues
