### ISSUE TITLE
No network (not even wired) with Openec box after #4495?

### ISSUE THREAD

**Issue by LouiS22** [OpenELEC/OpenELEC.tv#4516]
Hi folks,

The latest dev build (#4512) breaking the network connection (at least for me). No wired, no wireless connection. I'm using Openec box from Wetek. Had to go back to stable one.  I'm using DHCP and from there a static IP to for the device. This issue seems started (or went to the repo) a few days ago (my guess is #4495). Hope this helps, if you need further info, please let me know! 

PS: Keep up with this awesome work ;)

**Comment by lrusak** [comment]
Do a clean build and report back.

#4495 has nothing to do with this....

**Comment by LouiS22** [comment]
Thanks for the prompt reply. Just started a clean build, will report back with the results.

**Comment by NoNaMe-Lviv** [comment]
Works

**Comment by chewitt** [comment]
closing..
