### ISSUE TITLE
pvr.vdr.vnsi is broken

### ISSUE THREAD

**Issue by Karl-opec** [OpenELEC/OpenELEC.tv#4518]
Kodi 16-beta5 does not load pvr.vdr.vnsi. because of version differences. Which is the right
Version?, where can i find it?, to build.

**Comment by lrusak** [comment]
PROJECT=something ARCH=something ./scripts/create_addon pvr.vdr.vnsi

Will build it for you using the latest version

**Comment by Karl-opec** [comment]
Sorry, after a clean Build of openelec the issue has gone away.
