### ISSUE TITLE
Fuse /packages/sysutils/fuse/package.mk

### ISSUE THREAD

**Issue by Lusephur** [OpenELEC/OpenELEC.tv#4521]
Source has moved from sourceforge see http://sourceforge.net/projects/fuse/files/?source=navbar

Any change of updating the package.mk file to point to the correct source?

**Comment by Lusephur** [comment]
###edited package.mk to retrieve the tar.gz. Might not be to required specifications. 


################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2014 Stephan Raue (stephan@openelec.tv)
#
#  OpenELEC is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  OpenELEC is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

PKG_NAME="fuse"
PKG_VERSION="2.9.4"
PKG_REV="1"
PKG_ARCH="any"
PKG_LICENSE="GPL"
PKG_SITE="https://github.com/libfuse/libfuse/releases/download/"
PKG_URL="https://github.com/libfuse/libfuse/releases/download/fuse_2_9_4/fuse-2.9.4.tar.gz"
PKG_DEPENDS_TARGET="toolchain"
PKG_PRIORITY="optional"
PKG_SECTION="system"
PKG_SHORTDESC="fuse: A simple user-space filesystem interface for Linux"
PKG_LONGDESC="FUSE provides a simple interface for userspace programs to export a virtual filesystem to the Linux kernel. FUSE also aims to provide a secure method for non privileged users to create and mount their own filesystem implementations."

PKG_IS_ADDON="no"
PKG_AUTORECONF="yes"

PKG_CONFIGURE_OPTS_TARGET="--enable-lib \
                           --enable-util \
                           --disable-example \
                           --enable-mtab \
                           --disable-rpath \
                           --with-gnu-ld"

pre_configure_target() {
# fuse fails to build with GOLD linker on gcc-4.9
  strip_gold
}

post_makeinstall_target() {
  rm -rf $INSTALL/etc/init.d
  rm -rf $INSTALL/etc/udev
}

**Comment by MilhouseVH** [comment]
Submit a Pull Request...

**Comment by Lusephur** [comment]
Can't at present, I'm away from the pc till Dec 29th. I included a zip of the edited package.mk before heading to the airport. If someone else wishes to make a pr then please do. I'm not sure about the url request for fuse-2.9.4 (if it fits guidelines, but it works.)

**Comment by CvH** [comment]
https://github.com/OpenELEC/OpenELEC.tv/pull/4523
