### ISSUE TITLE
iptables 1.6 stop networking on amlogic devices

### ISSUE THREAD

**Issue by assafla** [OpenELEC/OpenELEC.tv#4527]
Hi. after updating to 1.6 iptables i have no network interfaces in kodi.

**Comment by MilhouseVH** [comment]
Do a clean build if you haven't already.

**Comment by assafla** [comment]
Did a clean build. didnt work. still no network.

**Comment by assafla** [comment]
If I revert back to iptables 1.4 it works fine

**Comment by axbmcuser** [comment]
Network on Intel D54250WYKH stopped working for me, too.

**Comment by NoNaMe-Lviv** [comment]
for my wetek, networks works.
make clean and build.

**Comment by assafla** [comment]
Ive removed the entire build dir and make build again with no success.

**Comment by NoNaMe-Lviv** [comment]
img?

**Comment by assafla** [comment]
Im building for x8hp amlogic

**Comment by chewitt** [comment]
I'm closing the ticket here as we don't provide or support the AMLogic builds. Please raise the issue over here: https://github.com/codesnake/OpenELEC.tv. Thanks.

**Comment by assafla** [comment]
you are building for wetek and it is an amlogic based device...
