### ISSUE TITLE
.url files for fuse point [wrongly] to sourceforge (should be github)

### ISSUE THREAD

**Issue by lsr1** [OpenELEC/OpenELEC.tv#4530]
when trying to build oe, this fails because the .url files on 

http://sources.openelec.tv/mirror/fuse/

contain URLs that point to sourceforge. however, on the sf page http://sourceforge.net/projects/fuse/files/ one can read: 

"As of 2015-12-22, this project may now be found at https://github.com/libfuse/."

2015-12-25 22:30 CET lsr1:
Uhm sorry, I'm new at this :-/ - so here is more info. When i try to build, the following happens:

*******snip*********

  GET      fuse
--2015-12-25 21:40:08--  http://prdownloads.sourceforge.net/fuse/fuse-2.X/2.9.4/fuse-2.9.4.tar.gz
Resolving prdownloads.sourceforge.net (prdownloads.sourceforge.net)... 216.34.181.59
Connecting to prdownloads.sourceforge.net (prdownloads.sourceforge.net)|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-12-25 21:40:08 ERROR 404: Not Found.

--2015-12-25 21:40:08--  http://sources.openelec.tv/mirror/fuse/fuse-2.9.4.tar.gz
Resolving sources.openelec.tv (sources.openelec.tv)... 82.220.2.33
Connecting to sources.openelec.tv (sources.openelec.tv)|82.220.2.33|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-12-25 21:40:08 ERROR 404: Not Found.

*******snap*********
The direct dl fails (for obvious reasons), and the backup via sources.openelec.tv fails then too.

Also, this might be obvious to anybody here anyway ... but I have found the old reference in 
OpenELEC.tv/packages/sysutils/fuse/package.mk

2015-12-25 22:46 CET lsr1:
Had to add that: Thank you for this great project (OpenElec) and all the hard work you are doing!

**Comment by MilhouseVH** [comment]
Have you pulled the latest version of the fuse package from master - it now points at github.

Non-master branches may still be pointing at sourceforge.

**Comment by lsr1** [comment]
https://github.com/OpenELEC/OpenELEC.tv/commit/1f7ecc3f19b823123a3293a4d99f64d702dc2b41

should have gotten the newest version before posting - was fixed 2 days ago. apologies. :-(
