### ISSUE TITLE
Content added after 2015 do not appear in recents

### ISSUE THREAD

**Issue by gareth820** [OpenELEC/OpenELEC.tv#4569]
Content from NAS with dates after 2015 are not appearing under recents in the iMX6 version of Isengard.
I have both a Raspberry Pi 2 and a Cubox i4Pro. The same content appear correctly in the Raspberry Pi but not in the Cubox. I have double checked the date and time stamps and verified that they are correct. Content added after Dec 31 2015 appear as the oldest files in lists sorted by date added and do not appear in the recent preview sections above the menu bar.

**Comment by MilhouseVH** [comment]
What "date added" dates are in the Kodi database for the post-2015 content on the imx6? And for the same media, what "date added" dates are in the database on the RPi? And what is the modification timestamp as reported by the NAS?

**Comment by gareth820** [comment]
Hi... I just checked the databases and here is what i have found:
                                      NAS                                         RPI 2                                    iMX6
Date/Time        2 Jan 2016 / 11:56 PM              2016-01-01 / 19:10:00        1970-01-01 / 8:00:30

I tried it again just now. I removed the content from the library and rebooted Kodi to force a rescan and this time, it was added properly... I tried this several times yesterday but it never came out right.

**Comment by chewitt** [comment]
I'm closing this as there's no discernible problem.
