### ISSUE TITLE
No HDMI audio on the Kangaroo computer (Intel Atom X5-Z8500)

### ISSUE THREAD

**Issue by jmdacruz** [OpenELEC/OpenELEC.tv#4572]
Device in newegg: http://www.newegg.com/Product/Product.aspx?Item=N82E16883722001

I was able to boot OE 6 via an SD card, and performance is great except for the lack of audio. There is a related post in the forums (http://openelec.tv/forum/68-audio/79230-no-audio-on-kangaroo) in which somebody points out this SoC may never be supported. This would be very sad, considering that these devices are becoming ubiquitous, they are quite cheap, and performance for OE is excellent. What's the issue that prevents support for these SoCs in OE 6?

**Comment by MilhouseVH** [comment]
seo already replied to you in the thread, explaining the unfortunate situation regarding Linux and audio drivers for this chipset, which is designed for Windows (as that is how it is sold).

Short of OpenELEC developers writing an audio driver just for this chipset (which isn't going to happen) there's nothing anyone can do. Use it to run Windows, or get your money back (or use it as a headless Linux device).

**Comment by chewitt** [comment]
All users with an unsupported device claim it is super popular and will result in mass adoption. If your claim proves true someone upstream will add audio drivers to the Linux kernel and then it's a simple patch or kernel config change - which we will be happy to do. Until then, this is closed because it's not possible. Thanks.

**Comment by jmdacruz** [comment]
Thanks, that's what I needed to know... It wasn't clear on the forum whether this was a missing Linux kernel driver or something else.

**Comment by sraue** [comment]
would be intresting to see: http://openelec.tv/forum/68-audio/79230-no-audio-on-kangaroo#154862

**Comment by jmdacruz** [comment]
Yep, was I just mentioned on the forum that I'll gladly provide that information (I'll post it here).

**Comment by jmdacruz** [comment]
Here you go @sraue: https://gist.github.com/jmdacruz/f8f2d9735244e9b4b3a9

**Comment by chewitt** [comment]
update to a milhouse test build that includes a newer kernel

**Comment by sraue** [comment]
please test this build and provide the same logs http://snapshots.openelec.tv/OpenELEC-Generic.x86_64-6.0-devel-20160104091551-r21696-gac9f6fb.tar

**Comment by jmdacruz** [comment]
@sraue, tested with version devel-20160104091551-r21696-gac9f6fb: https://gist.github.com/jmdacruz/80ef6243850957da2f46

**Comment by sraue** [comment]
please test http://snapshots.openelec.tv/OpenELEC-Generic.x86_64-7.0-devel-20160105070612-r21825-gc7acc67.tar it will become oe-7 later and has a new kernel. provide the same logs. if this will not work we have to wait until there are proper drivers...

**Comment by jmdacruz** [comment]
@sraue, as requested [here](https://github.com/OpenELEC/OpenELEC.tv/commit/4d1f7ff9c7c6addff23f43439d49ab33343168fd#commitcomment-15258718), tested with version devel-20160105070612-r21825-gc7acc67: https://gist.github.com/jmdacruz/fa6b5db5c041b145d8a6

Couple of comments:
* Kodi's UI sort of hanged during startup, I had to SSH into the box and do ```systemctl restart kodi``` in order to get it up and running. This only happened the first time.
* This might be related to the fact that I have been having issues with the wireless upon reboot: OE starts Kodi after the network wait timeout expires, without a successful connection. I have to manually activate the network on the OE settings and then restart Kodi manually with systemctl
* The Audio settings page now shows "PulseAudio Sound Server" as the only option on the "Audio output device" item in Kodi's "Audio output" menu in settings. As an improvement from the previous builds, the UI doesn't hang-up when navigating to the audio settings menu.
* As you can probably tell from the logs, there's still no audio output via HDMI.

**Comment by sraue** [comment]
thanks much, then the only solution actually will be a external USB soundcard until the drivers are updated/included in kernel

**Comment by jmdacruz** [comment]
Sounds good. Question for you, @sraue: What would be the best way to track this? Should we leave this issue open until drivers are available in the linux kernel? There are a few issues on the Kernel's bugzilla that might be related, [here](https://bugzilla.kernel.org/show_bug.cgi?id=86581), [here](https://bugzilla.kernel.org/show_bug.cgi?id=109131) and [here](https://bugzilla.kernel.org/show_bug.cgi?id=95681), which you can link to this issue.

**Comment by escalade** [comment]
It can be supported with a patch now: http://www.cnx-software.com/2016/04/19/hdmi-audio-in-linux-is-now-working-on-cherry-trail-mini-pcs-openelec-7-0-image-released/

**Comment by sraue** [comment]
ca you test http://snapshots.openelec.tv/OpenELEC-Generic.x86_64-8.0-devel-20160426180528-r22685-g65d4dac.tar and report back?

**Comment by escalade** [comment]
Sorry I don't have this unit, just came across the info when researching it. It's not released in Europe yet, but I'm thinking of buying one when it is. Great price for such a small and neat Intel box. Anyways, hopefully one of the previous commenters can test it.

**Comment by maxengel** [comment]
I can test, but being new to OE, are there instructions on how to apply that devel branch version.

**Comment by sraue** [comment]
simply update to this version with putting the tar file in updates samba share (see: http://wiki.openelec.tv/index.php/Updating_OpenELEC#Manually_Updating_OpenELEC )

**Comment by maxengel** [comment]
Sorry for being dense (and new) but when I copy the install image to a USB drive, it simply says "boot." I can hit tab for options, and am presented with "live" or "install".

**Comment by jmdacruz** [comment]
These are excellent news! I'll test the build within the next couple of days and report back (My unit has been sitting in a box since I posted this issue... SD card with OE ready and all)

**Comment by jmdacruz** [comment]
@sraue Let me know if there is a newer build you'd like me to test... right now I'm about to test this one: http://snapshots.openelec.tv/OpenELEC-Generic.x86_64-8.0-devel-20160426180528-r22685-g65d4dac.tar

**Comment by sraue** [comment]
there is no newer build which changes anything related to this issue report

**Comment by jmdacruz** [comment]
It seems you are up to something here, @sraue ! I tested this new build, and I was able to get audio via HDMI (hooray!), both for GUI sounds and videos.

The bad news is that Kodi keeps crashing (it gets into a "crash and restart" cycle). It's important to mention that the OS itself is not crashing, it's just Kodi that keeps crashing. The weird thing is that the crash doesn't seem to be related to the audio situation at all (at least not on the surface...): Kodi crashes consistently and precisely a few seconds (less than 10) after it starts, every single time, no matter if you are trying to play a movie or doing nothing.

Luckily, I had enabled SSH access with the previous build (in which Kodi was working fine, except for the missing audio of course), so I was able to get the crashlogs. I've created a gist with 7 different crashlogs, here (I've removed some private information such as usernames, passwords, and internal IP address, but the rest should be there): https://gist.github.com/jmdacruz/fdf126e55b69e4999d9926534a48d853

Let me know if you need me to test anything else or provide any other info... you guys are so close to get this thing running!

**Comment by jmdacruz** [comment]
@sraue bumping this thread... let me know if there are any new builds I can test.

**Comment by Schlesiger** [comment]
Any updates on this?

**Comment by fritsch** [comment]
Works here:
http://forum.kodi.tv/showthread.php?tid=269815&pid=2356552#pid2356552

Btw. these boxes have cripled hardware with (until now) no mainline kernel
support. It's not on OE or LE to patch that stuff in. As it is quite
intrusive and every kernel shipped with these patches won't receive
upstream support anymore as it touches relevant important global audio
parts.

2016-06-11 22:13 GMT+02:00 Connor Schlesiger <notifications@github.com>:

> Any updates on this?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4572#issuecomment-225391784>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABCfHXmCpo748W1-qeJq69H8zuN73NOjks5qKxbogaJpZM4G90LE>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by jmdacruz** [comment]
@fritsch Yep, that's understood. The build that @sraue sent above already has said patch from the upstream kernel, and it's actually working just fine. The last problem I reported seems to be a complete different thing, but since it was related to this thread I just listed it here. I'll give LibreELEC a try on this box if it's actually working.

**Comment by Schlesiger** [comment]
@fritsch LibreELEC audio works with the z8500/Kangaroo? I tried the latest from that thread and still had no audio.

**Comment by fritsch** [comment]
Patch was removed as not suitable for Kernel 4.7 anymore. Use an older 4.6
based build, please.
Am 14.07.2016 3:53 vorm. schrieb "Connor Schlesiger" <
notifications@github.com>:

**Comment by Schlesiger** [comment]
@fritsch Thanks! It's working now!

**Comment by jmdacruz** [comment]
How can I find a build based on 4.6? Nothing here (http://snapshots.openelec.tv/) indicates the kernel version. Thanks!
