### ISSUE TITLE
With recent inclusion of Pulse Audio in Master AAC2.0 isn't working properly

### ISSUE THREAD

**Issue by pyrodex** [OpenELEC/OpenELEC.tv#4585]
I noticed last night after a clean re-compile and upgrade to a master copy that files with AAC2.0 were silent and not playing audio. I tried a 5.1 file without any issues and was able to revert to HDMI0 and the same file played just fine. 

I have a 5.1 setup and a 2.0 setup and both exhibited the same problems. 

Debug log from the 5.1 setup below.

http://paste.ubuntu.com/14431337/

**Comment by lrusak** [comment]
Don't use the "Pulseaudio Sound Server" audio device in kodi. This is for bluetooth audio only.

**Comment by pyrodex** [comment]
Is there a way to make Pulse Audio a lesser choice in the selection options or by default in OpenELEC? It seems to be the default choice out of the gate and not sure if there is a way to control this behavior if this is only for Bluetooth audio.

**Comment by lrusak** [comment]
Possibly, but it would take some patching I think.
