### ISSUE TITLE
ArchLinux wrong package name for uboot-tools

### ISSUE THREAD

**Issue by foxbunny** [OpenELEC/OpenELEC.tv#4588]
```
error: target not found: u-boot-tools
````

Actual package name is `uboot-tools`.

**Comment by lrusak** [comment]
and what does this have to do with OpenELEC?

**Comment by chewitt** [comment]
I'm closing the ticket because Ubuntu and Fedora are the only distros we code dependent package install support for when building. If you want to build on another distro the build process will probably work but it becomes your responsibility to have all the correct packages installed.

**Comment by foxbunny** [comment]
Maybe the build should just fail in that case instead of pretending to support the distro? Or print a clearer message about it?

**Comment by lrusak** [comment]
Why not submit a PR?

**Comment by foxbunny** [comment]
To clarify:

```
**** Your system lacks the following tools needed to build OpenELEC ****
mkimage
**** You seem to use a arch system ****
would you like to install the needed tools ? (y/n)
```

This (mis)leads me to believe that it has Arch Linux support, which it apparently does not.

**Comment by foxbunny** [comment]
> Why not submit a PR?

I will look into it at some point as time permits.
