### ISSUE TITLE
vdr-addons update

### ISSUE THREAD

**Issue by Karl-opec** [OpenELEC/OpenELEC.tv#4589]
Please update at least the following vdr addons to the latest state:

satip : https://github.com/rofafor/vdr-plugin-satip/tree/vdr-2.2.x branch vdr-2.2.x
dvbapi: https://github.com/manio/vdr-plugin-dvbapi.git

Best Regards

**Comment by CvH** [comment]
With vdr-addon 6.0.2 the sat>ip plugin is up to date, dvbapi is too unsafe for a bump at the 6.0 branch (already updated at 7.0 branch).

**Comment by chewitt** [comment]
I'm closing the ticket as updates have been pushed to repos in line with @CvH comments. Thanks.
