### ISSUE TITLE
OE 7 (git master): Exit-Button (showexitbutton) does nothing

### ISSUE THREAD

**Issue by axbmcuser** [OpenELEC/OpenELEC.tv#4619]
showexitbutton=true (via as.xml)

Exit button is shown, but once you select it, the shutdown menu closes and the system behaves as you never clicked the button.

Thanks

(compiled generic)

**Comment by sraue** [comment]
we dont support exiting kodi, thats why this button is disabled per default

**Comment by axbmcuser** [comment]
Oh. Allright... I've been using the Exit-Button successfully up to Isengard on all my OE-clients and since it's the first major update where it suddenly stopped working i figured it's worth mentioning. Did not know it's not officially supported by OE though.

Well. I think i can live with that - although i will miss the button a little bit. ;-)

Still. Thanks!

**Comment by lrusak** [comment]
@acbmcuser what are you wanting to exit kodi for? All it will show is a black screen and even then systemd will start it up again

**Comment by fritsch** [comment]
Perhaps he can start an xterm from shell or press right click to get
fluxbox menu? No idea really.

2016-01-14 5:59 GMT+01:00 Lukas Rusak <notifications@github.com>:

> @acbmcuser what are you wanting to exit kodi for? All it will show is a
> black screen and even then systemd will start it up again
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4619#issuecomment-171530142>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by axbmcuser** [comment]
I use it like some kind of "(fast) soft reboot" (really NOT 20 times every day, but still) when i want/have to fully reload the tvheadend client, changed some addon- or skin-related stuff or changed something simple within advancedsettings.xml.
If enabled, the button sits nicely at the top of the shutdown-menu, so it was really the most accessible way for me and in many cases saved me a full reboot (which i of course also do in purpose - when needed).

I could use the KODI remote app from now on (does quitting still work there? Did not test it yesterday), but with looking for the smartphone, opening the app, navigating to the quit-buton it already takes more time than the normal reboot.

Would be interesting to know if it's a technical decision to not support it? Does reloading KODI do something bad in some cases? Since it's hidden by default, the reason really can't be that a user may get's confused by the wording (Exit/Reboot), can it?

 Is it on purpose it stopped working starting with Jarvis?

**Comment by axbmcuser** [comment]
Out of interest: Just tried the Official Kodi Remote (iOS App) with todays Jarvis OE Nightly. 
The inApp "Quit KODI app" button also stopped working. (maybe all as intended since the Quit() function seems out of order alltogether...)
