### ISSUE TITLE
Kodi ARM 6.0.0 for RasberriPi /512MB Ram Not Showing up on TV Screen

### ISSUE THREAD

**Issue by franky29** [OpenELEC/OpenELEC.tv#4629]
Upgraded OpenElec from version 5.0.8 to 6.0.0 and The TV powers on the RasberryPi via USB (ther is enough power). When I press the power button on my TV remote, the Pi powers on and OpenElec Kodi starts to show up on my TV in version 5.0.8 but when upgraded to 6.0.0 I power on my TV which in turn sends power to the Pi but Kodi doesn't show up on the screen. 

The Pi is powered on cause I can PING it and also SSH into it no issues. 

I have to physically reboot the Pi in order to get Kodi to show up. 

I've downgraded back to 5.0.8 and the issue has been resolved. 

This might be an HDMI issue but not sure at this point.

**Comment by chewitt** [comment]
User support is provided via the forums. Thanks.

**Comment by franky29** [comment]
My goal wasn't for user support but to submit a bug report.  I've fixed my own issues by reverting back a revision but thanks for letting me know. I'll go to the forums if I decide to upgrade to 6.0.0                                                                                                                                                                                                                                                                                                                                        Julien                                                                                                                                                                                                                 From: Christian HewittSent: Saturday, January 16, 2016 9:38 PMTo: OpenELEC/OpenELEC.tvReply To: OpenELEC/OpenELEC.tvCc: franky29Subject: Re: [OpenELEC.tv] Kodi ARM 6.0.0 for RasberriPi /512MB Ram Not Showing up on TV Screen (#4629)Closed #4629.

—Reply to this email directly or view it on GitHub.
