### ISSUE TITLE
RPi2 DTS and DD Audio Passthrough

### ISSUE THREAD

**Issue by sburgh01** [OpenELEC/OpenELEC.tv#4639]
Hello,
the DD or DTS Audio Passthrough is not working with RPI2.
I tried some things and want to show you what i know right now.

My Setup:
RPi -> HDMI -> Onkyo TX-SR308 -> HDMI -> Samsung UE40ES6100 TV
RPi -> LAN-wired

I used a fresh Openelec setup with all default settings exept Audio.
Audi settings:
HDMI output / 5.1 / Passthrough activated / DD, DTS and DD Plus compatiple AVR.

With Testbuild No.0119, 20-Jan-2016 from http://forum.kodi.tv/showthread.php?tid=250817
the audio was always resampled to Bitstream - I got multichannel Audio but no DTS or DD stream acording to the AVR. (And also a high CPU usage compared to a build with working passthrough.)

I tried the last stable Build of OpenELEC 6.00: it worked (same settings and testfiles)
So i tried many different Builds and figured out the turningpoint for this issue.
I tried at least 20 differnet builds to find it. every tested build after it had the same issue. And every tested before were ok.

its working with Kodi-v16 Build No.1005, 05-Oct-2015 from http://forum.kodi.tv/showthread.php?tid=231092
And it doesnt work with build No.1006, 06-Oct-2015 and any newer Version.
So the error or change should be somewhere in these updates of No.1006 back in v16: http://forum.kodi.tv/showthread.php?tid=231092&pid=2125625#pid2125625

I also tried the same builds for RPi1 (tested on RPi1-B) with the same fresh setup and it works properly in all tested builds, so its only a problem to RPi2.

Here a list of the relevant tested builds (i cant list all tested builds, its to much). all tested with the same configuration and the Kernel and System images were updated or downgraded through the smb update directory and reboot.

* stable Openelec 6.00
  * RPi1: :sound: :ok: 
  * RPI2: :sound: :ok: 
* Kodi.V17 Milhouse build  No.0119, 20-Jan-2016:
 * RPi1 :sound: :ok: 
 * RPi2 :mute: :no_entry_sign:
* Kodi.V16 Milhouse build  No.1204, 04-Dec-2015: 
 * RPi1 :sound: :ok: 
 * RPi2 :mute: :no_entry_sign:
* Kodi.V16 Milhouse build No.1006, 06-Oct-2015:
 * RPi1 :sound: :ok: 
 * RPi2 :mute: :no_entry_sign:
* Kodi.V16 Milhouse build No.1005, 05-Oct-2015:
 * RPi1 :sound: :ok: 
 * RPi2 :sound: :ok:

**Comment by popcornmix** [comment]
I think the Pi1/Pi2 distinction is probably a red herring.
Pi2 defaults to omxplayer disabled and Pi1 defaults to omxplayer enabled.
The use of omxplayer is far more likely to be relevant that whether you are running on Pi1 or Pi2.

So, test by explicitly enabling or disabling omxplayer and report the results.

Build 1006 was one of the VideoPlayer updates. Note that videoplayer is more restrictive about when passthrough is allowed than dvdplayer was. In particular enabling "sync playback to display" will disable passthough and playing a live stream (e.g. live TV) will disable passthrough.

It is possible that videoplayer will support passthrough in more situations in the future, but for now this is just "not supported".

So it might be that what you are seeing is just expected behaviour.

**Comment by sburgh01** [comment]
ok It workes. it really was a settings issue with the "sync playback to display" option.
I also tried the other Options with the Kodi.V17 Milhouse build No.0119, 20-Jan-2016:

I try to immitate a table with the results below.

"Sync Option" | "A/V Sync method" | Player | Working or not
Enabled | "resample audio" | MMAL | :no_entry:  
Disabled | - | MMAL | :ok: 
Enabled | "Adjust-PLL" | MMAL | :ok: 
And ALL Options with OMX Player are :ok:

So It is just the default options that are not working.
And this is so obvious with the Option "resample Audio" but I didn´t see it :disappointed_relieved: :blush: 

The only question now is: 
Why is passthrough working with OMX Player and option "resample audio"? 
Raspberry pi is not able to encode DTS or DD, or is it?
Is OMX Player ignoring this option/setting? 
(Can be closed after this question)

**Comment by popcornmix** [comment]
Yes, omxplayer ignores "resample audio".
