### ISSUE TITLE
RPI: CONFIG_RTC_DRV_PCF8563 is not set

### ISSUE THREAD

**Issue by xjezda00** [OpenELEC/OpenELEC.tv#4646]
Hi,

From projects/RPi2/linux/linux.arm.conf I can see that unfortunately there is only one RTC module enabled - for DS1307 chip:
CONFIG_RTC_DRV_DS1307=m
# CONFIG_RTC_DRV_PCF8563 is not set

but nothing else. Can you please build modules for other RTC chips too? At least to be consistent with /flash/overlays/README:
Name:   i2c-rtc
Info:   Adds support for a number of I2C Real Time Clock devices
Load:   dtoverlay=i2c-rtc,<param>
Params: ds1307                   Select the DS1307 device
        ds3231                   Select the DS3231 device
        mcp7941x                 Select the MCP7941x device
        pcf2127                  Select the PCF2127 device
        pcf8523                  Select the PCF8523 device
        pcf8563                  Select the PCF8563 device

I unfortunately have PF85163 which should be handled by pcf8563 module but can not use it now.

Thank you,
David.

**Comment by MilhouseVH** [comment]
I've added support for  PCF2127, PCF8523 and PCF8563.

DS3231 and MCP7941x don't seem to have any drivers that I can find.
