### ISSUE TITLE
Feature Request: Add an option to select a disk partition instead of a raw device.

### ISSUE THREAD

**Issue by TierraDelFuego** [OpenELEC/OpenELEC.tv#4652]
I would have been able to install openelec in a few minutes if there was an option to install to an existing partition. Right now the installer asks for a raw disk. Like /dev/sda instead of /dev/sda2 or /dev/sda3 or /dev/sda4, etc.

Maybe I can make this change myself and by mounting the installer and editing the installer program. I did not see anything about how to do that.

**Comment by lrusak** [comment]
It's because we require two specific partitions on the disk. So we need to create these ourself.

You can always install OpenELEC Manually if you want a little more control, but you will always need  two separate partitions.

**Comment by TierraDelFuego** [comment]
I did try the manual install. But I gave up due to needing two partitions.  I have tried to repartition the drive and I think I may have destroyed the linux install on there so no going back now. Should allow for a single partition, you can always create a mount point and mount any other filesytem the kernel supports. So the two partition requirement seems odd to me.

**Comment by MilhouseVH** [comment]
OpenELEC: Open **Embedded** Linux Entertainment Center

Emphasis on the embedded. It needs/wants two partitions, this doesn't seem an unreasonable requirement for an embedded system. If you want to run Kodi from a single partition, use something else other than OpenELEC.

**Comment by lrusak** [comment]
Nope, look into how OpenELEC works and you will understand why it needs two partitions

the first partition `/system` contains a readonly squashfs filesystem
the second partition `/storage` contains the writeable user directory.

In order for OE to operate in the manner it does, having two partitions is **mandatory**

**Comment by chewitt** [comment]
I'm closing this ticket because OE intentionally targets "dedicated" HTPC hardware and we have no goal to support multi-boot configurations with the installer. Deploying into a single partition wouldn't itself be too challenging to figure out but that does not result in a successful install. We would also need to derive and then modify the users existing installed bootloader or we have to nuke/overwrite with syslinux. Both are high-risk activities that are not going to be implemented. Thanks.

**Comment by TierraDelFuego** [comment]
Plenty of embedded experience and there's no correlation between embedded and # partitions. Not sure why you wouldn't want a more flexible installer that offers more choices. But maybe you only cater to the lowest common denominator. I got it installed. I was just kicking the tires to see what openelec/kodi was like. Maybe it's just this version but HD video, either local or remote, didn't work. Mplayer from a linux distro installed to the same drive was fine playing the video from a usb drive.

**Comment by lrusak** [comment]
User support is provided via the forums. If you have an issue while using OE or Kodi please take your questions there. Thanks.
