### ISSUE TITLE
XPad driver update for Linux Kernel

### ISSUE THREAD

**Issue by Hedda** [OpenELEC/OpenELEC.tv#4654]
XPad driver update in the OpenELEC Linux kernel is wanted for improved Xbox gamepad input support for use with Kodi's RetroPlayer branch.

That is, several pull requests been submitted upstream for the Linux kernel 4.5 with changes to improve the XPad driver to better handle Xbox One controllers including adding Force Feedback (rumble) support. And this pull request for the Linux 4.5 kernel also include other improvements like more rubust support for the Xbox 360 Wireless Controller.

http://www.phoronix.com/scan.php?page=news_item&px=XPad-Input-Linux-4.5

More details via this pull request:

http://lkml.iu.edu/hypermail/linux/kernel/1601.2/04543.html

XPad is the Linux USB input driver for Xbox compatible gamepad controllers. 

https://www.kernel.org/doc/Documentation/input/xpad.txt

**Comment by MattDevo** [comment]
I've actually been backporting these improvements in OE for awhile now (though not currently up-to-date), nice to see them finally making it upstream.

see: https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/linux/patches/4.4.2/linux-063-xpad-fix_xbox360_wireless.patch

**Comment by sraue** [comment]
fixed with https://github.com/OpenELEC/OpenELEC.tv/pull/4810
