### ISSUE TITLE
TP-Link Archer T4U-AC1200 Raspberry Pi 2 OpenElec 6.0

### ISSUE THREAD

**Issue by virajkanwade** [OpenELEC/OpenELEC.tv#4658]
Doesn't work on 6.0? I removed the ethernet cable, attached the T4U and started the raspberry pi. The openelec network tab does not indicate anything other than wired networks.

**Comment by virajkanwade** [comment]
@sraue  Sometimes adding new tickets for minor differences ends up creating so many junk tickets that half of them never get looked at! So I was trying to be conservative. But if guys work that way, fine, here you go. And by the way to 'comment' and close the ticket, I believe you did have to take a look at the 'closed ticket'.

**Comment by lrusak** [comment]
Please have a read here --> https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md

**Comment by chewitt** [comment]
Assuming we embed the correct driver, it is probably missing the USB device ID's for this brand/model of adapter. As you have not provided any information on chipset and ID's for this device there's is nothing that we can do, and this ticket is closed due to lack of update. Thanks.
