### ISSUE TITLE
Sound DD, DTS not working on version 6.0.0.

### ISSUE THREAD

**Issue by SLOluka** [OpenELEC/OpenELEC.tv#4667]
Hello!

I use OpenELEC on Raspberry 2. I installed version 5.0.8, where pass through the sound work fine (DD, DTS) through LG TV to the receiver.
When I uploaded the new version 6.0.0, the sound did not work anymore. The sound passed through only 48kHz. I tried everything, but I have not found a solution.
Thnx!

Luka

**Comment by chewitt** [comment]
I’m closing the ticket because this issue tracker is used for development bug-reports. General end-user help and support is provided through the OpenELEC forums: http://openelec.tv/forum. Thanks.
