### ISSUE TITLE
Build of master fails

### ISSUE THREAD

**Issue by grin1** [OpenELEC/OpenELEC.tv#4674]
>BUILD    debug (target)
  INSTALL    debug (target)
      INSTALL    gdb (target)
basename: extra operand build.OpenELEC-WeTek_Play.arm-7.0-devel/image/system/lib/modules/RTL8192CU'
Try basename --help' for more information.
make: *** [release] Fehler 1

What is the problem here?

**Comment by stefansaraev** [comment]
remove it from ADDITIONAL_DRIVERS

@sraue @lrusak you better remove it too. wetek doesn't really need this 3rdparty rtl piece of nonsense.

**Comment by sraue** [comment]
@stefansaraev where it does help to remove this from ADDITIONAL_DRIVERS?

@grin1 please paste the output from ``` ls -lah build.OpenELEC-WeTek_Play.arm-7.0-devel/image/system/lib/modules```

**Comment by grin1** [comment]
> drwxr-xr-x 3 grin1 users 4,0K Feb  3 14:41 3.10.94
drwxr-xr-x 2 grin1 users 4,0K Feb  3 14:41 RTL8188EU
drwxr-xr-x 2 grin1 users 4,0K Feb  3 14:41 RTL8192CU
drwxr-xr-x 2 grin1 users 4,0K Feb  3 14:41 RTL8192DU
drwxr-xr-x 2 grin1 users 4,0K Feb  3 14:41 wetekdvb

**Comment by kdietrich** [comment]
Can confirm. Submitted a PR.

**Comment by codesnake** [comment]
@stefansaraev Someone still use USB Wi-Fi sticks instead of built-in Wi-Fi on WeTek Play.

**Comment by stefansaraev** [comment]
yea sure.

**Comment by codesnake** [comment]
Strange, just rebuilt the WeTek Play project from master without any problems.

**Comment by chewitt** [comment]
I'm closing this ticket as I built both WP/WC from current master yesterday so this is a local build issue on your environment. Make sure you are doing clean (not incremental) builds and remove ~/.ccache* - if you have further issues open a thread in the forums. Thanks.
