### ISSUE TITLE
Please update openvpn to  2.3.10

### ISSUE THREAD

**Issue by Karl-opec** [OpenELEC/OpenELEC.tv#4683]
Please update openvpn addon to  2.3.10, because 2.3.10 fixed a long standing
issue, where the default config used to small sndbuf and rcvbuf values. Which has a
great impact on network performance.

**Comment by stefansaraev** [comment]
feel free to do so in unofficial repo ?

**Comment by Karl-opec** [comment]
it has dependence to a newer ssl Version. The Variable SSL_CTX_get0_certificate
is needed. in my local Version i worked around that.  I adapted openvpn/ssl_openssl.c
to make it compile for older openssl versions. To do it right is beyond my capabilities.

My 2.3.10 Version does work right so far.

**Comment by sraue** [comment]
added in https://github.com/OpenELEC/OpenELEC.tv/commit/e8678a0be712c41db9a8f0639f51b59c633e97e8
