### ISSUE TITLE
Compiled nvdia_legacy and failed to start xorg, not supported GPU?

### ISSUE THREAD

**Issue by Gizmo-Ger** [OpenELEC/OpenELEC.tv#4685]
I wanted to compile from the latest source (PROJECT=Nvidia_Legacy ARCH=x86_64 make release on Asus AT5IONT) but it keeps saying failed to start xorg, is your GPU supported? Is ION2 not supported under OpenELEC 7.0 anymore? I can add a boot log if it helps.

**Comment by chewitt** [comment]
ION2 cards are supported but you should be building "Generic" not Nvidia_legacy. The Generic image now contains both current and legacy drivers. I'm closing the ticket here because this is a development bug tracker. If you have further questions please open a thread in the forums. Thanks.
