### ISSUE TITLE
Legacy Nvidia build failing on Quadro NVS 140M

### ISSUE THREAD

**Issue by megazone23** [OpenELEC/OpenELEC.tv#4689]
Video card:  Quadro NVS 140M 
PCI ID: 10de:0429
OpenELEC versions: 6.0.0 and 6.0.1

When booting getting the following message:

A start job is running for Xorg Server (11s/ 1min 31sec)
... bunch of startup messages

failed to start xorg.
is your GPU supported?

this repeats after a minute or two.

Using 5.0.8 works correctly.

**Comment by MilhouseVH** [comment]
Upload `/var/log/Xorg.0.log`

**Comment by chewitt** [comment]
I'm closing the ticket here because this is a development bug tracker. End-user support is done through the OpenELEC forums. Thanks.

**Comment by megazone23** [comment]
I was on IRC and xe- told me to open the issue in git.
