### ISSUE TITLE
AirPlay and Bonjour not working on Amlogic MXQ (S805, HD18Q) -- OpenELEC 6

### ISSUE THREAD

**Issue by IMlibre** [OpenELEC/OpenELEC.tv#4694]
I installed OE 6 on two Amlogic MX devices (aka "Android TV box") this past week, the MX (G18ref, 8726MX SoC) and the MXQ (HD18Q, S805 SoC).  The software works beautifully and I am so happy I made the switch away from Android because both devices were practically useless with Android due to constant freezing.  Now with OE both devices are much faster and 1000% more reliable vs. Android 4.4.2 (stock OS).  Even under heavy usage I have not noticed one freeze-up on either device with OE, despite all the tweaking and customizing which involved lots of connecting to both boxes via sftp, ssh, and samba.

**MX**
Surprisingly the MX (dual-core) is faster overall and boots and loads Kodi in 19 seconds vs. the MXQ (quad-core) which is ready in 23 seconds.  Also, the MX box has no issues whatsoever.  I installed the  'unofficial' OE 6 software on the MX available from freaktab.com:

http://freaktab.com/forum/tv-player-support/amlogic-based-tv-players/s802/others/19253-rom-openelec-for-amlogic-based-tv-boxes-m8-mxq-tv110-mx2-g18

The only thing I don't like on the MX, and it's a little thing, is the ugly text-based "OpenELEC (Unofficial) - Version 6.0.0.0" that appears at the upper left of the TV screen at the same time as the OE logo splash-screen on boot -- if there is a way to remove that I would like to know since I would like the box to act and look more like an appliance rather than a computer.

AirPlay and Bonjour services work perfectly on the MX box.  When the MX box is on I can see it in Finder (OS X 10.6) and if I start iTunes the AirPlay icon appears every time.

![airplay itunes](https://cloud.githubusercontent.com/assets/17124433/12889269/2251b9c6-ce4c-11e5-9d85-ec5681fee667.png)

**MXQ**
The OE software for the MXQ was obtained from YouTube user 'JustMe ROMs':
https://www.youtube.com/watch?v=QEuBQEGTpP4

On the MXQ Kodi also functions very well overall but the MXQ box does not appear in the Finder via Bonjour (automatically), however, I can connect via 'Finder/Connect to Server' to: smb://<my-mxq-box-name> (or using smb://<IP-address-of-MXQ> and then it will appear in Finder.  I don't mind this though since I don't always need to see the device in Finder.

AirPlay will not work at all on the MXQ.  I have mirrored the settings I used on the MX but it simply will not work from iTunes on my Mac or other Apple devices.  Previously with Android, AirPlay worked without issues on the same MXQ box with Kodi 15.2, so this seems to be an issue with the MXQ port of OpenELEC 6.0.

Thank you,

John

**Comment by chewitt** [comment]
I'm closing this ticket because OpenELEC does not develop, test or release software images for MX hardware and this is a development bug tracker not an end-user support forum. Issues with Amlogic builds can be reported here: https://github.com/codesnake/OpenELEC.tv/issues

NB: Kodi support for AirPlay is reverse engineered with partial success and is frequently broken by iOS updates. It works for a while, then it breaks, then it works, then it's broken again, etc.
