### ISSUE TITLE
fix Python 2.7.10

### ISSUE THREAD

**Issue by sraue** [OpenELEC/OpenELEC.tv#4703]
https://github.com/OpenELEC/OpenELEC.tv/pull/4500#issuecomment-169562986 showed Python is broken after the update to 2.7.10. even if this works in most cases there is still a issue with including host *flags.
we have 2 choices, fix or revert to python 2.7.3 (fixing preferred)

**Comment by lrusak** [comment]
Can you describe the issue better? I tried looking into this today but couldn't find anything wrong.

**Comment by sraue** [comment]
fixed in https://github.com/OpenELEC/OpenELEC.tv/pull/4833
