### ISSUE TITLE
Connman failed to get ipv6 address from dhcpv6 when "IPv6.DHCP.LastAddress" exist in config file

### ISSUE THREAD

**Issue by itechatmxc** [OpenELEC/OpenELEC.tv#4709]
ISC DHCP 4.2.8, radvd in managed mode. Running on current pfSense.
DHCP server on LAN interface ( /64 subnet ) with DHCPv6 Static Mappings based on DUID.

Found that OpenELEC has  a correct global IPv6 address (from DHCPv6 server)  only when first configured by OpenELEC Configuration Addon. It lasts until a reboot or shutdown.

My /storage/.cache/connman/ethernet_bcXXXXXXXX_cable/settings looks like this: 

`[ethernet_bcXXXXXXXX_cable]
Name=Wired
AutoConnect=true
Modified=2016-02-14T20:34:37.987594Z
IPv4.method=dhcp
IPv6.method=auto
IPv6.privacy=disabled
IPv6.DHCP.DUID=000100011XXXXXXXXXXXX834480
IPv4.DHCP.LastAddress=192.168.XX.XX
IPv6.DHCP.LastAddress=2001:XXX:XXX:XXX::237

`
 
There are two ways how to fix  the issue:

1. to use OpenELEC Configuration Addon to disable and then enable IPv6 on the wired connection
2. to delete the line with  IPv6.DHCP.LastAddress from the config file.

As the both ways are far from ideal, I made a shutdown script that solves the issue:

`OpenELEC:~ # cat /storage/.config/shutdown.sh
 
case "$1" in
  halt)
    # your commands here
    ;;
  poweroff)
    # your commands here
    ;;
  reboot)
    # your commands here
    ;;
  *)
    # your commands here
    ;;
esac
find /storage/.cache/connman/ -type f -name settings -print0 | xargs -0 -r sed -i '/IPv6.DHCP.LastAddress/d'
`

**Comment by chewitt** [comment]
Is this in OpenELEC 6.0.1 or a 7.0 development build?

**Comment by itechatmxc** [comment]
It was 6.0.1, but before I raised the issue, I went through Git code to find a connman version and/or patches.
What I found is a patch [https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/network/connman/patches/connman-06-fix-lease-expiry-issues.patch](https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/network/connman/patches/connman-06-fix-lease-expiry-issues.patch)  However this patch is rather related to DNS and TIME servers and not an IPv6 addresses.

I can try a latest 7.0 snapshot from [http://snapshots.openelec.tv/](http://snapshots.openelec.tv/) if you like or to revamp my old devel VM to pull and compile from git.

**Comment by chewitt** [comment]
http://chewitt.openelec.tv/test has some recent 7.0 builds; please see if these address the issue?

**Comment by itechatmxc** [comment]
Many thanks.
Tried [http://chewitt.openelec.tv/test/OpenELEC-Generic.x86_64-7.0-devel-20160205080617-r21993-g64a0a8b.tar](http://chewitt.openelec.tv/test/OpenELEC-Generic.x86_64-7.0-devel-20160205080617-r21993-g64a0a8b.tar) and to my surprise, it worked very well. I had no issues with on my dual stack network. As the 6.0.1 is my "production" box, I'm going to use the suspend.sh script until 7.0 becomes stable.

**Comment by chewitt** [comment]
Thanks for testing and confirming. I'll close the ticket down.
