### ISSUE TITLE
WeTek OE edition RCU: incorrect keymapping

### ISSUE THREAD

**Issue by 1358** [OpenELEC/OpenELEC.tv#4710]
There are 6 hardware buttons on the WeTek OE edition RCU that are mapped to 3 key codes, what is really confusing.
```
c00e2 & c0179 > KEY_MUTE
7003a & 7003d > KEY_ZOOM
7003d & 70040 > KEY_MENU
```
![wetekoercu](https://cloud.githubusercontent.com/assets/1583407/13052092/17ba9dbe-d3fd-11e5-95ee-56f7e2cf592d.png)
IMO c00e2 should be mapped to KEY_TV, 70040 to KEY_INFO and 7003e to KEY_TAB (in order to toggle menu/fullscreen, as the icon suggests). The icon on 7003a  does not look like "zoom" for me, too.

**Comment by sraue** [comment]
this has be done this way otherwise the mappings of the WeTek original remote is messed up. there must be comprimisses... you can remap via keyboard.xml byself

**Comment by 1358** [comment]
pleas re-read my report again.
I cannot do this myself because there are 6 hardware buttons that are mapped to the same key codes I have to use in the keyboard.xml:

c00e2 & c0179 > KEY_MUTE
7003a & 7003d > KEY_ZOOM
7003d & 70040 > KEY_MENU

These are highlighted red in the picture above.

**Comment by 1358** [comment]
@sraue please re-read my report. 

I cannot do this myself because there are 6 hardware buttons that are mapped to 3 key codes.
So regardless what I do in the keymap.xml there are always two keys that do the same. These are highlighted red in the picture above.

c00e2 & c0179 > KEY_MUTE (113)
7003a & 7003d > KEY_ZOOM (372)
7003d & 70040 > KEY_MENU (139)

Or is there a way to distinguish in the keyboard.xml whether KEY_MENU (139) has been fired by hardware value 7003d or 70040? Unfortunately there is nothing in the docs about it.

**Comment by ElMatthews** [comment]
Exactly the same issue here. Any update on how this can be achieved?

**Comment by 1358** [comment]
It seems as if they can be remapped:
http://openelec.tv/forum/146-wetek-play/79954-openelec-remote-control-key-mapping#157780 (I prefer KEY_INFO, KEY_TV and KEY_TAB for F10 F11 F12)

However in my opinion the shared key codes are still a bug (https://github.com/OpenELEC/OpenELEC.tv/issues/4711)

**Comment by ElMatthews** [comment]
ps: how did you find this information? can'' we add the keys in the remote config?

**Comment by 1358** [comment]
the key codes and raw values? if kodi is not running evtest is very talkative

**Comment by ElMatthews** [comment]
ok thanks for the info. I do agree that this is confusing. In the meantime I will try to remap them.

**Comment by ElMatthews** [comment]
remapping as specified in http://openelec.tv/forum/146-wetek-play/79954-openelec-remote-control-key-mapping#157780 works.

Thanks!
