### ISSUE TITLE
Add support for BrosTrend WNA016 USB WiFi Adapter

### ISSUE THREAD

**Issue by reminisc3** [OpenELEC/OpenELEC.tv#4717]
This USB WiFi adapter is not being detected. Would be great if support was added. 

Thanks!

**Comment by chewitt** [comment]
I will leave this open for 48 hours for you to provide some facts like chipset and device ID's - we don't like guessing these things. If nothing is updated the ticket will be closed. Thanks.

**Comment by reminisc3** [comment]
Sorry, this is for the Raspberry Pi 2. I can try and contact the vendor for more information on this unit.

**Comment by sraue** [comment]
you only have to provide the output from "dmesg" and "lsusb"

**Comment by sraue** [comment]
closing, please open a new iss report if you can provide the logfiles
