### ISSUE TITLE
RTL8192EU wifi usb driver support

### ISSUE THREAD

**Issue by ilanbowen** [OpenELEC/OpenELEC.tv#4719]
Hi,

Can support please be added for the RTL8192EU wifi usb dongle?

Cheers,
Ilan.

**Comment by vpeter4** [comment]
I think it is already included. What is the issue?

**Comment by ilanbowen** [comment]
openelec doesn't recognize this adapter and although I have the driver I have no way of installing it on openelec.
Windows didn't automatically recognize it either until I installed the driver from the supplier (I have the linux driver also)

**Comment by sraue** [comment]
No  Infos about your System and Hardware you want use.  No logs...  How we should help.

**Comment by ilanbowen** [comment]
I have installed openelec 6.0 on raspberry pi2, which logs would you like?

**Comment by fritsch** [comment]
Those that you were asked for twice while filing this issue.

2016-02-18 13:16 GMT+01:00 ilanbowen <notifications@github.com>:

> I have installed openelec 6.0 on raspberry pi2, which logs would you like?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4719#issuecomment-185692319>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by ilanbowen** [comment]
sorry to waste your time guys. I wrestled with this a few weeks ago and couldn't get it to work. I didn't try again before opening this case. I just installed the 6.0.1 update and it's working now. thanks for all your help and speedy response!
