### ISSUE TITLE
New amlogic cec driver reboots my TV

### ISSUE THREAD

**Issue by uros-z** [OpenELEC/OpenELEC.tv#4721]
Hello,

I have a problem with new cec driver. It reboots my TV. If I disable cec(Samsung anynet) on my TV then reboots go away. Debug log is [here](http://sprunge.us/TeGh). Also cec does not work at all.

Best regards,
Uros

**Comment by gdachs** [comment]
This log messages are not from my driver.

Gerald

**Comment by uros-z** [comment]
How can I generate a log for your driver?

**Comment by gdachs** [comment]
There is nothing special to be done, I use just the log of the system, so journalctl is the command to use.

But I am currently not interested in the log, as I told I am working on a better version of the drive.

Gerald

**Comment by uros-z** [comment]
OK

**Comment by uros-z** [comment]
I tested the new cec driver and it works, TV no longer reboots.
There is a small problem tho. If I reboot OE then cec does not reconnect. I have to disconnect anynet/cec device and then reconect to make it work. 

Anyway great yob!

**Comment by gdachs** [comment]
Does this happen on every reboot, or only on the first. Please try again. Send me the output of journalctl.

**Comment by sraue** [comment]
should be fixed with https://github.com/OpenELEC/OpenELEC.tv/commit/a75c01b37e4db4e44e5fb3b0451d95f46d9c447e

**Comment by uros-z** [comment]
I tried it 6 times with that commit and it never connected after reboot, now 12h later I can't reproduce it. It just works.

**Comment by gdachs** [comment]
I have tried it with the last image too, one reboot didn't work, made a rescan, it worked and survived a reboot. I think we can close this now. If it happens again, make a new issue with the output of journalctl attached, okay?

**Comment by uros-z** [comment]
OK
