### ISSUE TITLE
Feature freeze

### ISSUE THREAD

**Issue by lrusak** [OpenELEC/OpenELEC.tv#4722]
I am proposing a feature freeze for the upcoming 7.0 release.

I have set a date of this monday to get all the last package updates and major features merged before releasing 6.95.1

I would like to see the following in:
- [ ] #4701 
- [x] ~~#4720~~
- [x] ~~#4723~~

Also ~~glibc 2.23~~ and llvm 3.8 (hopefully released before monday, otherwise we may have to make an exception)

If anyone has any other PR's, commits, opinions, please add them here as I would like to track everything we need before feature freeze.

EDIT: updated for glibc bump

**Comment by MilhouseVH** [comment]
:100: This *needs* to happen, no more delays.

glibc is #4723 btw.

**Comment by anoma** [comment]
Strongly agree.

The current release blockers

https://github.com/OpenELEC/OpenELEC.tv/issues/4703
https://github.com/OpenELEC/OpenELEC.tv/issues/4526

do not seem significant enough to stop the beta cycle starting.

**Comment by MilhouseVH** [comment]
Nobody other than @sruae understands why #4703 is a release blocker - the problem is already resolved as far as I understand. I suggest ignoring release blocker #4703 for now unless there is some explanation of what the actual problem is.

**Comment by sraue** [comment]
@milhouse see the compile out from python packages (like pillow) you will see host dirs included in the output while linking... we only have much luck this is not a problem and no one knows what for issues we have because of this or will have because of this

**Comment by sraue** [comment]
and everyone complains because of package updates and blabla but such issues are much more danger in my eyes and should never be ignored... so no release until this is solved!!!

**Comment by lrusak** [comment]
@sraue I have yet to see any ill effects from this (I honestly don't even see the issue). How is it a problem with python when the problem was with building Pillow?

We cannot wait any longer, Kodi 16.0 final is about to be tagged.

**Comment by sraue** [comment]
'''/home/stephan/projects/openelec-master/build.OpenELEC-Generic.x86_64-7.0-devel/toolchain/bin/x86_64-openelec-linux-gnu-gcc -DNDEBUG -O2 -Wall -pipe -I/home/stephan/projects/openelec-master/build.OpenELEC-Generic.x86_64-7.0-devel/toolchain/include -Wno-format-security -march=x86-64 -m64 -fomit-frame-pointer -Wall -pipe -Os -fexcess-precision=fast -flto -ffat-lto-objects -mmmx -msse -msse2 -mfpmath=sse -fPIC -I/home/stephan/projects/openelec-master/build.OpenELEC-Generic.x86_64-7.0-devel/toolchain/x86_64-openelec-linux-gnu/sysroot/usr/include/freetype2 -I/home/stephan/projects/openelec-master/build.OpenELEC-Generic.x86_64-7.0-devel/Pillow-3.1.0/libImaging -I/home/stephan/projects/openelec-master/build.OpenELEC-Generic.x86_64-7.0-devel/toolchain/x86_64-openelec-linux-gnu/sysroot/usr/include -I/home/stephan/projects/openelec-master/build.OpenELEC-Generic.x86_64-7.0-devel/toolchain/x86_64-openelec-linux-gnu/sysroot/usr/include/python2.7 -c _imagingmorph.c -o build/temp.linux-x86_64-2.7/_imagingmorph.o
/home/stephan/projects/openelec-master/build.OpenELEC-Generic.x86_64-7.0-devel/toolchain/bin/x86_64-openelec-linux-gnu-gcc -shared -march=x86-64 -m64 -s -Wl,--as-needed -fuse-ld=gold -fuse-linker-plugin -flto -march=x86-64 -m64 -fomit-frame-pointer -Wall -pipe -Os -fexcess-precision=fast -flto -ffat-lto-objects -mmmx -msse -msse2 -mfpmath=sse build/temp.linux-x86_64-2.7/_imagingmorph.o -L/home/stephan/projects/openelec-master/build.OpenELEC-Generic.x86_64-7.0-devel/toolchain/x86_64-openelec-linux-gnu/sysroot/usr/lib -L/home/stephan/projects/openelec-master/build.OpenELEC-Generic.x86_64-7.0-devel/toolchain/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/PIL/_imagingmorph.so'''
all -I/home/stephan/projects/openelec-master/build.OpenELEC-Generic.x86_64-7.0-devel/toolchain/include and -L/home/stephan/projects/openelec-master/build.OpenELEC-Generic.x86_64-7.0-devel/toolchain/lib must go, and ity python related, its not there when building with oe-6.0 branch

**Comment by sraue** [comment]
and this was the the real issue with pillow originally before changing the pkgconfig scripts stuff

**Comment by arco** [comment]
Weirdly, the update to glibc-2.23 broke amlogic remote for me, in that nothing happens when pressing any buttons. Rolling back to 2.22 it's working as normal again. Very odd.

**Comment by sraue** [comment]
@arco what for a remote, please start a new issue report with more infos...

**Comment by gdachs** [comment]
@sraue: tested wetek play/core with fresh build from master built this morning (glibc-2.23).
Both work with their corresponding wetek remote, and via cec with the remote from the samsung tv ;).
