### ISSUE TITLE
No language being installed on 1st boot

### ISSUE THREAD

**Issue by MikeBuzz** [OpenELEC/OpenELEC.tv#4725]
09:14:40  49.660557 T:1967587328 WARNING: CLangInfo: unable to load language "resource.language.de_de". Trying to determine matching language addon...
09:14:40  49.667912 T:1697641536  NOTICE: Thread AirPlayServer start, auto delete: false
09:14:40  49.673264 T:1967587328 WARNING: CLangInfo: unable to find an installed language addon matching "resource.language.de_de". Trying to find an installable language...

seems that if you install either 6.0.0 or 6.0.1 it does some geo ip check to find what language to install, if the language addon fails to install then you just get background screen with no menu

if you install with out inet connection it fails the geo ip check so uses english language which does not need to download to install

so to fix either disable geoip check, or default install to english, or include the language packs with in OE

**Comment by MikeBuzz** [comment]
gui settings on 1st boot

http://sprunge.us/gBjY

<language>resource.language.de_de</language>

(9:44:30 AM) hhttww: i have new installed, and started wihtout internet
(9:44:33 AM) hhttww: and now ...
(9:44:44 AM) hhttww: menü is here, and setup menü is in english

**Comment by tpmodding** [comment]
I have the same issue! may after the welcome message you can put another message for asking for the language instead of downloading it with the geoip check, i'm from germany but use the english menu...

**Comment by sraue** [comment]
there is no geoip check, i think its getting your TV language via CEC. please try again with 6.0.3 and report back
