### ISSUE TITLE
cant build from master after last few commits 

### ISSUE THREAD

**Issue by daweze** [OpenELEC/OpenELEC.tv#4727]
cant build from master Generic x64 errors out on plymouth-lite.  i have tried twice today.

ply-frame-buffer.c: At top level:
ply-frame-buffer.c:204:26: warning: 'p_visual' defined but not used [-Wunused-function]
 static const char const *p_visual(int visual)
                          ^
../sysdeps/x86_64/fpu/multiarch/s_floor.S:27: error: undefined reference to '_dl_x86_cpu_features'
../sysdeps/x86_64/fpu/multiarch/e_pow.c:8: error: undefined reference to '_dl_x86_cpu_features'
../sysdeps/x86_64/fpu/multiarch/s_rint.S:27: error: undefined reference to '_dl_x86_cpu_features'
../sysdeps/x86_64/fpu/multiarch/e_exp.c:9: error: undefined reference to '_dl_x86_cpu_features'
collect2: error: ld returned 1 exit status
Makefile:3: recipe for target 'ply-image' failed
make[1]: *** [ply-image] Error 1
make[1]: Leaving directory '/home/daweze/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/plymouth-lite-0.6.0'
make: *** [image] Error 1
daweze@ubuntu:~/OpenELEC.tv$

**Comment by sraue** [comment]
we know

**Comment by MilhouseVH** [comment]
Yeah sorry, it's being looked into. The glibc bump has been a bit of a nightmare. It builds fine on Raspberry Pi/Pi2 which is what I initially build tested - should have known better to assume it would also be fine on x86. :frowning:
