### ISSUE TITLE
Mistake at compilation of OPENELEC in UNUNTU 15.10

### ISSUE THREAD

**Issue by ed68** [OpenELEC/OpenELEC.tv#4732]
BUILD    plymouth-lite (init)
make[1]: Entering directory '/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/plymouth-lite-0.6.0'
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/toolchain/bin/x86_64-openelec-linux-gnu-gcc -march=x86-64 -m64 -fomit-frame-pointer -Wall -pipe -Os -fexcess-precision=fast -flto -ffat-lto-objects -mmmx -msse -msse2 -mfpmath=sse -Wl,-Bstatic `pkg-config --cflags libpng`  ply-image.c ply-frame-buffer.c -o ply-image  -lm `pkg-config --libs libpng` -lm -lz -Wl,-Bdynamic -lc -march=x86-64 -m64 -s -Wl,--as-needed -fuse-ld=gold -fuse-linker-plugin -flto
ply-image.c:138:1: warning: 'transform_to_argb32' defined but not used [-Wunused-function]
 transform_to_argb32 (png_struct   *png,
 ^
ply-frame-buffer.c: In function 'flush_generic':
ply-frame-buffer.c:104:25: warning: variable 'x2' set but not used [-Wunused-but-set-variable]
   unsigned long x1, y1, x2, y2;
                         ^
ply-frame-buffer.c:103:10: warning: variable 'bytes_per_row' set but not used [-Wunused-but-set-variable]
   size_t bytes_per_row;
          ^
ply-frame-buffer.c:101:22: warning: unused variable 'column' [-Wunused-variable]
   unsigned long row, column;
                      ^
ply-frame-buffer.c: In function 'flush_xrgb32':
ply-frame-buffer.c:127:25: warning: variable 'x2' set but not used [-Wunused-but-set-variable]
   unsigned long x1, y1, x2, y2, y;
                         ^
ply-frame-buffer.c: At top level:
ply-frame-buffer.c:204:26: warning: 'p_visual' defined but not used [-Wunused-function]
 static const char const *p_visual(int visual)
                          ^
../sysdeps/x86_64/fpu/multiarch/s_floor.S:27: error: undefined reference to '_dl_x86_cpu_features'
../sysdeps/x86_64/fpu/multiarch/e_pow.c:8: error: undefined reference to '_dl_x86_cpu_features'
../sysdeps/x86_64/fpu/multiarch/s_rint.S:27: error: undefined reference to '_dl_x86_cpu_features'
../sysdeps/x86_64/fpu/multiarch/e_exp.c:9: error: undefined reference to '_dl_x86_cpu_features'
collect2: error: ld returned 1 exit status
Makefile:3: recipe for target 'ply-image' failed
make[1]: *** [ply-image] Error 1
make[1]: Leaving directory '/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/plymouth-lite-0.6.0'
Makefile:9: ошибка выполнения рецепта для цели «release»
make: *** [release] Ошибка 1

**Comment by Gizmo-Ger** [comment]
I´m having the same issue.

**Comment by vpeter4** [comment]
https://github.com/OpenELEC/OpenELEC.tv/issues/4727
