### ISSUE TITLE
cm-online script is broken

### ISSUE THREAD

**Issue by CvH** [OpenELEC/OpenELEC.tv#4745]
The cm-online script from conman is broken since at least [OE 5.95.2](http://openelec.tv/forum/79-tvheadend/77627-sat-ip-server-disabled-after-restart)
```cm-online $WAIT_FOR_NET_TIME``` doesn't work
Tvh, Oscam are currently affected, at VDR not yet implemented. 
Services getting started regardless if there is a connection.

**Comment by sraue** [comment]
why the release blocker is removed? this has to work

**Comment by lrusak** [comment]
It is only broken for unofficial add-ons.

**Comment by sraue** [comment]
whats the difference between the usage in the core and the addons?

**Comment by sraue** [comment]
fixed @CvH @lrusak ?

**Comment by CvH** [comment]
@sraue I have to look for oscam too (today/tomorrow)
