### ISSUE TITLE
Add support for DVB USB stick Hauppauge WinTV SoloHD

### ISSUE THREAD

**Issue by Salokyn** [OpenELEC/OpenELEC.tv#4748]
Hello,
Could you apply the following patches in order to let the DVB USB stick Hauppauge WinTV SoloHD be recognized by OpenElec please : http://git.linuxtv.org/media_tree.git/commit/?id=1efc21701d94ed0c5b91467b042bed8b8becd5cc
I tested it myself on OpenElec 6.0.1 as explained on the forum : http://openelec.tv/forum/82-dvb-t-t2-support/80112-hauppauge-wintv-solohd-support .

**Comment by vpeter4** [comment]
This is not good enough? https://github.com/OpenELEC/OpenELEC.tv/commit/75f253f91647021de5d603d5957a8993a91f59e5

Search before posting...

**Comment by Salokyn** [comment]
Sorry ! I did not make a new search since yesterday.
Thank you.
