### ISSUE TITLE
live tv channels freeze

### ISSUE THREAD

**Issue by ad015** [OpenELEC/OpenELEC.tv#4753]
i am using latest dev build generic for my htpc and i got alot of freeze on some live tv channels ,
but working fine in old dev builds.
back to  openelec 6.0.1 working fine.

any idea

**Comment by CvH** [comment]
What are you using (VDR,Tvh ...)?
What system are you using ?
Where is a logfile ?
Sorry without any information nobody could help you.

**Comment by ad015** [comment]
i am using vdr , ok i will reinstall it and upload the log soon.

**Comment by chewitt** [comment]
I'm closing the ticket because this is a development bug tracker. End-user support is provided through the forums. Please create a thread there. Thanks.
