### ISSUE TITLE
Amlogic amremote broken after glibc-2.23

### ISSUE THREAD

**Issue by arco** [OpenELEC/OpenELEC.tv#4759]
I have an Android TV stick, the UStick MK809 Plus, which I'm cooking my own OpenELEC builds for. This stick comes with the same remote controller that most of these similar sticks comes with. It's using the remotecfg utility from the amremote package to load the key config.

This has worked fine, up until the upgrade to glibc-2.23, which seems to cause this utility to not work anymore, resulting in the remote controller not functioning. I can't see anything terrible wrong in the logs, and the utility seems to load the remote config file when run. So something quite odd is happening here.

For now, as a workaround, I'm using a prebuilt static linked remotecfg binary from the stock Android rom that came with the stick. With this the remote controller works again.

**Comment by LouiS22** [comment]
Probably the same issue on WeTek Play with OE and using a Harmony One with remote.cfg - the Harmony is not working anymore (while the original remote is OK).

**Comment by arco** [comment]
Ok, so there's a segmentation fault happening.

Output pre glibc-2.23:
OpenELEC:~ # remotecfg /etc/amremote/wetek.conf 
curpara:factory_code  bc430001
curpara:work_mode  00000001
curpara:repeat_enable  00000001
curpara:release_delay  00000096
curpara:debug_enable  00000001
curpara:reg_control  000fbe40
KEYMAP_LEVEL: ircode = 0xca, keycode = 116
           work_mode = 1
       repeat_enable = 0x1
        factory_code = 48195
       release_delay = 0x96
        debug_enable = 0x1
         reg_control = 1031744

Output after glibc-2.23:
OpenELEC:~ # remotecfg /etc/amremote/wetek.conf 
curpara:factory_code  bc430001
curpara:work_mode  00000001
curpara:repeat_enable  00000001
curpara:release_delay  00000096
curpara:debug_enable  00000001
curpara:reg_control  000fbe40
Segmentation fault (core dumped)

**Comment by fritsch** [comment]
I hope you have recompiled everything against this new glibc, right after
issueing a full make clean.

2016-02-24 0:04 GMT+01:00 Arne Coucheron <notifications@github.com>:

> Ok, so there's a segmentation fault happening.
>
> Output pre glibc-2.23:
> OpenELEC:~ # remotecfg /etc/amremote/wetek.conf
> curpara:factory_code bc430001
> curpara:work_mode 00000001
> curpara:repeat_enable 00000001
> curpara:release_delay 00000096
> curpara:debug_enable 00000001
> curpara:reg_control 000fbe40
> KEYMAP_LEVEL: ircode = 0xca, keycode = 116
> work_mode = 1
> repeat_enable = 0x1
> factory_code = 48195
> release_delay = 0x96
> debug_enable = 0x1
> reg_control = 1031744
>
> Output after glibc-2.23:
> OpenELEC:~ # remotecfg /etc/amremote/wetek.conf
> curpara:factory_code bc430001
> curpara:work_mode 00000001
> curpara:repeat_enable 00000001
> curpara:release_delay 00000096
> curpara:debug_enable 00000001
> curpara:reg_control 000fbe40
> Segmentation fault (core dumped)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4759#issuecomment-187955691>
> .
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by arco** [comment]
@fritsch Yeah tried full clean build several times. :)

Will try with the fix @codesnake pushed. I have a feeling it will help. :)

**Comment by fritsch** [comment]
Wait until the proper fix is in place

**Comment by NoNaMe-Lviv** [comment]
wetek IR remote "power" not works

**Comment by gdachs** [comment]
NoYou have rebuild OpenELEC with the fix above and knows already that it doesn't work? You are fast.

Gerald

**Comment by lrusak** [comment]
@gdachs I have also rebuilt with the above fix and the power button on the remote indeed is not working

**Comment by NoNaMe-Lviv** [comment]
yes.clean rebuild. WeTeK IR remote power button not working with fi.

**Comment by lrusak** [comment]
@NoNaMe-Lviv I just tested this latest commit with the Wetek core and it fixes it for me. No more segfault.

You might want to verify that the latest amremote version is being used.

**Comment by NoNaMe-Lviv** [comment]
wetek play. yes, last amremote not working button as with the previous one. broken at updates on 22 February.

**Comment by codesnake** [comment]
I tried on Core and it works. Will try on Play.

**Comment by NoNaMe-Lviv** [comment]
Power button working good
