### ISSUE TITLE
Very new Sony DualShock 4 controllers do not connect to the input service over bluetooth

### ISSUE THREAD

**Issue by jasonritzke** [OpenELEC/OpenELEC.tv#4764]
This is a known issue with new model DS4 controllers and has been patched in kernel 4.5. Upstream patch here https://git.kernel.org/cgit/linux/kernel/git/jikos/hid.git/commit/?h=for-4.5/sony&id=b71b5578a84d297954e4812ba0ca2d466e61cf42

I've submitted a pull request to resolve this in the current version of OpenELEC. I've built and performed preliminary testing, it seems to resolve the connectivity issue (configuring the controller is another matter entirely. #4763

**Comment by sraue** [comment]
thanks, merged, no need to create a seperate issue report, all pullrequests are issues too :-)

**Comment by jasonritzke** [comment]
Thanks, and will do. I git okay but I do not github well :-(
