### ISSUE TITLE
Builds Fail to Compile - Unable to DL pkg-config-0.29.tar.gz

### ISSUE THREAD

**Issue by islipfd19** [OpenELEC/OpenELEC.tv#4768]
All builds failed to compile, package 'pkg-config-0.29.tar.gz' isn't available to be downloaded anywhere including "http://sources.openelec.tv/mirror/pkg-config/"

I do have the file from another machine where the builds were being built on. I've tar'd them uploaded them here so they can be placed on the OpenELEC mirror.

[pkg-config.tar.gz](https://github.com/OpenELEC/OpenELEC.tv/files/144360/pkg-config.tar.gz)

**Comment by sraue** [comment]
uploaded to the mirror
