### ISSUE TITLE
Intel compute stick / openelec no wireless/Bluetooth 

### ISSUE THREAD

**Issue by xBr0th3rx** [OpenELEC/OpenELEC.tv#4770]
Hello everybody,
I still have the problem with my Intel® Compute Stick STCK1A32WFC
the WLAN chip is Realtek and I dont See any Access point.
And Bluetooth dont work ins stand "no Bluetooth adapter found"
And I still have the problem that I can not masquerade as HDMI for the audio setting.

I hope you can help me.

mfg xBr0th3rx
(Sorry for my bad english, I made my google translator.)

**Comment by chewitt** [comment]
I'm closing the ticket here because this is a development bug tracker not an end-user help forum. Please follow up via the forums - I already replied to your original post. Thanks.
