### ISSUE TITLE
Problems with DTS-HD/Dolby True-HD

### ISSUE THREAD

**Issue by pacoma** [OpenELEC/OpenELEC.tv#4771]
So now to the strange behavior; under Windows everything runs as should all sound formats (DTS, DTS-HD MA, Dolby True HD ...) everything goes via passthrough.

Under OpenELEC 7.0 (Jarvis 16 Final) all is ok, until the first set of the Soundsettings, can play everything via passtrough. After the first reboot, the HD sound formats no longer audible via passtrough, do I have disable DTS-HD and Dolby True-HD in the settings as a supported format of the receiver, teh Movie are sound DTS via passtrough but not DTS-HD.

If I delete the guisettings.xml and re-set the settings it works again until I reboot the HTPC..

my HW Config:
CPU:
AMD Athlon(tm) 5350 APU with Radeon(tm) R3, 4 cores available

Sounddevices:
Enumerated ALSA devices:
Device 1
m_deviceName : hdmi:CARD=HDMI,DEV=0
m_displayName : HDA ATI
m_displayNameExtra: @@@
m_deviceType : AE_DEVTYPE_HDMI
m_channels : FL,FR,FC
m_sampleRates : 32000,44100,48000,96000,192000
m_dataFormats : AE_FMT_LPCM,AE_FMT_AC3,AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_DTSHD,AE_FMT_TRUEHD,AE_FMT_EAC3,AE_FMT_DTS,AE_FMT_AAC
Device 2
m_deviceName : hdmi:CARD=HDMI,DEV=1
m_displayName : HDA ATI
m_displayNameExtra: HDMI
m_deviceType : AE_DEVTYPE_HDMI
m_channels : FL,FR,LFE,FC,BC,BL,BR,FLOC,FROC,BLOC,BROC,TFC,TC,TFL,TFR,UNKNOWN1
m_sampleRates : 32000,44100,48000,88200,96000,176400,192000
m_dataFormats : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_LPCM,AE_FMT_DTSHD,AE_FMT_TRUEHD,AE_FMT_EAC3,AE_FMT_DTS,AE_FMT_AC3,AE_FMT_AAC
Device 3
m_deviceName : @:CARD=Generic,DEV=0
m_displayName : HD-Audio Generic
m_displayNameExtra: ALC662 rev1 Analog
m_deviceType : AE_DEVTYPE_PCM
m_channels : FL,FR
m_sampleRates : 48000
m_dataFormats : AE_FMT_S32NE
Enumerated PULSE devices:
Device 1
m_deviceName : Default
m_displayName : Default
m_displayNameExtra: Bluetooth Audio (PULSEAUDIO)
m_deviceType : AE_DEVTYPE_PCM
m_channels : FL,FR
m_sampleRates : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
m_dataFormats : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT

**Comment by pacoma** [comment]
Workaround, dont use "adjust  display refresh rate" play all video with 60Hz. Its not ok, but a Way

**Comment by fritsch** [comment]
Known since years: https://bugs.freedesktop.org/show_bug.cgi?id=75064 please bump this bugreport.

**Comment by chewitt** [comment]
I'm closing the ticket here to avoid another ticket that never closes. If and/or when this is ever corrected upstream we will pick up the fix. Thanks.
