### ISSUE TITLE
Python 2.7.11 is not compiled

### ISSUE THREAD

**Issue by hoblins** [OpenELEC/OpenELEC.tv#4774]
Hello,
I'm trying to compile the current master branch for RPi2.
It stops with errors during compiling several files of Python 2.7.11.
There seem to be some links to the old folder .../Python-2.7.10/...
Please find attached the log for one of the files not found:

building '_multibytecodec' extension
creating build/temp.linux-x86_64-2.7/cjkcodecs
/home/OpenELEC.tv/build.OpenELEC-RPi2.arm-7.0-devel/toolchain/bin/host-gcc -pthread -fPIC -fno-strict-aliasing -O2 -Wall -pipe -I/home/OpenELEC.tv/build.OpenELEC-RPi2.arm-7.0-devel/toolchain/include -Wno-format-security -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I. -IInclude -I/home/OpenELEC.tv/build.OpenELEC-RPi2.arm-7.0-devel/Python-2.7.11/Include -I/usr/include -I/home/OpenELEC.tv/build.OpenELEC-RPi2.arm-7.0-devel/toolchain/include -I/home/OpenELEC.tv/build.OpenELEC-RPi2.arm-7.0-devel/**Python-2.7.10**/Include -I/home/OpenELEC.tv/build.OpenELEC-RPi2.arm-7.0-devel/Python-2.7.11/.x86_64-linux-gnu -c cjkcodecs/multibytecodec.c -o build/temp.linux-x86_64-2.7/cjkcodecs/multibytecodec.o
gcc: error: cjkcodecs/multibytecodec.c: No such file or directory
gcc: fatal error: no input files

**Comment by sraue** [comment]
you have todo a new fullbuild, with removing the build.OpenELEC* folder

**Comment by hoblins** [comment]
Thank you, that worked.
I didn't expect this behavior cause I compiled OpenELEC many times after git pull without a new full build.
