### ISSUE TITLE
OpenELEC freezes when connecting to the network

### ISSUE THREAD

**Issue by esfomeado** [OpenELEC/OpenELEC.tv#4776]
Hi,

This problem happens on versions: 5.95, 6.00, 6.01.
On the version 5.0.8 it works just fine.
This happens on raspberry pi 2.

I have the following Wifi adapter (TL - WN725N).

When i connect to the internet with this adapter openELEC freezes.
I don't know how i can provide more details to you guys.

**Comment by chewitt** [comment]
I'm closing the ticket because this is a development bug tracker. End-user support is provided through the forums - please start a thread there. Thanks.

**Comment by esfomeado** [comment]
Yeah but support on forum is almost zero.
