### ISSUE TITLE
geniatech atv390 S802-B

### ISSUE THREAD

**Issue by arpu** [OpenELEC/OpenELEC.tv#4784]
hello @codesnake 
i try to make a img for this device (meson8 hdmiin) 
firmwarefile:
http://www.fernsehfee.de/downloads/update_telecontrol_ATV390_20150902.img

i extract the kernel config
http://lpaste.net/153492
and  generate all dtd files from the multi amlogic device tree file 
(attached) 
[stv.tar.gz](https://github.com/OpenELEC/OpenELEC.tv/files/149389/stv.tar.gz)

question is what dtd file is used for my devide how can i found this out?

**Comment by chewitt** [comment]
Please ask questions to https://github.com/codesnake/OpenELEC.tv/issues as OpenELEC does not directly support the Amlogic sub-projects. Thanks.
