### ISSUE TITLE
WetekPlay starts with color noise, when LG simplink is ON

### ISSUE THREAD

**Issue by justason** [OpenELEC/OpenELEC.tv#4795]
WetekPlay starts with color noise, when LG simplink is ON

**Comment by gdachs** [comment]
Never heard this before, but you could try this [build](https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/devel/libcec/patches/libcec-03-amlogic-support.patch#L104). Another LG user tested it successfully.

**Comment by sraue** [comment]
works in 6.0.3? please report back

**Comment by sraue** [comment]
no reply after more then one week, closing
