### ISSUE TITLE
RPi & RPi2 fail to build 

### ISSUE THREAD

**Issue by islipfd19** [OpenELEC/OpenELEC.tv#4800]
RPi & RPi2 fail to build. The same error is indicated in the build log.

  AS      arch/arm/boot/compressed/hyp-stub.o
  AS      arch/arm/boot/compressed/lib1funcs.o
  AS      arch/arm/boot/compressed/ashldi3.o
  AS      arch/arm/boot/compressed/bswapsdi2.o
  AS      arch/arm/boot/compressed/piggy.gzip.o
  LD      arch/arm/boot/compressed/vmlinux
  OBJCOPY arch/arm/boot/zImage
  Kernel: arch/arm/boot/zImage is ready
make[1]: Leaving directory '/var/lib/jenkins/workspace/OpenELEC.tv_RPi2/build.OpenELEC-RPi2.arm-7.0-devel/linux-4.4.2'
cp: cannot stat 'arch/TARGET_KERNEL_ARCH/boot/dts/*.dtb': No such file or directory
Makefile:9: recipe for target 'release' failed
make: *** [release] Error 1
Build step 'Execute shell' marked build as failure
[RPi_build.log.tar.gz](https://github.com/OpenELEC/OpenELEC.tv/files/152807/RPi_build.log.tar.gz)
[RPi2_build.log.tar.gz](https://github.com/OpenELEC/OpenELEC.tv/files/152806/RPi2_build.log.tar.gz)

**Comment by vpeter4** [comment]
Few missing $: https://github.com/lrusak/OpenELEC.tv/commit/ae9e7cab5fdaa4d492ebb6d05d2b205dd554f67b#commitcomment-16417025

Can you fix this by hand and report back if works.

**Comment by islipfd19** [comment]
Yes, my builds are kicked off by Jenkins on my machines. I've fixed the three lines in my forked repo and am currently building RPi2. I'll know in a few of hours.

**Comment by sraue** [comment]
fixed in https://github.com/OpenELEC/OpenELEC.tv/commit/14d2a01f38182727ba202f33d26bebcc5562c630
