### ISSUE TITLE
Kernel issue on Raspberry Pi3 with OpenELEC 6.0.3

### ISSUE THREAD

**Issue by nickerejv** [OpenELEC/OpenELEC.tv#4801]
On boot with fresh installation of OpenELEC 6.0.3 on Raspberry Pi3 the following kernel error is thrown.

[    0.279461] ------------[ cut here ]------------
[    0.279482] WARNING: CPU: 0 PID: 1 at arch/arm/mm/ioremap.c:301 __arm_ioremap_pfn_caller+0x18c/0x1b0()
[    0.279491] Modules linked in:
[    0.279506] CPU: 0 PID: 1 Comm: swapper/0 Not tainted 4.1.18 #1
[    0.279513] Hardware name: BCM2709
[    0.279520] Backtrace:
[    0.279543] [<80012764>] (dump_backtrace) from [<80012984>] (show_stack+0x18/0x1c)
[    0.279551]  r6:60000113 r5:80869560 r4:00000000 r3:00000000
[    0.279582] [<8001296c>] (show_stack) from [<80507dcc>] (dump_stack+0xac/0xcc)
[    0.279601] [<80507d20>] (dump_stack) from [<8001e4c4>] (warn_slowpath_common+0x8c/0xbc)
[    0.279608]  r7:0000012d r6:8001814c r5:00000009 r4:00000000
[    0.279634] [<8001e438>] (warn_slowpath_common) from [<8001e598>] (warn_slowpath_null+0x24/0x2c)
[    0.279641]  r8:0002d962 r7:80856dd4 r6:2d962000 r5:00000e10 r4:00002000
[    0.279672] [<8001e574>] (warn_slowpath_null) from [<8001814c>] (__arm_ioremap_pfn_caller+0x18c/0x1b0)
[    0.279690] [<80017fc0>] (__arm_ioremap_pfn_caller) from [<800181c4>] (__arm_ioremap_caller+0x54/0x5c)
[    0.279697]  r9:806695f0 r8:aefe6b1c r7:ad962e10 r6:ad962e00 r5:ad06ef10 r4:00000000
[    0.279729] [<80018170>] (__arm_ioremap_caller) from [<80017ea8>] (__arm_ioremap+0x20/0x24)
[    0.279736]  r4:00000000
[    0.279757] [<80017e88>] (__arm_ioremap) from [<802b3e1c>] (brcmvirt_gpio_probe+0xa0/0x194)
[    0.279777] [<802b3d7c>] (brcmvirt_gpio_probe) from [<802fcfb4>] (platform_drv_probe+0x34/0x68)
[    0.279785]  r8:00000000 r7:80869b78 r6:00000000 r5:80869b78 r4:ad962e10
[    0.279817] [<802fcf80>] (platform_drv_probe) from [<802fb8f8>] (really_probe+0x1b8/0x294)
[    0.279824]  r5:ad962e10 r4:808b3c34
[    0.279845] [<802fb740>] (really_probe) from [<802fbad0>] (__driver_attach+0xa0/0xa4)
[    0.279853]  r8:00000109 r7:00000000 r6:ad962e44 r5:80869b78 r4:ad962e10 r3:00000007
[    0.279885] [<802fba30>] (__driver_attach) from [<802f9c64>] (bus_for_each_dev+0x74/0xa8)
[    0.279892]  r6:802fba30 r5:80869b78 r4:00000000 r3:ad829c5c
[    0.279919] [<802f9bf0>] (bus_for_each_dev) from [<802fb36c>] (driver_attach+0x24/0x28)
[    0.279926]  r6:8086e108 r5:ad168b00 r4:80869b78
[    0.279950] [<802fb348>] (driver_attach) from [<802fb020>] (bus_add_driver+0x150/0x1f8)
[    0.279968] [<802faed0>] (bus_add_driver) from [<802fbf68>] (driver_register+0x80/0x100)
[    0.279975]  r7:8067e808 r6:ad16b100 r5:808556a0 r4:80869b78
[    0.280003] [<802fbee8>] (driver_register) from [<802fcf78>] (__platform_driver_register+0x5c/0x64)
[    0.280011]  r5:808556a0 r4:808556a0
[    0.280033] [<802fcf1c>] (__platform_driver_register) from [<8067e824>] (brcmvirt_gpio_driver_init+0x1c/0x20)
[    0.280049] [<8067e808>] (brcmvirt_gpio_driver_init) from [<80009688>] (do_one_initcall+0x94/0x1dc)
[    0.280065] [<800095f4>] (do_one_initcall) from [<80669e40>] (kernel_init_freeable+0x150/0x230)
[    0.280073]  r10:8069d9f4 r9:806695f0 r8:00000109 r7:80883000 r6:80883000 r5:00000006
[    0.280095]  r4:806a2364
[    0.280112] [<80669cf0>] (kernel_init_freeable) from [<805057fc>] (kernel_init+0x10/0xf0)
[    0.280119]  r10:00000000 r9:00000000 r8:00000000 r7:00000000 r6:00000000 r5:805057ec
[    0.280141]  r4:00000000
[    0.280158] [<805057ec>] (kernel_init) from [<8000f808>] (ret_from_fork+0x14/0x2c)
[    0.280165]  r4:00000000 r3:ad844000
[    0.280216] ---[ end trace 599b0ba8e8093f43 ]---

OpenELEC:~ # lsmod
Module                  Size  Used by
hci_uart               11657  1
btbcm                   3852  1 hci_uart
bluetooth             273858  3 btbcm,hci_uart
brcmfmac              164388  0
brcmutil                4729  1 brcmfmac
cfg80211              226808  1 brcmfmac
bcm2835_gpiomem         2588  0
bcm2708_rng              821  0
OpenELEC:~ # lsusb
Bus 001 Device 004: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
OpenELEC:~ # cat /etc/release
[dmesg-output.txt](https://github.com/OpenELEC/OpenELEC.tv/files/153086/dmesg-output.txt)

RPi2.arm-6.0.3
OpenELEC:~ # uname -a
Linux OpenELEC 4.1.18 #1 SMP Mon Feb 29 20:48:22 CET 2016 armv7l GNU/Linux

This happens on every boot. 

If you need more information, please let me know
Regards
Nikolay
[Uploading dmesg-output.txt…]()

**Comment by tomchiverton** [comment]
My Pi3 boots fine using NOOBS to install OpenElec. Maybe your image is corrupt. Did you try downloading it again and reburning the install?

**Comment by HiassofT** [comment]
FYI: Updating the GPU firmware seems to fix this issue:
http://openelec.tv/forum/124-raspberry-pi/69870-wolfson-audio-card-support?start=270#159271

The master branch should be fine, and #4826 should fix this for the  6.0 branch

Haven't tested myself, still waiting for Farnell to ship my RPi3s...

**Comment by nickerejv** [comment]
Thanks HiassofT, updating the firmware solved the kernel warning for me. The GPU firmware version is now:
# vcgencmd version
Mar  7 2016 17:12:02
Copyright (c) 2012 Broadcom
version 552adf40d2c18ab95fbfbbca990d303a170f3d74 (clean) (release)

used to be:
 # vcgencmd version
Feb 19 2016 19:53:38
Copyright (c) 2012 Broadcom
version 573126451d3fb80e6de5ffb7d1fa117d814417b8 (clean) (release)
