### ISSUE TITLE
RPI: "gpio-poweroff" overlay not working

### ISSUE THREAD

**Issue by Hollol** [OpenELEC/OpenELEC.tv#4812]
For my RPI (2B) / OpenELEC media center I build a power switch which is also able to cut the 5V power line upon a logical low-to-high transition. In principle, there is an overlay called "gpio-poweroff" which should exactly do this signal transition when the Pi is shutdown. 

See for example: https://github.com/raspberrypi/linux/issues/1031

I included the corresponding device tree/overlay into my config.txt (dtoverlay=gpio-poweroff) and it seems, that the overlay is actually loaded during boot. 
But unfortunately the overlay is not working correctly in OpenELEC. The GPIO state is not changing upon shutdown and the GPIO is even not changed to an output as it should.

I already asked for help in the Raspberry forum and there it was confirmed, that (although) loaded correctly) the overlay is not behaving as it should in OpenELEC. On Raspian it is working as expected.

Please also see: https://www.raspberrypi.org/forums/viewtopic.php?p=918743#p918743

I hope, there is a chance to make this overlay working also in OpenELEC, because it really gives a nice possibility for automatic power management on the Pi.

Thanks

**Comment by lrusak** [comment]
No idea really. Can you check what kernel raspbian is using where it works?

OpenELEC 6.x is using 4.1.x
OpenELEC 7.x is using 4.4.x

So maybe try a milhouse build and see if it is working.

**Comment by MilhouseVH** [comment]
I've just read the referenced thread, tried my latest 4.4.3 kernel/master build and it's producing the same (incorrect) results - GPIO 26 is still showing as INPUT. Unfortunately if @pelwell is stumped then it's unlikely I'll be able to work it out! :(

@pelwell: If you have any ideas or can suggest a kernel logging patch that may provide more information/clues, I'd be happy to build the kernel and test.

**Comment by Hollol** [comment]
I thought this feature is really implemented in the firmware/kernel. Is there anything special about firmware/kernel in openelec?

**Comment by MilhouseVH** [comment]
Nothing special, but the kernel is configured slightly differently to Raspbian and other Pi distributions as OpenELEC is more focused on supporting specific hardware/services so doesn't need to include so many kernel options. Possibly a setting is missing from the OpenELEC kernel for this to work.

**Comment by Hollol** [comment]
Thanks for the clarification. Hopefully, @pelwell finds time to look into this issue as you suggested.

**Comment by pelwell** [comment]
It's not been forgotten. I'm off work at the moment, but when I can I'll give Milhouse a patch with some tests in to try and work out what is failing.

**Comment by sraue** [comment]
should be fixed with https://github.com/OpenELEC/OpenELEC.tv/pull/4840 can you test?

**Comment by pelwell** [comment]
Yes, that would do it.
