### ISSUE TITLE
Please compile mysql client with --with-openssl

### ISSUE THREAD

**Issue by sopparus** [OpenELEC/OpenELEC.tv#4813]
Hi! While trying to setup mysql over ssl with openelec I noticed it didnt work from openelec but it did from my windows computer. Checked
https://github.com/OpenELEC/OpenELEC.tv/blob/25bebf2a198940545185ae9b2bb25920f83de80b/packages/databases/mysql/package.mk

and it seems mysql client is lacking ssl support, im no expert so maybe there is more to it but will you please consider adding this?
bump to 5.7 is required for TLS 1.2 btw.

should probably be
--with-ssl=/path/to/openssl/lib
or something simular btw

From http://download.nust.na/pub6/mysql/doc/refman/5.1/en/secure-using-ssl.html
To use OpenSSL instead, specify the --with-ssl option with the path to the directory where the OpenSSL header files and libraries are located:

shell> ./configure --with-ssl=path

Thanks alot

**Comment by lrusak** [comment]
added in #4817
