### ISSUE TITLE
RPi2: Multi-boot problem

### ISSUE THREAD

**Issue by AhmedKamal20** [OpenELEC/OpenELEC.tv#4821]
Using : Raspberry Pi 2 
Installed Rasbian and OpenELEC v 5.0.2
booting into Rasbian works fine , but OpenELEC failed to boot . 
this is the screen when i trying to boot with : 

**NOOBS 1.5**    

![1.5](http://i.imgur.com/7ku7yZD.jpg)

**NOOBS 1.8**    

[Failed] Failed to start udev  kernel device manager .    

![1.8](http://i.imgur.com/GF3Hk3r.jpg)

**Comment by sraue** [comment]
please try a newer noobs version and openelec release

**Comment by AhmedKamal20** [comment]
NOOBS 1.8 is the latest , and it installs OpenELEC v 5.0.2 , is there a way to install the latest OpenELEC with noobs ?

**Comment by tomchiverton** [comment]
I get v6.0.3 from NOOBS.

**Comment by AhmedKamal20** [comment]
OK , It finally booted , but with v5.0.2 , with NOOBS 1.8 , i checked for updates from OpenELEC setting and i found v5.0.8 , and upgraded to it , worked fine , but YouTube plugin didn't work.   

about , v6.0.3 , no clue , i can't find away to get it through NOOBS , any help ?

**Comment by MilhouseVH** [comment]
You need to manually upgrade from 5.x to 6.x, as automatic updating between major releases is not supported. Copy the 6.0.3 tar file into the OpenELEC "Update" folder and reboot.

**Comment by AhmedKamal20** [comment]
By "tar file" you mean this , right ?  

[![](https://i.imgur.com/E40M260.png)](http://releases.openelec.tv/OpenELEC-RPi2.arm-6.0.3.tar?mirrorlist)

and sorry , Where is the Update folder? , i can't find it through this mess
PS : this is my sd card that has NOOBS with Rasbian and OpenELEC    
![image](https://cloud.githubusercontent.com/assets/14352372/13651805/a90058ac-e651-11e5-9307-993bad2b4eb8.png)

**Comment by lrusak** [comment]
@AhmedKamal20 see, http://wiki.openelec.tv/index.php/Updating_OpenELEC

**Comment by AhmedKamal20** [comment]
OK , i got it , thank you guys , and sorry for asking previously answered question.
@sraue please, close this issue.
