### ISSUE TITLE
amvideocap0 for Wetek Core - solved

### ISSUE THREAD

**Issue by uros-z** [OpenELEC/OpenELEC.tv#4827]
Hi,

I found the problem which was the cause for the missing /dev/amvideocap0.

I removed /* from line 295 and */ from line 309 in /arch/arm/boot/dts/amlogic/meson8m2_wetek_core.dtd file.

Can someone please make a patch, I don't know how or fix the meson8m2_wetek_core.dtd file at the source.

Best regards,
Uros

**Comment by stefansaraev** [comment]
@codesnake could you please update it upstream ?

**Comment by stefansaraev** [comment]
@uros-z thanks for this btw, I was trying to figure why rendercapture did not work here. I was blind not seeing the whole block commented..

**Comment by codesnake** [comment]
@stefansaraev Sure, will update DTS for Core today.

**Comment by uros-z** [comment]
@stefansaraev No problem. I'm glad I could make a small contribution.
