### ISSUE TITLE
Updates should be on by default 

### ISSUE THREAD

**Issue by tomchiverton** [OpenELEC/OpenELEC.tv#4830]
I just installed to a Pi using NOOBS. Automatic updates was off. 
Users rarely change defaults, and defaulting to remaining insecure in a device that has access to important digital content seems a strange choice.

**Comment by sraue** [comment]
afaik they are disabled but the notification is enabled, so the user is seeing he has to react...

**Comment by tomchiverton** [comment]
Users many never see the prompt. 
For instance, openelec headless (just a speaker) or if the user isn't watching for the few seconds the update message displays before vanishing forever. 
Please consider reopening. 
-- 
Tom
