### ISSUE TITLE
Uncompressed (?) audio not always playing

### ISSUE THREAD

**Issue by cvwillegen** [OpenELEC/OpenELEC.tv#4835]
When playing back FLAC files, I regularly get no audio from my receiver. When I force my receiver to 'switch' to the input that OpenElec is connected to, I get audio back, but the next track (and the track after that) play back without any sound.

In the attached log files you can see that I Played back 4 tracks from an album that shows the problem. During playback of the first track, I selected the input on my receiver (and got audio). During the full second track, there was no sound. During the third track, I selected the input on my receiver, again, and got audio. Then, I got silence again at the start of the fourth track.

The log files are from 1970-01-01 since I rebooted before starting the album to get the cleanest possible log files.

I updated to OpenElec 6.0.3 this morning. I also noticed the problem in 6.0.1 but had not reported it yet.
[log-1970-01-01-00.09.53.zip](https://github.com/OpenELEC/OpenELEC.tv/files/162789/log-1970-01-01-00.09.53.zip)

I also tried playing back an album with MP3 files. This appears to work without problems.

**Comment by popcornmix** [comment]
Does changing resample quality from "GPU" to "Low" make a difference?
Does using a nightly/milhouse build make a difference?
http://forum.kodi.tv/showthread.php?tid=250817

**Comment by cvwillegen** [comment]
On Tue, Mar 8, 2016 at 12:34 PM, popcornmix <notifications@github.com> wrote:
> Does changing resample quality from "GPU" to "Low" make a difference?

No.

> Does using a nightly/milhouse build make a difference?

No

Christ van Willegen

**Comment by cvwillegen** [comment]
Also, the interface sounds are not playing back.

**Comment by cvwillegen** [comment]
Setting 'Keep audio alive' to 'Always' does solve it...
