### ISSUE TITLE
RTL8812AU update kernel module

### ISSUE THREAD

**Issue by gsgleason** [OpenELEC/OpenELEC.tv#4838]
I am currently use a USB RTL8812AU based USB WLAN NIC and the performance is terrible. It constantly drops and freezes. I'm on Openelec legacy 64 bit 6.0.3 and it's using module version v4.2.2_7502.20130517, which is old, from https://github.com/abperiasamy/rtl8812AU_8821AU_linux

I am using  version v4.3.14_13455.20150212 in Arch Linux with very good results from  https://github.com/Grawp/rtl8812au_rtl8821au

Would it be possible update the 8812au module to this version?

**Comment by sraue** [comment]
we could weekly change the repos for the sources... there are so much and every is different... if we change this now... how we can be sure it dont breaks for others? i will try todo this, if you are willing to test and compare (with providing good results) and only for master.

see also https://github.com/Grawp/rtl8812au_rtl8821au/issues/3

**Comment by sraue** [comment]
please also provide the package source receipts for this driver in Arch

**Comment by sraue** [comment]
this one? https://aur4.archlinux.org/packages/rtl8812au_rtl8821au-dkms-git/

**Comment by sraue** [comment]
added with https://github.com/OpenELEC/OpenELEC.tv/pull/4840

**Comment by gsgleason** [comment]
Yes, that is what I'm using in Arch and it works well for me.  I'm attempting to compile openelec from course by updating packages/linux-drivers/RTL8812AU/package.mk with the URL of the newer driver.

**Comment by sraue** [comment]
you should use the commit... the updated patches are needed too

**Comment by gsgleason** [comment]
Can you explain how to do that?  I'm very novice.  What git commands?

**Comment by gsgleason** [comment]
Ok, I did that and ended up with this version of RTL8812AU: v4.3.14_13455.20150212_BTCOEX20150128-51

I'll see how it works.  

Looking at my Arch Linux I am actually using v4.3.20_14803.20150724_beta from the aforementioned driver's 4.3.22_beta branch: https://github.com/Grawp/rtl8812au_rtl8821au/tree/4.3.22_beta wtih good results, but the beta tag is a little offputting, to I'll continue to test this commit.

**Comment by sraue** [comment]
any news? added the newer driver in https://github.com/OpenELEC/OpenELEC.tv/commit/57f8ea67b585e98c62bbebb20f48a33810f59e9a please test too and report back

**Comment by gsgleason** [comment]
The version v4.3.14_13455.20150212 did not work well.  I had similar issues of intermittent lack of data.  Pings had packet loss and sometimes 3 seconds of delay.

I will get the new commit and let you know.

**Comment by sopparus** [comment]
this version worked alot better for me then the other one that come with imx6

**Comment by sraue** [comment]
@sopparus imx6? this driver is disabled there in recent master

**Comment by sopparus** [comment]
@sraue, yes but mk01 built an image for me with this driver and kernel 4.4 which makes it work on imx6

**Comment by sraue** [comment]
ok, @gsgleason let me know if you have problems building our master

**Comment by gsgleason** [comment]
It built fine. The new driver works much better, but the network doesn't work after resuming from suspend.  I use systemctl suspend from arch (systemd) and upon resume it works.  I don't know if this is something you can look at or not.

**Comment by sraue** [comment]
@gsgleason can you try to unload the module before suspending and then reload on wakeup?
if this works i would try todo this automatically

**Comment by gsgleason** [comment]
@sraue I could theoretically unload the module via SSH before suspend, but if it remains unloaded after resume I'd have no SSH access. Is there a way to get a terminal otherwise?  The other TTY (Alt F2, etc) don't have a login prompt.

**Comment by gsgleason** [comment]
That did NOT work.  I just ended up with a black screen with a mouse pointer, and the logs showed segfaults against kodi.bin.  I can't see how that's related to the change I made or if I happened to get a non-working commit.  Is it worth trying again?

**Comment by sraue** [comment]
i will create a testbuild later, or if you want do byself try to add the module name in packages/sysutils/busybox/config/suspend-modules.conf and rebuild busybox with ```rm -rf build.OpenELEC*/busybox-* && make```

**Comment by gsgleason** [comment]
I think there is something else wrong.  Black screen with nothing but mouse cursor.  

Kodi.log: http://pastebin.com/UuMe5udS
dmesg: http://pastebin.com/NtUsyK7w

**Comment by sraue** [comment]
@gsgleason try after https://github.com/OpenELEC/OpenELEC.tv/commit/3e250d216a64c6c0a18e7aa5ace3fe3117c3d057

**Comment by gsgleason** [comment]
Similar failure:

20:08:15 T:139876879927424   FATAL: addon 'skin.estouchy' is missing.
20:08:15 T:139876879927424   FATAL: CServiceManager::Init: Unable to start CAddonMgr

**Comment by sraue** [comment]
@gsgleason can you post your /usr/share/kodi/system/addon-manifest.xml from your running system?

**Comment by gsgleason** [comment]
I already went back to commit 57f8ea6 to get back to Kodi 16.x as I didn't want to be on an Alpha release.  I manually updated the packages/sysutils/busybox/config/suspend-modules.conf file and added module 8812au.

I do not have a I do not have the file addon-manifest.xml currently.  If you would like me to go back to the master branch and recompile to test, I can do so.

**Comment by sraue** [comment]
you can add this to openelec-7.0 too, this will be added in our beta 2, to build openelec-7.0 use https://github.com/OpenELEC/OpenELEC.tv/tree/openelec-7.0

for sure i am intrested in your old addon-manifest.xml if you still have this, otherwise a further test with master if its now fixed would be noce, if you can do this.

will close this now since the driver is updated and the supend funktion should work (in 7.0 too)

**Comment by sraue** [comment]
thanks much for your help

**Comment by gsgleason** [comment]
I just compiled master again without modifications, and the module seems to work well, and the suspect-resume is good.

Here is the requested file:

<?xml version="1.0"?>
<addons>
  <addon>audioencoder.xbmc.builtin.aac</addon>
  <addon>audioencoder.xbmc.builtin.wma</addon>
  <addon>game.controller.default</addon>
  <addon>kodi.adsp</addon>
  <addon>kodi.audiodecoder</addon>
  <addon>kodi.game</addon>
  <addon>kodi.guilib</addon>
  <addon>kodi.inputstream</addon>
  <addon>kodi.peripheral</addon>
  <addon>kodi.resource</addon>
  <addon>metadata.album.universal</addon>
  <addon>metadata.artists.universal</addon>
  <addon>metadata.common.allmusic.com</addon>
  <addon>metadata.common.fanart.tv</addon>
  <addon>metadata.common.htbackdrops.com</addon>
  <addon>metadata.common.imdb.com</addon>
  <addon>metadata.common.musicbrainz.org</addon>
  <addon>metadata.common.theaudiodb.com</addon>
  <addon>metadata.common.themoviedb.org</addon>
  <addon>metadata.local</addon>
  <addon>metadata.themoviedb.org</addon>
  <addon>metadata.tvdb.com</addon>
  <addon>repository.xbmc.org</addon>
  <addon>resource.images.weathericons.default</addon>
  <addon>resource.language.en_gb</addon>
  <addon>resource.uisounds.confluence</addon>
  <addon>screensaver.xbmc.builtin.black</addon>
  <addon>screensaver.xbmc.builtin.dim</addon>
  <addon>script.module.pil</addon>
  <addon>skin.estuary</addon>
  <addon>webinterface.default</addon>
  <addon>xbmc.addon</addon>
  <addon>xbmc.audioencoder</addon>
  <addon>xbmc.codec</addon>
  <addon>xbmc.core</addon>
  <addon>xbmc.gui</addon>
  <addon>xbmc.json</addon>
  <addon>xbmc.metadata</addon>
  <addon>xbmc.pvr</addon>
  <addon>xbmc.python</addon>
  <addon>xbmc.webinterface</addon>
  <addon>os.openelec.tv</addon>
  <addon>repository.openelec.tv</addon>
  <addon>service.openelec.settings</addon>
</addons>

**Comment by sraue** [comment]
thanks much
