### ISSUE TITLE
TBS5520 and TBS6522 Multi-Standard TV Tuner USB Box and PCI Express Board drivers support?

### ISSUE THREAD

**Issue by Hedda** [OpenELEC/OpenELEC.tv#4839]
Can you please add latest Linux drivers for TBS Technologies "TBS 5520" USB Box and "TBS 6522" Tuner Board to OpenELEC?

http://www.tbsdtv.com/download/

Same Linux drivers and latest for TBS5520 amd TBS6522 is currently v160219 here as of the time writing this request:

http://www.tbsdtv.com/download/document/common/tbs-linux-drivers_v160219.zip

TBS5520 and TBS6522 multi-standard tuner USB box and board supports DVB-T2, DVB-S2, DVB-C, and ISDB-T standards.

http://www.cnx-software.com/2015/11/14/tbs5520-multi-standard-tuner-box-and-linux-drivers/

http://www.tbsdtv.com/products/tbs5520_multi-standard_tv_tuner_usb_box.html

http://www.tbsdtv.com/products/tbs6522_multi-standard_dual_tuner_pcie_card.html

FYI, the cheapest place I seen that TBS5520 Multi-standard TV Tuner USB Box can be purchased is here:

http://www.buydvb.net/tbs5520-multistandard-tv-tuner-usb-box-p-131.html
https://www.tbs-technology.de/shop/product_info.php?products_id=68

**Comment by CvH** [comment]
This would break every other DVB driver at the system (the TBS drivers are based at an ~4 year old driver set).

You need and "special" image for this -> http://goo.gl/FD90Kr

**Comment by Hedda** [comment]
Any way to convince TBS to release different drivers for OpenELEC mainline?

Perhaps OpenELEC could contact TBS about sponsorship and partnership?

**Comment by CvH** [comment]
This isn't a OpenELEC problem, the same effect you got with every linux out there (the TBS drivers replace the whole DVB drivers at the system).

**Comment by Hedda** [comment]
OK, so don't you think that Team OpenELEC developers could influence the TBS Technologies company to develop proper Linux drivers for that uses the Linux kernel DVB API (DVB API)?

If some Team OpenELEC developer would contact the TBS Technologies company and talk with them to explain this issue and why the TBS Technologies company need to begin to develop compatible Linux drivers, and how that would be in everyones interest.

Maybe a more political and financial question than a techical one, but coming from the authority of a popular Linux distroution like OpenELEC maybe, just maybe, the TBS Technologies company would listen it if was put forward in a way for them to understand why this is important for mainiling drivers.

**Comment by CvH** [comment]
@Hedda 
afaik this was already tried (from other distros). Also the TBS cards are working pretty well with OE - you just need the "special" image for it (like you need to install the drivers at other distros). Not really that big problem at all. If you have further questions you can contact me at the OE board/thread (no need to spam the mailboxes from the git users).
