### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vpeter4** [OpenELEC/OpenELEC.tv#4842]
Dear sraue,

can I ask you if you have read the letter you received it by multiple channels? Some answer to give back would be appropriate. Time is running out and there will be no return after deadline.

Because you are actively using github this is our last attempt to reach you.

Thank you.

**Comment by sraue** [comment]
i answered @chewitt last morning. and i ask you all to not bitch in the public and maybe use PMs on slack for personal questions

**Comment by chewitt** [comment]
For the record I have received nothing by email, slack, sms, whatsapp or skype, and considering there is a private channel dedicated to this in slack it's amusing that you choose to reply in public here.

**Comment by sraue** [comment]
@vpeter asked here, so i answered him here... also for the record
