### ISSUE TITLE
OpenELEC-RPi.arm-6.0.3.tar file will not unpackt to an img.

### ISSUE THREAD

**Issue by rin67630** [OpenELEC/OpenELEC.tv#4843]
Dear Openelec Team.
The last OpenELEC-RPi.arm-6.0.3.tar file unpacks to a folder, not to an .img file.
Can you please take action?
Regards

**Comment by MilhouseVH** [comment]
As it should, no action to be taken. Download OpenELEC-RPi.arm-6.0.3.img.gz if you want a file that unpacks to a .img file.
