### ISSUE TITLE
avahi-0.6.32/configure: line 27741: xyes: command not found

### ISSUE THREAD

**Issue by wbsgu** [OpenELEC/OpenELEC.tv#4844]
Compiling recent master of openelec 7.0. Is there some dependency missing that normally openelec compile check have missed to install before compiling or why did i get this message:

/home/a/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/avahi-0.6.32/configure: line 27741: xyes: command not found

**Comment by sraue** [comment]
please post config.log from avahi source dir

**Comment by sraue** [comment]
closing this for now
