### ISSUE TITLE
Update Raspberry Pi 2/3 Firmware and Kernel for better Integrated Wifi

### ISSUE THREAD

**Issue by hhromic** [OpenELEC/OpenELEC.tv#4845]
Hello,
first of all great work with OpenELEC. I'm very impressed of the engineering put behind this project. The resulting system is smooth as silk and very professional.

I just got a Raspberry Pi 3 with -as you know- integrated onboard Wifi. I installed OpenELEC on it and runs flawlessly except that the integrated WiFi module goes to sleep very quickly and the system loses connectivity unless you keep it pinging or streaming from the network. In addition the performance of the WiFi module is very unstable.

I tracked down the issue to a well-known (by now) problem that the Power Management was defaulted to "ON" in the initial kernels supporting this Wifi module. The RPI foundation already switched this setting to "OFF" in their latest firmware/kernel as can be seen in this commit:

https://github.com/raspberrypi/firmware/commit/8b4e5482b52e6fb438dddc0d88ba0ba8d44af54b

```
kernel: brcmfmac: Disable power management
See: https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=138312
```

So I would like to kindly ask if there is any chance to get an updated OpenELEC 6.0.4 release including this updated kernel? I verified that the updated kernel is versioned as 4.1.19 (just one ahead of the already included 4.1.18 in OpenELEC). So I guess this should be almost straight-forward to do.

The WiFi module going to sleep and having unstable connection is very annoying and shadows an otherwise almost perfect system.

Thanks!
Hugo.

**Comment by hhromic** [comment]
Hello again,
I think this commit is much more useful as it is on the source code and not pre-compiled binaries. Sorry for that:

https://github.com/raspberrypi/linux/commit/1f133059e579d7aeef76ab8402b95eb4418e8ca4

So it's a very simple patch actually.

Cheers,
Hugo.

**Comment by sraue** [comment]
should be fixed in https://github.com/OpenELEC/OpenELEC.tv/commit/eaa7ac105ac3f3916beba9e4a37c4e8c8a6c3036

**Comment by hhromic** [comment]
Great stuff !
Looking very forward to the next OE 6.0.x update release ;)

Thanks,
Hugo.
