### ISSUE TITLE
add support for Leoxsys USB wifi adapter (driver links included)

### ISSUE THREAD

**Issue by baijuchaudhari** [OpenELEC/OpenELEC.tv#4848]
please add support for this tiny usb wifi adapter. company has provided drivers, but i dont know how to install them in OpenElec. the adapter works great without drivers(default driver) in Wheezy.
Actually, i'm able to connect to different networks, but unable to do Wifi tethering. it just says working in bottom-right corner and goes away.
since it already has linux drivers, i hope the solution might be simpler.
here are links-
product-
https://paytm.com/shop/p/leoxsys-150-mbps-wireless-usb-adapter-black-COMLEOXSYS-150-3GTE21399B34E89B0?q=Leoxsys%20150%20Mbps%20Wireless%20USB%20Adapter%20%28Black%29&from=autosuggest
drivers page-
http://www.leoxsys.com/downloads.php
my adapter driver-
https://www.dropbox.com/s/d8ji8kssh25bswq/linux_rtl8188eus.rar?dl=0

thanks.

**Comment by sraue** [comment]
please post a lsusb and dmesg output from a system with connected usb adapter

**Comment by baijuchaudhari** [comment]
sorry but, i read about its(openelec) 'read only' file system and how its been locked up, i gave up using it. also, soon i will not be having access to it(rpi2 and all its setup) any longer.
however, currently i'm using OSMC latest version with kodi'16. so, i'm posting results for osmc(probably they might help you.).

OSMC lsusb-

Bus 001 Device 004: ID 0bda:8179 Realtek Semiconductor Corp.
Bus 001 Device 005: ID 0480:d010 Toshiba America Info. Systems, Inc.
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

OSMC dmesg-
[    0.000000] Booting Linux on physical CPU 0xf00
[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 4.4.3-3-osmc (root@rpi2) (gcc version 4.9.2 (Debian 4.9.2-10) ) #1 SMP PREEMPT Tue Mar 1 15:51:08 UTC 2016
[    0.000000] CPU: ARMv7 Processor [410fc075] revision 5 (ARMv7), cr=10c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] Machine model: Raspberry Pi 2 Model B Rev 1.1
[    0.000000] cma: Reserved 8 MiB at 0x2e400000
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] On node 0 totalpages: 192512
[    0.000000] free_area_init_node: node 0, pgdat 80bcd900, node_mem_map add64000
[    0.000000]   Normal zone: 1692 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 192512 pages, LIFO batch:31
[    0.000000] [bcm2709_smp_init_cpus] enter (9660->f3003010)
[    0.000000] [bcm2709_smp_init_cpus] ncores=4
[    0.000000] PERCPU: Embedded 13 pages/cpu @aefab000 s23552 r8192 d21504 u53248
[    0.000000] pcpu-alloc: s23552 r8192 d21504 u53248 alloc=13*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 190820
[    0.000000] Kernel command line: dma.dmachans=0x7f35 bcm2708_fb.fbwidth=592 bcm2708_fb.fbheight=448 bcm2709.boardrev=0xa21041 bcm2709.serial=0xa59b215e smsc95xx.macaddr=B8:27:EB:9B:21:5E bcm2708_fb.fbswap=1 bcm2709.uart_clock=3000000 bcm2709.disk_led_gpio=47 bcm2709.disk_led_active_low=0 vc_mem.mem_base=0x3dc00000 vc_mem.mem_size=0x3f000000  root=/dev/mmcblk0p2 rootfstype=ext4 rootwait quiet osmcdev=rbp2
[    0.000000] PID hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Memory: 741084K/770048K available (7997K kernel code, 437K rwdata, 1864K rodata, 1792K init, 764K bss, 20772K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
    vector  : 0xffff0000 - 0xffff1000   (   4 kB)
    fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
    vmalloc : 0xaf800000 - 0xff800000   (1280 MB)
    lowmem  : 0x80000000 - 0xaf000000   ( 752 MB)
    modules : 0x7f000000 - 0x80000000   (  16 MB)
      .text : 0x80008000 - 0x809a9764   (9862 kB)
      .init : 0x809aa000 - 0x80b6a000   (1792 kB)
      .data : 0x80b6a000 - 0x80bd75f4   ( 438 kB)
       .bss : 0x80bda000 - 0x80c992ac   ( 765 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] Preemptible hierarchical RCU implementation.
[    0.000000]  Build-time adjustment of leaf fanout to 32.
[    0.000000] NR_IRQS:16 nr_irqs:16 16
[    0.000000] Architected cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000011] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000033] Switching to timer-based delay loop, resolution 52ns
[    0.000324] Console: colour dummy device 80x30
[    0.000548] console [tty0] enabled
[    0.000575] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=192000)
[    0.000601] pid_max: default: 32768 minimum: 301
[    0.000954] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000975] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.002205] Disabling cpuset control group subsystem
[    0.002255] Initializing cgroup subsys io
[    0.002287] Initializing cgroup subsys memory
[    0.002341] Initializing cgroup subsys devices
[    0.002366] Initializing cgroup subsys freezer
[    0.002391] Initializing cgroup subsys net_cls
[    0.002464] CPU: Testing write buffer coherency: ok
[    0.002546] ftrace: allocating 19380 entries in 57 pages
[    0.052998] CPU0: update cpu_capacity 1024
[    0.053037] CPU0: thread -1, cpu 0, socket 15, mpidr 80000f00
[    0.053054] [bcm2709_smp_prepare_cpus] enter
[    0.053195] Setting up static identity map for 0x8240 - 0x8298
[    0.132585] [bcm2709_boot_secondary] cpu:1 started (0) 17
[    0.132939] [bcm2709_secondary_init] enter cpu:1
[    0.132996] CPU1: update cpu_capacity 1024
[    0.133004] CPU1: thread -1, cpu 1, socket 15, mpidr 80000f01
[    0.162618] [bcm2709_boot_secondary] cpu:2 started (0) 18
[    0.162899] [bcm2709_secondary_init] enter cpu:2
[    0.162932] CPU2: update cpu_capacity 1024
[    0.162940] CPU2: thread -1, cpu 2, socket 15, mpidr 80000f02
[    0.192697] [bcm2709_boot_secondary] cpu:3 started (0) 16
[    0.192949] [bcm2709_secondary_init] enter cpu:3
[    0.192981] CPU3: update cpu_capacity 1024
[    0.192989] CPU3: thread -1, cpu 3, socket 15, mpidr 80000f03
[    0.193082] Brought up 4 CPUs
[    0.193112] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.193122] CPU: All CPU(s) started in HYP mode.
[    0.193131] CPU: Virtualization extensions available.
[    0.194017] devtmpfs: initialized
[    0.205659] VFP support v0.3: implementor 41 architecture 2 part 30 variant 7 rev 5
[    0.206174] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.207241] pinctrl core: initialized pinctrl subsystem
[    0.208052] NET: Registered protocol family 16
[    0.213501] DMA: preallocated 4096 KiB pool for atomic coherent allocations
[    0.242842] cpuidle: using governor ladder
[    0.272871] cpuidle: using governor menu
[    0.279905] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.279926] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.280111] Serial: AMBA PL011 UART driver
[    0.280428] 3f201000.uart: ttyAMA0 at MMIO 0x3f201000 (irq = 87, base_baud = 0) is a PL011 rev2
[    0.281123] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.354535] bcm2835-dma 3f007000.dma: DMA legacy API manager at f3007000, dmachans=0x1
[    0.356520] SCSI subsystem initialized
[    0.356752] usbcore: registered new interface driver usbfs
[    0.356862] usbcore: registered new interface driver hub
[    0.357024] usbcore: registered new device driver usb
[    0.363108] raspberrypi-firmware soc:firmware: Attached to firmware from 2016-02-25 18:56
[    0.390309] clocksource: Switched to clocksource arch_sys_counter
[    0.443107] FS-Cache: Loaded
[    0.443547] CacheFiles: Loaded
[    0.460030] NET: Registered protocol family 2
[    0.461332] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[    0.461475] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[    0.461667] TCP: Hash tables configured (established 8192 bind 8192)
[    0.461800] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.461867] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.462226] NET: Registered protocol family 1
[    0.462752] RPC: Registered named UNIX socket transport module.
[    0.462770] RPC: Registered udp transport module.
[    0.462781] RPC: Registered tcp transport module.
[    0.462792] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.575148] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 5 counters available
[    0.577593] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    0.577776] audit: initializing netlink subsys (disabled)
[    0.577852] audit: type=2000 audit(0.539:1): initialized
[    0.593808] VFS: Disk quotas dquot_6.6.0
[    0.594230] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.597026] FS-Cache: Netfs 'nfs' registered for caching
[    0.598210] NFS: Registering the id_resolver key type
[    0.598281] Key type id_resolver registered
[    0.598294] Key type id_legacy registered
[    0.601828] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 252)
[    0.602033] io scheduler noop registered
[    0.602635] io scheduler bfq registered (default)
[    0.602648] BFQ I/O-scheduler version: v7r7
[    0.605518] BCM2708FB: allocated DMA memory ee800000
[    0.605566] BCM2708FB: allocated DMA channel 0 @ f3007000
[    0.611458] Console: switching to colour frame buffer device 74x28
[    1.498323] bcm2835-rng 3f104000.rng: hwrng registered
[    1.498462] vc-cma: Videocore CMA driver
[    1.498478] vc-cma: vc_cma_base      = 0x00000000
[    1.498489] vc-cma: vc_cma_size      = 0x00000000 (0 MiB)
[    1.498500] vc-cma: vc_cma_initial   = 0x00000000 (0 MiB)
[    1.498827] vc-mem: phys_addr:0x00000000 mem_base=0x3dc00000 mem_size:0x3f000000(1008 MiB)
[    1.519774] brd: module loaded
[    1.531075] loop: module loaded
[    1.532158] vchiq: vchiq_init_state: slot_zero = 0xae880000, is_master = 0
[    1.533923] Loading iSCSI transport class v2.0-870.
[    1.535003] usbcore: registered new interface driver smsc95xx
[    1.535073] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    1.735424] Core Release: 2.80a
[    1.735446] Setting default values for core params
[    1.735474] Finished setting default values for core params
[    1.935906] Using Buffer DMA mode
[    1.935923] Periodic Transfer Interrupt Enhancement - disabled
[    1.935933] Multiprocessor Interrupt Enhancement - disabled
[    1.935945] OTG VER PARAM: 0, OTG VER FLAG: 0
[    1.935961] Dedicated Tx FIFOs mode
[    1.936398] WARN::dwc_otg_hcd_init:1047: FIQ DMA bounce buffers: virt = 0xae814000 dma = 0xee814000 len=9024
[    1.936438] FIQ FSM acceleration enabled for :
Non-periodic Split Transactions
Periodic Split Transactions
High-Speed Isochronous Endpoints
[    1.936463] dwc_otg: Microframe scheduler enabled
[    1.936532] WARN::hcd_init_fiq:413: FIQ on core 1 at 0x8057a3e8
[    1.936551] WARN::hcd_init_fiq:414: FIQ ASM at 0x8057a758 length 36
[    1.936570] WARN::hcd_init_fiq:439: MPHI regs_base at 0xaf87e000
[    1.936655] dwc_otg 3f980000.usb: DWC OTG Controller
[    1.936727] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    1.936785] dwc_otg 3f980000.usb: irq 62, io mem 0x00000000
[    1.936840] Init: Port Power? op_state=1
[    1.936851] Init: Power Port (0)
[    1.937178] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    1.937200] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.937216] usb usb1: Product: DWC OTG Controller
[    1.937233] usb usb1: Manufacturer: Linux 4.4.3-3-osmc dwc_otg_hcd
[    1.937249] usb usb1: SerialNumber: 3f980000.usb
[    1.938394] hub 1-0:1.0: USB hub found
[    1.938463] hub 1-0:1.0: 1 port detected
[    1.939317] dwc_otg: FIQ enabled
[    1.939331] dwc_otg: NAK holdoff enabled
[    1.939341] dwc_otg: FIQ split-transaction FSM enabled
[    1.939384] Module dwc_common_port init
[    1.939729] usbcore: registered new interface driver usb-storage
[    1.940101] mousedev: PS/2 mouse device common for all mice
[    1.940715] usbcore: registered new interface driver usbtouchscreen
[    1.941047] bcm2835-cpufreq: min=600000 max=900000
[    1.943713] sdhci: Secure Digital Host Controller Interface driver
[    1.943721] sdhci: Copyright(c) Pierre Ossman
[    1.944022] sdhost: log_buf @ ae813000 (ee813000)
[    2.020326] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    2.020523] sdhci-pltfm: SDHCI platform and OF driver helper
[    2.021031] ledtrig-cpu: registered to indicate activity on CPUs
[    2.021195] hidraw: raw HID events driver (C) Jiri Kosina
[    2.021357] usbcore: registered new interface driver usbhid
[    2.021365] usbhid: USB HID core driver
[    2.021833] Initializing XFRM netlink socket
[    2.021866] NET: Registered protocol family 17
[    2.022002] Key type dns_resolver registered
[    2.022138] Registering SWP/SWPB emulation handler
[    2.022939] registered taskstats version 1
[    2.023109] vc-sm: Videocore shared memory driver
[    2.023123] [vc_sm_connected_init]: start
[    2.041048] [vc_sm_connected_init]: end - returning 0
[    2.043932] Freeing unused kernel memory: 1792K (809aa000 - 80b6a000)
[    2.077721] mmc0: host does not support reading read-only switch, assuming write-enable
[    2.079771] mmc0: new high speed SDHC card at address 0002
[    2.090656] mmcblk0: mmc0:0002 00000 7.42 GiB
[    2.092256]  mmcblk0: p1 p2
[    2.130485] Indeed it is in host mode hprt0 = 00021501
[    2.258887] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    2.269183] fsck: E2fsck run: /bin/e2fsck -p -C 0 /dev/mmcblk0p2
[    2.269418] fsck: Filesystem UUID: c31f0c8f-a492-4959-a542-5db854a211bb
[    2.269663] fsck: /dev/mmcblk0p2: clean, 37769/470496 files, 338552/1881856 blocks
[    2.320353] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    2.320514] Indeed it is in host mode hprt0 = 00001101
[    2.520671] usb 1-1: New USB device found, idVendor=0424, idProduct=9514
[    2.520695] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.521456] hub 1-1:1.0: USB hub found
[    2.521550] hub 1-1:1.0: 5 ports detected
[    2.800390] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    2.900730] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[    2.900755] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.903693] smsc95xx v1.0.4
[    2.963417] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-3f980000.usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:9b:21:5e
[    3.040391] usb 1-1.4: new high-speed USB device number 4 using dwc_otg
[    3.141045] usb 1-1.4: New USB device found, idVendor=0bda, idProduct=8179
[    3.141072] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    3.141084] usb 1-1.4: Product: 802.11n NIC
[    3.141095] usb 1-1.4: Manufacturer: Realtek
[    3.141106] usb 1-1.4: SerialNumber: 00E04C0001
[    3.414116] random: systemd urandom read with 67 bits of entropy available
[    3.466210] NET: Registered protocol family 10
[    3.730374] usb 1-1.3: new high-speed USB device number 5 using dwc_otg
[    3.831947] usb 1-1.3: New USB device found, idVendor=0480, idProduct=d010
[    3.831970] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    3.831982] usb 1-1.3: Product: External USB 3.0
[    3.831993] usb 1-1.3: Manufacturer: Toshiba
[    3.832004] usb 1-1.3: SerialNumber: 20130503010387
[    3.832862] usb-storage 1-1.3:1.0: USB Mass Storage device detected
[    3.843731] scsi host0: usb-storage 1-1.3:1.0
[    3.889934] systemd[1]: Cannot add dependency job for unit dispman_vncserver.service, ignoring: Unit dispman_vncserver.service failed to load: No such file or directory.
[    3.890348] systemd[1]: Cannot add dependency job for unit display-manager.service, ignoring: Unit display-manager.service failed to load: No such file or directory.
[    3.890563] systemd[1]: Found ordering cycle on basic.target/start
[    3.890584] systemd[1]: Found dependency on sysinit.target/start
[    3.890603] systemd[1]: Found dependency on kbd.service/start
[    3.890622] systemd[1]: Found dependency on remote-fs.target/start
[    3.890638] systemd[1]: Found dependency on remote-fs-pre.target/start
[    3.890655] systemd[1]: Found dependency on connman.service/start
[    3.890671] systemd[1]: Found dependency on dbus.service/start
[    3.890687] systemd[1]: Found dependency on basic.target/start
[    3.890705] systemd[1]: Breaking ordering cycle by deleting job kbd.service/start
[    3.890726] systemd[1]: Job kbd.service/start deleted to break ordering cycle starting with basic.target/start
[    3.890996] systemd[1]: Found ordering cycle on basic.target/start
[    3.891019] systemd[1]: Found dependency on sysinit.target/start
[    3.891037] systemd[1]: Found dependency on rpcbind.service/start
[    3.891055] systemd[1]: Found dependency on network-online.target/start
[    3.891072] systemd[1]: Found dependency on network.target/start
[    3.891088] systemd[1]: Found dependency on connman.service/start
[    3.891104] systemd[1]: Found dependency on dbus.service/start
[    3.891120] systemd[1]: Found dependency on basic.target/start
[    3.891137] systemd[1]: Breaking ordering cycle by deleting job rpcbind.service/start
[    3.891157] systemd[1]: Job rpcbind.service/start deleted to break ordering cycle starting with basic.target/start
[    4.133810] fuse init (API version 7.23)
[    4.141750] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    4.399613] systemd-udevd[188]: starting version 215
[    4.593965] lirc_dev: IR Remote Control driver registered, major 244
[    4.608774] lirc_rpi: module is from the staging directory, the quality is unknown, you have been warned.
[    4.656481] bcm2835-wdt 3f100000.watchdog: Broadcom BCM2835 watchdog timer
[    4.659687] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
[    4.854404] usbcore: registered new interface driver uas
[    4.982094] mmcblk0: r/w command failed, status = 0x80000900
[    5.044083] mmc0: tried to reset card
[    5.114947] r8188eu: module is from the staging directory, the quality is unknown, you have been warned.
[    5.125027] Chip Version Info: CHIP_8188E_Normal_Chip_TSMC_A_CUT_1T1R_RomVer(0)
[    5.162502] usbcore: registered new interface driver r8188eu
[    5.292681] FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[    5.570486] lirc_rpi: auto-detected active low receiver on GPIO pin 18
[    5.571038] lirc_rpi lirc_rpi: lirc_dev: driver lirc_rpi registered at minor = 0
[    5.571060] lirc_rpi: driver registered!
[    5.892700] input: lircd as /devices/virtual/input/input0
[    6.324093] systemd-journald[165]: Received request to flush runtime journal from PID 1
[    6.863502] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[    6.864107] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    8.451542] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    8.453106] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xC5E1
[    8.508016] 8021q: 802.1Q VLAN Support v1.8
[    8.986278] random: nonblocking pool is initialized
[   11.027286] scsi 0:0:0:0: Direct-Access     Toshiba  External USB 3.0 0201 PQ: 0 ANSI: 6
[   11.030263] sd 0:0:0:0: [sda] Very big device. Trying to use READ CAPACITY(16).
[   11.039015] sd 0:0:0:0: Attached scsi generic sg0 type 0
[   11.058897] sd 0:0:0:0: [sda] 732566645 4096-byte logical blocks: (3.00 TB/2.73 TiB)
[   11.060693] sd 0:0:0:0: [sda] Write Protect is off
[   11.060724] sd 0:0:0:0: [sda] Mode Sense: 2b 00 00 00
[   11.062111] sd 0:0:0:0: [sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[   11.064831] sd 0:0:0:0: [sda] 732566645 4096-byte logical blocks: (3.00 TB/2.73 TiB)
[   11.101505]  sda: sda1
[   11.105994] sd 0:0:0:0: [sda] 732566645 4096-byte logical blocks: (3.00 TB/2.73 TiB)
[   11.106816] sd 0:0:0:0: [sda] Attached SCSI disk
[   13.267628] Console: switching to colour dummy device 80x30

i hope this may help you.
thanks.

**Comment by sraue** [comment]
the driver for this wlan device is installed per default on openelec and should work. if there are problems please post logs from a running openelec system.

> i read about its(openelec) 'read only' file system and how its been locked up, i gave up using it. 
yes openelec has a readonly filesystem for the system files, but configuration and userdata can be written and stored on the disks. OpenELEC is not *locked up*, please tell to the OSMC guy who told this.
