### ISSUE TITLE
imx6 failed to build from latest commits - RTL8812AU: update to RTL8812AU-9fc227c

### ISSUE THREAD

**Issue by islipfd19** [OpenELEC/OpenELEC.tv#4849]
Build log attached.

/var/lib/jenkins/workspace/OpenELEC.tv_imx6/build.OpenELEC-imx6.arm-7.0-devel/RTL8812AU-9fc227c/os_dep/linux/ioctl_linux.c: In function '_rtw_ioctl_wext_private':
/var/lib/jenkins/workspace/OpenELEC.tv_imx6/build.OpenELEC-imx6.arm-7.0-devel/RTL8812AU-9fc227c/os_dep/linux/ioctl_linux.c:15299:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while((++k < num_priv_args) && strcmp(priv_args[k].name, cmdname));
             ^
/var/lib/jenkins/workspace/OpenELEC.tv_imx6/build.OpenELEC-imx6.arm-7.0-devel/RTL8812AU-9fc227c/os_dep/linux/ioctl_linux.c:15302:8: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (k == num_priv_args) {
        ^
/var/lib/jenkins/workspace/OpenELEC.tv_imx6/build.OpenELEC-imx6.arm-7.0-devel/RTL8812AU-9fc227c/os_dep/linux/ioctl_linux.c:15313:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   while ((++j < num_priv_args) && ((priv_args[j].name[0] != '\0') ||
               ^
/var/lib/jenkins/workspace/OpenELEC.tv_imx6/build.OpenELEC-imx6.arm-7.0-devel/RTL8812AU-9fc227c/os_dep/linux/ioctl_linux.c:15318:9: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (j == num_priv_args) {
         ^
Makefile:1276: recipe for target '_module_/var/lib/jenkins/workspace/OpenELEC.tv_imx6/build.OpenELEC-imx6.arm-7.0-devel/RTL8812AU-9fc227c' failed
make[2]: *** [_module_/var/lib/jenkins/workspace/OpenELEC.tv_imx6/build.OpenELEC-imx6.arm-7.0-devel/RTL8812AU-9fc227c] Error 2
make[2]: Leaving directory '/var/lib/jenkins/workspace/OpenELEC.tv_imx6/build.OpenELEC-imx6.arm-7.0-devel/linux-cuboxi-3.14-ea83bda'
Makefile:1565: recipe for target 'modules' failed
make[1]: *** [modules] Error 2
make[1]: Leaving directory '/var/lib/jenkins/workspace/OpenELEC.tv_imx6/build.OpenELEC-imx6.arm-7.0-devel/RTL8812AU-9fc227c'
Makefile:12: recipe for target 'image' failed
make: *** [image] Error 2
[log.zip](https://github.com/OpenELEC/OpenELEC.tv/files/172705/log.zip)

**Comment by sopparus** [comment]
I also hit this, might be some pointers here -> https://github.com/n-aizu/rtl8812au/commit/f49a5fe18d876ecbf2ec38e5a75db4371f9d037b
for anyone who knows what they're doing

**Comment by sraue** [comment]
fixed in https://github.com/OpenELEC/OpenELEC.tv/commit/e304184971f1952c38df8a2eb10dbb74978c3a20
