### ISSUE TITLE
DVB-C Card support/ driver removed from OPENELEC ?!

### ISSUE THREAD

**Issue by major-mayer** [OpenELEC/OpenELEC.tv#4853]
Hey,
I'm forwarding this from the tvheadend forum (and OPENELEC), because i was told that it may be an error related to OPENELEC driver support not to tvheadend.
## Here is the text: 

> laurenz bihlamyer wrote:

```
Hey there,
My Openelec setup worked pretty good until i upgraded the system to version 6 Today.
I had to reactivate tvheadend back and frontend manually after i upgraded ( server) system.
In the web interface i can still find all services, muxes and networks, but my problem is, that the DVB-C adapter is missing.
I even have access on the EPG and it's still accurate, but i am not able to watch any television,
because when i start, OPENELEC shows me something like no free adapter (i'm using it on german so...).
Due to the upgrade of OPENELEC TVHeadend also got upgraded to version 4.0.8
I am using tvheadend as the back- and frontend for many devices in my house, so i'm totally fucked up now, because I cannot watch TV anymore.
Please help

Update #1: My old DVB-T Stick is still recognized by tvheadend, but my DVB-C card won't show up. Just like the driver has been deleted in the last update.

Card: Mystique CaBiX - C2 DVB-C
Logs if needed in the attachment
```

--------- Answer
Your dmesg log shows..

[   12.178290] cx23885 driver version 0.0.4 loaded
[   12.178482] cx23885[0]: Your board isn't known (yet) to the driver.
[   12.178482] cx23885[0]: Try to pick one of the existing card configs via
[   12.178482] cx23885[0]: card=<n> insmod option.  Updating to the latest
[   12.178482] cx23885[0]: version might help as well.
[   12.178486] cx23885[0]: Here is a list of valid choices for the card=<n> insmod option:
[   12.178487] cx23885[0]:    card=0 -> UNKNOWN/GENERIC
[   12.178489] cx23885[0]:    card=1 -> Hauppauge WinTV-HVR1800lp
[   12.178490] cx23885[0]:    card=2 -> Hauppauge WinTV-HVR1800

Looks like support for your card has been removed from the kernel in openelec (more than likely omitted by whoever builds it). This isn't a Tvheadend issue but an Openelec one, please open an issue here
## Don't forget to include the logs :) In the meantime downgrade until they fix it.

U can find the thread here: https://tvheadend.org/boards/5/topics/20355?r=20360#message-20360
If u need more logs or information, ask me, but remember i'm not a dev and english is not my native language :)
[log-2016-03-16-21.10.10.zip](https://github.com/OpenELEC/OpenELEC.tv/files/178130/log-2016-03-16-21.10.10.zip)

**Comment by sraue** [comment]
can you post the same logs from the working system too?

**Comment by iGamerHD** [comment]
Yeah the problem is, that I updated my openelec to version 6. 
I have an backup from 5 but when I restore I don't get a downgrade, only my data is restored not the whole system. But I will try to downgrade to version 5 this evening. 

Gesendet mit TypeApp

**Comment by iGamerHD** [comment]
Here you go, downgrading was a shit, i don't want to do this again.
Hope it will help finding the bug, because now everything works well again.
For me, i will stay on Openelec 5.0.8 for the next time.

[log-2016-03-17-20.51.48.zip](https://github.com/OpenELEC/OpenELEC.tv/files/178659/log-2016-03-17-20.51.48.zip)
