### ISSUE TITLE
Compile error.

### ISSUE THREAD

**Issue by ed68** [OpenELEC/OpenELEC.tv#4855]
Scanning dependencies of target userhdhomerun
make[3]: Leaving directory '/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/.x86_64-openelec-linux-gnu'
make[3]: Entering directory '/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/.x86_64-openelec-linux-gnu'
[ 25%] Building CXX object CMakeFiles/userhdhomerun.dir/main.o
[ 25%] Building CXX object CMakeFiles/userhdhomerun.dir/conf_inifile.o
[ 37%] Building CXX object CMakeFiles/userhdhomerun.dir/hdhomerun_control.o
[ 50%] Building CXX object CMakeFiles/userhdhomerun.dir/hdhomerun_tuner.o
[ 62%] Building CXX object CMakeFiles/userhdhomerun.dir/hdhomerun_controller.o
[ 75%] Building CXX object CMakeFiles/userhdhomerun.dir/log_file.o
[ 87%] Building CXX object CMakeFiles/userhdhomerun.dir/thread_pthread.o
In file included from /home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/thread_pthread.cpp:1:0:
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/thread_pthread.h: In constructor 'ThreadPthread::ThreadPthread()':
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/thread_pthread.h:26:8: warning: 'ThreadPthread::m_running' will be initialized after [-Wreorder]
   bool m_running;
        ^
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/thread_pthread.h:20:8: warning:   'bool ThreadPthread::m_stop' [-Wreorder]
   bool m_stop;
        ^
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/thread_pthread.cpp:5:1: warning:   when initialized here [-Wreorder]
 ThreadPthread::ThreadPthread()
 ^
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_controller.cpp: In constructor 'HdhomerunController::HdhomerunController(int)':
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_controller.cpp:97:22: warning: deleting object of polymorphic class type 'HdhomerunTuner' which has non-virtual destructor might cause undefined behaviour [-Wdelete-non-virtual-dtor]
               delete tuner;
                      ^
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_controller.cpp: In destructor 'HdhomerunController::~HdhomerunController()':
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_controller.cpp:153:10: warning: deleting object of polymorphic class type 'Control' which has non-virtual destructor might cause undefined behaviour [-Wdelete-non-virtual-dtor]
   delete m_control;
          ^
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_controller.cpp:160:12: warning: deleting object of polymorphic class type 'HdhomerunTuner' which has non-virtual destructor might cause undefined behaviour [-Wdelete-non-virtual-dtor]
     delete tuner;
            ^
In file included from /home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_control.cpp:22:0:
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_control.h: In constructor 'Control::Control(HdhomerunController*)':
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_control.h:70:24: warning: 'Control::m_hdhomerun' will be initialized after [-Wreorder]
   HdhomerunController* m_hdhomerun;
                        ^
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_control.h:64:7: warning:   'int Control::m_fdIoctl' [-Wreorder]
   int m_fdIoctl;
       ^
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_control.cpp:37:1: warning:   when initialized here [-Wreorder]
 Control::Control(HdhomerunController* _hdhomerun)
 ^
In file included from /home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_control.cpp:22:0:
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_control.h:64:7: warning: 'Control::m_fdIoctl' will be initialized after [-Wreorder]
   int m_fdIoctl;
       ^
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_control.h:62:7: warning:   'int Control::m_read' [-Wreorder]
   int m_read;
       ^
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_control.cpp:37:1: warning:   when initialized here [-Wreorder]
 Control::Control(HdhomerunController* _hdhomerun)
 ^
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_control.cpp: In member function 'void Control::FE_SET_Frontend(const dvbhdhomerun_control_mesg&)':
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_control.cpp:206:10: warning: unused variable 'ret' [-Wunused-variable]
      int ret = tuner->Tune(_mesg.u.frequency);
          ^
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_tuner.cpp: In member function 'void HdhomerunTuner::StartStreaming(int)':
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_tuner.cpp:225:8: warning: unused variable 'ret' [-Wunused-variable]
    int ret = hdhomerun_device_set_tuner_filter(m_device, StrPidFilter.c_str());
        ^
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_tuner.cpp: In member function 'int HdhomerunTuner::ReadSignalStrength()':
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_tuner.cpp:319:8: warning: unused variable 'ret' [-Wunused-variable]
    int ret = hdhomerun_device_get_tuner_status(m_device, NULL, &hdhomerun_status);
        ^
[100%] Linking CXX executable userhdhomerun
make[3]: Leaving directory '/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/.x86_64-openelec-linux-gnu'
[100%] Built target userhdhomerun
make[2]: Leaving directory '/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/.x86_64-openelec-linux-gnu'
make[1]: Leaving directory '/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/.x86_64-openelec-linux-gnu'
config/functions: line 111: [: too many arguments
ls: cannot access /home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/.install_pkg/lib/modules/*: No such file or directory
basename: missing operand
Try 'basename --help' for more information.
config/functions: line 111: [: too many arguments
cp: target '/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/.install_pkg/lib/modules/hdhomerun/hdhomerun/' is not a directory
Makefile:9: ошибка выполнения рецепта для цели «release»
make: *** [release] Ошибка 1

**Comment by sraue** [comment]
please do a new build with removing the build.OpenELEC.Generic.x86_64-7.0-devel/ dir completly
