### ISSUE TITLE
Compile error. Part 2.

### ISSUE THREAD

**Issue by ed68** [OpenELEC/OpenELEC.tv#4858]
BUILD    dvbhdhomerun (target)
make[1]: Entering directory '/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/kernel'
Building driver... ccflags-y=-Idrivers/media/dvb-core -Idrivers/media/frontends -Idrivers/media/dvb/dvb-core -Idrivers/media/dvb/frontends
make -C /home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/linux-4.5  M=/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/kernel modules
make[2]: Entering directory '/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/linux-4.5'
  Building modules, stage 2.
  MODPOST 3 modules
WARNING: "dvb_dmx_init" [/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/kernel/dvb_hdhomerun.ko] undefined!
WARNING: "dvb_unregister_adapter" [/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/kernel/dvb_hdhomerun.ko] undefined!
WARNING: "dvb_register_frontend" [/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/kernel/dvb_hdhomerun.ko] undefined!
WARNING: "dvb_unregister_frontend" [/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/kernel/dvb_hdhomerun.ko] undefined!
WARNING: "dvb_frontend_detach" [/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/kernel/dvb_hdhomerun.ko] undefined!
WARNING: "dvb_dmxdev_release" [/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/kernel/dvb_hdhomerun.ko] undefined!
WARNING: "dvb_dmx_swfilter" [/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/kernel/dvb_hdhomerun.ko] undefined!
WARNING: "dvb_dmx_release" [/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/kernel/dvb_hdhomerun.ko] undefined!
WARNING: "dvb_register_adapter" [/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/kernel/dvb_hdhomerun.ko] undefined!
WARNING: "dvb_dmxdev_init" [/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/kernel/dvb_hdhomerun.ko] undefined!
make[2]: Leaving directory '/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/linux-4.5'
make[1]: Leaving directory '/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/kernel'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/.x86_64-openelec-linux-gnu
make[1]: Entering directory '/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/.x86_64-openelec-linux-gnu'
make[2]: Entering directory '/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/.x86_64-openelec-linux-gnu'
make[3]: Entering directory '/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/.x86_64-openelec-linux-gnu'
Scanning dependencies of target userhdhomerun
make[3]: Leaving directory '/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/.x86_64-openelec-linux-gnu'
make[3]: Entering directory '/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/.x86_64-openelec-linux-gnu'
[ 12%] Building CXX object CMakeFiles/userhdhomerun.dir/hdhomerun_controller.o
[ 25%] Building CXX object CMakeFiles/userhdhomerun.dir/hdhomerun_tuner.o
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_tuner.cpp: In member function 'void HdhomerunTuner::StartStreaming(int)':
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_tuner.cpp:225:8: warning: unused variable 'ret' [-Wunused-variable]
    int ret = hdhomerun_device_set_tuner_filter(m_device, StrPidFilter.c_str());
        ^
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_tuner.cpp: In member function 'int HdhomerunTuner::ReadSignalStrength()':
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_tuner.cpp:319:8: warning: unused variable 'ret' [-Wunused-variable]
    int ret = hdhomerun_device_get_tuner_status(m_device, NULL, &hdhomerun_status);
        ^
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_controller.cpp: In constructor 'HdhomerunController::HdhomerunController(int)':
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_controller.cpp:97:22: warning: deleting object of polymorphic class type 'HdhomerunTuner' which has non-virtual destructor might cause undefined behaviour [-Wdelete-non-virtual-dtor]
               delete tuner;
                      ^
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_controller.cpp: In destructor 'HdhomerunController::~HdhomerunController()':
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_controller.cpp:153:10: warning: deleting object of polymorphic class type 'Control' which has non-virtual destructor might cause undefined behaviour [-Wdelete-non-virtual-dtor]
   delete m_control;
          ^
/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/userhdhomerun/hdhomerun_controller.cpp:160:12: warning: deleting object of polymorphic class type 'HdhomerunTuner' which has non-virtual destructor might cause undefined behaviour [-Wdelete-non-virtual-dtor]
     delete tuner;
            ^
[ 37%] Linking CXX executable userhdhomerun
make[3]: Leaving directory '/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/.x86_64-openelec-linux-gnu'
[100%] Built target userhdhomerun
make[2]: Leaving directory '/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/.x86_64-openelec-linux-gnu'
make[1]: Leaving directory '/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/.x86_64-openelec-linux-gnu'
config/functions: line 111: [: too many arguments
ls: cannot access /home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/.install_pkg/lib/modules/*: No such file or directory
basename: missing operand
Try 'basename --help' for more information.
config/functions: line 111: [: too many arguments
cp: target '/home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/.install_pkg/lib/modules/hdhomerun/hdhomerun/' is not a directory
Makefile:9: ошибка выполнения рецепта для цели «release»
make: *** [release] Ошибка 1

**Comment by sraue** [comment]
you have done a fullbuild? check if the build.* folder contains 2 linux-* folders

**Comment by ed68** [comment]
you have done a fullbuild?

 

Yes. Full remove and new run git command.

 

check if the build.* folder contains 2 linux-* folders

 

итого 236

drwxrwxr-x 59 hcefm hcefm 4096 марта 20 14:51 .

drwxrwxr-x 13 hcefm hcefm 4096 марта 20 15:57 ..

drwxrwxr-x 10 hcefm hcefm 4096 марта 20 13:45 autoconf-2.69

drwxr-xr-x  6 hcefm hcefm 4096 марта 20 13:46 autoconf-archive-2015.09.25

drwxr-xr-x 12 hcefm hcefm 4096 марта 20 13:45 automake-1.15

drwxrwxr-x 19 hcefm hcefm 4096 марта 20 14:03 binutils-2.26

drwxr-xr-x 15 hcefm hcefm 4096 марта 20 13:53 bison-3.0.4

drwxr-xr-x 36 hcefm hcefm 4096 марта 20 14:44 busybox-1.24.2

drwxrwxr-x  5 hcefm hcefm 4096 марта 20 13:42 ccache-3.2.3

drwxrwxr-x 12 hcefm hcefm 4096 марта 20 14:25 cmake-3.5.0

drwxr-xr-x 13 hcefm hcefm 4096 марта 20 14:32 cpio-2.12

drwxrwxr-x  5 hcefm hcefm 4096 марта 20 14:44 cpu-firmware-9885c9c

drwxrwxr-x  9 hcefm hcefm 4096 марта 20 14:46 dosfstools-3.0.28

drwxrwxr-x 12 hcefm hcefm 4096 марта 20 14:57 dvbhdhomerun-20130704

drwxr-xr-x 23 hcefm hcefm 4096 марта 20 14:46 e2fsprogs-1.42.13

drwxrwxr-x  3 hcefm hcefm 4096 марта 20 14:35 entropy-0

drwxr-xr-x  8 hcefm hcefm 4096 марта 20 14:30 fakeroot-1.20.2

drwxrwxr-x  9 hcefm hcefm 4096 марта 20 13:53 flex-2.5.39

drwxr-xr-x 44 hcefm hcefm 4096 марта 20 14:44 gcc-5.3.0

drwxr-xr-x 11 hcefm hcefm 4096 марта 20 13:43 gettext-0.19.7

drwxrwxr-x 72 hcefm hcefm 4096 марта 20 14:43 glibc-2.23

drwxrwxr-x 18 hcefm hcefm 4096 марта 20 14:05 gmp-6.1.0

drwxrwxr-x  4 hcefm hcefm 4096 марта 20 14:57 image

drwxrwxr-x  7 hcefm hcefm 4096 марта 20 14:46 initramfs

drwxrwxr-x  5 hcefm hcefm 4096 марта 20 13:46 intltool-0.51.0

drwxrwxr-x  5 hcefm hcefm 4096 марта 20 14:40 keyutils-1.5.9

drwxr-xr-x 14 hcefm hcefm 4096 марта 20 14:33 kmod-22

drwxrwxr-x  9 hcefm hcefm 4096 марта 20 14:30 libcap-2.25

drwxrwxr-x  3 hcefm hcefm 4096 марта 20 14:52 libhdhomerun-20150826

drwxr-xr-x 10 hcefm hcefm 4096 марта 20 14:44 libpng-1.6.21

drwxrwxr-x  9 hcefm hcefm 4096 марта 20 13:46 libtool-2.4.6

drwxrwxr-x 28 hcefm hcefm 4096 марта 20 14:51 linux-4.5

drwxr-xr-x 16 hcefm hcefm 4096 марта 20 14:29 lzo-2.09

drwxrwxr-x 11 hcefm hcefm 4096 марта 20 13:45 m4-1.4.17

drwxr-xr-x  9 hcefm hcefm 4096 марта 20 13:42 make-4.1

drwxr-xr-x  7 hcefm hcefm 4096 марта 20 14:06 mpc-1.0.3

drwxr-xr-x 11 hcefm hcefm 4096 марта 20 14:06 mpfr-3.1.3

drwxr-xr-x  8 hcefm hcefm 4096 марта 20 14:30 mtools-4.0.18

drwxrwxr-x 12 hcefm hcefm 4096 марта 20 14:46 open-iscsi-bf39941

drwxr-xr-x  8 hcefm hcefm 4096 марта 20 14:40 pciutils-3.4.1

drwxrwxr-x  5 hcefm hcefm 4096 марта 20 13:44 pkg-config-0.29

drwxr-xr-x  3 hcefm hcefm 4096 марта 20 14:44 plymouth-lite-0.6.0

drwxrwxr-x  3 hcefm hcefm 4096 марта 20 14:30 populatefs-95cc98b

drwxr-xr-x  8 hcefm hcefm 4096 марта 20 14:51 RTL8192CU-v4.0.2_9000.20130911

drwxrwxr-x  8 hcefm hcefm 4096 марта 20 14:51 RTL8192DU-9e7eb15

drwxrwxr-x  9 hcefm hcefm 4096 марта 20 14:51 RTL8192EU-a322c84

drwxrwxr-x  9 hcefm hcefm 4096 марта 20 14:51 RTL8812AU-928e27f

drwxrwxr-x 10 hcefm hcefm 4096 марта 20 13:42 sed-4.2.2

drwxr-xr-x  4 hcefm hcefm 4096 марта 20 14:29 squashfs-4.3

drwxrwxr-x 60 hcefm hcefm 4096 марта 20 14:51 .stamps

drwxrwxr-x 26 hcefm hcefm 4096 марта 20 14:40 systemd-229

drwxrwxr-x  3 hcefm hcefm 4096 марта 20 14:31 timezone-data-2016a

drwxrwxr-x 12 hcefm hcefm 4096 марта 20 14:30 toolchain

drwxrwxr-x 28 hcefm hcefm 4096 марта 20 14:45 util-linux-2.27.1

drwxrwxr-x  5 hcefm hcefm 4096 марта 20 14:44 v86d-0.1.10

drwxrwxr-x  4 hcefm hcefm 4096 марта 20 14:40 wireless-regdb-2016.02.08

drwxr-xr-x 15 hcefm hcefm 4096 марта 20 13:42 xz-5.2.2

drwxrwxr-x 13 hcefm hcefm 4096 марта 20 14:29 yasm-1.3.0

drwxr-xr-x 17 hcefm hcefm 4096 марта 20 14:44 zlib-1.2.8

**Comment by sraue** [comment]
i dont see a error before it dont find /home/hcefm/OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/.install_pkg/lib/modules/ please check if this lir exist and if so what is in... if it dont exist please post again the full compile output from this package again on a pastebin site

**Comment by ed68** [comment]
OpenELEC/master/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/dvbhdhomerun-20130704/

/dvbhdhomerun-20130704$ ls -alR .install_pkg

.install_pkg:

итого 12

drwxrwxr-x  3 hcefm hcefm 4096 марта 20 14:57 .

drwxrwxr-x 12 hcefm hcefm 4096 марта 20 14:57 ..

drwxrwxr-x  3 hcefm hcefm 4096 марта 20 14:57 lib

 

.install_pkg/lib:

итого 12

drwxrwxr-x 3 hcefm hcefm 4096 марта 20 14:57 .

drwxrwxr-x 3 hcefm hcefm 4096 марта 20 14:57 ..

drwxrwxr-x 3 hcefm hcefm 4096 марта 20 14:57 modules

 

.install_pkg/lib/modules:

итого 12

drwxrwxr-x 3 hcefm hcefm 4096 марта 20 14:57 .

drwxrwxr-x 3 hcefm hcefm 4096 марта 20 14:57 ..

drwxrwxr-x 2 hcefm hcefm 4096 марта 20 14:57 hdhomerun

 

.install_pkg/lib/modules/hdhomerun:

итого 8

drwxrwxr-x 2 hcefm hcefm 4096 марта 20 14:57 .

drwxrwxr-x 3 hcefm hcefm 4096 марта 20 14:57 ..

 

Not files. Full output tomorrow.

**Comment by ed68** [comment]
I ask to close a problem. She not to a reshilasye Arises at addition of additional modules in Openelec.

**Comment by sraue** [comment]
what you mean?

**Comment by ed68** [comment]
I have additional 
OpenELEC modules.
If I add them isn't compiled.

Sorry. Log compiling :



[openelec.zip](https://github.com/OpenELEC/OpenELEC.tv/files/182702/openelec.zip)
