### ISSUE TITLE
RPi2 Failed to build From Latest Master

### ISSUE THREAD

**Issue by islipfd19** [OpenELEC/OpenELEC.tv#4860]
[1;32mINSTALL[0m    bluez [1;37m(target)[0m
  [1;36mCHECKOUT[0m      kodi
Cloning into bare repository 'sources/kodi/kodi-newclock5.git'...
POST git-upload-pack (gzip 5502 to 2804 bytes)
fatal: Not a valid object name
  [1;36mUNPACK[0m   kodi
      [1;32mAPPLY PATCH[0m [1;37m(common)[0m   /var/lib/jenkins/workspace/OpenELEC.tv_RPi2/packages/mediacenter/kodi/patches/kodi-100.01-enable-PYTHONOPTIMIZE-with-external-Python.patch
can't find file to patch at input line 14
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From 26d1905c371dd7e0e23bb589ccf29f2bfec5b8af Mon Sep 17 00:00:00 2001
|From: Stefan Saraev <stefan@saraev.ca>
|Date: Sat, 18 Apr 2015 15:12:49 +0300
|Subject: [PATCH 01/13] enable PYTHONOPTIMIZE with external Python
|
|---
| xbmc/interfaces/python/XBPython.cpp | 7 +++----
| 1 file changed, 3 insertions(+), 4 deletions(-)
|
|diff --git a/xbmc/interfaces/python/XBPython.cpp b/xbmc/interfaces/python/XBPython.cpp
|index af8d608..6213dbe 100644
|--- a/xbmc/interfaces/python/XBPython.cpp
|+++ b/xbmc/interfaces/python/XBPython.cpp
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored
Makefile:12: recipe for target 'image' failed
make: *** [image] Error 1
Build step 'Execute shell' marked build as failure
CIFS: Current build result is [FAILURE], not going to run.
Sending e-mails to: islipfd19@gmail.com
Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
Returning node parameter for mimas
Script-Clear CCACHE is disabled. Triggering skipped
Finished: FAILURE

[log.zip](https://github.com/OpenELEC/OpenELEC.tv/files/182222/log.zip)

**Comment by brimur** [comment]
I can confirm and also the imx6 build failed too

````
In file included from /home/media/OpenELEC.tv/build.OpenELEC-imx6.arm-8.0-devel/libcec-6d68d21/src/libcec/adapter/IMX/IMXCECAdapterCommunication.cpp:31:0:
/home/media/OpenELEC.tv/build.OpenELEC-imx6.arm-8.0-devel/libcec-6d68d21/src/libcec/adapter/IMX/IMXCECAdapterCommunication.h:31:36: fatal error: platform/threads/mutex.h: No such file or directory
compilation terminated.
src/libcec/CMakeFiles/cec.dir/build.make:182: recipe for target 'src/libcec/CMakeFiles/cec.dir/adapter/IMX/IMXCECAdapterCommunication.cpp.o' failed
make[3]: *** [src/libcec/CMakeFiles/cec.dir/adapter/IMX/IMXCECAdapterCommunication.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /home/media/OpenELEC.tv/build.OpenELEC-imx6.arm-8.0-devel/libcec-6d68d21/src/libcec/adapter/AdapterFactory.cpp:63:0:
/home/media/OpenELEC.tv/build.OpenELEC-imx6.arm-8.0-devel/libcec-6d68d21/src/libcec/adapter/IMX/IMXCECAdapterCommunication.h:31:36: fatal error: platform/threads/mutex.h: No such file or directory
compilation terminated.
src/libcec/CMakeFiles/cec.dir/build.make:206: recipe for target 'src/libcec/CMakeFiles/cec.dir/adapter/AdapterFactory.cpp.o' failed
make[3]: *** [src/libcec/CMakeFiles/cec.dir/adapter/AdapterFactory.cpp.o] Error 1
make[3]: Leaving directory '/home/media/OpenELEC.tv/build.OpenELEC-imx6.arm-8.0-devel/libcec-6d68d21/.armv7a-openelec-linux-gnueabi'
CMakeFiles/Makefile2:215: recipe for target 'src/libcec/CMakeFiles/cec.dir/all' failed
make[2]: *** [src/libcec/CMakeFiles/cec.dir/all] Error 2
make[2]: Leaving directory '/home/media/OpenELEC.tv/build.OpenELEC-imx6.arm-8.0-devel/libcec-6d68d21/.armv7a-openelec-linux-gnueabi'
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/media/OpenELEC.tv/build.OpenELEC-imx6.arm-8.0-devel/libcec-6d68d21/.armv7a-openelec-linux-gnueabi'
make: *** [image] Error 2


````

**Comment by islipfd19** [comment]
RPi fails to builds as well.

5.37/.install_pkg/usr/bin/hex2hcd
libtool: install: /usr/bin/install -c tools/mpris-proxy /var/lib/jenkins/workspace/OpenELEC.tv_RPi/build.OpenELEC-RPi.arm-8.0-devel/bluez-5.37/.install_pkg/usr/bin/mpris-proxy
make[1]: Leaving directory '/var/lib/jenkins/workspace/OpenELEC.tv_RPi/build.OpenELEC-RPi.arm-8.0-devel/bluez-5.37'
  [1;33mBUILD[0m    network [1;37m(target)[0m
  [1;32mINSTALL[0m    network [1;37m(target)[0m
      [1;32mINSTALL[0m    connman [1;37m(target)[0m
          [1;32mINSTALL[0m    glib [1;37m(target)[0m
              [1;32mINSTALL[0m    libffi [1;37m(target)[0m
              [1;32mINSTALL[0m    pcre [1;37m(target)[0m
              [1;32mINSTALL[0m    Python [1;37m(host)[0m
          [1;32mINSTALL[0m    readline [1;37m(target)[0m
          [1;32mINSTALL[0m    dbus [1;37m(target)[0m
              [1;32mINSTALL[0m    expat [1;37m(target)[0m
          [1;32mINSTALL[0m    iptables [1;37m(target)[0m
              [1;32mINSTALL[0m    libmnl [1;37m(target)[0m
              [1;32mINSTALL[0m    libnftnl [1;37m(target)[0m
          [1;32mINSTALL[0m    wpa_supplicant [1;37m(target)[0m
              [1;32mINSTALL[0m    libnl [1;37m(target)[0m
          [1;32mINSTALL[0m    ppp [1;37m(target)[0m
          [1;32mINSTALL[0m    pptp [1;37m(target)[0m
          [1;32mINSTALL[0m    openvpn [1;37m(target)[0m
              [1;32mINSTALL[0m    lzo [1;37m(target)[0m
      [1;32mINSTALL[0m    iana-etc [1;37m(target)[0m
      [1;32mINSTALL[0m    ethtool [1;37m(target)[0m
      [1;32mINSTALL[0m    openssh [1;37m(target)[0m
      [1;32mINSTALL[0m    bluez [1;37m(target)[0m
  [1;36mCHECKOUT[0m      kodi
Cloning into bare repository 'sources/kodi/kodi-newclock5.git'...
POST git-upload-pack (gzip 5502 to 2805 bytes)
fatal: Not a valid object name
  [1;36mUNPACK[0m   kodi
      [1;32mAPPLY PATCH[0m [1;37m(common)[0m   /var/lib/jenkins/workspace/OpenELEC.tv_RPi/packages/mediacenter/kodi/patches/kodi-100.01-enable-PYTHONOPTIMIZE-with-external-Python.patch
can't find file to patch at input line 14
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From 26d1905c371dd7e0e23bb589ccf29f2bfec5b8af Mon Sep 17 00:00:00 2001
|From: Stefan Saraev <stefan@saraev.ca>
|Date: Sat, 18 Apr 2015 15:12:49 +0300
|Subject: [PATCH 01/13] enable PYTHONOPTIMIZE with external Python
|
|---
| xbmc/interfaces/python/XBPython.cpp | 7 +++----
| 1 file changed, 3 insertions(+), 4 deletions(-)
|
|diff --git a/xbmc/interfaces/python/XBPython.cpp b/xbmc/interfaces/python/XBPython.cpp
|index af8d608..6213dbe 100644
|--- a/xbmc/interfaces/python/XBPython.cpp
|+++ b/xbmc/interfaces/python/XBPython.cpp
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored
Makefile:12: recipe for target 'image' failed
make: *** [image] Error 1
Build step 'Execute shell' marked build as failure
CIFS: Current build result is [FAILURE], not going to run.
Sending e-mails to: islipfd19@gmail.com
Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
Returning node parameter for mimas

**Comment by sraue** [comment]
can you manually test this command:

```
git clone -v --bare -b newclock5 https://github.com/popcornmix/xbmc.git kodi-newclock5.git
cd kodi-newclock5.git
git archive --format=tar --prefix=kodi-test/ 8506a5e | xz > kodi-8506a5e.tar.xz
```

**Comment by islipfd19** [comment]
In what directory do you want the command performed in?

**Comment by sraue** [comment]
any temporary, but i think i know whats the problem...

**Comment by sraue** [comment]
@islipfd19 should be solved now with last commit, please try and report back

**Comment by islipfd19** [comment]
Just performed the command and this is what I received:
fatal: Not a valid object name

I'll kick off a build manually on my Jenkins box for RPi & RPi2; won't have a status until a few hours since other jobs are running and queued.

WeTek Play also failed and I expect WeTek Core and imx6 to fail as well. The WeTek Play failed with a different error so I'll open a new issue on that.

**Comment by sraue** [comment]
yes open new isses for every single different error

**Comment by sraue** [comment]
@brimur should be fixed in https://github.com/OpenELEC/OpenELEC.tv/commit/7d7d71f6eae7c330fd563e13583a10d27a87c9ce

**Comment by islipfd19** [comment]
RPi built successfully, waiting for RPi2 to complete

**Comment by islipfd19** [comment]
RPi built successfully, waiting for RPi2 to complete

**Comment by islipfd19** [comment]
RPi2 built successfully

**Comment by grimace** [comment]
This is still broken. What did you do to fix?
