### ISSUE TITLE
Kodi fails to start due to missing skin.estouchy

### ISSUE THREAD

**Issue by pyrodex** [OpenELEC/OpenELEC.tv#4865]
Latest master pull for both x86_64 and RPI

`20:58:54 258.318909 T:1962663936   FATAL: addon 'skin.estouchy' is missing.`

Was able to work around by pulling it from GIT and putting it in local addons until this is resolved.

**Comment by sraue** [comment]
can you test again with latest master (and removed the pulled addon)

**Comment by pyrodex** [comment]
compiling now and I'll report back.

**Comment by pyrodex** [comment]
Looks good!

**Comment by sraue** [comment]
thanks much \o/
