### ISSUE TITLE
imx6 build (fd6af69) succsessful, but kodi won't start

### ISSUE THREAD

**Issue by dolorosus** [OpenELEC/OpenELEC.tv#4867]
Hi,

just for the records:  imx6 build (fd6af69) is succsessful, but the produced image won't start kodi (loops) on cubox.
Which logfiles should I provide?

**Comment by sraue** [comment]
ca you please test the latest again? afaik you only have to rebuild kodi

**Comment by dolorosus** [comment]
Kodi starts now. Thanks

**Comment by sraue** [comment]
thanks much
