### ISSUE TITLE
OE 7.0 beta1 skin settings not save

### ISSUE THREAD

**Issue by Celedhrim** [OpenELEC/OpenELEC.tv#4872]
On wetek play , totally fresh install on a new sdcard

Boot ok , change a gui config ( like hide "programs" entry) , reboot via kodi menu , "programs" back !

See here for the same issue :
http://forum.kodi.tv/showthread.php?tid=258557 

The workaround is to proper shutdown kodi with "Exit" but it's not available in OE.
So , no gui setting persistence at all

Can't find issue on kodi for that , but 7.0 final could not come with such issue.

**Comment by Celedhrim** [comment]
Fix un beta 2 !

Thx for your great job

**Comment by sraue** [comment]
thanks much for reporting back and closing :-)
