### ISSUE TITLE
Generic fails to build from master

### ISSUE THREAD

**Issue by islipfd19** [OpenELEC/OpenELEC.tv#4874]
Commit # r22485
Commit - 51c94452b87a85ddfa674c3c90d4b414bb9253d9

openelec-linux-gnu/lib'
make[2]: Entering directory '/var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/.x86_64-openelec-linux-gnu/tools/llvm-shlib'
llvm[2]: Compiling libllvm.cpp for Release build (PIC)
llvm[2]: Linking Release Shared Library libLLVM-3.8.so
lto1: internal compiler error: compressed stream: data error
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
lto-wrapper: fatal error: /var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/x86_64-openelec-linux-gnu-g++-5.3.0 returned 1 exit status
compilation terminated.
/var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/lib/gcc/x86_64-openelec-linux-gnu/5.3.0/../../../../x86_64-openelec-linux-gnu/bin/ld.gold: fatal error: lto-wrapper failed
collect2: error: ld returned 1 exit status
/var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/Makefile.rules:1192: recipe for target '/var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/.x86_64-openelec-linux-gnu/Release/lib/libLLVM-3.8.so' failed
make[2]: *** [/var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/.x86_64-openelec-linux-gnu/Release/lib/libLLVM-3.8.so] Error 1
make[2]: Leaving directory '/var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/.x86_64-openelec-linux-gnu/tools/llvm-shlib'
/var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/Makefile.rules:866: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/.x86_64-openelec-linux-gnu'
Makefile:12: recipe for target 'image' failed
make: *** [image] Error 2

[build.zip](https://github.com/OpenELEC/OpenELEC.tv/files/187706/build.zip)

**Comment by sraue** [comment]
how you build? its a VM? how much RAM you have allocated if you build in a VM?

**Comment by islipfd19** [comment]
I built it as I always do, it was successful yesterday. This build was built on Ubuntu 15.10 with 4GB of RAM (this is a jenkins slave). It also occasionally fails on Ubuntu 15.10 server with 4GB of RAM (this is jenkins master)

Commands that are run at each build cycle are
make clean
PROJECT=Generic ARCH=x86_64 make image

I find it fails regularly, it's even worse when I had the ubuntu ccache package installed, I have since removed it; I found that it would get corrupted a few times a week.

**Comment by sraue** [comment]
there are no changes to llvm the last days... or to the compiler, can you try with clean ~/.ccache-openelec and ~/.ccache?

**Comment by islipfd19** [comment]
I ran `scripts/clean ~/.ccache-openelec` from the workspace directory on jenkins master and slave. It produced this output:

  CLEAN    /var/lib/jenkins/.ccache-openelec
      * Removing build.OpenELEC-Generic.x86_64-8.0-devel//var/lib/jenkins/.ccache-openelec-* ...

The .ccache directory doesn't exist.

I kicked off another build, it's running on the slave. That's where it failed previously. Should know how it turns out in a few hours.

It would be interesting to see if it helps as I've only encountered these types of llvm issue building Generic.

**Comment by sraue** [comment]
hmm scripts/clean was not meant for this, but if it works, why not? a simple rm -rf ~/.ccache-openelec does the same :-)

llvm is only integrated in the generic builds, thats why it dont fail on other builds. but llvm is very ram hungry while compiling :-) thats why i ask

**Comment by islipfd19** [comment]
I don't think scripts/clean did anything useful. The directory path in the produced output doesn't exist whatsoever. I ran scripts/clean because clean was an unrecognized command; I don't have ccache natively installed. When I did, I ran into llvm issues more frequently.

I could call a downstream job and use the ccache binary that's in the 'build*/toolchain/bin' directory to clear it when Generic fails. Although I'd have no way to determine if llvm cause the build to fail or if it was a git change until sometime after I review the failure. Generic is scheduled to run shortly after midnight and typically on master.

I've run the command `rm -rf ~/.ccache-openelec` in the past and it has worked, but doing so impacts the performance of the other projects being built (the cache needs to be built over again). I recently read that llvm is RAM hungry, it's amazing how hungry it is!

Would it be feasible to limit the amount of memory usage during llvm compile time using '-mlimit' flag as described here: [http://llvm.org/docs/CommandGuide/bugpoint.html](url)?

**Comment by islipfd19** [comment]
As I suspected, the `scripts/clean ~/.ccache-openelec` did nothing. I cleaned the ccache using the binary in the toolchain.

This is the error I got on this attempt:
openelec-linux-gnu/lib'
make[2]: Entering directory '/var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/.x86_64-openelec-linux-gnu/tools/llvm-shlib'
llvm[2]: Compiling libllvm.cpp for Release build (PIC)
llvm[2]: Linking Release Shared Library libLLVM-3.8.so

out of memory allocating 7267882958631081011 bytes after a total of 31908480 bytes
collect2: error: ld returned 1 exit status
/var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/Makefile.rules:1192: recipe for target '/var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/.x86_64-openelec-linux-gnu/Release/lib/libLLVM-3.8.so' failed
make[2]: *** [/var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/.x86_64-openelec-linux-gnu/Release/lib/libLLVM-3.8.so] Error 1
make[2]: Leaving directory '/var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/.x86_64-openelec-linux-gnu/tools/llvm-shlib'
/var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/Makefile.rules:866: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/.x86_64-openelec-linux-gnu'
Makefile:12: recipe for target 'image' failed
make: *** [image] Error 2

[build.zip](https://github.com/OpenELEC/OpenELEC.tv/files/188425/build.zip)

**Comment by sraue** [comment]
out of memory allocating 7267882958631081011 bytes after a total of 31908480 bytes <--- it seems it needs much memory, can you free some or you have a swappartition added? (best is to have at least 8GB while building)

**Comment by islipfd19** [comment]
I have a cron job that runs every hour to release memory that wasn't freed when it should have been. I already have a swap partition available but I know its 4GB so I created an additional 8GB swap file and kicked off the build process again.

**Comment by islipfd19** [comment]
This last attempt was successful. Though I do not know if clearing the ccache fixed the build as it did in the past or added 8GB of swap did. I should know within a week's time as long as there are commits made to master and they don't break the build process. Only time will tell.

**Comment by sraue** [comment]
thanks much

**Comment by islipfd19** [comment]
Got the error again. This time it had an issue allocating 2,040 Pebibytes...

ake[5]: Leaving directory '/var/lib/jenkins/workspace/fork-OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/.x86_64-openelec-linux-gnu/lib/Target/X86/Utils'
make[4]: Leaving directory '/var/lib/jenkins/workspace/fork-OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/.x86_64-openelec-linux-gnu/lib/Target/X86'
make[3]: Leaving directory '/var/lib/jenkins/workspace/fork-OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/.x86_64-openelec-linux-gnu/lib/Target'
make[2]: Leaving directory '/var/lib/jenkins/workspace/fork-OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/.x86_64-openelec-linux-gnu/lib'
make[2]: Entering directory '/var/lib/jenkins/workspace/fork-OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/.x86_64-openelec-linux-gnu/tools/llvm-shlib'
llvm[2]: Compiling libllvm.cpp for Release build (PIC)
llvm[2]: Linking Release Shared Library libLLVM-3.8.so

out of memory allocating 2297045431422144479 bytes after a total of 34988672 bytes
collect2: error: ld returned 1 exit status
/var/lib/jenkins/workspace/fork-OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/Makefile.rules:1192: recipe for target '/var/lib/jenkins/workspace/fork-OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/.x86_64-openelec-linux-gnu/Release/lib/libLLVM-3.8.so' failed
make[2]: *** [/var/lib/jenkins/workspace/fork-OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/.x86_64-openelec-linux-gnu/Release/lib/libLLVM-3.8.so] Error 1
make[2]: Leaving directory '/var/lib/jenkins/workspace/fork-OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/.x86_64-openelec-linux-gnu/tools/llvm-shlib'
/var/lib/jenkins/workspace/fork-OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/Makefile.rules:866: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/var/lib/jenkins/workspace/fork-OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/llvm-3.8.0/.x86_64-openelec-linux-gnu'
Makefile:12: recipe for target 'image' failed
make: *** [image] Error 2
Build step 'Execute shell' marked build as failure
