### ISSUE TITLE
Tvheadend 7.0.3  DVBSky S952  Signal Problem

### ISSUE THREAD

**Issue by ladigb** [OpenELEC/OpenELEC.tv#4875]
Hi
i just instaled new version on Tvheadend 7.0.3 and is problem with card DVBSky S952 
when i conect cable from satelite is fine for 10 sec then is stop working like on print scrn

![fisrt](https://cloud.githubusercontent.com/assets/15628243/14076855/5afd7d8e-f4dd-11e5-8b1c-4ab08d96a1b4.png)

![sec](https://cloud.githubusercontent.com/assets/15628243/14076866/8258f9da-f4dd-11e5-9afc-35c0a61427c2.png)

**Comment by sraue** [comment]
please report again here: https://github.com/OpenELEC/unofficial-addons/issues you can also provide any lofiles from the running system?
