### ISSUE TITLE
[OE 7 beta 1] Python expects subprocess in /home/stephan/...

### ISSUE THREAD

**Issue by jonashrem** [OpenELEC/OpenELEC.tv#4878]
I'm not a python coder so there might be there is a reason that modul is not included in OE but not quite sure if it should search there ;) (doesn't seem to anywhere else through) .

Device is RP2

Traceback: 

> Traceback (most recent call last):
>   File "./wol_pc.py", line 37, in <module>
>     subprocess.Popen(bashCommand)
>   File "/home/stephan/projects/openelec-7.0/build.OpenELEC-RPi2.arm-6.95.1/Python-2.7.11/.install_pkg/usr/lib/python2.7/subprocess.py", line 710, in __init__
>   File "/home/stephan/projects/openelec-7.0/build.OpenELEC-RPi2.arm-6.95.1/Python-2.7.11/.install_pkg/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
> OSError: [Errno 2] No such file or directory

**Comment by sraue** [comment]
can you provide this file for testing?

**Comment by jonashrem** [comment]
Which file? The wol_pc.py?

I solved it for myself be using os.system instead of subprocess.Popen but here is a minimal example to reproduce

> exec /usr/bin/python -x "$0" "$@"
> 
> 
> import subprocess
> 
> bashCommand = "echo 'on 0' | cec-client -s"
> subprocess.Popen(bashCommand)

**Comment by jonashrem** [comment]
oh, ups. Sorry to steal your time than ;)
