### ISSUE TITLE
openelec official addon repo 7 down!

### ISSUE THREAD

**Issue by ad015** [OpenELEC/OpenELEC.tv#4880]
OpenELEC-Generic.x86_64-8.0 
openelec official addon repo 7 not working .

**Comment by sraue** [comment]
actually there is still no repo for master builds which should be 8.0 later, will fix this the next hours, but it will need a new build

**Comment by ad015** [comment]
Thanks for you'r replay.
keep up the good work.

**Comment by walterheisenberg** [comment]
is the repo for OE8 already online?
