### ISSUE TITLE
Apply patch failed while building from master

### ISSUE THREAD

**Issue by Gizmo-Ger** [OpenELEC/OpenELEC.tv#4886]
I´m running into a problem building from master. A python patch couldn´t be applied.

APPLY PATCH (common)   /home/shs/OpenELEC.tv/packages/mediacenter/kodi/patches/kodi-100.01-enable-PYTHONOPTIMIZE-with-external-Python.patch
can't find file to patch at input line 14
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From 26d1905c371dd7e0e23bb589ccf29f2bfec5b8af Mon Sep 17 00:00:00 2001
|From: Stefan Saraev <stefan@saraev.ca>
|Date: Sat, 18 Apr 2015 15:12:49 +0300
|Subject: [PATCH 01/13] enable PYTHONOPTIMIZE with external Python
|
|---
| xbmc/interfaces/python/XBPython.cpp | 7 +++----
| 1 file changed, 3 insertions(+), 4 deletions(-)
|
|diff --git a/xbmc/interfaces/python/XBPython.cpp b/xbmc/interfaces/python/XBPython.cpp
|index af8d608..6213dbe 100644
|--- a/xbmc/interfaces/python/XBPython.cpp
|+++ b/xbmc/interfaces/python/XBPython.cpp
--------------------------
File to patch:

**Comment by krissetto** [comment]
This commit doesn't resolve the problem for all. I just checked, compiling from latest master, and all seems good, except I still get this error
