### ISSUE TITLE
Change TIME ZONE 

### ISSUE THREAD

**Issue by Luiscvi** [OpenELEC/OpenELEC.tv#4890]
i try a lot of times to change the hour of my system but nothing works,

nano /storage/.config/autostart.sh

#!/bin/sh
(sleep 30; \
/usr/sbin/ntpdate pool.ntp.org; \
)&

but no works

**Comment by sraue** [comment]
you have to change the timezone in kodi byself, no need to play with ntp, this will be done automatically if you have a working internet connection

**Comment by hadifarnoud** [comment]
I tried to change timezone in Kodi @sraue. I also set ntp servers `#1` and `#2`.  it still does not set the time correctly
