### ISSUE TITLE
Imx6 failed to build from master

### ISSUE THREAD

**Issue by islipfd19** [OpenELEC/OpenELEC.tv#4891]
[1;32mAPPLY PATCH[0m [1;37m(common)[0m   /var/lib/jenkins/workspace/OpenELEC.tv_imx6/packages/mediacenter/kodi/patches/kodi-100.01-enable-PYTHONOPTIMIZE-with-external-Python.patch
can't find file to patch at input line 14
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From 26d1905c371dd7e0e23bb589ccf29f2bfec5b8af Mon Sep 17 00:00:00 2001
|From: Stefan Saraev <stefan@saraev.ca>
|Date: Sat, 18 Apr 2015 15:12:49 +0300
|Subject: [PATCH 01/13] enable PYTHONOPTIMIZE with external Python
|
|---
| xbmc/interfaces/python/XBPython.cpp | 7 +++----
| 1 file changed, 3 insertions(+), 4 deletions(-)
|
|diff --git a/xbmc/interfaces/python/XBPython.cpp b/xbmc/interfaces/python/XBPython.cpp
|index af8d608..6213dbe 100644
|--- a/xbmc/interfaces/python/XBPython.cpp
|+++ b/xbmc/interfaces/python/XBPython.cpp
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored
Makefile:12: recipe for target 'image' failed
make: *** [image] Error 1
Build step 'Execute shell' marked build as failure

**Comment by brimur** [comment]
Dammit Stefan, not again!

**Comment by sraue** [comment]
would like to know whats different... here it works :-) @islipfd19 do you clean the source directory before you build?

**Comment by sraue** [comment]
also its not needed to report this always 3 times for every project

**Comment by islipfd19** [comment]
Did yesterday after the failure. I'll know later today whether it's
successful.

**Comment by islipfd19** [comment]
Still failing...
        ^
DVDVideoCodecIMX.cpp:561:8: error: 'CODEC_ID_KMVC' was not declared in this scope
   case CODEC_ID_KMVC:
        ^
DVDVideoCodecIMX.cpp:565:8: error: 'CODEC_ID_VP8' was not declared in this scope
   case CODEC_ID_VP8:
        ^
DVDVideoCodecIMX.cpp:569:8: error: 'CODEC_ID_MPEG4' was not declared in this scope
   case CODEC_ID_MPEG4:
        ^
/var/lib/jenkins/workspace/OpenELEC.tv_imx6/build.OpenELEC-imx6.arm-8.0-devel/kodi-72769f6/Makefile.include:97: recipe for target 'DVDVideoCodecIMX.o' failed
make[2]: *** [DVDVideoCodecIMX.o] Error 1
make[2]: Leaving directory '/var/lib/jenkins/workspace/OpenELEC.tv_imx6/build.OpenELEC-imx6.arm-8.0-devel/kodi-72769f6/xbmc/cores/VideoPlayer/DVDCodecs/Video'
Makefile:414: recipe for target 'xbmc/cores/VideoPlayer/DVDCodecs/Video/Video.a' failed
make[1]: *** [xbmc/cores/VideoPlayer/DVDCodecs/Video/Video.a] Error 2
make[1]: *** Waiting for unfinished jobs....
CPP     xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxCDDA.o
CPP     xbmc/guilib/GUITextLayout.o
CPP     xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.o
CPP     xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxClient.o
CPP     xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxUtils.o
CPP     xbmc/guilib/GUITexture.o
CPP     xbmc/guilib/GUIToggleButtonControl.o
CPP     xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxVobsub.o
CPP     xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxCC.o
CPP     xbmc/guilib/GUIVideoControl.o
CPP     xbmc/cores/VideoPlayer/DVDDemuxers/DVDFactoryDemuxer.o
CPP     xbmc/guilib/GUIVisualisationControl.o
CPP     xbmc/guilib/GUIWindow.o
CPP     xbmc/guilib/GUIWindowManager.o
AR      xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxers.a
make[2]: Leaving directory '/var/lib/jenkins/workspace/OpenELEC.tv_imx6/build.OpenELEC-imx6.arm-8.0-devel/kodi-72769f6/xbmc/cores/VideoPlayer/DVDDemuxers'
CPP     xbmc/guilib/GUIWrappingListContainer.o
CPP     xbmc/guilib/imagefactory.o
CPP     xbmc/guilib/IWindowManagerCallback.o
CPP     xbmc/guilib/LocalizeStrings.o
CPP     xbmc/guilib/Resolution.o
LocalizeStrings.cpp: In function 'bool LoadXML(const string&, std::map<unsigned int, LocStr>&, std::string&, uint32_t)':
LocalizeStrings.cpp:75:115: warning: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'std::map<unsigned int, LocStr>::size_type {aka unsigned int}' [-Wformat=]
   CLog::Log(LOGDEBUG, "LocalizeStrings: loaded %lu strings from file %s", strings.size() - originalSize, filename.c_str());
                                                                                                                   ^
CPP     xbmc/guilib/Shader.o
CPP     xbmc/guilib/StereoscopicsManager.o
CPP     xbmc/guilib/Texture.o
CPP     xbmc/guilib/TextureBundleXBT.o
CPP     xbmc/guilib/TextureBundle.o
CPP     xbmc/guilib/TextureManager.o
CPP     xbmc/guilib/VisibleEffect.o
CPP     xbmc/guilib/XBTF.o
CPP     xbmc/guilib/XBTFReader.o
CPP     xbmc/guilib/TextureGL.o
CPP     xbmc/guilib/TexturePi.o
CPP     xbmc/guilib/GUIFontTTFGL.o
CPP     xbmc/guilib/GUITextureGLES.o
CPP     xbmc/guilib/MatrixGLES.o
CPP     xbmc/guilib/GUIShader.o
AR      xbmc/guilib/guilib.a
make[2]: Leaving directory '/var/lib/jenkins/workspace/OpenELEC.tv_imx6/build.OpenELEC-imx6.arm-8.0-devel/kodi-72769f6/xbmc/guilib'
make[1]: Leaving directory '/var/lib/jenkins/workspace/OpenELEC.tv_imx6/build.OpenELEC-imx6.arm-8.0-devel/kodi-72769f6'
Makefile:12: recipe for target 'image' failed
make: *** [image] Error 2
Build step 'Execute shell' marked build as failure
CIFS: Current build result is [FAILURE], not going to run.

**Comment by fritsch** [comment]
Was already fixed upstream.

2016-04-01 21:04 GMT+02:00 islipfd19 <notifications@github.com>:

> Still failing...
> ^
> DVDVideoCodecIMX.cpp:561:8: error: 'CODEC_ID_KMVC' was not declared in
> this scope
> case CODEC_ID_KMVC:
> ^
> DVDVideoCodecIMX.cpp:565:8: error: 'CODEC_ID_VP8' was not declared in this
> scope
> case CODEC_ID_VP8:
> ^
> DVDVideoCodecIMX.cpp:569:8: error: 'CODEC_ID_MPEG4' was not declared in
> this scope
> case CODEC_ID_MPEG4:
> ^
> /var/lib/jenkins/workspace/OpenELEC.tv_imx6/build.OpenELEC-imx6.arm-8.0-devel/kodi-72769f6/Makefile.include:97:
> recipe for target 'DVDVideoCodecIMX.o' failed
> make[2]: *** [DVDVideoCodecIMX.o] Error 1
> make[2]: Leaving directory
> '/var/lib/jenkins/workspace/OpenELEC.tv_imx6/build.OpenELEC-imx6.arm-8.0-devel/kodi-72769f6/xbmc/cores/VideoPlayer/DVDCodecs/Video'
> Makefile:414: recipe for target
> 'xbmc/cores/VideoPlayer/DVDCodecs/Video/Video.a' failed
> make[1]: *** [xbmc/cores/VideoPlayer/DVDCodecs/Video/Video.a] Error 2
> make[1]: *** Waiting for unfinished jobs....
> CPP xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxCDDA.o
> CPP xbmc/guilib/GUITextLayout.o
> CPP xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.o
> CPP xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxClient.o
> CPP xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxUtils.o
> CPP xbmc/guilib/GUITexture.o
> CPP xbmc/guilib/GUIToggleButtonControl.o
> CPP xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxVobsub.o
> CPP xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxCC.o
> CPP xbmc/guilib/GUIVideoControl.o
> CPP xbmc/cores/VideoPlayer/DVDDemuxers/DVDFactoryDemuxer.o
> CPP xbmc/guilib/GUIVisualisationControl.o
> CPP xbmc/guilib/GUIWindow.o
> CPP xbmc/guilib/GUIWindowManager.o
> AR xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxers.a
> make[2]: Leaving directory
> '/var/lib/jenkins/workspace/OpenELEC.tv_imx6/build.OpenELEC-imx6.arm-8.0-devel/kodi-72769f6/xbmc/cores/VideoPlayer/DVDDemuxers'
> CPP xbmc/guilib/GUIWrappingListContainer.o
> CPP xbmc/guilib/imagefactory.o
> CPP xbmc/guilib/IWindowManagerCallback.o
> CPP xbmc/guilib/LocalizeStrings.o
> CPP xbmc/guilib/Resolution.o
> LocalizeStrings.cpp: In function 'bool LoadXML(const string&, std::map&,
> std::string&, uint32_t)':
> LocalizeStrings.cpp:75:115: warning: format '%lu' expects argument of type
> 'long unsigned int', but argument 3 has type 'std::map::size_type {aka
> unsigned int}' [-Wformat=]
> CLog::Log(LOGDEBUG, "LocalizeStrings: loaded %lu strings from file %s",
> strings.size() - originalSize, filename.c_str());
> ^
> CPP xbmc/guilib/Shader.o
> CPP xbmc/guilib/StereoscopicsManager.o
> CPP xbmc/guilib/Texture.o
> CPP xbmc/guilib/TextureBundleXBT.o
> CPP xbmc/guilib/TextureBundle.o
> CPP xbmc/guilib/TextureManager.o
> CPP xbmc/guilib/VisibleEffect.o
> CPP xbmc/guilib/XBTF.o
> CPP xbmc/guilib/XBTFReader.o
> CPP xbmc/guilib/TextureGL.o
> CPP xbmc/guilib/TexturePi.o
> CPP xbmc/guilib/GUIFontTTFGL.o
> CPP xbmc/guilib/GUITextureGLES.o
> CPP xbmc/guilib/MatrixGLES.o
> CPP xbmc/guilib/GUIShader.o
> AR xbmc/guilib/guilib.a
> make[2]: Leaving directory
> '/var/lib/jenkins/workspace/OpenELEC.tv_imx6/build.OpenELEC-imx6.arm-8.0-devel/kodi-72769f6/xbmc/guilib'
> make[1]: Leaving directory
> '/var/lib/jenkins/workspace/OpenELEC.tv_imx6/build.OpenELEC-imx6.arm-8.0-devel/kodi-72769f6'
> Makefile:12: recipe for target 'image' failed
> make: *** [image] Error 2
> Build step 'Execute shell' marked build as failure
> CIFS: Current build result is [FAILURE], not going to run.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenELEC/OpenELEC.tv/issues/4891#issuecomment-204526181>
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B
