### ISSUE TITLE
Generic fails to build from master

### ISSUE THREAD

**Issue by islipfd19** [OpenELEC/OpenELEC.tv#4894]
rc4/src/gallium/targets/dri-vdpau.dyn -march=x86-64 -m64 -Wl,--as-needed -fuse-ld=gold -fuse-linker-plugin -flto   -Wl,-soname -Wl,gallium_dri.so -o .libs/gallium_dri.so
lto1: internal compiler error: compressed stream: data error
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
lto-wrapper: fatal error: /var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/x86_64-openelec-linux-gnu-g++-5.3.0 returned 1 exit status
compilation terminated.
/var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/lib/gcc/x86_64-openelec-linux-gnu/5.3.0/../../../../x86_64-openelec-linux-gnu/bin/ld.gold: fatal error: lto-wrapper failed
collect2: error: ld returned 1 exit status
Makefile:914: recipe for target 'gallium_dri.la' failed
make[4]: *** [gallium_dri.la] Error 1
make[4]: Leaving directory '/var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/mesa-11.2.0-rc4/.x86_64-openelec-linux-gnu/src/gallium/targets/dri'
Makefile:586: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/mesa-11.2.0-rc4/.x86_64-openelec-linux-gnu/src/gallium'
Makefile:681: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/mesa-11.2.0-rc4/.x86_64-openelec-linux-gnu/src'
Makefile:626: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/lib/jenkins/workspace/OpenELEC.tv_Generic/build.OpenELEC-Generic.x86_64-8.0-devel/mesa-11.2.0-rc4/.x86_64-openelec-linux-gnu'
Makefile:12: recipe for target 'image' failed
make: *** [image] Error 2

**Comment by sraue** [comment]
i think something with your build is wrong, remove ccache and do a fullbuild again
