### ISSUE TITLE
busybox 1.24.2 isn't available for download

### ISSUE THREAD

**Issue by islipfd19** [OpenELEC/OpenELEC.tv#4898]
Attached is the latest version downloaded prior to the link being unavailable.
[busybox.zip](https://github.com/OpenELEC/OpenELEC.tv/files/200860/busybox.zip)

**Comment by gdachs** [comment]
I have no problems with downloading https://busybox.net/downloads/busybox-1.24.2.tar.bz2.

Gerald

**Comment by islipfd19** [comment]
busybox.net was down during the time I was building. I see it up now as well. Hoping this version can be added to the OE mirror.
