### ISSUE TITLE
/linux-amlogic-3.10-c8d5b2f.tar.xz: Scheme missing.-Master branch & 6.0 (dev)_wetekcore image

### ISSUE THREAD

**Issue by JustMev** [OpenELEC/OpenELEC.tv#4899]
when I click on teh link via teh website it works when i try get it it from terminal is does work and get this error below
 
GET      linux
/linux-amlogic-3.10-c8d5b2f.tar.xz: Scheme missing.
/linux/linux-amlogic-3.10-c8d5b2f.tar.xz: Scheme missing.
/linux-amlogic-3.10-c8d5b2f.tar.xz: Scheme missing.
/linux/linux-amlogic-3.10-c8d5b2f.tar.xz: Scheme missing.
/linux-amlogic-3.10-c8d5b2f.tar.xz: Scheme missing.
/linux/linux-amlogic-3.10-c8d5b2f.tar.xz: Scheme missing.
/linux-amlogic-3.10-c8d5b2f.tar.xz: Scheme missing.
/linux/linux-amlogic-3.10-c8d5b2f.tar.xz: Scheme missing.
/linux-amlogic-3.10-c8d5b2f.tar.xz: Scheme missing.
/linux/linux-amlogic-3.10-c8d5b2f.tar.xz: Scheme missing.
/linux-amlogic-3.10-c8d5b2f.tar.xz: Scheme missing.
/linux/linux-amlogic-3.10-c8d5b2f.tar.xz: Scheme missing.
/linux-amlogic-3.10-c8d5b2f.tar.xz: Scheme missing.
/linux/linux-amlogic-3.10-c8d5b2f.tar.xz: Scheme missing.
/linux-amlogic-3.10-c8d5b2f.tar.xz: Scheme missing.
/linux/linux-amlogic-3.10-c8d5b2f.tar.xz: Scheme missing.
/linux-amlogic-3.10-c8d5b2f.tar.xz: Scheme missing.
/linux/linux-amlogic-3.10-c8d5b2f.tar.xz: Scheme missing.
/linux-amlogic-3.10-c8d5b2f.tar.xz: Scheme missing.
/linux/linux-amlogic-3.10-c8d5b2f.tar.xz: Scheme missing.

Cant't get linux sources : /linux-amlogic-3.10-c8d5b2f.tar.xz
 Try later !!

**Comment by sraue** [comment]
what you changed? which branch? it seems you miss the $DISTRO_SRC variable somewhere

**Comment by JustMev** [comment]
solved the first issue now I get this on the master branch for WeTek_Core have checked my g++ and gcc version both on 5.3.0

o build/min-insn-modes.o build/gensupport.o build/print-rtl.o build/read-md.o build/errors.o ../build-x86_64-linux-gnu/libiberty/libiberty.a -lm
build/genautomata /root/OpenELEC.tv/build.OpenELEC-WeTek_Core.arm-8.0-devel/gcc-5.3.0/gcc/common.md /root/OpenELEC.tv/build.OpenELEC-WeTek_Core.arm-8.0-devel/gcc-5.3.0/gcc/config/arm/arm.md \
  insn-conditions.md > tmp-automata.c
/bin/sh: line 1: 16969 Killed                  build/genautomata /root/OpenELEC.tv/build.OpenELEC-WeTek_Core.arm-8.0-devel/gcc-5.3.0/gcc/common.md /root/OpenELEC.tv/build.OpenELEC-WeTek_Core.arm-8.0-devel/gcc-5.3.0/gcc/config/arm/arm.md insn-conditions.md > tmp-automata.c
Makefile:2137: recipe for target 's-automata' failed
make[3]: *** [s-automata] Error 137
make[3]: Leaving directory '/root/OpenELEC.tv/build.OpenELEC-WeTek_Core.arm-8.0-devel/gcc-5.3.0/.armv7a-openelec-linux-gnueabi-bootstrap/gcc'
Makefile:4096: recipe for target 'all-gcc' failed
make[2]: *** [all-gcc] Error 2
make[2]: Leaving directory '/root/OpenELEC.tv/build.OpenELEC-WeTek_Core.arm-8.0-devel/gcc-5.3.0/.armv7a-openelec-linux-gnueabi-bootstrap'
Makefile:852: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/OpenELEC.tv/build.OpenELEC-WeTek_Core.arm-8.0-devel/gcc-5.3.0/.armv7a-openelec-linux-gnueabi-bootstrap'
make: *** [image] Error 2

**Comment by sraue** [comment]
looks a bit like not much enough RAM avaible, other then that you should not build as root, otherwise you can loose your data/system if something goes wrong
