### ISSUE TITLE
Openelec 7.0 Beta 1: AMD new drivers do not support ATI Radeon HD 7450

### ISSUE THREAD

**Issue by sensei73** [OpenELEC/OpenELEC.tv#4901]
Hi, I tried to migrate to Openlec 7.0 beta 1 to have Kodi Jarvis, but my ATI Radeon HD 7450 doesn't seems to be supported anymore. At the startup I have "Failed to start Xorg"
In the changelog there is an mention about a new AMD driver, is this related? Thanks in advance.

**Comment by sraue** [comment]
can you paste /var/log/Xorg*.log

**Comment by sraue** [comment]
closing for now, please create a new issue report if this problem still exist
