### ISSUE TITLE
Nvidia ION RAID fails / No software raid available

### ISSUE THREAD

**Issue by yamlfd** [OpenELEC/OpenELEC.tv#4907]
I have installed my openelec on an 6 year old ION mainboard from Zotac. This worked flawless under windows and media center for the past years. Now I tried openelec and since tvheadend has implemented unicable support, what was for sure not available 6 years ago. I used openelec for about 3 months now from an USB stick only, and now I decided to install it to my disks in my HTPC.

Well this went fine, but it looks like the RAID is malfunctioning / in a failed state. I have searched around a bit and found some comments about "fakeRaid". I investigated what fakeRaid is and I guess the mainboard has such a fakeRaid, but I'm not 100% sure... however all the errors indicate that the root cause for the failing raid is OpenElec.

I have found at least one comment where someone said that OpenElec has intentionally removed fakeRaid support from the kernel. I'm SHOCKED if this is really true.

I have several TB of data in my HTPC including holiday photos and so on. Nothing of this data including my running tvheadend must crash. That is why I have two hard disks in my system. This make my critical HTPC server fail save to hard disk failures.

Can someone explain me why ION systems are supported, but ION raids are not? I do not get it. I understand that an RPI and the other minimal systems does not require raid drivers, but the standard linux installations really should support this for backend TV servers.

Can you add this support to OpenElec 7, please? I do not like to loose any of my critical data...

**Comment by stefansaraev** [comment]
your fakeraid was never supported, and I'd bet it will never be. go to bios and switch to ahci mode.

**Comment by yamlfd** [comment]
What does the ahci mode change here? How does it solve the issue? I checked the bios, but I'm not sure what it does.

Can you explain it a bit more, please?

Having no hdd fail save system is really no option to me.

**Comment by pyrodex** [comment]
AHCI mode would basically disable your fakeraid system (https://en.wikipedia.org/wiki/Advanced_Host_Controller_Interface). I honestly don't think OpenELEC is ideal for you since the principle is a SMALL enough operating system to run a media center and a raid system wouldn't be ideal in that principle. I think if these items are important to you maybe you can invest in a separate TRUE raid type device that is on your network you can access using your HTPC over supported network protocols like CIFS(SMB)/NFS that would house all your important data.

**Comment by yamlfd** [comment]
What type of htpc servers are dou running? Are you really running 3/4TB disk without a raid? I do not like to loose these masive amount of data just because of a hdd defect. There is no free slot as the only available is in use by a digital devices SAT controller card.

The principle to build a small and smart image is very good, but leaving out raid is totally crazy.

If you talk about weebox, rpi you can really leave raid outside, but not on normal linux versions. They can simply require such drivers.

Removing or leaving these drivers out just because of saving a few mb is simply a bad and wrong idea. These stuff do not hurt, but helps people who run real htpc servers.

Of my openelec server dies, all rpi's have no backend any longer. This takes down multiple TVs and make them all unusable by a single point of failure.

This can only wrong. I may better go back to windows than, but I do not like as I like openelec a lot. It is much faster than windows however it lacks bluray support.

**Comment by pyrodex** [comment]
My HTPCs are small systems. Most are RPI2s and one RPI3 but with 8GB or 16GB microSD cards. My only x86 HTPC is still running a 16GB SSD. All of my precious data is on a completely separate system which has a REAL raid card running raid 6 so I can personally sustain a 2 drive loss without losing my data. My raid system says on 24/7 while my HTPCs go up/down all the time based on who is watching them. My raid system also runs my MythTV setup so it is also my DVR for the entire house. 

I am sorry but you need to evaluate what you do and don't want from OpenELEC and I don't think what you want matches it's needs today nor will it ever. OpenELEC can be used as a TV headend server yes but it isn't mean to be a storage server as well.

**Comment by yamlfd** [comment]
That is very basic. 

No bluray support, additional hardware box required, no single device that does everything, no 2/4/8 channel DVB-S2, no unicable support, and would require additional powerlan adapters in my case. And I never heard of an inaudible nas systems yet. Some self build server can become inaudible, but I have also limited rooms and powerlan is really slow. With good luck I have 10mb/s and if some energy safe lights turned on only 5mb/s.

I'm not asking for any edge case configurations I think. Openelec supports ION, but not the raid build-in all these systems?!?

I would also be fine with a basic approach like "software raid". If this is installable - optionally as addon - it would be fine, but I guess this is not possible with kernel modules. Is there a way to install these drivers manually myself without recompiling openelec? Just asking...

Just because openelec does not support this today does not mean it can not supported in future. I think there is real need for raid support. Maybe in worst case in an additional build, but i think this would be real overkill.

**Comment by MilhouseVH** [comment]
>  I think there is real need for raid support.
In a lightweight media center? No, there's really not - that what NAS is for. The days of the high powered monster PC stuffed with disks sitting under the TV are numbered. And even if there were a need to support RAID, it wouldn't IMHO be worth supporting Nvidia RAID which is an obsolete/discontinued product that never worked very well in the first place. ION users are also becoming a vanishingly small percentage of the user base, and the number that want/need Nvidia RAID is, well it's probably just you, I'm afraid.

Your best option would be a self build, or as suggested re-evaluate your setup and needs - repurpose your ION box as a NAS using a purpose built NAS OS (FreeNAS? UnRAID?) and a small/quiet/low powered OpenELEC client, or continue using your existing hardware but use an alternative OS for Kodi that meets your RAID needs.

**Comment by yamlfd** [comment]
I'm sure it is not only me who is asking for raid support.

I have only opened the case. You should always expect 1000 more people who do not have a github account and do not like or cannot report their issues. This github queue is also a bit "hidden" and people are primarily pointed to the forum. Nothing that really helps if nobody has an answer nor an idea about technical stuff. I have also read the forum, like to other 1000 that have not opened a case here. :-)

A qnap/synology nas up to 8 drives as an example has no pcie slots as I know. I cannot run a 8 channel DVD-S2 card with Unicable support inside and there is also no CI/CI+ slot available. You may know - these are force-introduced more and more. These systems also have no real raid controllers just to be fair... this are also _software raids_, too. These NAS would also have _no bluray drive_ connected. How have you connected a bluray drive to your RPI3? I'm interrested... I also have no plans to run my own NAS system as the boxes from synology/qnap - how limiting they are - still best fit for these tasks. But they are really loud and nothing for a living room... I have one of these noise makers in my living room with only 2 disks and these need to leave very soon.

It also looks like 4K systems will require very heavy powered systems. That is why I do not replace my old mainboard today. I wait until Q4/2016 or later for the next Intel generation in the hope that the system may require less power. Today it looks like you need an i7 to get this running smoothly. Really not that funny. I'm also not aware of a single low power system that support HEVC / H.265 in hardware.

Sure - the number ob discontinued ION systems is not growing, but mini-ITX boards are still standard and they will only have one PCIe slot. I can only decide for DVD-S2 here as there is no other option available to view live TV. It also requires CI slots. Something I cannot solve with any Android box like a Wetek box. I like this product, but it does not fit and is far away from a complete solution.

HTPCs cannot only small streaming devices. I know Amazon Prime and Netfilix are trying to tell us this bullsh**, but it is not reality. Netflix is only available on Windows as I have read (i'm not using it) and trying to get Amazon Prime running on Kodi is really a mess. Additionally they do not provide real time broadcasts and the video content at Amazon is really questionable quality. Youtube also does not offer any replacement to LIVE TV.

Openelec is perfect to me, it only lacks software raid support. Nothing I need to re-evaluate and aside - there are no alternatives - I already evaluated many of them. That is why I'm here. Getting things finally done with the right system and not any other.

**Comment by fritsch** [comment]
> I have only opened the case. You should always expect 1000 more people who do not have a github account and do not like or cannot report their issues. This github queue is also a bit "hidden" and people are primarily pointed to the forum. Nothing that really helps if nobody has an answer nor an idea about technical stuff. I have also read the forum, like to other 1000 that have not opened a case here. :-)

We have this discussion every second year. Those users should use something else. A real linux distribution wich can support their usecase with ease. Raid is a pandora box ... which will ask for LVM next, dmcrypt afterwards and so on and so on. Just install Ubuntu server, use a systemd upstart for kodi and all will be fine.

**Comment by yamlfd** [comment]
I tried Kodibuntu last weekend. It is really a mess. Totally outdated out of the box, seems to have no raid support, 4 heavy bugs like sat card driver firmware package is broken / has invalid dependencies (ubuntu bug), diskfilter writes error on boot (ubuntu bug), mce remote not working with IMON (no idea yet why - in OpenElec it is just one addon - click and forget), Kodibuntu takes ages too boot (every Windows 7/8/10 is faster), splash screen has awful resolution and black bars, PVR addons / tvheadend requires command line (not a dealbreaker, but suxxx if you know openelec), shutdown/standby is not working (both openelec/ubuntu) and has it's source in the SAT card (firmware driver bug). Ubuntu really suxxx to me.

I never expierenced this under Debian yet, but also never tried installing a HTPC on Debian, too.

How many MByte does it costs to integrate Software Raid/LVM/Crypting and how much does this delay boot time or increase memory usage? I would still prefer to make this optional featues, but they should exists. I'm not asking for all, just Software Raid and have no plans to ask for LVM or Crypting as it slows down a box really hard.

If this raid issues bubble up every 1-2 years you should _listen_ to the sux _customers_ bringing this to your attention, sat back, think about it and than just integrate it - as it looks like a lot of people need it and it makes sense in a HTPC. A software raid does not hurt much. Crypting my local tv box as it could get stolen at home - unrealistic. Do not save sooo much porn on it and you do not need to crypt it *G*. I see the reasons for doing this and as smaller these boxes become the easier you can steal or loose them (usb stick size), but that is totally different to a **HDD failure** that will happen 100% for sure and cause **data loss**.

**Comment by gdachs** [comment]
To answer your question what htpc server I use. It is a HP Proliant Microserver Gen8 with a RAID 5, but of course I don't use OpenELEC on this server. It uses Ubuntu server. I have no need for a RAID on my various OpenELEC clients. They even don't have a HDD at all, they use a small SD Card big enough to hold the OS.
If you are right that 1000 users can't use OpenELEC because of the missing RAID support, who cares? What benefit will another 1000 users gain for the project?

**Comment by yamlfd** [comment]
As it bubbles up so often this are more users. :-)

**Comment by gdachs** [comment]
Makes no difference.

**Comment by yamlfd** [comment]
That sounds like you do not care about the customers/community of OpenElec. A questionable point of view.

**Comment by fritsch** [comment]
It rather sounds like you do not care about the devs which need to support all the possible mess users will do to their mass of data ...

**Comment by sraue** [comment]
thats not true... we care, but adding raidsupport is not a trivial task and very complex (esp in automated live builds like OpenELEC is), and we DONT want to destroy the data of many 100k's users only to have such feature. We have to add automated checks if the user have raid, need raid or not... we must decide this by factors we have on the system already...
All our stuff behind Kodi is done simple as possible, and we (OpenELEC) think 10 times before we implement something and what can happen if something fails... of its to risky for Users data then we dont add...

**Comment by MilhouseVH** [comment]
> As it bubbles up so often this are more users. :-)

It only requires one person every two years for it to "bubble up". 6 years, one user every 1-2 years. 6 users, tops.

While it's true that It's an issue that is raised from time to time, it is by individuals - not 1000s. And not very often. If it were a common issue, we'd see more of it on the forums, but we don't. The vast majority of users understand the intent behind OpenELEC, for it to be a lightweight OS to run Kodi - that's why they use it, they don't then try and make it into something it is not intended to be.

> It also looks like 4K systems will require very heavy powered systems. That is why I do not replace my old mainboard today. I wait until Q4/2016 or later for the next Intel generation in the hope that the system may require less power. Today it looks like you need an i7 to get this running smoothly. 

This is an aside, but many ARM-based systems now support 4K playback (including HEVC). For example, ODROID. Intel i7 is definitely not a requirement.

>How many MByte does it costs to integrate Software Raid/LVM/Crypting and how much does this delay boot time or increase memory usage?

That's only part of the reason to not add it, the other is the ongoing support overhead for a feature that hardly anyone (a handful of users out of 500,000) requires or uses. Once it's added, users will expect support and nobody other than the user with the problem will be using the feature - certainly none of the developers will be using it - which makes support considerably more difficult. It's a lose/lose situation.

And once non-core/niche features are being added, where do you stop? You have to draw the line somewhere.

> These NAS would also have no bluray drive connected. How have you connected a bluray drive to your RPI3? I'm interrested...

Since you asked, I rip BluRays to MKV that are stored on my NAS (HP N36L with FreeNAS and ZFS RAID). I've got a hardware RAID controller in the HP N36L (LSI 9211-8i) but it's run in IT mode as hardware RAID thankfully died a death in the late 2000's and is just a mugs game now. My primary OpenELEC client isn't even an RPi3, it's a Revo3700 (ION2) which has no BluRay drive.

**Comment by stefansaraev** [comment]
> you should listen to the sux customers bringing this to your attention

no. not really. and devs who work on the distro here, they dont have *customers*

if you have a hardware controller, that does not require shitload of firmware and proprietary userspace tools to operate, let us know, I am sure it can be added. but your fake raid - no. not gonna happen.

**Comment by yamlfd** [comment]
Everyone installing openelec is a openelec customer. Also if he is not paying money.

What raid controllers may fit into mini pcie and have no shitload? So I can buy one and remove the wlan card.

**Comment by yamlfd** [comment]
Software raid adds shitload or not?

**Comment by stefansaraev** [comment]
fake/software raid adds support burden to a distribution, that was never supposed to be NAS.

**Comment by yamlfd** [comment]
@Milhouse: 

> This is an aside, but many ARM-based systems now support 4K playback (including HEVC). For example, ODROID. Intel i7 is definitely not a requirement

In theory this sounds good, practically I do not think this has HDMI 2.0, isn't it? HDMI 1.4 is no real 4k - this is just a bad compromise. This is like selling _HD Ready_ TV's if _Full HD_ is available and what I want, but the vendors are telling me my TV has _HD_ and they know they are selling me sh**. I do not like being taken for a fool. Is there any Android device available that support real 4k with 50/60 frames? :-)

@All:

I would be more than thankful if someone has a hint about a mini pcie card that is supported in OpenELEC or could be supported... I cannot find anything useful.

**Comment by islipfd19** [comment]
Enough of this noise please! The Devs have provided you with an answer. If you need support for OpenELEC, post a thread in the specific section of the OE forum.
