### ISSUE TITLE
System not powered off after shutdown

### ISSUE THREAD

**Issue by alexhass** [OpenELEC/OpenELEC.tv#4908]
My ION board does not power off. Openelec shots down, but it is not switched off. What's wron with openelec. I think I have seen this on 7.x and latest 6.03.

How can I help you fixing this issue? What logs are required and where can I find them?

**Comment by sebjacob** [comment]
I see something similar, glad someone opened an 'issue' here.

For the record, not sure it responsible, but I run openelec off an nfs pxe server.

**Comment by yamlfd** [comment]
I have read a lot of stuff in past days and found that there is a known issue with Digital Devices Cine S2 - ngene driver. This should prevent the power-off.

This known defect requires a small bugfix to the ngene driver. I will post the link later, but I have not tried the bugfix yet on kodiubuntu where the issue also exists.

**Comment by yamlfd** [comment]
Here is the link. http://wiki.easy-vdr.de/index.php?title=Digital_Devices_CineS2 and https://wiki.ubuntuusers.de/DVB-Karten/Digital_Devices_Cine_S2/. I hope you can read German.

**Comment by islipfd19** [comment]
I recommend you clone the OE project, commit your changes/fixes in you tree with what you found and test. Post a link on the OE forum of the image you build for others users can test your fixes. Once satisfied, submit a pull request for your changes.

I don't believe a Dev will actively look into this without having specific hardware to test on... But I may be mistaken...

**Comment by yamlfd** [comment]
I'm not a OE developer and I never build a linux distribution. Sorry, I cannot do this myself I think. As it is a known issue with this driver and documented in other VDR projects it could be safe to give it a try.

Otherwise I'm fine if you tell me how to increase logging and provide your the logs that will show you what is hanging on my shutdown. If this log will also point to the driver It can be committed and we can try again with a new build and I can provide the required feedback.

**Comment by sebjacob** [comment]
@yamlfd Do you have a Digital Devices Cine S2 device installed on your system?

I know I don't, but have 'shutdown issues'

**Comment by yamlfd** [comment]
Yes. Cine S2, v5.4

**Comment by sebjacob** [comment]
my issue is solved in 6.95.3! even suspend over oxe/nfs seems to work.

**Comment by yamlfd** [comment]
Shutdown problem is not solved for me in Beta 3.

**Comment by sebjacob** [comment]
me either, got excited too fast, after a few days, did get the old behavior back... :(

**Comment by alexhass** [comment]
This issue is still in https://libreelec.tv/
