### ISSUE TITLE
OpenELEC on KVM on CentOS7

### ISSUE THREAD

**Issue by smacz42** [OpenELEC/OpenELEC.tv#4910]
Hello all, hope all is well.

I've been trying to install OpenELEC on CentOS7 as a VM on KVM unsuccessfully. I am able to spin up various other distros (Debian, pfSense) easily enough. However, I keep getting a `No bootable device` error when I spin up the OpenELEC VM.

I downloaded the OpenELEC beta 2 `.img` file from the downloads page. I've read that KVM support was integrated(?) [here](https://github.com/OpenELEC/OpenELEC.tv/pull/4564) but am unable to find out if that is in the beta 2 release. Any help?

**Comment by piotrasd** [comment]
mount OE.img as primary disk (and setup boot from him) add second disk where you will install 
and use SATA emulation not VIRTIO driver (virto blk driver is as module and i cannot start with him OE, when in builtin then is no problem with boot with Virtio )

i tried create file in configfiles/modules-load.d -  virtio-blk.conf and put line virtio-blk, virtio but nothing help
