### ISSUE TITLE
openelec-7.0: cubox-i4: failure to build vdr-addon

### ISSUE THREAD

**Issue by susisstrolch** [OpenELEC/OpenELEC.tv#4912]
Trying to build the vdr-addon from openelec-7.0 branch:

Step 1: sync git and build oe-7.0
```
strolch@strolch:~/Development/OpenELEC> git pull
strolch@strolch:~/Development/OpenELEC> git submodule sync
strolch@strolch:~/Development/OpenELEC> git submodule update --init
strolch@strolch:~/Development/OpenELEC> export ARCH=arm
strolch@strolch:~/Development/OpenELEC> export PROJECT=imx6
strolch@strolch:~/Development/OpenELEC> make clean
strolch@strolch:~/Development/OpenELEC> make system
```
OE is build as expected.
Step 2: (try to) build vdr-addon:
```
strolch@strolch:~/Development/OpenELEC> scripts/create_addon vdr-addon
```
(excerpt from) Result [vdr_addon-openelec-7.0...origin:openelec-7.0-imx6-c86a0e4.4.txt](https://github.com/OpenELEC/OpenELEC.tv/files/211706/vdr_addon-openelec-7.0.origin.openelec-7.0-imx6-c86a0e4.4.txt)
:
```
  BUILD    vdr-plugin-vnsiserver (target)
config/functions: line 111: [: too many arguments
Package vdr was not found in the pkg-config search path.
...

 
```

**Comment by vpeter4** [comment]
Check if you have more than one tvheadend folder in packages:
`find packages -name tvheadend`

**Comment by susisstrolch** [comment]
Only one occurance:
```
strolch@strolch:~/Development/OpenELEC> find packages -name vdr-plugin-vnsiserver
packages/addons/depends/multimedia/vdr-plugin-vnsiserver
strolch@strolch:~/Development/OpenELEC> 
```
Is "packages/addons/depends/multimedia/" the proper path for vdr?

**Comment by sraue** [comment]
technically the path dont matter, its only there to sort the packages

**Comment by vpeter4** [comment]
@susisstrolch, I think the fastest way to fix this issue would be to put some echo's to log file.
