### ISSUE TITLE
compiling error Generic.x86_64-8.0-devel

### ISSUE THREAD

**Issue by ad015** [OpenELEC/OpenELEC.tv#4915]
Generic.x86_64-8.0-devel

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Makefile:9: recipe for target 'release' failed
make: *** [release] Error 2

**Comment by sraue** [comment]
which package? seems a package failed to townload, but your pasted info is not enough to investigate why

**Comment by ad015** [comment]
how do i know which package is this ?

**Comment by vpeter4** [comment]
You see the name of the package few lines before. Next time don't post only few last lines or error.
And I build master over night without a problem.

**Comment by ad015** [comment]
i hope this can help

`make[3]: Entering directory '/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/xorg-server-1.18.3/.x86_64-openelec-linux-gnu/test'
make[4]: Entering directory '/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/xorg-server-1.18.3/.x86_64-openelec-linux-gnu/test'
make[5]: Entering directory '/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/xorg-server-1.18.3/.x86_64-openelec-linux-gnu/test'
make[5]: Nothing to be done for 'install-exec-am'.
make[5]: Nothing to be done for 'install-data-am'.
make[5]: Leaving directory '/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/xorg-server-1.18.3/.x86_64-openelec-linux-gnu/test'
make[4]: Leaving directory '/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/xorg-server-1.18.3/.x86_64-openelec-linux-gnu/test'
make[3]: Leaving directory '/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/xorg-server-1.18.3/.x86_64-openelec-linux-gnu/test'
make[2]: Leaving directory '/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/xorg-server-1.18.3/.x86_64-openelec-linux-gnu/test'
make[2]: Entering directory '/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/xorg-server-1.18.3/.x86_64-openelec-linux-gnu'
make[3]: Entering directory '/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/xorg-server-1.18.3/.x86_64-openelec-linux-gnu'
make[3]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/xorg-server-1.18.3/.install_pkg/usr/share/aclocal'
 /bin/mkdir -p '/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/xorg-server-1.18.3/.install_pkg/usr/lib/pkgconfig'
 /usr/bin/install -c -m 644 /home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/xorg-server-1.18.3/xorg-server.m4 '/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/xorg-server-1.18.3/.install_pkg/usr/share/aclocal'
 /usr/bin/install -c -m 644 xorg-server.pc '/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/xorg-server-1.18.3/.install_pkg/usr/lib/pkgconfig'
make[3]: Leaving directory '/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/xorg-server-1.18.3/.x86_64-openelec-linux-gnu'
make[2]: Leaving directory '/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/xorg-server-1.18.3/.x86_64-openelec-linux-gnu'
make[1]: Leaving directory '/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/xorg-server-1.18.3/.x86_64-openelec-linux-gnu'
      INSTALL    xorg-server (target)
          INSTALL    font-util (target)
          INSTALL    fontsproto (target)
          INSTALL    randrproto (target)
          INSTALL    recordproto (target)
          INSTALL    renderproto (target)
          INSTALL    dri2proto (target)
          INSTALL    dri3proto (target)
          INSTALL    fixesproto (target)
          INSTALL    damageproto (target)
          INSTALL    videoproto (target)
          INSTALL    inputproto (target)
          INSTALL    xf86dgaproto (target)
          INSTALL    xf86vidmodeproto (target)
          INSTALL    xf86driproto (target)
          INSTALL    xf86miscproto (target)
          INSTALL    presentproto (target)
          INSTALL    libpciaccess (target)
          INSTALL    libX11 (target)
              INSTALL    xproto (host)
              INSTALL    xproto (target)
              INSTALL    xextproto (target)
              INSTALL    xcmiscproto (target)
              INSTALL    bigreqsproto (target)
              INSTALL    kbproto (target)
              INSTALL    xtrans (target)
              INSTALL    libXau (target)
              INSTALL    libxcb (target)
                  INSTALL    xcb-proto (target)
                  INSTALL    libpthread-stubs (target)
          INSTALL    libXfont (target)
              INSTALL    fontcacheproto (target)
              INSTALL    freetype (target)
                  INSTALL    libpng (target)
              INSTALL    libfontenc (target)
          INSTALL    libXinerama (target)
              INSTALL    xineramaproto (target)
              INSTALL    libXext (target)
          INSTALL    libxshmfence (target)
          INSTALL    libxkbfile (target)
          INSTALL    libdrm (target)
          INSTALL    pixman (target)
          INSTALL    xorg-launch-helper (target)
          INSTALL    glproto (target)
          INSTALL    mesa (target)
              INSTALL    libXdamage (target)
                  INSTALL    libXfixes (target)
              INSTALL    libXxf86vm (target)
              INSTALL    elfutils (target)
              INSTALL    llvm (target)
                  INSTALL    llvm (host)
              INSTALL    libvdpau (target)
          INSTALL    libepoxy (target)
          INSTALL    glu (target)
      INSTALL    encodings (target)
          INSTALL    font-util (host)
      INSTALL    font-xfree86-type1 (target)
      INSTALL    font-bitstream-type1 (target)
      INSTALL    font-misc-misc (target)
          INSTALL    font-cursor-misc (target)
      INSTALL    xkeyboard-config (target)
          INSTALL    xkbcomp (target)
      INSTALL    xrandr (target)
          INSTALL    libXrandr (target)
              INSTALL    libXrender (target)
      INSTALL    setxkbmap (target)
      INSTALL    fluxbox (target)
      INSTALL    xf86-input-evdev (target)
          INSTALL    libevdev (target)
          INSTALL    mtdev (target)
      INSTALL    xf86-video-nvidia (target)
      INSTALL    xf86-video-nvidia-legacy (target)
  UNPACK   xmlstarlet

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Makefile:12: recipe for target 'image' failed
make: *** [image] Error 2
`

**Comment by vpeter4** [comment]
`rm -f sources/xmlstarlet/xmlstarlet*` and run make again.

**Comment by ad015** [comment]
ok i will try now.
Thanks vpeter4

**Comment by ad015** [comment]
same problem 


Connecting to sourceforge.net (sourceforge.net)|216.34.181.60|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sourceforge.net/publish/ [following]
--2016-04-12 14:13:13--  https://sourceforge.net/publish/
Connecting to sourceforge.net (sourceforge.net)|216.34.181.60|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17271 (17K) [text/html]
Saving to: 'sources/xmlstarlet/xmlstarlet-1.6.1.tar.gz'

xmlstarlet-1.6.1.tar.gz                     100%[=============================================================================================>]  16.87K  69.2KB/s   in 0.2s   

2016-04-12 14:13:15 (69.2 KB/s) - 'sources/xmlstarlet/xmlstarlet-1.6.1.tar.gz' saved [17271/17271]

  UNPACK   xmlstarlet

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Makefile:12: recipe for target 'image' failed
make: *** [image] Error 2

**Comment by vpeter4** [comment]
[File](https://github.com/OpenELEC/OpenELEC.tv/blob/6b2383d7b9498f518495937b0c12c65c6837ecd2/packages/textproc/xmlstarlet/package.mk#L25) was removed from server
`PKG_URL="http://netcologne.dl.sourceforge.net/project/xmlstar/$PKG_NAME/$PKG_VERSION/$PKG_NAME-$PKG_VERSION.tar.gz"`

Replace with 
`PKG_URL="https://sourceforge.net/projects/xmlstar/files/$PKG_NAME/$PKG_VERSION/$PKG_NAME-$PKG_VERSION.tar.gz"`

Remove xmlstarlet source and run make again.

**Comment by ad015** [comment]
its working now
thanks vpeter4
