### ISSUE TITLE
OpenELEC master: can't build vdr-addon

### ISSUE THREAD

**Issue by susisstrolch** [OpenELEC/OpenELEC.tv#4917]
scripts/create_addon vdr-addon refuses to build the add-on:
*** ERROR: service.multimedia.vdr-addon: ADDON_VERSION '8.0' not supported ***

**Comment by sraue** [comment]
fixed in https://github.com/OpenELEC/OpenELEC.tv/commit/a1a39418920ed5d3588b78ee430ecee2fd66cbe9
