### ISSUE TITLE
Support Maxwell desktop GPUs

### ISSUE THREAD

**Issue by gouchi** [OpenELEC/OpenELEC.tv#4918]
When kernel 4.6 is released, to support Maxwell desktop GPUs, you will need redistributable signed firmwares. Please add [them](http://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git/commit/?id=c4f6a36d694bc4dbaeb6c9edae4889b4af2659ce).

**Comment by lrusak** [comment]
@gouchi OpenELEC uses the nvidia proprietary driver, it doesn't need the signed firmware images.
