### ISSUE TITLE
Kodi 17: no PVR addons

### ISSUE THREAD

**Issue by rinaldus** [OpenELEC/OpenELEC.tv#4923]
I compiled and installed current master branch version of OpenElec (23ad42c5aa2127ed2357ce0f65b688636930a8ac) to my Raspberry Pi 2, but didn't find any PVR addons. Are PVR addons exist for alpha version Kodi 17 or they just don't work?

**Comment by sraue** [comment]
they dont exist yet

**Comment by bingbong1** [comment]
i have just flashed openelec onto revo nettop , the kodi version is 16.1 and it has no pvr clients listed either ?? searched everywhere and cant find a working link to add from , any advice would be appreciated .
