### ISSUE TITLE
Kodi crashes and restarts in some situations

### ISSUE THREAD

**Issue by yamlfd** [OpenELEC/OpenELEC.tv#4926]
Still trying to find the logic, but it looks like kodi (crashes and) restarts in some strange situations.

1. Reboot OE 7 BETA 2.
2. Connect kodi remote (from iOS)
3. Select live tv (tvheadend server and client is installed on OE)
4. select "tv channels" group
5. *bam* kodi restarts (not  OE - just kodi)

After the restart i can select tv channels via the kodi remote without any issues.

If I can share some logs with you, let me know what you need and where I can find the log, please.

**Comment by fritsch** [comment]
Man, that's your 10th bugreport and you still don't provide what: https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md

It's not about a matter of "if you want to share a log" it's about you _have_ to share your log. Without those the bugreport is invalid, it is closed and you are sent to the forum. 

Please stick to the rules.

**Comment by yamlfd** [comment]
Should be fixed in 16.1 RC2 or later
