### ISSUE TITLE
Two buttons not working on OSMC remote

### ISSUE THREAD

**Issue by Menturan** [OpenELEC/OpenELEC.tv#4927]
On the official [OSMC remote](https://osmc.tv/store/product/osmc-remote-control/) the menu- and info-buttons doesn't get recognized by kodi. 
Context menu 
`15:12:02 545.700378 T:1967575040   DEBUG: CLinuxInputDevice::KeyEvent: TranslateKey returned XBMCK_UNKNOWN from code(438)`
Info
`15:12:01 544.383118 T:1967575040   DEBUG: CLinuxInputDevice::KeyEvent: TranslateKey returned XBMCK_UNKNOWN from code(358)`

**Device info**
```
MEDIAPI:~ # cat /proc/bus/input/devices 
I: Bus=0003 Vendor=2252 Product=1037 Version=0110
N: Name="HBGIC Technology Co., Ltd. USB Keyboard Mouse"
P: Phys=usb-3f980000.usb-1.5/input0
S: Sysfs=/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.5/1-1.5:1.0/0003:2252:1037.0004/input/input2
U: Uniq=
H: Handlers=sysrq kbd event2 
B: PROP=0
B: EV=120013
B: KEY=10000 7 ff9f207a c14057ff febeffdf ffefffff ffffffff fffffffe
B: MSC=10
B: LED=7

I: Bus=0003 Vendor=2252 Product=1037 Version=0110
N: Name="HBGIC Technology Co., Ltd. USB Keyboard Mouse"
P: Phys=usb-3f980000.usb-1.5/input1
S: Sysfs=/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.5/1-1.5:1.1/0003:2252:1037.0005/input/input3
U: Uniq=
H: Handlers=kbd mouse1 event3 
B: PROP=0
B: EV=1f
B: KEY=3f 3007f 0 0 0 0 4c3ffff 17aff32d bf544446 0 0 70001 130f93 8b17c000 677bfa d941dfed 9ed680 4400 0 10000002
B: REL=143
B: ABS=1 0
B: MSC=10
```
**evtest**
[evtest.txt](https://github.com/OpenELEC/OpenELEC.tv/files/228622/evtest.txt)

I'm using OpenElec v6.0.3. Tried with v7.0 beta 2 but same result.

In OSMCs repo there is a lirc config file. Don't know if we could reuse to get the buttons working.
https://github.com/osmc/osmc/blob/master/package/remote-osmc/files/etc/lirc/osmc-remote-lircd.conf

**Comment by sraue** [comment]
there is no support in OE6.0.3 and 7.0b2 for this osmc remote

**Comment by samnazarko** [comment]
It's supported on the latest version of OE/LE, although they are betas.

**Comment by Menturan** [comment]
I tested with 7.0b3. Info-button worked right away and contex-menu-button had to be configured with 'Kemap Editor'. I hope this get into the next stable version! :)
