### ISSUE TITLE
OpenSSH Unable to retrieve from FTP - OpenSSH-7.2p2

### ISSUE THREAD

**Issue by islipfd19** [OpenELEC/OpenELEC.tv#4929]
Please upload latest openssh-7.2p2 to OpenELEC mirror as the build fails to download the version using ftp.

[openssh-7.2p2.tar.gz](https://github.com/OpenELEC/OpenELEC.tv/files/230880/openssh-7.2p2.tar.gz)

**Comment by sraue** [comment]
done
