### ISSUE TITLE
Generic.x86_64-8.0-devel Compiling failed

### ISSUE THREAD

**Issue by ad015** [OpenELEC/OpenELEC.tv#4931]
Hi
Generic.x86_64-8.0-devel last changes Apr 22, 2016 
Compiling failed.

/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/host-gcc -Wl,-rpath,/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/lib -L/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/lib   floppyd.o llong.o -o floppyd   -lXau -lX11 
make[1]: Leaving directory '/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/mtools-4.0.18/.x86_64-linux-gnu'
make[1]: Entering directory '/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/mtools-4.0.18/.x86_64-linux-gnu'
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/mtools-4.0.18/mkinstalldirs /home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/mtools-4.0.18/mkinstalldirs /home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/mtools-4.0.18/mkinstalldirs /home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin
/usr/bin/install -c floppyd /home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/floppyd
/usr/bin/install -c mtools /home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mtools
/usr/bin/install -c floppyd_installtest /home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/floppyd_installtest
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/mtools-4.0.18/mkinstalldirs /home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/mtools-4.0.18/mkinstalldirs /home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/info
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/floppyd.1
/usr/bin/install -c mkmanifest /home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mkmanifest
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/floppyd_installtest.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mattrib
if test -f mtools.info; then \
  for i in mtools.info*; do \
    /usr/bin/install -c -m 644 $i /home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/info/$i; \
  done; \
else \
  for i in /home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/mtools-4.0.18/mtools.info*; do \
    /usr/bin/install -c -m 644 $i /home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/info/`echo $i | sed 's|^/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/mtools-4.0.18/||'`; \
  done; \
fi; \
if [ -n "/usr/bin/install-info" ] ; then \
	/usr/bin/install-info --info-dir=/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/info /home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/info/mtools.info; \
fi
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mattrib.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mcat
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mbadblocks.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mcat.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mcd
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mcd.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mclasserase.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mclasserase
install-info: /home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mcheck
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/info/dir: empty file
Makefile:222: recipe for target 'install-info' failed
make[1]: *** [install-info] Error 1
make[1]: *** Waiting for unfinished jobs....
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mcopy.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mcopy
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mxtar
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mdel.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mdel
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/uz
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mdeltree.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mdeltree
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/tgz
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mdir.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mcomp
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mdir
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mdu.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/amuFormat.sh
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mdu
rm -f /home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/lz
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mformat.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mformat
cd /home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin && ln -s uz lz
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/minfo.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/minfo
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mkmanifest.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mlabel.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mlabel
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mmd.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mmd
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mmount.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mmount
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mmove.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mmove
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mpartition.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mpartition
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mrd.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mrd
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mren.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mren
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mshortname.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mtype
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mshowfat.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mtoolstest
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mtoolstest.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mshortname
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mtools.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mtype.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mshowfat
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man1/mzip.1
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mbadblocks
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/bin/mzip
mkdir /home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man5
/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/toolchain/share/man/man5/mtools.5
make[1]: Leaving directory '/home/ad/OpenELEC.tv/build.OpenELEC-Generic.x86_64-8.0-devel/mtools-4.0.18/.x86_64-linux-gnu'
Makefile:12: recipe for target 'image' failed
make: *** [image] Error 2
ad@Dreamer:~/OpenELEC.tv$

**Comment by sraue** [comment]
you have to paste more of the output, the real error is not shown

**Comment by sraue** [comment]
please test latest master again

**Comment by sraue** [comment]
closing, please open a new report if this issue still exist
