### ISSUE TITLE
Please enable hardening options

### ISSUE THREAD

**Issue by jvoisin** [OpenELEC/OpenELEC.tv#4936]
The [config]( https://github.com/OpenELEC/OpenELEC.tv/tree/master/config ) folder contains a lot of compilation-related options, like [optimizations]( https://github.com/OpenELEC/OpenELEC.tv/blob/master/config/optimize ), but there is nothing related to hardening. It would be great to take a look at [some]( https://wiki.debian.org/Hardening#Notes_on_Memory_Corruption_Mitigation_Methods ) [documentation]( https://www.owasp.org/index.php/C-Based_Toolchain_Hardening#GCC.2FBinutils ), and to create a `hardening` configuration file.

**Comment by sraue** [comment]
-D_FORTIFY_SOURCE=2 and stack protector support added in master, others should be selcted step by step and added if usefull. please open new reports if more are needed/usefull in your case.
