### ISSUE TITLE
 Could not find SHA of rpi git: OpenELEC.tv/packages/linux/package.mk 

### ISSUE THREAD

**Issue by hoblins** [OpenELEC/OpenELEC.tv#4942]
Hello,
I couldn't find the SHA 7d73e63. Last one is 6006082.
Presumably this led to a compile error.

[https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/linux/package.mk#L44](https://github.com/OpenELEC/OpenELEC.tv/blob/master/packages/linux/package.mk#L44)

**Comment by ghent360** [comment]
+1 got the same error. RPi does not build.
