### ISSUE TITLE
SSL certificates fail

### ISSUE THREAD

**Issue by ffsi** [OpenELEC/OpenELEC.tv#4951]
Rclone gives x509: failed to load system roots and no roots provided error

Failed to exchange auth code for token: Post https://accounts.google.com/o/oauth2/token: x509: failed to load system roots and no roots provided

Maybe some useful info from http://rclone.org/faq/

> This means that rclone can’t file the SSL root certificates. Likely you are running rclone on a NAS with a cut-down Linux OS.
> 
> Rclone (via the Go runtime) tries to load the root certificates from these places on Linux.
> 
> "/etc/ssl/certs/ca-certificates.crt", // Debian/Ubuntu/Gentoo etc.
> "/etc/pki/tls/certs/ca-bundle.crt",   // Fedora/RHEL
> "/etc/ssl/ca-bundle.pem",             // OpenSUSE
> "/etc/pki/tls/cacert.pem",            // OpenELEC
> 
> So doing something like this should fix the problem. It also sets the time which is important for SSL to work properly.
> 
> mkdir -p /etc/ssl/certs/
> curl -o /etc/ssl/certs/ca-certificates.crt https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt
> ntpclient -s -h pool.ntp.org
> 
> Note that you may need to add the --insecure option to the curl command line if it doesn’t work without.
> 
> curl --insecure -o /etc/ssl/certs/ca-certificates.crt https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt
> 
>

**Comment by tcamargo** [comment]
It seems a dupe of #4941. I have the same problem with docker on 6.95.3.
```
# docker pull tcamargo/python
Using default tag: latest
Pulling repository docker.io/tcamargo/python
Error while pulling image: Get https://index.docker.io/v1/repositories/tcamargo/python/images: x509: failed to load system roots and no roots provided
```

**Comment by ffsi** [comment]
Builded manualy, and confirm, its working!

**Comment by tcamargo** [comment]
@ffsi what have you built? OE?

**Comment by ffsi** [comment]
@tcamargo Yes
