### ISSUE TITLE
Proposal: Additional kernel modules - on demand download utility

### ISSUE THREAD

**Issue by gitchomik** [OpenELEC/OpenELEC.tv#4952]
Hi, 

Please provide utility, addon or something that allow to download
suitable Openelec kernel modules (one or all of them).
I know that OpenELEC can loading modules and also 7.0 
support docker addon, so for example I want to use mdadm utility
to manage software RAID devices, but it requires some kernel modules.
I think that docker addon can produce a lot of request PR for additional kernel modules.

Or maybe Unofficial addons can provide this kind of utility ?

**Comment by codesnake** [comment]
You can just make your own build enabling any modules you want in kernel config.

**Comment by gitchomik** [comment]
@codesnake Sure, you can also build your own linux based media HT,  in linux world you can just build whatever you emagine, but ... why not provide this solution to everyone who needs that ?

**Comment by stefansaraev** [comment]
> why not provide this solution to everyone who needs that ?

what stops you doing that?

**Comment by gitchomik** [comment]
@stefansaraev one simple thing - build and hosting server.  Openelec team, already builds image so it is "just" add building all modules. Other thing if something is provided by Openelec it  will be probably better acceptable then provided by unknown addon mainteiner.

**Comment by stefansaraev** [comment]
aha, okay ;)

**Comment by sraue** [comment]
this will not work easyly and with every simple kernel update they must be regenerated and versioned. i see no real usecase, also because some modules depends on others this will be much more work then report missing modules and add in the core build.

**Comment by gitchomik** [comment]
Probably you are right that can be complicated, but ... Openwrt has resolved this problem by producing a lot of "kmod-*" packages (versioned - kernel modules, regenereted on every kernel change). You said there is "no real usecase", in my case it was managing software RAID devices. OpenELEC doesn't provide of way of installing additional packages (filesystem is read only), but docker addon give us new possibilities unfortunately limited to **readonly** kernel.
