### ISSUE TITLE
Please upload libssh-0.7.3.tar.xz to openelec own mirror

### ISSUE THREAD

**Issue by pajtaz** [OpenELEC/OpenELEC.tv#4966]
I was attempting to build from scratch and libssh 0.7.3 could not be downloaded. The download server is temporary down: https://red.libssh.org/projects/libssh/files

Also, there is no 0.7.3 version on OpenELEC mirror folder.

If some of the developer have already the file in their sources, please upload it to:
http://sources.openelec.tv/mirror/libssh/

Thank You!

**Comment by sraue** [comment]
cheanged in https://github.com/OpenELEC/OpenELEC.tv/commit/bc508f5
