### ISSUE TITLE
Tvheadend loses channels on reboot

### ISSUE THREAD

**Issue by yuvalsegev11** [OpenELEC/OpenELEC.tv#4967]
Hi everybody, trying to use tvheadend with DVB-T over OE 7.0.3 , and after I set up my channels and map them all to the EPG , when I reboot , channels mapping is lost and there's no "TV" options in kodi, and I need to map the channels again in order to get it to work.

Tvheadend 4.0.9
OE 7.0.3 
RPi 3
'

**Comment by CvH** [comment]
this is a known Tvh problem, use Tvh 4.1.1900+
you can partly fix it with an proper sd card

**Comment by yuvalsegev11** [comment]
Ok thanks!
