### ISSUE TITLE
What does the .patch.bk suffix mean?

### ISSUE THREAD

**Issue by tgharib** [OpenELEC/OpenELEC.tv#4971]
Hi all,

I'm using the linux-999.21-BT.CT-audio.patch to compile my kernel and I noticed that it was renamed to linux-999.21-BT.CT-audio.patch.bk. I was wondering if that meant anything. I tried to do a bit of research but the "bk" is only two letters so I was getting so many irrelevant search results.

**Comment by sraue** [comment]
this patch actualy dont apply or dont work, so its renamed to .bk (backup) until there is a fix for this patch

**Comment by tgharib** [comment]
Ah gotchya. Thanks for the clarification.
