### ISSUE TITLE
SolidRun I4P-300-D not supported by openELEC 7.0.0 IMX6 Image

### ISSUE THREAD

**Issue by doemer** [OpenELEC/OpenELEC.tv#4999]
Hi

As usual on an update I tried to use the built in update function from OpenELEC but ended up in an Exception starting with Comm: swapper/2 Not tainted. 

I created an SD-Card with the latest img file and tried again. This time it allready failed when doing the repartitioning in the begining with CPU 3 Stuck.

As the previous builds still work fine, this must be BUG/Problem related to this specific "old" SolidRun Model.

Thx a lot 

Regards,

Doemer

**Comment by spielkind** [comment]
Seems to be related to the u-boot update: https://github.com/OpenELEC/OpenELEC.tv/commit/f92a45a040b75e4a57bf8c462bdd670e18c3b06b

As workaround use the u-boot file from 6.95.3, at least for us this fixed the kernel panic.

**Comment by doemer** [comment]
hi spielkind

Thx a lot for the hint. Works fine when using the previous u-boot.img. 

Regards,

Doemer

**Comment by sraue** [comment]
thanks for the find, will fix asap

**Comment by sraue** [comment]
can you try with
http://snapshots.openelec.tv/OpenELEC-imx6.arm-7.0-devel-20161231135043-r22956-g4da0fcd.img.gz (image) or
http://snapshots.openelec.tv/OpenELEC-imx6.arm-7.0-devel-20161231135043-r22956-g4da0fcd.tar (tar)

**Comment by Tomalak** [comment]
@sraue Nope, that does not yet work right. 

The boot loader starts, there's no instant kernel panic, but the device does not boot either. Black screen, the status LED blinks a bit and that's it.

(SolidRun CuBox is being used here. As described by @spielkind, the 7.0.0 image with the `u-boot.img` file transplanted from 6.95.3 works.

**Comment by doemer** [comment]
@sraue 

Happy New Year :)

Thx for the new image. It worked fine here. System is up and running.

Regards,

Doemer

**Comment by sraue** [comment]
should be solved with https://github.com/OpenELEC/OpenELEC.tv/commit/c66a29388ff8f4a97e4adee65804f7567dc87ab3
