### ISSUE TITLE
OpenELEC Compile ZLIB Library

### ISSUE THREAD

**Issue by sghazagh** [OpenELEC/OpenELEC.tv#5003]
I am trying to compile OpenELEC 7.0.1.
The installation and make is looking for zlib 1.2.10 to compile.
However, ZLIB 1.2.10 is not available in "http://sources.openelec.tv/mirror/zlib/" folder.

Please upload all dependency packages for successful compile of OpenELEC 7.0.1.

Thanks

**Comment by sghazagh** [comment]
"http://zlib.net/zlib-1.2.10.tar.xz" is not available but "http://zlib.net/zlib-1.2.11.tar.xz"  is alright.
Change it in "Packages\compress\zlib\mkfile"

**Comment by sraue** [comment]
fixed in https://github.com/OpenELEC/OpenELEC.tv/commit/3ea1e1e0428faaa3f610ac44a30937ad20126245 and https://github.com/OpenELEC/OpenELEC.tv/commit/dc3c96ac4b70ed7499443ff723732f617b53b31f
