### ISSUE TITLE
RPI2 with devel-20170307230646-r24313-g1822f7f and libCEC version 4.0.2 double commands

### ISSUE THREAD

**Issue by FirelightLokeren** [OpenELEC/OpenELEC.tv#5020]
Hi,

Kodi does see each command of the remote twice.
When i push arrow down the cursor goes 2 lines down.

Kien regards

**Comment by sraue** [comment]
which system? you are using your tv remote?

**Comment by FirelightLokeren** [comment]
I think i found the problem. I'm using a harmony one remote. When i use the original tv remote it works like sharm


Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: Stephan Raue <notifications@github.com> Datum: 14/03/17  16:28  (GMT+01:00) Aan: "OpenELEC/OpenELEC.tv" <OpenELEC.tv@noreply.github.com> Cc: FirelightLokeren <Koen@firelight.be>, Author <author@noreply.github.com> Onderwerp: Re: [OpenELEC/OpenELEC.tv] RPI2 with devel-20170307230646-r24313-g1822f7f and libCEC version 4.0.2 double commands (#5020) 
which system? you are using your tv remote?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenELEC/OpenELEC.tv","title":"OpenELEC/OpenELEC.tv","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenELEC/OpenELEC.tv"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sraue in #5020: which system? you are using your tv remote?\r\n"}],"action":{"name":"View Issue","url":"https://github.com/OpenELEC/OpenELEC.tv/issues/5020#issuecomment-286457669"}}}
