### ISSUE TITLE
Auto mounting fails on RPi2 using Openelec 8.0.0

### ISSUE THREAD

**Issue by rwky** [OpenELEC/OpenELEC.tv#5025]
Since upgrading to Openelec 8.0.0 auto mounting of external hard drives has stopped working, I can still mount manually.

Previously on 7.0.1 this worked fine.

Logs attached.

[log-2017-04-10-15.55.17.zip](https://github.com/OpenELEC/OpenELEC.tv/files/910684/log-2017-04-10-15.55.17.zip)

**Comment by sraue** [comment]
should work in 8.0.1
