### ISSUE TITLE
Auto mount of HDD fails on Cubox-I4Pro in OpenELEC 8

### ISSUE THREAD

**Issue by OveV** [OpenELEC/OpenELEC.tv#5026]
Upgraded to 8.0 from 6.0. 
Now the external hdd connected to the esata port is no longer found
(Similar symptom as #5025 but different HW.)

Here's my analysis:
udevadm complains about 'blkid' being unknown:
tv:~ # udevadm test /devices/soc0/soc/2200000.sata/ata1 2>&1 | grep 95
Reading rules file: /usr/lib/udev/rules.d/95-udevil-mount.rules
/usr/lib/udev/rules.d/95-udevil-mount.rules:9: IMPORT{builtin} 'blkid' unknown

/usr/lib/udev/rules.d/95-udevil-mount.rules uses /usr/bin/systemctl restart udevil-mount@/dev/%k.service to mount the hdd.

/usr/lib/systemd/system/udevil-mount@.service  uses "ExecStart=-/usr/bin/udevil --mount %I" to mount the HDD
I suspect  %I in my case is /dev/sda1
tv:~ # /usr/bin/udevil --mount /dev/sda1
udevil: error 64: unable to determine device fstype - specify with -t

info about my disk 
tv:~ # /sbin/blkid -o udev -p /dev/sda1
ID_FS_UUID=1bce953a-ba95-4187-9bde-abaa1595326e
ID_FS_UUID_ENC=1bce953a-ba95-4187-9bde-abaa1595326e
ID_FS_VERSION=1.0
ID_FS_TYPE=ext4
ID_FS_USAGE=filesystem
ID_PART_ENTRY_SCHEME=dos
ID_PART_ENTRY_UUID=000a061a-01
ID_PART_ENTRY_TYPE=0x83
ID_PART_ENTRY_NUMBER=1
ID_PART_ENTRY_OFFSET=63
ID_PART_ENTRY_SIZE=1953520002
ID_PART_ENTRY_DISK=8:0

If I do as udevil suggests, i.e. specify with -t everything works: 
tv:~ # /usr/bin/udevil --mount /dev/sda1 -t ext4
Mounted /dev/sda1 at /media/sda1-ata-WDC_WD10EADS-00L

BR,
//Ove

**Comment by sraue** [comment]
should work in 8.0.1
