### ISSUE TITLE
Network issues OE 8.0.0

### ISSUE THREAD

**Issue by maxonly1** [OpenELEC/OpenELEC.tv#5028]
Good to see that the usb drive bug is noted. I experienced it too. I also have some other problems that other members seem to have. For some reason I couldn't connect to my wifi network. It gave me an input/output error or sometimes it couldn't find my network at all. A wired connection worked, but when i tried to access the samba share it asked for a username and password.

I was using a Raspberry Pi 2b with Openelec 8.0.0 (manually updated from 7.0.1), but had to revert back to 7.0.1. 
Wifi adapter: TP-LINK TL-WN725N

**Comment by sraue** [comment]
can you post the logile zip you find in logfiles samba share?

**Comment by maxonly1** [comment]
I'm sorry. I probably can't since I downgraded to 7.0.1. Or does the logfile stay in that folder after downgrading?

Max

Op 14 apr. 2017 13:35 schreef Stephan Raue <notifications@github.com>:

can you post the logile zip you find in logfiles samba share?

**Comment by maxonly1** [comment]
I checked the folder. For some reason it didn't create a logfile that day.

**Comment by DeanCording** [comment]
Experiencing wifi connection problems with Openelec 8.0.0 & 8.0.1 as well.  Worked ok with 7.0.1

Raspberry Pi 2b
NetGear, Inc. WNA1000M 802.11bgn [Realtek RTL8188CUS] wifi dongle

Also experience problem with Edimax Technology Co., Ltd EW-7811Un 802.11n Wireless Adapter [Realtek RTL8188CUS] wifi dongle

Wifi connectivity is intermittent - occasionally it works fine but mostly it fails to associate or even detect WLANs.

[log-2017-04-11-19.37.50.zip](https://github.com/OpenELEC/OpenELEC.tv/files/924101/log-2017-04-11-19.37.50.zip)

**Comment by DeanCording** [comment]
Workaround is to blacklist rtl8xxxu module

  echo "blacklist rtl8xxxu" >  /storage/.config/modprobe.d/rtl8xxxu.conf

Refer http://openelec.tv/forum/124-raspberry-pi/83480-rpi2-openelec-8-0-wifi-problems
