### ISSUE TITLE
VPN no longer working

### ISSUE THREAD

**Issue by stupesX** [OpenELEC/OpenELEC.tv#5029]
I have a ZOTAC AD11 Plus. I have upgraded from 6.0.3 to 8.0.0 today and openVPN has stopped working.
The thrust of the error is:
ERROR Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)

OpenVPN is reporting as 2.4.1 x86_64-openelec-linux-gnu Apr 9th build.

I believe the issue is that the module support for the kernel dev/net/tun is not properly supported. I would be happy to use a different VPN program if one is advised?

**Comment by stupesX** [comment]
OK the fix was as follows from this page:
https://www.kernel.org/doc/Documentation/networking/tuntap.txt

Create device node:
     mkdir /dev/net (if it doesn't exist already)
     mknod /dev/net/tun c 10 200
  
  Set permissions:
     e.g. chmod 0666 /dev/net/tun

**Comment by stupesX** [comment]
Ok just to clean this one off. 
I realised that /dev/net/tun disappeared on reboot doh!

I therefore ssh in and nano /storage/.config/autostart.sh
below are the contents:
(
mkdir /dev/net;
mknod /dev/net/tun c 10 200;
chmod 0666 /dev/net/tun;
) &

**Comment by sraue** [comment]
fixed in 8.0.1
