### ISSUE TITLE
OpenELEC 8.0.0 "storage" Extending Size Problem

### ISSUE THREAD

**Issue by sghazagh** [OpenELEC/OpenELEC.tv#5032]
Hi all,
I tried compiling the "OpenELEC 8.0.0" and after successful compile I tried to load my RPi3 device.
All are good except the OpenELEC cannot resize the "STORAGE" partition (/dev/mmcblk0p2) to extend to the SD card size.

I just managed to manually extend it by mounting to a Linux Machine and resize it (fdisk+resize2fs) and in Setting reset all the OpenELEC settings (Hard Reset) and in next restart I saw the partition has resized.

I think this is the issue the developers need to have look and fix it.
Please advise if there is any quick fix for that.

Thanks

**Comment by sraue** [comment]
should work in 8.0.1
