### ISSUE TITLE
VU_/Enigma2 Client crashes Kodi on OpenElec 8.0.1

### ISSUE THREAD

**Issue by mintsoft** [OpenELEC/OpenELEC.tv#5033]
Hello,

Since upgrading to 8.0.0 (and now 8.0.1) when I try to install the VU+/Enigma2 PVR Client addon, it crashes Kodi completely. I've uninstalled the addon totally and reinstalled, however the same behaviour happens.

It was working under Openelec 6 (what I was running before I upgraded) without issue.

I've attached the kodi crash log, the only thing that stands out to me is:
```
11:37:26.895 T:140061268072192   ERROR: Unable to load /usr/lib/kodi/system/libsse4-x86_64.so, reason: /usr/lib/kodi/system/libsse4-x86_64.so: cannot open shared object file: No such file or directory
```

I'm not sure if this is a KODI problem or Openelec specific currently. 
Hardware wise, I'm running on an Asrock BeeBox with a Intel N3150 using the on-cpu Intel graphics.

[kodi_crashlog_20170416113821.txt](https://github.com/OpenELEC/OpenELEC.tv/files/924214/kodi_crashlog_20170416113821.txt)

**Comment by sraue** [comment]
try with 8.0.2 please

**Comment by mintsoft** [comment]
@sraue It works in 8.0.2; thanks
