### ISSUE TITLE
Old apr package.mk build fails: include/apr_escape_test_char.h: No such file or directory

### ISSUE THREAD

**Issue by streppuiu** [OpenELEC/OpenELEC.tv#5041]
Hi, I am trying to crosscompile apache for openelec 8 on lubuntu and am receiving this error while building apr library:

.../httpd/apr/package.mk: line 72: include/apr_escape_test_char.h: No such file or directory

 I managed to compile this lib without problem on oe 6. I assume some path is set differently and now include files cannot be found. What do I have to do to make my addons compile? I am attaching my mk file below.

[package.mk.txt](https://github.com/OpenELEC/OpenELEC.tv/files/968356/package.mk.txt)

Thank you.

**Comment by CvH** [comment]
@streppuiu you can try the latest version of the addon from [here](https://github.com/vpeter4/LibreELEC.tv/commits/lamp-addon)

**Comment by streppuiu** [comment]
Thank you for the info. I will certainly give it a try but I would also like to build my own, for fun :) . I will also look at the code to see if I can adapt my addon to build properly. I might come back with other questions.

**Comment by sraue** [comment]
possible you need something like this: https://patchwork.openembedded.org/patch/72991/
