### ISSUE TITLE
OpenELEC 8.0.3 JustBoom not working

### ISSUE THREAD

**Issue by francesco-vannini** [OpenELEC/OpenELEC.tv#5043]
None of the JustBoom HATs are automatically recognised and therefore cannot be selected in Audio devices.
Altering the /flash/config.txt to include
dtparam=audio=off
dtoverlay=justboom-dac or justboom-digi
will also not work

**Comment by francesco-vannini** [comment]
@sraue any chance you could look into this please? I am just keen to update the guide on our website. Thanks.

**Comment by shawaj** [comment]
Any update on this at all?

**Comment by sraue** [comment]
is 8.0.4 working for you?

**Comment by francesco-vannini** [comment]
Yes 8.0.4. is working fine.

On 6 Jun 2017 06:08, "Stephan Raue" <notifications@github.com> wrote:

is 8.0.4 working for you?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenELEC/OpenELEC.tv/issues/5043#issuecomment-306383338>,
or mute the thread

**Comment by sraue** [comment]
thanks much
