### ISSUE TITLE
Systemd: Suspend/Resume-Scripts not working (x64)

### ISSUE THREAD

**Issue by richardmayer** [OpenELEC/OpenELEC.tv#5046]
Hello,

I'm pretty sure, that the Suspend/Resume script in /usr/lib/systemd/system-sleep is not being executed properly, when suspending/resuming the system (x64 Platform).
I have no problem in LibreELEC, but there seem to be some differences in the systemd-behaviour between LE and OE.

I noted my observations in this forum thread. It would be great, if somebody took a look into this.
http://openelec.tv/forum/90-miscellaneous/83653-suspend-resume-script-not-working

Best Regards

Richard Mayer

**Comment by sraue** [comment]
found the issue, will be committed soon, thanks for your report

**Comment by sraue** [comment]
is 8.0.4 working for you?

**Comment by richardmayer** [comment]
Yes, it's working perfectly now with 8.0.4!
Thanks for the quick fix!
I guess the Issue can be closed...

**Comment by sraue** [comment]
thanks much
