### ISSUE TITLE
OpenELEC 8.0.3 

### ISSUE THREAD

**Issue by sghazagh** [OpenELEC/OpenELEC.tv#5060]
Hello all,
I see there is OpenELEC 8.0.3 image in openelec.tv site for RPi2/3.
I need to compile it myself but there is not a tag or release for 8.0.3.

I cannot find any commit having the 8.0.3 changes!
Can anyone help and tell me how I can obtain the 8.0.3 codes from GITHUB?

Thanks

**Comment by sraue** [comment]
committed and tagged
