### ISSUE TITLE
lakka change video drivers

### ISSUE THREAD

**Issue by ravarage** [OpenELEC/OpenELEC.tv#5070]
in retro arch the only way I can play games is changing it to gdi driver while that option is not available for lakka os , you cant change video driver and when I load the games I restart to XMB screen thank 

I am using first generation of intel  core driver GPU intel hd graghics

https://downloadcenter.intel.com/product/97497/Graphics-for-Previous-Generation-Intel-Processors

**Comment by noxarivis** [comment]
This project is dead.
Use LibreELEC!
