### ISSUE TITLE
OpenELEC Latest Release

### ISSUE THREAD

**Issue by sghazagh** [OpenELEC/OpenELEC.tv#5079]
Hi,
What is the latest version of OpenELEC at the moment?
The latest release is 8.0.4 from June and there is not any newer release since then.
However, the version file shows 8.1!
Can you please clarify the latest branch which we can download for compile?
Would you please also make a 'Release' or 'Tag' showing the latest available working version.

Thanks,

**Comment by CvH** [comment]
The addon version has nothing to do with the release version (you bump this if you need to rebuild all of your addons due some lib change). The latest git changes can be found here and the latest released version is 8.0.4. There is nothing like an "invisible" development branch or something.
The latest is https://github.com/OpenELEC/OpenELEC.tv/tree/8.0.4 .

**Comment by sghazagh** [comment]
Ok, Thanks...
I got it now...
