### ISSUE TITLE
3 minor annoyances on version 8.0.4

### ISSUE THREAD

**Issue by pitsi** [OpenELEC/OpenELEC.tv#5080]
Before I start, I would like to mention that I have been using version 8.x since 8.0.3 and I was using 7.x before that only on my pi zero. Moreover, all issues mentioned here happen both on the rpi zero version and on the x64 version of 8.0.4.

a) The openelec icon, on openelec settings, under the settings menu, when using the stock estuary skin, has a small vertical misplacement as seen in the pic. Please center it... for ocd reasons.

![screenshot001](https://user-images.githubusercontent.com/5880037/30848546-20ffae02-a2a8-11e7-8d04-45ff76f104d4.png)

b) Please do NOT include ALL of kodi's language packs on the installation! Kodi updates them on first run, all 60+ of them, and it is a really tedious procedure and useless thing to do. So, provide only the english one and let the user download the langiage pack(s) he needs.

c) The folders backup, emulators, logfiles and recordings do not exist under /storage, although they should be made via samba before they are shared. E.g. the backup folder as listed in smb.conf

[Backup]
  path = /storage/backup
  available = yes
  browsable = yes
  public = yes
  writable = yes
  root preexec = mkdir -p /storage/backup

Creating them by hand makes them instantly visible and usable over the network.

**Comment by noxarivis** [comment]
Use LibreELEC

1 month without reply is a clear sign that this project is dead

**Comment by pitsi** [comment]
(answering to both your suggestions on my issues)

I would, but openelec has one valuable tool for me in its repos that libreelec doesn't: htop, so I switched to it from libreelec. Plus, when I switched, openelec moved from 8.0.2 to 8.0.3 to 8.0.4 in a couple of days, so I would not name it as dead.
On top of that, I would ask libreelec to add htop (and ncdu) but the libreelec repo on github does not allow me to open an issue.

**Comment by MilhouseVH** [comment]
> I would, but openelec has one valuable tool for me in its repos that libreelec doesn't: htop, so I switched to it from libreelec. 

You'll find `htop` in the `System Tools` add-on available from the LibreELEC repository.

LibreELEC also includes `top` from `procps-ng` rather than the far more limited version from `busybox`, which may make `htop` unnecessary.

> but the libreelec repo on github does not allow me to open an issue.

There is a LibreELEC forum with a "feature request" sub-forum for that kind of thing. It's probably not appropriate for me to post a link but you should be able to find it yourself.

**Comment by pitsi** [comment]
Is there some url for the libreelec repo so I can check myself? I do not recall the system tools addon to include htop, beacuse I did have it installed on libreelec 7.x. And no, top does not suit my needs.

As for the forum part, I refrain from registering new accounts in numerous forums for no particular reason.

And please do not spam every single issue here with "the project is dead, use libreelec".

**Comment by MilhouseVH** [comment]
> Is there some url for the libreelec repo so I can check myself? I do not recall the system tools addon to include htop, beacuse I did have it installed on libreelec 7.x. And no, top does not suit my needs.

Added in 8.2: https://github.com/LibreELEC/LibreELEC.tv/blob/libreelec-8.2/packages/addons/addon-depends/system-tools-depends/htop/package.mk

> As for the forum part, I refrain from registering new accounts in numerous forums for no particular reason.

I thought you wanted something which seemed reason enough to me. I can understand you not wanting to open yet another forum account but that's what you'll need to do if you want engage with the LibreELEC community. They're quite friendly - and there's no spam!

> And please do not spam every single issue here with "the project is dead, use libreelec".

I think you have me confused with someone else.

**Comment by pitsi** [comment]
Yes, indeed I confused you with someone else. I am really sorry :(
I will give libreelec a try now.

**Comment by noxarivis** [comment]
@MilhouseVH 
Nice teaming up

**Comment by pitsi** [comment]
Now that 2019 ends, and since oe is long dead, I am closing this.
I have moved to libreelec since then and there are no plans to leave anytime soon.
