### ISSUE TITLE
Please add ncdu as terminal only app

### ISSUE THREAD

**Issue by pitsi** [OpenELEC/OpenELEC.tv#5081]
As the title describes, having ncdu on openelec would really help us check what is consuming disk space, especially on small-sized filesystems. Here is it's site with screenshots 

https://dev.yorhel.nl/ncdu/scr

**Comment by noxarivis** [comment]
Use LibreELEC

1 month without reply is a clear sign that this project is dead

**Comment by pitsi** [comment]
Now that 2019 ends, and since oe is long dead, I am closing this.
I have moved to libreelec since then and there are no plans to leave anytime soon.
