### ISSUE TITLE
Support TVDB scraper v2

### ISSUE THREAD

**Issue by willhowlett** [OpenELEC/OpenELEC.tv#5087]
The TVDB api v1 is going to be shut down soon, and Openelec is currently not able to support v2 due to lack of support for parsing xslt

Currently only v1.8.5 of the TVDB addon works on openelec, version 2.x does not work. When the old api is shut down (which will happen very soon) v1.8.5 will stop working too. 

Please see the following threads for more information 
https://forum.kodi.tv/showthread.php?tid=323230
https://github.com/xbmc/repo-scrapers/pull/57
http://openelec.tv/forum/73-video-management/84621-no-longer-scraping-on-2-computers#171015

**Comment by noxarivis** [comment]
u know this project is almost dead ?

**Comment by willhowlett** [comment]
To be honest until I came across this issue I wasn’t aware of that. Like lots of people I’ve used openelec for ages and never had a problem with it so carried on using it. I’m going to switch to libreelec very soon because of this issue but thought it still worth flagging just in case anyone still cared :)

**Comment by noxarivis** [comment]
just use libreelec dude :)
there was 6 months nothing

**Comment by andreabettich** [comment]
Is this going to be fixed?

**Comment by journeym** [comment]
This is a needed feature, people are switching to libreelec because ot this.
https://forum.kodi.tv/showthread.php?tid=323230&page=8

**Comment by willhowlett** [comment]
I switched to libreelec because of this issue and it was completely painless. Switching should be a no brainier. Openelec is clearly a dead project
