### ISSUE TITLE
[raspberry pi] ISO files not played

### ISSUE THREAD

**Issue by michelinok** [OpenELEC/OpenELEC.tv#689]
ISO files are not played at all, nothing happens when trying to play them.
Tryed 30 files....
I'm using the latest git version from github.

**Comment by jkiddo** [comment]
it still an issue on Openelec on 5.0.3

**Comment by popcornmix** [comment]
@jkiddo if you have a problem, create a new issue (this one is almost 3 years old).
Make sure you read:
https://github.com/OpenELEC/OpenELEC.tv/blob/master/CONTRIBUTING.md

and make sure you have an mpeg-2 codec licence.
