### ISSUE TITLE
enable LEAP control

### ISSUE THREAD

**Issue by chixxi** [OpenELEC/OpenELEC.tv#730]
Please please enable support for this device in openelec as soon as possible:

https://live.leapmotion.com/

**Comment by cusspvz** [comment]
Seems that it has Linux support already.

Leap on X Server: https://www.youtube.com/watch?v=bjHo9It55zA

Although we could read the code he wrotes and create an device input plugin with special features (one such as HDMI-CEC) that could be shipped by default on OE.
