### ISSUE TITLE
[raspberry pi] Analog output of 5.1 - voices very low, background sounds very loud

### ISSUE THREAD

**Issue by Joshfindit** [OpenELEC/OpenELEC.tv#915]
This has always happened on some files (got the raspberry about a week ago)

My first theory was that the channels being output were just the back left and back right.
It also feels like the centre channel is getting dropped (since I know some mastering puts all voice in the centre channel)

This issues is regardless of any audio setting that I set in the XBMC GUI.

If there's any specific testing I can do to track this down, simply request it here along with the logfiles to use the paste command on, and I'll be happy to help. :)

OpenELEC Version: devel-20120704035426-r11487
OpenELEC git: 4f2faf55b8d57c62413dc6dd37efa1ead1d715b2

Example 1 where this is especially bad (voices below a whisper while background audio is at a shout)

File as reported by ffmpeg:

```
Input #0, matroska,webm, from 'tvshow.mkv':
creation_time   : 2012-05-13 23:29:14
Duration: 00:22:33.01, start: 0.000000, bitrate: 5352 kb/s
Stream #0:0(eng): Video: h264 (High), yuv420p, 1280x720, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
Stream #0:1: Audio: ac3, 48000 Hz, 5.1(side), s16, 384 kb/s (default)
```

Example 2

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'movie.mp4':
major_brand     : isom
minor_version   : 1
compatible_brands: isomavc1
creation_time   : 2011-08-17 12:05:58
Duration: 01:56:38.84, start: 0.000000, bitrate: 2677 kb/s
Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x528 [SAR 1:1 DAR 80:33], 2290 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc
Stream #0:1(eng): Audio: aac (mp4a / 0x6134706D), 48000 Hz, 5.1, s16, 383 kb/s
```

**Comment by swfiua** [comment]
I am finding the analog sound output from the audio sound jack is low volume, poor quality and with a slight lag relative to the HDMI sound.

I am using Openelec 5.08.

Are there console tools I can use to explore what is happening?  

Whilst I like the minimal install that openelec does and the focus on kodi, it makes it hard to dig into these problems.

Any advice gratefully received.

Many thanks for OpenElec, mostly loving it :)
